'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const Bridge=require('../apps-script-legacy-bridge.js'),Controller=require('../legacy-jahit-controller.js');
const {createRuntimeFixture,KEY,OAUTH}=require('./helpers/apps-script-runtime-fixture.cjs'),{fakeIndexedDB}=require('./helpers/command-indexeddb-fixture.cjs');
const copy=v=>JSON.parse(JSON.stringify(v)),tick=()=>new Promise(r=>setImmediate(r));
const DEPLOYMENT='https://script.google.com/macros/s/SYNTHETIC_DEPLOYMENT_0000000000/dev',DB='soldier-apps-script-legacy-journal:v1';
function fixture(extra={}){
  const f=createRuntimeFixture(),idb=extra.idb||fakeIndexedDB(),binding={...f.seed.binding};delete binding.apiKey;
  // Functions stay in the VM realm; only JSON values cross the synthetic RPC.
  f.context.__runtime=f.create();f.context.__binding=f.realm(binding);
  const vm=require('node:vm');const rpc=vm.runInContext('Fixture.modules.rpc.createAppsScriptLegacyRpcGateway({enabled:true,binding:__binding,runtime:__runtime})',f.context);
  const listeners=new Set(),views=[],finances=[],clears=[],stats={calls:[],tokens:0,subscriptions:0},controls={tokenGate:null,gate:null,drop:null,failure:null,result:null};let active=true;
  const user={uid:f.seed.identity.uid,emailVerified:true,providerData:[{providerId:'google.com'}],async getIdToken(force){assert.equal(force,true);stats.tokens++;if(controls.tokenGate)await controls.tokenGate();return f.seed.token;}},auth={currentUser:user,app:{options:{projectId:binding.projectId,databaseURL:binding.databaseURL}}};
  function runner(failure,success){return {withFailureHandler(fn){return runner(fn,success);},withSuccessHandler(fn){return runner(failure,fn);},soldierLegacyRpc(payload){const request=copy(payload);stats.calls.push(request);queueMicrotask(async()=>{if(controls.gate)await controls.gate(request);try{const value=copy(rpc.dispatch(f.realm(request)));if(controls.drop?.(request,value))return;if(controls.failure?.(request,value)){failure(Error('SYNTHETIC_PRIVATE_ERROR'));return;}success(controls.result?controls.result(value,request):value);}catch{failure(Error('SYNTHETIC_PRIVATE_EXCEPTION'));}});}};}
  const options={enabled:true,...binding,deploymentURL:DEPLOYMENT,auth,indexedDB:idb.api,scriptRun:runner(),subscribeAuth(cb){stats.subscriptions++;listeners.add(cb);return ()=>listeners.delete(cb);},isCurrent:()=>active,onView:v=>views.push(v),onFinance:v=>finances.push(v),onClear:v=>clears.push(v)};
  const command=(id='one')=>({...copy(f.command),requestId:'request-'+id,operationId:'operation-'+id});
  const journals=()=>[...(idb.databases.get(DB)?.stores.get('journals')?.values()||[])];
  return {f,idb,options,auth,user,stats,controls,views,finances,clears,listeners,command,journals,create:changes=>Bridge.createAppsScriptLegacyBridge({...options,...changes}),signout(){active=false;auth.currentUser=null;for(const cb of [...listeners])cb(null);}};
}

test('disabled HtmlService bridge never reads dependencies, arguments, tokens or storage',async()=>{let hits=0;const o={};for(const k of ['auth','scriptRun','indexedDB'])Object.defineProperty(o,k,{get(){hits++;throw Error();}});const q=new Proxy({}, {get(){hits++;throw Error();},ownKeys(){hits++;throw Error();}}),b=Bridge.createAppsScriptLegacyBridge(o);for(const r of [await b.connect(),await b.prepare(q),await b.pending(),await b.send(q),await b.readOwnOperations(q),await b.readOwnFinance(q)])assert.deepEqual(r,{ok:false,error:'service_disabled'});assert.equal(hits,0);});
test('actual generated server and gateway provide own scoped operations and stored finance through fixed RPC only',async()=>{const f=fixture(),b=f.create(),r=await b.connect();assert.equal(r.ok,true);assert.equal(r.binding.workerId,'worker-1');assert.deepEqual(r.profile,{active:true,owner:false,workerId:'worker-1',modules:{jahit:true}});assert.equal((await b.readOwnFinance()).view.storedJahit.records[0].stored.total,999.75);assert.equal(f.finances.length,1);assert.equal((await b.readOwnOperations('other-worker')).error,'invalid_request');assert.equal((await b.readOwnFinance('other-worker')).error,'invalid_request');assert.deepEqual(f.stats.calls.map(q=>q.kind),['read','readFinance']);assert.equal(f.idb.databases.has('soldier-command-journal:v1'),false);assert.equal(f.idb.databases.has(DB),true);for(const canary of [OAUTH,KEY,'SYNTHETIC_PRIVATE_ROOT_CANARY','Other Partner'])assert.equal(JSON.stringify({r,finance:f.finances}).includes(canary),false);b.dispose();assert.equal(f.listeners.size,0);});
test('durable same-command recovery after lost acknowledgement reloads and resolves without a second write',async()=>{const f=fixture(),b=f.create();assert.equal((await b.connect()).ok,true);const cmd=f.command();assert.equal((await b.prepare(cmd)).ok,true);cmd.good=15;f.controls.failure=q=>q.kind==='execute';assert.deepEqual(await b.send('request-one'),{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(f.f.fixture.stats.writes,1);assert.equal((await b.pending()).commands[0].good,2);b.dispose();f.controls.failure=null;const c=f.create();assert.equal((await c.connect()).ok,true);assert.deepEqual(await c.send('request-one'),{ok:true,replayed:true,operationId:'operation-one'});assert.equal(f.f.fixture.stats.writes,1);assert.deepEqual((await c.pending()).commands,[]);assert.equal(f.stats.calls.at(-1).kind,'resolve');assert.equal(f.journals()[0].includes(f.f.seed.token),false);assert.equal(f.journals()[0].includes(OAUTH),false);assert.equal(f.journals()[0].includes('"phase":"accepted"'),true);c.dispose();});
test('missing acknowledgement timeout retains the exact command and accepts its late receipt only through resolution',async()=>{const f=fixture(),b=f.create({requestTimeoutMs:100});await b.connect();await b.prepare(f.command());f.controls.drop=q=>q.kind==='execute';assert.equal((await b.send('request-one')).error,'result_unknown');assert.equal((await b.pending()).commands.length,1);f.controls.drop=null;assert.equal((await b.send('request-one')).replayed,true);assert.equal(f.f.fixture.stats.writes,1);assert.equal(f.stats.calls.at(-1).kind,'resolve');b.dispose();});
test('accepted IDs remain durable and never execute again when server resolution cannot confirm them',async()=>{const f=fixture(),b=f.create();await b.connect();await b.prepare(f.command());assert.equal((await b.send('request-one')).ok,true);assert.equal((await b.prepare({...f.command(),good:1})).error,'invalid_request');f.controls.result=(v,q)=>q.kind==='resolve'?{ok:false,error:'result_unknown',retrySameCommand:true}:v;assert.equal((await b.send('request-one')).error,'result_unknown');assert.equal(f.f.fixture.stats.writes,1);assert.equal(f.stats.calls.at(-1).kind,'resolve');assert.equal((await b.pending()).commands.length,0);b.dispose();});
test('an aborted journal preparation or dispatch cannot send a write; accepted acknowledgement storage failure stays pending',async()=>{const f=fixture(),b=f.create();await b.connect();f.idb.control.putFail=true;assert.equal((await b.prepare(f.command())).error,'unavailable');assert.equal(f.f.fixture.stats.puts,0);f.idb.control.putFail=false;await b.prepare(f.command());f.idb.control.putFail=true;assert.equal((await b.send('request-one')).error,'unavailable');assert.equal(f.stats.calls.length,1);f.idb.control.putFail=false;f.controls.result=(v,q)=>{if(q.kind==='execute')f.idb.control.putFail=true;return v;};assert.equal((await b.send('request-one')).error,'result_unknown');assert.equal(f.f.fixture.stats.writes,1);f.idb.control.putFail=false;f.controls.result=null;assert.equal((await b.send('request-one')).replayed,true);assert.equal(f.f.fixture.stats.writes,1);b.dispose();});
test('account signout during a token refresh blocks RPC and preserves the prepared command',async()=>{const f=fixture(),b=f.create();await b.connect();await b.prepare(f.command());let release,start;const began=new Promise(r=>{start=r;});f.controls.tokenGate=()=>{start();return new Promise(r=>{release=r;});};const pending=b.send('request-one');await began;f.signout();release();assert.equal((await pending).error,'access_denied');assert.equal(f.stats.calls.length,1);assert.equal(f.f.fixture.stats.writes,0);assert.equal(f.listeners.size,0);assert.equal(f.journals()[0].includes('request-one'),true);});
test('signout during a submitted RPC clears own data and a late server commit is recovered without duplicate writing',async()=>{const f=fixture(),b=f.create();await b.connect();await b.prepare(f.command());let release,start;const began=new Promise(r=>{start=r;});f.controls.gate=q=>{if(q.kind==='execute'){start();return new Promise(r=>{release=r;});}};const p=b.send('request-one');await began;f.signout();assert.equal((await p).error,'access_denied');release();await tick();assert.equal(f.f.fixture.stats.writes,1);assert.equal(f.views.length,1);assert.equal(f.clears.length,1);assert.equal(f.journals()[0].includes('"phase":"dispatched"'),true);});
test('auth object, project or service-runner drift blocks further reads and unsubscribes',async()=>{for(const mutate of [f=>{f.auth.currentUser={...f.user};},f=>{f.auth.app.options.databaseURL='https://demo-other.firebaseio.com';},f=>{f.options.scriptRun.withFailureHandler=()=>{};}]){const f=fixture(),b=f.create();await b.connect();mutate(f);assert.equal((await b.readOwnOperations()).error,'access_denied');assert.equal(f.stats.calls.length,1);assert.equal(f.listeners.size,0);}});
test('a retryable initial read does not duplicate the auth subscription',async()=>{const f=fixture();let once=true;f.controls.result=v=>{if(once){once=false;return {ok:false,error:'busy'};}return v;};const b=f.create();assert.equal((await b.connect()).error,'busy');assert.equal((await b.connect()).ok,true);assert.equal(f.stats.subscriptions,1);assert.equal(f.listeners.size,1);b.dispose();});
test('malformed, foreign-binding and raw-root responses fail before publishing data',async()=>{for(const change of [v=>{v.view.binding.uid='other-user';},v=>{v.root={private:'SYNTHETIC_PRIVATE_ROOT_CANARY'};},v=>{v.view.products[0].tarif=1;},v=>{v.view.products[0].assignments[0].remaining=9;},v=>{v.view.products=[];v.view.workerLabel='x'.repeat(1048705);}]){const f=fixture();f.controls.result=v=>{change(v);return v;};assert.equal((await f.create().connect()).ok,false);assert.equal(f.views.length,0);assert.equal(f.idb.stats.opens,0);}const g=fixture(),b=g.create();await b.connect();g.controls.result=(v,q)=>{if(q.kind==='readFinance')v.view.binding.workerId='other-worker';return v;};assert.equal((await b.readOwnFinance()).error,'access_denied');assert.equal(g.finances.length,0);});
test('retained account/grant/deployment journals are never silently adopted or submitted',async()=>{const f=fixture(),b=f.create();await b.connect();await b.prepare(f.command());b.dispose();const c=f.create({deploymentURL:DEPLOYMENT.replace('/dev','/exec')});assert.equal((await c.connect()).error,'unavailable');assert.equal(f.f.fixture.stats.writes,0);assert.equal(f.journals()[0].includes('/dev'),true);const g=fixture({idb:f.idb});g.controls.result=v=>{if(v.view)v.view.binding.grantRevision=2;return v;};const d=g.create();assert.equal((await d.connect()).ok,true);assert.deepEqual((await d.pending()).commands,[]);assert.equal(g.journals().some(x=>x.includes('request-one')),true);assert.equal(g.f.fixture.stats.writes,0);d.dispose();});
test('two tabs cannot replace a prepared payload and corrupt duplicate-key storage fails closed without reset',async()=>{const f=fixture(),a=f.create(),b=f.create();await a.connect();await b.connect();const r=await Promise.all([a.prepare(f.command()),b.prepare({...f.command(),good:1})]);assert.equal(r.filter(v=>v.ok).length,1);assert.equal(r.find(v=>!v.ok).error,'invalid_request');a.dispose();b.dispose();const m=f.idb.databases.get(DB).stores.get('journals'),key=[...m.keys()][0],old=m.get(key),bad=old.replace('"schemaVersion":1','"schemaVersion":1,"\\u0073chemaVersion":1');m.set(key,bad);assert.equal((await f.create().connect()).ok,false);assert.equal(m.get(key),bad);assert.equal(f.f.fixture.stats.writes,0);});
test('client supplied worker, rate, total, grant override and over-reporting never reach the RPC write',async()=>{const f=fixture(),b=f.create();await b.connect();for(const cmd of [{...f.command(),workerId:'other-worker'},{...f.command(),total:1},{...f.command(),tarif:1},{...f.command(),expectedGrantRevision:2},{...f.command(),workDate:'2026-02-30'}])assert.equal((await b.prepare(cmd)).error,'invalid_request');assert.equal((await b.prepare({...f.command(),good:30})).error,'conflict');assert.equal(f.stats.calls.length,1);assert.equal(f.f.fixture.stats.puts,0);b.dispose();});
test('actual Jahit controller uses the HtmlService bridge, keeps one report ID through uncertainty and shows updated own progress',async()=>{const f=fixture(),states=[];let ids=0;const c=Controller.createLegacyJahitController({enabled:true,isCurrent:()=>f.auth.currentUser===f.user,newId:()=>String(++ids),onState:s=>states.push(s),createBridge:cb=>f.create({...cb})});assert.equal((await c.connect()).ok,true);assert.equal(c.selectAssignment('product-1','assignment-1').ok,true);f.controls.failure=q=>q.kind==='execute';assert.equal((await c.submit({workDate:null,good:2,reject:0})).error,'result_unknown');assert.equal(states.at(-1).pending[0].requestId,'request-1');assert.equal((await c.submit({workDate:null,good:2,reject:0})).error,'pending_review');f.controls.failure=null;assert.equal((await c.retry('request-1')).replayed,true);assert.equal(states.at(-1).pending.length,0);assert.equal(states.at(-1).view.products[0].assignments[0].reportedGood,5);assert.equal(ids,1);assert.equal(f.f.fixture.stats.writes,1);c.dispose();});
