'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Bridge=require('../legacy-production-bridge.js'),Canonical=require('../production-bridge.js'),{fakeIndexedDB}=require('./helpers/command-indexeddb-fixture.cjs');
const PROJECT='demo-legacy-browser',URL='https://'+PROJECT+'.firebaseio.com',ORIGIN='https://service.example.invalid',ENDPOINT=ORIGIN+Bridge.PATHS.append;
const copy=v=>JSON.parse(JSON.stringify(v)),tick=()=>new Promise(r=>setImmediate(r));
function fixture(extra={}){
  const idb=extra.idb||fakeIndexedDB(),app={options:{projectId:PROJECT,databaseURL:URL}},scope={projectId:PROJECT,databaseURL:URL,tenantId:'tenant-demo',uid:'caller-demo',grantRevision:1},profile={active:true,owner:false,workerId:'worker-demo',modules:{jahit:true}},binding={...scope,workerId:'worker-demo',division:'jahit'};
  const source={schemaVersion:1,binding,workerLabel:'Synthetic own partner',products:[{productId:'product-demo',series:'Synthetic',namaBarang:'Example',size:'M',sourceVersion:'a'.repeat(64),assignments:[{assignmentId:'assignment-demo',assigned:10,reportedGood:0,reportedReject:0,remaining:10}],reports:[],hasUnlistedLegacy:false}]};
  const controls={rawOwn:null,ownMutate:null,sessionMutate:null,loseAck:false,deny:false,gate:null,tokenGate:null},stats={calls:[],tokens:0,commits:0,disposes:0},receipts=new Map(),views=[],clears=[];let active=true,callbacks;
  const user={uid:scope.uid,emailVerified:true,providerData:[{providerId:'google.com'}],async getIdToken(force){assert.equal(force,true);stats.tokens++;if(controls.tokenGate)await controls.tokenGate();return 'header.payload.signature';}},auth={app,currentUser:user},database={app};
  function response(url,result,status=200){const raw=typeof result==='string'?result:JSON.stringify(result),r=new Response(raw,{status,headers:{'Content-Type':'application/json'}});Object.defineProperties(r,{url:{value:url,configurable:true},type:{value:'cors'},redirected:{value:false}});return r;}
  async function fetch(url,o){stats.calls.push({url,options:o});assert.equal(o.credentials,'omit');assert.equal(o.cache,'no-store');assert.equal(o.redirect,'error');assert.equal(o.referrerPolicy,'no-referrer');assert.equal(o.headers.Authorization,'Bearer header.payload.signature');if(controls.gate)await controls.gate(url,o);if(controls.deny)return response(url,{ok:false,error:'access_denied'},403);
    if(url===ORIGIN+Bridge.PATHS.own){assert.equal(o.method,'GET');assert.equal(Object.hasOwn(o,'body'),false);let v=copy(source);if(controls.ownMutate)controls.ownMutate(v);return response(url,controls.rawOwn===null?{ok:true,view:v}:controls.rawOwn);}
    if(url===ORIGIN+'/v1/production/session')return response(url,{ok:true,session:{schemaVersion:1,...scope,profile,cycles:[]}});
    assert.equal(o.method,'POST');const body=JSON.parse(o.body);assert.deepEqual(Object.keys(body),['command']);const cmd=body.command;assert.deepEqual(Object.keys(cmd).sort(),['kind','requestId','operationId','productId','assignmentId','expectedGrantRevision','expectedSourceVersion','workDate','good','reject'].sort());let ack=receipts.get(cmd.requestId);
    if(url===ORIGIN+Bridge.PATHS.resolve)return ack?response(url,{...ack,replayed:true}):response(url,{ok:false,error:'result_unknown',retrySameCommand:true},503);
    assert.equal(url,ENDPOINT);if(!ack){stats.commits++;ack={ok:true,replayed:false,operationId:cmd.operationId};receipts.set(cmd.requestId,ack);const p=source.products[0],a=p.assignments[0];a.reportedGood+=cmd.good;a.reportedReject+=cmd.reject;a.remaining-=cmd.good+cmd.reject;p.reports.push({operationId:cmd.operationId,assignmentId:cmd.assignmentId,workDate:cmd.workDate||'2026-10-06',good:cmd.good,reject:cmd.reject,completed:cmd.good+cmd.reject});p.sourceVersion='b'.repeat(64);}else ack={...ack,replayed:true};if(controls.loseAck){controls.loseAck=false;throw Error('synthetic-response-lost');}return response(url,ack);
  }
  const options={enabled:true,projectId:PROJECT,databaseURL:URL,tenantId:scope.tenantId,endpointURL:ENDPOINT,auth,database,indexedDB:idb.api,fetch,isCurrent:()=>active,onView:v=>views.push(v),onClear:c=>clears.push(c),createSessionBridge(cb){callbacks=cb;return {async connect(){let r={ok:true,scope:copy(scope),profile:copy(profile),cycles:[]};if(controls.sessionMutate)controls.sessionMutate(r);return r;},dispose(){stats.disposes++;}};}};
  const command=(id='one')=>({kind:'appendJahit',requestId:'request-'+id,operationId:'operation-'+id,productId:'product-demo',assignmentId:'assignment-demo',expectedGrantRevision:scope.grantRevision,expectedSourceVersion:source.products[0].sourceVersion,workDate:null,good:2,reject:1});
  return {idb,options,scope,profile,binding,source,controls,stats,auth,database,views,clears,receipts,response,command,create:changes=>Bridge.createLegacyProductionBridge({...options,...changes}),revoke(){callbacks.onClear('access_changed');},signout(){auth.currentUser=null;active=false;},callback:()=>callbacks};
}
test('SOURCE OFF does not read config or arguments, touch storage, token or callback',async()=>{let reads=0;const o={};for(const k of ['auth','endpointURL','indexedDB','isCurrent'])Object.defineProperty(o,k,{get(){reads++;throw Error();}});const b=Bridge.createLegacyProductionBridge(o),arg=new Proxy({}, {get(){throw Error();},ownKeys(){throw Error();}});for(const r of [await b.connect(),await b.prepare(arg),await b.pending(),await b.send(arg),await b.readOwnOperations(arg)])assert.equal(r.error,'service_disabled');assert.equal(reads,0);});
test('same verified own binding, fixed cross-origin endpoint and isolated durable namespace expose only narrow operational fields',async()=>{const f=fixture(),b=f.create(),r=await b.connect();assert.equal(r.ok,true);assert.equal(r.binding.workerId,'worker-demo');assert.equal(Object.isFrozen(r.view.products[0]),true);assert.deepEqual(Object.keys(r.view),['schemaVersion','binding','workerLabel','products']);assert.ok(f.idb.databases.has('soldier-legacy-command-journal:v1'));assert.equal(f.idb.databases.has('soldier-command-journal:v1'),false);assert.equal(f.stats.calls.length,1);assert.equal((await b.readOwnOperations('worker-other')).error,'invalid_request');assert.equal(f.stats.calls.length,1);b.dispose();});
test('lost append response persists exact same command across reload and resolve prevents a second commit',async()=>{const f=fixture(),b=f.create();await b.connect();const cmd=f.command();assert.equal((await b.prepare(cmd)).ok,true);cmd.good=9;f.controls.loseAck=true;assert.deepEqual(await b.send('request-one'),{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(f.stats.commits,1);assert.equal((await b.pending()).commands[0].good,2);b.dispose();const c=f.create();await c.connect();assert.equal((await c.pending()).commands.length,1);const r=await c.send('request-one');assert.equal(r.ok,true);assert.equal(r.replayed,true);assert.equal(f.stats.commits,1);assert.deepEqual((await c.pending()).commands,[]);assert.equal(f.stats.calls.at(-1).url,ORIGIN+Bridge.PATHS.resolve);const journal=[...f.idb.databases.get('soldier-legacy-command-journal:v1').stores.get('journals').values()][0];assert.equal(journal.includes('header.payload.signature'),false);assert.equal(journal.includes('"phase":"accepted"'),true);assert.equal(journal.includes('"good":2'),true);c.dispose();});
test('acknowledged command cannot be replaced or recreated after server resolution becomes unknown',async()=>{const f=fixture(),b=f.create();await b.connect();const cmd=f.command();await b.prepare(cmd);await b.send(cmd.requestId);assert.equal((await b.prepare({...cmd,good:1})).error,'invalid_request');f.receipts.clear();const before=f.stats.commits;assert.equal((await b.send(cmd.requestId)).error,'result_unknown');assert.equal(f.stats.commits,before);assert.equal(f.stats.calls.at(-1).url,ORIGIN+Bridge.PATHS.resolve);b.dispose();});
test('old UID/grant/worker journals are retained without auto-submission or adoption',async()=>{const f=fixture(),b=f.create();await b.connect();await b.prepare(f.command());b.dispose();for(const change of ['uid','grantRevision','workerId']){const g=fixture({idb:f.idb});if(change==='uid'){g.scope.uid='caller-other';g.auth.currentUser.uid='caller-other';g.binding.uid='caller-other';}if(change==='grantRevision'){g.scope.grantRevision=2;g.binding.grantRevision=2;}if(change==='workerId'){g.profile.workerId='worker-other';g.binding.workerId='worker-other';}const c=g.create();const r=await c.connect();if(change==='workerId')assert.equal(r.ok,false);else{assert.equal(r.ok,true);assert.deepEqual((await c.pending()).commands,[]);}assert.equal(g.stats.commits,0);c.dispose();}assert.ok([...f.idb.databases.get('soldier-legacy-command-journal:v1').stores.get('journals').values()].some(raw=>raw.includes('request-one')));});
test('foreign/inactive/owner/multi-module sessions fail before own endpoint or journal open',async()=>{for(const mutate of [r=>{r.scope.uid='caller-other';},r=>{r.scope.tenantId='tenant-other';},r=>{r.profile.active=false;},r=>{r.profile.owner=true;},r=>{r.profile.modules.qc=true;},r=>{r.profile.workerId='worker/unsafe';}]){const f=fixture();f.controls.sessionMutate=mutate;assert.equal((await f.create().connect()).ok,false);assert.equal(f.stats.calls.length,0);assert.equal(f.idb.stats.opens,0);}});
test('full whitelist rejects another worker, raw payroll fields, opaque root rows, duplicate keys and invalid progress',async()=>{for(const mutate of [v=>{v.binding.workerId='worker-other';},v=>{v.products[0].tarif=42;},v=>{v.products[0].reports.push({opaque:true});},v=>{v.products[0].assignments[0].remaining=8;},v=>{v.binding.uid='caller-other';}]){const f=fixture();f.controls.ownMutate=mutate;assert.equal((await f.create().connect()).ok,false);assert.equal(f.views.length,0);}const f=fixture();f.controls.rawOwn='{"ok":false,"\\u006fk":true,"view":{}}';assert.equal((await f.create().connect()).ok,false);assert.equal(f.views.length,0);});
test('command extra role/worker/rate/total, accessors, overflow, invalid dates or source guards never deliver',async()=>{const f=fixture(),b=f.create();await b.connect();for(const c of [{...f.command(),workerId:'worker-other'},{...f.command(),tarif:1},{...f.command(),total:1},{...f.command(),role:'owner'},{...f.command(),workDate:'2026-02-30'},{...f.command(),workDate:'0000-01-01'},{...f.command(),good:Number.MAX_SAFE_INTEGER,reject:1},{...f.command(),requestId:'1'}])assert.equal((await b.prepare(c)).error,'invalid_request');assert.equal((await b.prepare({...f.command(),expectedSourceVersion:'c'.repeat(64)})).error,'conflict');let reads=0;const c=f.command();Object.defineProperty(c,'good',{enumerable:true,get(){reads++;return 1;}});assert.equal((await b.prepare(c)).error,'invalid_request');assert.equal(reads,0);assert.equal(f.stats.commits,0);assert.equal(f.stats.calls.length,1);b.dispose();});
test('atomic CAS requires durable preparation and dispatch mark before network; aborted writes retain prior command',async()=>{const f=fixture(),b=f.create();await b.connect();f.idb.control.putFail=true;assert.equal((await b.prepare(f.command())).error,'unavailable');assert.equal(f.stats.commits,0);f.idb.control.putFail=false;await b.prepare(f.command());f.idb.control.putFail=true;assert.equal((await b.send('request-one')).error,'unavailable');assert.equal(f.stats.calls.length,1);f.idb.control.putFail=false;assert.equal((await b.pending()).commands[0].requestId,'request-one');b.dispose();});
test('grant revocation during body read cancels the request and clears own data while preserving durable command',async()=>{const f=fixture(),b=f.create();await b.connect();await b.prepare(f.command());let release,started;const gate=new Promise(r=>{started=r;});f.controls.gate=async(url)=>{if(url!==ENDPOINT)return;started();await new Promise(r=>{release=r;});};const writing=b.send('request-one');await gate;f.revoke();assert.equal(f.stats.calls.at(-1).options.signal.aborted,true);release();assert.equal((await writing).error,'access_denied');assert.equal((await b.connect()).error,'access_denied');assert.ok(f.clears.includes('access_denied'));assert.equal(f.views.length,1);assert.ok([...f.idb.databases.get('soldier-legacy-command-journal:v1').stores.get('journals').values()][0].includes('request-one'));});
test('signout during token refresh blocks the append before network and database binding change blocks all later reads',async()=>{const f=fixture(),b=f.create();await b.connect();await b.prepare(f.command());let release,started;const gate=new Promise(r=>{started=r;});f.controls.tokenGate=()=>{started();return new Promise(r=>{release=r;});};const p=b.send('request-one');await gate;f.signout();release();assert.equal((await p).error,'access_denied');assert.equal(f.stats.calls.length,1);const g=fixture(),c=g.create();await c.connect();g.database.app={options:{projectId:PROJECT,databaseURL:'https://demo-other.firebaseio.com'}};assert.equal((await c.readOwnOperations()).error,'access_denied');assert.equal(g.stats.calls.length,1);});
test('journal malformed bytes fail closed without reset; no accepted-ID loss and two tabs cannot replace payload',async()=>{const f=fixture(),a=f.create(),b=f.create();await a.connect();await b.connect();const c=f.command();const results=await Promise.all([a.prepare(c),b.prepare({...c,good:1})]);assert.equal(results.filter(r=>r.ok).length,1);assert.equal(results.find(r=>!r.ok).error,'invalid_request');a.dispose();b.dispose();const map=f.idb.databases.get('soldier-legacy-command-journal:v1').stores.get('journals'),key=[...map.keys()][0],raw=map.get(key);map.set(key,raw.replace('"schemaVersion":1','"schemaVersion":1,"\\u0073chemaVersion":1'));const newer=f.create();assert.equal((await newer.connect()).ok,false);assert.equal(map.get(key).includes('\\u0073chemaVersion'),true);assert.equal(f.stats.commits,0);});
test('response URL redirects, malformed endless streams and oversized decoded JSON are rejected and cancelled',async()=>{const f=fixture(),bad=f.create({fetch:async url=>{const r=f.response(url,{ok:true,view:f.source});Object.defineProperty(r,'url',{value:ORIGIN+'/unexpected'});return r;}});assert.equal((await bad.connect()).ok,false);const g=fixture();g.controls.rawOwn=' '.repeat(1048705);assert.equal((await g.create().connect()).ok,false);let cancels=0,reads=0;const h=fixture(),b=h.create({fetch:async url=>({url,status:200,type:'cors',redirected:false,headers:new Headers({'Content-Type':'application/json'}),body:{getReader(){return {async read(){reads++;return {done:false,value:new Uint8Array(0)};},async cancel(){cancels++;},releaseLock(){}};}}})});assert.equal((await b.connect()).ok,false);assert.equal(cancels,1);assert.equal(reads,1048705);});
test('actual existing verified session bridge keeps grant-leaf lifecycle and opens no legacy whole-root listeners',async()=>{const f=fixture(),subscriptions=new Map(),authCallbacks=new Set();const value=path=>{const parts=path.split('/').slice(5);let v=path.endsWith('/revision')?f.scope.grantRevision:f.profile;for(const p of parts)v=v?.[p];return v??null;};const sdk={ref(db,path){return {path,toString:()=>URL+'/'+path};},onValue(ref,cb){subscriptions.set(ref.path,cb);queueMicrotask(()=>cb({val:()=>value(ref.path)}));return ()=>subscriptions.delete(ref.path);},onAuthStateChanged(auth,cb){authCallbacks.add(cb);return ()=>authCallbacks.delete(cb);}};const b=f.create({createSessionBridge:callbacks=>Canonical.createProductionBridge({...f.options,...callbacks,endpointURL:ORIGIN+'/v1/production/commands',sdk})});assert.equal((await b.connect()).ok,true);assert.ok([...subscriptions.keys()].every(p=>p.startsWith('authorityTenants/tenant-demo/grants/caller-demo/')));assert.equal([...subscriptions.keys()].some(p=>p.startsWith('soldier')),false);const active=[...subscriptions.keys()].find(p=>p.endsWith('/profile/active'));subscriptions.get(active)({val:()=>false});await tick();assert.equal((await b.pending()).error,'access_denied');assert.equal(subscriptions.size,0);assert.equal(authCallbacks.size,0);});
test('bounded accepted receipt evidence is retained at capacity, with no silent purge or delivery',async()=>{const f=fixture(),b=f.create();await b.connect();await b.prepare(f.command());const map=f.idb.databases.get('soldier-legacy-command-journal:v1').stores.get('journals'),key=[...map.keys()][0],doc=JSON.parse(map.get(key));doc.entries=Array.from({length:512},(_,i)=>({command:{...f.command(String(i))},phase:'accepted',receipt:{ok:true,replayed:false,operationId:'operation-'+i}}));const raw=JSON.stringify(doc);assert.ok(new TextEncoder().encode(raw).length<262144);map.set(key,raw);const r=await b.prepare(f.command('new'));assert.equal(r.error,'capacity_limit');assert.equal(map.get(key),raw);assert.equal(f.stats.commits,0);assert.deepEqual((await b.pending()).commands,[]);assert.equal((await b.send('request-0')).error,'result_unknown');assert.equal(f.stats.commits,0);assert.equal(map.get(key),raw);b.dispose();});
test('exact HTTP busy/unavailable write retry contracts retain same durable command and never imply acceptance',async()=>{for(const code of ['busy','unavailable']){const f=fixture(),b=f.create({fetch:async(url,o)=>url===ENDPOINT?f.response(url,{ok:false,error:code,retrySameCommand:true},503):f.options.fetch(url,o)});await b.connect();await b.prepare(f.command());assert.deepEqual(await b.send('request-one'),{ok:false,error:code,retrySameCommand:true});assert.equal(f.stats.commits,0);assert.equal((await b.pending()).commands[0].requestId,'request-one');b.dispose();}});
test('read busy has no command retry flag; extra flags or wrong write contract fail closed without a successful view/receipt',async()=>{let reads=0;const f=fixture(),b=f.create({fetch:async(url,o)=>url===ORIGIN+Bridge.PATHS.own&&++reads>1?f.response(url,{ok:false,error:'busy'},503):f.options.fetch(url,o)});assert.equal((await b.connect()).ok,true);assert.deepEqual(await b.readOwnOperations(),{ok:false,error:'busy'});assert.equal(f.views.length,1);b.dispose();for(const code of ['busy','unavailable','result_unknown']){const g=fixture(),c=g.create({fetch:async url=>g.response(url,{ok:false,error:code,retrySameCommand:true},503)});assert.equal((await c.connect()).error,'unavailable');assert.equal(g.views.length,0);}const h=fixture(),d=h.create({fetch:async(url,o)=>url===ENDPOINT?h.response(url,{ok:false,error:'busy'},503):h.options.fetch(url,o)});await d.connect();await d.prepare(h.command());assert.deepEqual(await d.send('request-one'),{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(h.stats.commits,0);assert.equal((await d.pending()).commands.length,1);d.dispose();});
