'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Codec=require('../legacy-view-client.js'),{createRuntimeFixture}=require('./helpers/apps-script-runtime-fixture.cjs');
const copy=v=>JSON.parse(JSON.stringify(v));
function finance(){const f=createRuntimeFixture(),r=f.normal(f.create().readFinance(f.fixture.readInput()));assert.equal(r.ok,true);return r.view;}
test('operation and command validators retain compatibility with genuine synthetic runtime DTOs',()=>{const f=createRuntimeFixture(),r=f.normal(f.create().read(f.fixture.readInput()));assert.deepEqual(Codec.normalizeLegacyOperationsView(r.view,r.view.binding),r.view);assert.deepEqual(Codec.normalizeLegacyCommand(f.command,1),f.command);});
test('finance whitelist retains stored totals and exact old markers without repricing or combining payment',()=>{const v=finance();v.storedJahit.records[0].stored.tanggal='Legacy date';v.storedJahit.records[0].stored.quantityBasis='Legacy reviewed basis';v.kasbon.records=[{sourceRecordId:'loan-1',stored:{tanggal:null,jumlah:10.25,sisa:3.75,status:'aktif'},cicilan:[{sourceRecordId:'payment-1',stored:{tanggal:'Stored date',jumlah:6.5,ket:'Stored note'}}]}];const normalized=Codec.normalizeLegacyFinanceView(v,v.binding);assert.deepEqual(normalized,v);assert.equal(normalized.storedJahit.records[0].stored.total,999.75);assert.equal(normalized.slip.paymentEvidence,'not_proven');assert.equal(normalized.combinedPayout,null);assert.equal(Object.isFrozen(normalized.kasbon.records[0].cicilan[0].stored),true);assert.notEqual(normalized,v);});
test('available/provisional, approved and repair slip entries remain separate and exact',()=>{const v=finance(),base={productId:'product-1',product:{series:'Synthetic',namaBarang:'Item',size:'M'},countId:'count-1',sourceType:'hitungFisik',tanggal:'2026-10-06',jumlah:2,tarif:0.125,total:0.25,provisional:true};v.slip.entries=[base,{...base,countId:'count-2',provisional:false},{...base,sourceType:'qcRepair',repairId:'repair-1',provisional:false}];assert.deepEqual(Codec.normalizeLegacyFinanceView(v,v.binding),v);});
test('pending review is preserved with null entries instead of inferred zero wages',()=>{const v=finance();v.slip.availability='pending_review';v.slip.entries=null;v.storedJahit.deletionSignatures='pending_review';assert.deepEqual(Codec.normalizeLegacyFinanceView(v,v.binding),v);v.slip.entries=[];assert.throws(()=>Codec.normalizeLegacyFinanceView(v,v.binding),/invalid_legacy_view/);});
test('foreign scope and raw identity/root/payroll extras fail before any finance result',()=>{for(const mutate of [v=>v.binding.workerId='worker-other',v=>v.binding.uid='caller-other',v=>v.binding.grantRevision=2,v=>v.root={private:true},v=>v.storedJahit.records[0].stored.workerId='foreign',v=>v.storedJahit.records[0].product.privateCost=99,v=>v.slip.ownerTotal=100,v=>v.kasbon.email='private@example.invalid']){const v=finance(),binding=copy(v.binding);mutate(v);assert.throws(()=>Codec.normalizeLegacyFinanceView(v,binding),/invalid_legacy_view/);}});
test('unknown payment claims, aggregates and unsupported historical lanes are rejected',()=>{for(const mutate of [v=>v.combinedPayout=100,v=>v.historicalAliases='included',v=>v.slip.paymentEvidence='paid',v=>v.storedJahit.basis='computed',v=>v.kasbon.basis='computed',v=>v.slip.coverage='all']){const v=finance();mutate(v);assert.throws(()=>Codec.normalizeLegacyFinanceView(v,v.binding),/invalid_legacy_view/);}});
test('invalid old monetary shapes, duplicate IDs and dates cannot escape the whitelist',()=>{for(const mutate of [v=>v.storedJahit.records[0].stored.total=-1,v=>v.storedJahit.records[0].stored.tarif='10',v=>v.storedJahit.records[0].stored.dibayar='yes',v=>v.storedJahit.records.push(copy(v.storedJahit.records[0])),v=>v.observedAt='yesterday',v=>v.workerLabel='bad\nlabel']){const v=finance();mutate(v);assert.throws(()=>Codec.normalizeLegacyFinanceView(v,v.binding),/invalid_legacy_view/);}});
test('slip quantities, arithmetic, repair provenance and duplicates are independently checked',()=>{const base={productId:'product-1',product:{series:'Synthetic',namaBarang:'Item',size:'M'},countId:'count-1',sourceType:'hitungFisik',tanggal:'2026-10-06',jumlah:2,tarif:2,total:4,provisional:false};for(const mutate of [e=>e.total=5,e=>e.jumlah=1.5,e=>e.sourceType='legacy',e=>e.tarif=0,e=>e.tanggal='2026-02-30',e=>e.sourceType='qcRepair',e=>e.repairId='unexpected']){const v=finance(),e=copy(base);mutate(e);v.slip.entries=[e];assert.throws(()=>Codec.normalizeLegacyFinanceView(v,v.binding),/invalid_legacy_view/);}const v=finance();v.slip.entries=[copy(base),copy(base)];assert.throws(()=>Codec.normalizeLegacyFinanceView(v,v.binding),/invalid_legacy_view/);});
test('accessors, sparse arrays, oversized fields and cycles never invoke getters or stringify hooks',()=>{const v=finance();let hits=0;Object.defineProperty(v.storedJahit.records[0].stored,'total',{enumerable:true,get(){hits++;throw Error('PRIVATE');}});assert.throws(()=>Codec.normalizeLegacyFinanceView(v,v.binding),/invalid_legacy_view/);assert.equal(hits,0);for(const mutate of [v=>v.storedJahit.records=Array(1),v=>v.kasbon.records=[{stored:{keterangan:'x'.repeat(1048577)},cicilan:[]}],v=>v.slip.toJSON=()=>{throw Error('PRIVATE');},v=>v.slip.cycle=v]){const q=finance();mutate(q);assert.throws(()=>Codec.normalizeLegacyFinanceView(q,q.binding),/invalid_legacy_view/);}});
