'use strict';
// The retained legacy UI and the public entry routes have separate contracts.
// Until main cutover, roots must remain exactly the reviewed old source. After
// cutover, every root must be a ready fixed router/chooser: mixed releases fail.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const Source=require('../server/apps-script/legacy-page-source.cjs'),ROOT=path.resolve(__dirname,'..');
const routes=Object.freeze({'jahit-command.html':'?division=jahit','qc-command.html':'?division=qc','maklon-upah.html':'?division=jahit','laporan-produksi.html':'?division=owner&ownerModule=laporan','potong-command.html':'?division=owner&ownerModule=potong','stok-bahan-command.html':'?division=owner&ownerModule=stok','gaji-harian-command.html':'?division=owner&ownerModule=gaji','hpp-command-v1.html':'?division=owner&ownerModule=hpp','pembelian-produk-v1.html':'?division=owner&ownerModule=pembelian','nota-penjualan.html':'?division=owner&ownerModule=nota','retur-command.html':'?division=owner&ownerModule=retur','owner-upah.html':'?division=owner&ownerModule=jahit','owner-tarif.html':'?division=owner&ownerModule=jahit'});
function state(){const file=path.join(ROOT,'soldier-main-routing.js'),active=fs.existsSync(file);return{active,router:active?fs.readFileSync(file,'utf8'):null};}
function html(file){return fs.readFileSync(path.join(ROOT,file),'utf8');}
function legacy(){for(const row of Source.rows)assert.equal(Source.reviewedSource(row.file,html(row.file)),Source.readLegacyPageSource(row.file));}
function realm(source){const targets=[],storage={getItem(){throw Error('draft read forbidden');},setItem(){throw Error('draft write forbidden');},removeItem(){throw Error('draft delete forbidden');}},window={location:{search:'?role=owner&uid=foreign&deploymentURL=https://foreign.invalid',hash:'#token=foreign',replace:value=>targets.push(value)},localStorage:storage,sessionStorage:storage};const context=vm.createContext({window});vm.runInContext(source,context);assert.equal(window.SoldierMainRouting.sourceOff,false);return{api:window.SoldierMainRouting,targets,window,context};}
test('main entries are a coherent reviewed legacy release or a complete protected routing cutover',()=>{
 assert.deepEqual(fs.readdirSync(ROOT).filter(file=>file.endsWith('.html')).sort(),Source.rows.map(row=>row.file).sort());const s=state();if(!s.active){legacy();return;}
 const r=realm(s.router);for(const [file,suffix]of Object.entries(routes)){const target=r.api.target(file),url=target.slice(0,-suffix.length);assert.match(url,/^https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]{20,200}\/exec$/);assert.equal(target,url+suffix);const entry=html(file);assert.doesNotMatch(entry,/firebase|SoldierAccess|localStorage|sessionStorage|indexedDB|import\(/i);assert.match(entry,/<script src="soldier-main-routing\.js\?v=secure-v1-[a-f0-9]{24}"><\/script>/);assert.ok(entry.indexOf('SoldierMainRouting.redirect('+JSON.stringify(file)+');')<entry.indexOf('<meta charset='));assert.ok(entry.includes('href="'+target.replaceAll('&','&amp;')+'"'));}
 const index=html('index.html');assert.doesNotMatch(index,/SoldierAccess|access-(?:control|session|policy)|data-soldier-locked/);assert.match(index,/>Masuk Owner<\/a>/);assert.match(index,/>Jahit · Owner<\/a>/);
});
test('main redirect routes ignore browser-selected authority and never fall back to a legacy app',()=>{
 const s=state();if(!s.active){legacy();return;}const r=realm(s.router);for(const file of Object.keys(routes)){const target=r.api.target(file);assert.equal(r.api.redirect(file),true);assert.equal(r.targets.at(-1),target);}for(const unknown of ['__proto__','../index.html','jahit-command.html?division=owner','https://foreign.invalid'])assert.throws(()=>r.api.target(unknown));r.window.location.replace=()=>{throw Error('blocked');};assert.equal(r.api.redirect('jahit-command.html'),false);assert.doesNotMatch(s.router,/firebase|fetch\(|serviceWorker|caches\.|localStorage|sessionStorage|indexedDB/i);
});
test('installed app cutover retains its identity and versions manifest/start/router/reload URLs without deleting drafts',()=>{
 const manifest=JSON.parse(html('manifest.json'));assert.equal(manifest.id,'./index.html');assert.equal(manifest.scope,'./');const s=state();if(!s.active){assert.equal(manifest.start_url,'./index.html');legacy();return;}
 assert.match(manifest.start_url,/^\.\/index\.html\?appVersion=secure-v1-[a-f0-9]{24}$/);const version=manifest.start_url.split('=')[1];assert.ok(html('index.html').includes('href="manifest.json?v='+version+'"'));assert.ok(html('index.html').includes("location.replace('index.html?appVersion="+version+"')"));for(const file of Object.keys(routes))assert.ok(html(file).includes('src="soldier-main-routing.js?v='+version+'"'));assert.doesNotMatch(s.router,/removeItem|deleteDatabase|caches\.delete|unregister\(/);
});
