'use strict';
const { test } = require('node:test'), assert = require('node:assert/strict'), vm = require('node:vm'), fs = require('node:fs');
const Access = require('../owner-access-management-client.js'), Codec = require('../owner-access-management-codec.js'), Server = require('../server/apps-script/owner-access-management.cjs');
const F = require('./fixtures/identity-tenant.cjs');
const { createLifecycleRuntimeFixture } = require('./helpers/lifecycle-runtime-fixture.cjs'), { fakeIndexedDB } = require('./helpers/command-indexeddb-fixture.cjs');
const DB = 'soldier-owner-access-journal:v1', URL = 'https://script.google.com/macros/s/SYNTHETIC_OWNER_ACCESS_0000000000000/dev';
function fixture(division = 'owner', indexed = fakeIndexedDB()) { const native = createLifecycleRuntimeFixture(division), { tariffPolicy, ...runtimeOptions } = native.options; runtimeOptions.profileLabels = { 'approval-1': 'Synthetic partner', 'approval-q': 'Synthetic quality' }; const states = [], listeners = new Set(), calls = [], controls = {}; let current, ids = 0, tokens = 0; const user = { uid: native.who.uid, async getIdToken() { tokens++; if (controls.tokenGate) await controls.tokenGate(); return native.readInput().idToken; } }; current = user;
  function runner(success, failure) { return { withSuccessHandler(fn) { return runner(fn, failure); }, withFailureHandler(fn) { return runner(success, fn); }, soldierOwnerAccessRpc(text) { const request = JSON.parse(text); calls.push(F.copy(request)); queueMicrotask(() => { try { const runtime = Server.createAppsScriptOwnerAccessManagementRuntime(runtimeOptions), gateway = Server.createAppsScriptOwnerAccessManagementRpcGateway({ enabled: true, binding: native.f.binding, runtime }); let result = gateway.dispatchJson(text); if (controls.drop?.(request, result)) { failure(Error('SYNTHETIC_RPC_ACK_LOSS')); return; } if (controls.reply) result = controls.reply(result, request); success(result); } catch { failure(Error('SYNTHETIC_NATIVE_EXCEPTION')); } }); } }; }
  const options = { enabled: true, ...native.f.binding, user, getCurrentUser: () => current, subscribeAuth(cb) { listeners.add(cb); return () => listeners.delete(cb); }, googleScriptRun: runner(), deploymentURL: URL, indexedDB: indexed.api, newId: () => 'synthetic-' + (++ids), onState: s => states.push(s) };
  const create = () => Access.createAppsScriptOwnerAccessBridge(options); return { native, options, indexed, calls, states, controls, user, create, get tokens() { return tokens; }, get listeners() { return listeners.size; }, journals: () => [...(indexed.databases.get(DB)?.stores.get('journals')?.values() || [])], replaceUser(next) { current = next; for (const cb of [...listeners]) cb(next); } };
}
const last = f => f.states.at(-1);
async function connect(f) { const bridge = f.create(); assert.equal((await bridge.connect()).ok, true); return bridge; }
test('OFF controller and bridge ignore injected dependencies and page does no DOM work', async() => { let calls = 0; const options = { enabled: false }; Object.defineProperty(options, 'rpc', { get() { calls++; throw Error(); } }); assert.deepEqual(await Access.createOwnerAccessController(options).connect(), { ok: false, error: 'service_disabled' }); assert.deepEqual(await Access.createAppsScriptOwnerAccessBridge(options).connect(), { ok: false, error: 'service_disabled' }); Access.mountOwnerAccessManagementPage(options).render(new Proxy({}, { get() { calls++; throw Error(); } })); assert.equal(calls, 0); });
test('bridge mounts owner targets after real account/root verification and isolates journal from business data', async() => { const f = fixture(), b = await connect(f); assert.equal(last(f).view.binding.division, 'owner'); assert.equal(last(f).view.targets[0].label, 'Synthetic partner'); assert.equal(last(f).pending.length, 0); assert.equal(f.native.stats.puts, 0); assert.equal(f.indexed.databases.has(DB), true); assert.equal(f.indexed.databases.has('soldier-command-journal:v1'), false); for (const marker of [F.EMAIL, F.QC_EMAIL, 'tarif', 'total', 'kasbonJahit']) assert.equal(JSON.stringify(last(f)).includes(marker), false); b.dispose(); assert.equal(f.listeners, 0); });
test('partner and QC cannot mount access controls or create an owner journal', async() => { for (const division of ['jahit', 'qc']) { const f = fixture(division), b = f.create(); assert.deepEqual(await b.connect(), { ok: false, error: 'access_denied' }); assert.equal(f.indexed.stats.opens, 0); assert.equal(f.native.stats.puts, 0); b.dispose(); } });
test('confirmed revoke preserves wages and stores exact command without tokens in separate journal', async() => { const f = fixture(), b = await connect(f), before = F.copy(f.native.root.soldier); assert.equal((await b.revoke('approval-1')).ok, true); assert.equal(last(f).view.targets[0].status, 'revoked'); assert.equal(last(f).pending.length, 0); assert.deepEqual(f.native.root.soldier, before); const raw = f.journals()[0], doc = JSON.parse(raw); assert.equal(doc.entries[0].phase, 'accepted'); assert.equal(doc.entries[0].command.expectedGrantRevision, 1); for (const marker of ['idToken', f.native.readInput().idToken, F.EMAIL, F.QC_EMAIL, 'tarif', 'total']) assert.equal(raw.includes(marker), false); assert.equal(f.native.stats.puts, 1); b.dispose(); });
test('a UUID beginning with a digit becomes a stable prefixed request ID and confirms once', async() => { const f = fixture(); f.options.newId = () => '01234567-89ab-4cde-8012-abcdef012345'; const b = await connect(f); const result = await b.revoke('approval-1'); assert.equal(result.ok, true); assert.equal(result.requestId, 'revoke-01234567-89ab-4cde-8012-abcdef012345'); assert.equal(f.native.stats.puts, 1); b.dispose(); });
test('lost acknowledgment survives browser reload and resolves original command without another PUT', async() => { const f = fixture(), a = await connect(f); f.controls.drop = request => request.kind === 'execute'; assert.deepEqual(await a.revoke('approval-1'), { ok: false, error: 'result_unknown', retrySameCommand: true }); const command = F.copy(last(f).pending[0]); assert.equal(JSON.parse(f.journals()[0]).entries[0].phase, 'dispatched'); a.dispose(); delete f.controls.drop; const b = await connect(f); assert.deepEqual(last(f).pending, [command]); assert.equal((await b.retry(command.requestId)).replayed, true); assert.equal(f.native.stats.puts, 1); assert.equal(last(f).pending.length, 0); b.dispose(); });
test('retry first resolves a dropped before-write request and only sends its exact retained command', async() => { const f = fixture(), b = await connect(f); let first = true; const old = f.options.googleScriptRun; f.options.googleScriptRun = old; f.native.hooks.budget = () => { if (first) { first = false; return false; } return true; }; assert.deepEqual(await b.revoke('approval-1'), { ok: false, error: 'rate_limited' }); const pending = last(f).pending[0]; assert.equal(pending.profileId, 'approval-1'); assert.equal(f.native.stats.puts, 0); assert.equal((await b.retry(pending.requestId)).ok, true); assert.equal(f.native.stats.puts, 1); assert.deepEqual(f.calls.filter(q => ['execute', 'resolve'].includes(q.kind)).map(q => q.kind), ['execute', 'resolve', 'execute']); b.dispose(); });
test('stale first command becomes rejected while uncertain stale retry stays pending', async() => { const f = fixture(), b = await connect(f); f.native.hooks.beforePut = () => { f.native.root.privateRoot = 'Synthetic concurrent'; }; assert.deepEqual(await b.revoke('approval-1'), { ok: false, error: 'conflict' }); assert.equal(JSON.parse(f.journals()[0]).entries[0].phase, 'rejected'); assert.equal(last(f).pending.length, 0); assert.equal(f.native.stats.writes, 0); b.dispose(); const g = fixture(), c = await connect(g); g.controls.drop = request => request.kind === 'execute'; assert.equal((await c.revoke('approval-1')).error, 'result_unknown'); const cmd = last(g).pending[0]; delete g.controls.drop; g.controls.reply = (reply, request) => request.kind === 'resolve' ? JSON.stringify({ ok: false, error: 'conflict' }) : reply; assert.equal((await c.retry(cmd.requestId)).error, 'conflict'); assert.equal(JSON.parse(g.journals()[0]).entries[0].phase, 'dispatched'); assert.equal(last(g).pending.length, 1); c.dispose(); });
test('unknown target, revoked target and UID selector cannot issue a write', async() => { const f = fixture(), b = await connect(f); for (const target of ['owner-1', 'missing', { uid: 'partner-1' }]) assert.equal((await b.revoke(target)).error, 'invalid_request'); assert.equal(f.native.stats.puts, 0); assert.equal((await b.revoke('approval-1')).ok, true); assert.equal((await b.revoke('approval-1')).error, 'invalid_request'); assert.equal(f.native.stats.puts, 1); b.dispose(); });
test('journal write failure prevents dispatch and keeps production grant unchanged', async() => { const f = fixture(), b = await connect(f); f.indexed.control.putFail = true; assert.equal((await b.revoke('approval-1')).error, 'unavailable'); assert.equal(f.calls.some(q => q.kind === 'execute'), false); assert.equal(f.native.stats.puts, 0); assert.equal(f.native.root.authorityTenants[F.TENANT].grants['partner-1'].profile.active, true); b.dispose(); });
test('account change clears view and pending display but retains uncertain command on disk', async() => { const f = fixture(), b = await connect(f); f.controls.drop = request => request.kind === 'execute'; assert.equal((await b.revoke('approval-1')).error, 'result_unknown'); const raw = f.journals()[0]; f.replaceUser(null); assert.equal(last(f).phase, 'blocked'); assert.equal(last(f).view, null); assert.deepEqual(last(f).pending, []); assert.equal(f.journals()[0], raw); assert.deepEqual(await b.refresh(), { ok: false, error: 'access_denied' }); });
test('new Auth object with same UID or token method drift cannot reuse owner authority', async() => { const f = fixture(), b = await connect(f), count = f.calls.length; f.replaceUser({ ...f.user }); assert.equal(last(f).view, null); assert.equal((await b.revoke('approval-1')).error, 'access_denied'); assert.equal(f.calls.length, count); const g = fixture(), c = await connect(g), before = g.calls.length; g.user.getIdToken = async() => g.native.readInput().idToken; assert.equal((await c.refresh()).error, 'access_denied'); assert.equal(last(g).view, null); assert.equal(g.calls.length, before); });
test('signout during token wait sends no request and clears UI', async() => { const f = fixture(), b = await connect(f); let release; f.controls.tokenGate = () => new Promise(resolve => { release = resolve; }); const before = f.calls.length, pending = b.refresh(); await new Promise(resolve => setImmediate(resolve)); f.replaceUser(null); release(); assert.equal((await pending).error, 'access_denied'); assert.equal(f.calls.length, before); assert.equal(last(f).view, null); });
test('foreign binding, raw email extra fields and duplicate JSON responses never mount', async() => { for (const alter of [v => v.view.binding.tenantId = 'foreign-tenant', v => v.view.targets[0].email = F.EMAIL, v => v.view.targets[0].label = 'unsafe\nlabel']) { const f = fixture(); f.controls.reply = raw => { const v = JSON.parse(raw); alter(v); return JSON.stringify(v); }; assert.equal((await f.create().connect()).error, 'unavailable'); assert.equal(f.indexed.stats.opens, 0); } const g = fixture(); g.controls.reply = () => '{"ok":true,"ok":false,"error":"access_denied"}'; assert.equal((await g.create().connect()).error, 'unavailable'); assert.equal(g.indexed.stats.opens, 0); });
test('tampered journal and a different deployment scope cannot replay retained command', async() => { const f = fixture(), a = await connect(f); f.controls.drop = request => request.kind === 'execute'; assert.equal((await a.revoke('approval-1')).error, 'result_unknown'); a.dispose(); const map = f.indexed.databases.get(DB).stores.get('journals'), [key, raw] = [...map.entries()][0], doc = JSON.parse(raw); doc.scope.deploymentURL = URL.replace('/dev', '/exec'); map.set(key, JSON.stringify(doc)); delete f.controls.drop; const b = f.create(); assert.equal((await b.connect()).error, 'unavailable'); assert.equal(f.native.stats.puts, 1); b.dispose(); });
test('malformed success after possible write stays unresolved until original receipt is confirmed', async() => { const f = fixture(), b = await connect(f); f.controls.reply = (raw, request) => { const v = JSON.parse(raw); if (request.kind === 'execute' && v.ok) v.profileId = 'approval-q'; return JSON.stringify(v); }; assert.deepEqual(await b.revoke('approval-1'), { ok: false, error: 'result_unknown', retrySameCommand: true }); assert.equal(last(f).pending.length, 1); delete f.controls.reply; assert.equal((await b.retry(last(f).pending[0].requestId)).ok, true); assert.equal(f.native.stats.puts, 1); b.dispose(); });
test('receipt journal persistence failure cannot claim completion and reload still resolves once', async() => { const f = fixture(), b = await connect(f); f.controls.reply = (raw, request) => { if (request.kind === 'execute') f.indexed.control.putFail = true; return raw; }; assert.equal((await b.revoke('approval-1')).error, 'result_unknown'); assert.equal(JSON.parse(f.journals()[0]).entries[0].phase, 'dispatched'); b.dispose(); f.indexed.control.putFail = false; delete f.controls.reply; const c = await connect(f); assert.equal((await c.retry(last(f).pending[0].requestId)).ok, true); assert.equal(f.native.stats.puts, 1); c.dispose(); });
test('JSON codec rejects escaped duplicate keys, getters, sparse arrays and hostile identity fields', () => { assert.throws(() => Codec.parseOwnerAccessJSON('{"kind":"read","k\\u0069nd":"execute"}')); let hits = 0; const raw = {}; Object.defineProperty(raw, 'kind', { enumerable: true, get() { hits++; return 'revokeAccess'; } }); assert.throws(() => Codec.normalizeOwnerAccessCommand(raw)); assert.equal(hits, 0); assert.throws(() => Codec.normalizeOwnerAccessView({ binding: {}, targets: new Array(2) })); const command = { kind: 'revokeAccess', requestId: 'r-1', profileId: 'approval-1', expectedOwnerGrantRevision: 1, expectedApprovalRevision: 2, expectedGrantRevision: 1 }; for (const extra of [{ uid: 'partner-1' }, { role: 'owner' }, { total: 0 }, { workerId: 'worker-2' }]) assert.throws(() => Codec.normalizeOwnerAccessCommand({ ...command, ...extra })); });
class Element { constructor(tag) { this.tagName = tag; this.children = []; this.textContent = ''; this.events = {}; } appendChild(node) { node.parent = this; this.children.push(node); } replaceChildren(...nodes) { this.children = []; for (const n of nodes) this.appendChild(n); } addEventListener(event, fn) { this.events[event] = fn; } remove() { if (this.parent) this.parent.children = this.parent.children.filter(n => n !== this); } }
test('owner page needs explicit confirmation, renders labels as text and retains review button after unknown result', async() => { const document = { createElement: tag => new Element(tag) }, container = document.createElement('main'), f = fixture(); let page; f.options.onState = state => { f.states.push(state); page?.render(state); }; const b = f.create(); page = Access.mountOwnerAccessManagementPage({ enabled: true, document, container, controller: b }); assert.equal((await b.connect()).ok, true); const all = () => { const visit = node => [node, ...node.children.flatMap(visit)]; return visit(container); }, button = title => all().find(n => n.tagName === 'button' && n.textContent === title); button('Cabut akses').events.click(); assert.equal(f.native.stats.puts, 0); assert.ok(button('Ya, cabut akses')); button('Batal').events.click(); assert.equal(f.native.stats.puts, 0); button('Cabut akses').events.click(); f.controls.drop = q => q.kind === 'execute'; button('Ya, cabut akses').events.click(); for (let i = 0; i < 10; i++) await new Promise(resolve => setImmediate(resolve)); assert.equal(f.native.stats.puts, 1); assert.ok(button('Periksa pencabutan akses Synthetic partner')); assert.equal(all().some(n => n.textContent.includes(F.EMAIL)), false); page.dispose(); b.dispose(); });
test('RPC timeout returns fixed error and a late success cannot replace an already delivered result', async() => { const source = fs.readFileSync(require.resolve('../owner-access-management-client.js'), 'utf8'), codecSource = fs.readFileSync(require.resolve('../owner-access-management-codec.js'), 'utf8'), callbacks = []; const f = fixture(); f.options.googleScriptRun = { withSuccessHandler(fn) { this.success = fn; return this; }, withFailureHandler(fn) { this.failure = fn; return this; }, soldierOwnerAccessRpc() {} }; const context = vm.createContext({ SoldierProductionCommandStore: require('../production-command-store.js'), hostOptions: f.options, setTimeout(fn) { callbacks.push(fn); return callbacks.length; }, clearTimeout() {} }); vm.runInContext(codecSource, context); vm.runInContext(source, context); const b = vm.runInContext('SoldierOwnerAccessManagement.createAppsScriptOwnerAccessBridge(Object.assign({},hostOptions))', context), result = b.connect(); for (let i = 0; i < 4; i++) await new Promise(resolve => setImmediate(resolve)); assert.equal(callbacks.length, 1); callbacks[0](); const delivered = await result; assert.equal(delivered.error, 'unavailable'); f.options.googleScriptRun.success('{"ok":false,"error":"access_denied"}'); assert.equal(delivered.error, 'unavailable'); assert.equal(f.indexed.stats.opens, 0); });
