'use strict';
const readReviewedLegacyHtml=require('./helpers/legacy-html-source.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Builder=require('../server/apps-script/build-owner-legacy-page.cjs'),Bootstrap=require('../apps-script-owner-legacy-bootstrap.js'),Client=require('../owner-business-storage-client.js'),Codec=require('../owner-business-storage-codec.js'),Gateway=require('../server/apps-script/owner-business-rpc-gateway.cjs');
const {createLifecycleRuntimeFixture}=require('./helpers/lifecycle-runtime-fixture.cjs'),{fakeIndexedDB}=require('./helpers/command-indexeddb-fixture.cjs');
const CONFIG=Object.freeze({enabled:true,photosEnabled:false,projectId:'demo-identity-state',databaseURL:'https://demo-identity-state-default-rtdb.asia-southeast1.firebasedatabase.app',tenantId:'synthetic-tenant',deploymentURL:'https://script.google.com/macros/s/SYNTHETIC_OWNER_LEGACY_000000000000000/dev',apiKey:'SYNTHETIC_PUBLIC_API_KEY_000000000',authDomain:'demo-identity-state.firebaseapp.com'});
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function photoChildFixture(division='owner'){
  const f=childFixture(division),slots={images:{present:true,value:{'SERIES|ITEM':'data:image/png;base64,U1lOVEhFVElD'}},productionPhotos:{present:true,value:{items:[]}}},watchers=new Set(),refs=new WeakMap();let connected=false,revision=1,disposed=false;
  f.cfg.photosEnabled=true;f.capability.configurationJSON=JSON.stringify(f.cfg);const app={options:{projectId:f.cfg.projectId,databaseURL:f.cfg.databaseURL,apiKey:f.cfg.apiKey,authDomain:f.cfg.authDomain}},nativeDb={app};f.capability.auth.app=app;
  const stats={loads:0,reads:0,writes:0,published:0,updaters:0,option:null};
  const state=()=>({phase:disposed?'blocked':connected?'ready':'idle',error:disposed?'access_denied':null,busy:false,...JSON.parse(JSON.stringify(slots)),revision,dataDigest:String(revision).padStart(64,'0'),pending:[]});
  const snap=slot=>Object.freeze({val:()=>JSON.parse(JSON.stringify(slots[slot].present?slots[slot].value:null)),exists:()=>slots[slot].present});
  const nativeSDK={ref(){throw Error('native SDK leaked');},get(){throw Error('native SDK leaked');},onValue(){throw Error('native SDK leaked');},runTransaction(){throw Error('native SDK leaked');},getDatabase:()=>nativeDb};
  f.capability.loadPhotoSDK=async root=>{assert.equal(root,f.root);stats.loads++;return{app,auth:f.capability.auth,db:nativeDb,sdk:nativeSDK};};
  f.root.SoldierOwnerProductionPhotos={createOwnerProductionPhotosClient(options){stats.option=options;assert.equal(options.user,f.capability.user);assert.equal(options.auth,f.capability.auth);assert.equal(options.db,nativeDb);assert.equal(options.app,app);assert.equal(options.binding.division,'owner');const sdk={ref(db,path){assert.equal(db,options.legacyDatabase);const slot=path==='soldier/produksi/images'?'images':path==='soldier/productionPhotos'?'productionPhotos':null;if(!slot)throw Error('fixed photo roots only');const r=Object.freeze({});refs.set(r,slot);return r;},get:async r=>{stats.reads++;return snap(refs.get(r));},onValue(r,callback){const emit=()=>callback(snap(refs.get(r)));watchers.add(emit);queueMicrotask(emit);return()=>watchers.delete(emit);},async runTransaction(r,fn){stats.updaters++;const slot=refs.get(r),value=fn(snap(slot).val());if(value===undefined)return{committed:false,snapshot:snap(slot)};stats.writes++;slots[slot]=value===null?{present:false}:{present:true,value:JSON.parse(JSON.stringify(value))};revision++;for(const watcher of watchers)watcher(state());return{committed:true,snapshot:snap(slot)};},set(r,value){return sdk.runTransaction(r,()=>value).then(()=>{});},update(){throw Error('not used');},remove(r){return sdk.set(r,null);}};return{get ready(){return connected&&!disposed;},sdk,connect:async()=>{connected=true;options.onState(state());return{ok:true};},getSnapshot:state,refresh:async()=>({ok:true}),retry:async()=>({ok:true}),subscribe(callback){watchers.add(callback);queueMicrotask(()=>callback(state()));return()=>watchers.delete(callback);},async publishPhotos(){stats.published++;},dispose(){disposed=true;watchers.clear();}};}};
  return{...f,photoStats:stats,photoSlots:slots,photoWatchers:watchers,nativeDb};
}
function retainedLaporanMerge(base,local,remote){
  const text=Builder.createProgram('laporan',CONFIG).scripts.find(s=>s.includes('function mergeLaporanRoot(')),one=/function laporanRoot\(raw\)\{[^\n]+\}/.exec(text)?.[0],merge=/function mergeLaporanRoot\(base,local,remote\)\{[\s\S]*?\n\}/.exec(text)?.[0];assert.ok(one&&merge);
  const context={ProductionSync:require('../production-sync.js'),CuttingPlanReconcile:require('../cutting-plan-reconcile.js')};context.window=context;vm.createContext(context);vm.runInContext(one+'\n'+merge,context);const result=context.mergeLaporanRoot(base,local,remote);assert.equal(result.ok,true);return JSON.parse(JSON.stringify(result.value));
}
function nativePhotoRealmFixture(){
  const f=childFixture(),Scope=require('../server/apps-script/protected-storage-scope.cjs'),Crypto=require('node:crypto'),clone=value=>JSON.parse(JSON.stringify(value)),stats={reads:0,writes:0,transactions:0,noops:0},control={};
  f.cfg.photosEnabled=true;f.capability.configurationJSON=JSON.stringify(f.cfg);const source=clone(f.native.root);source.soldier.produksi.images={photo:'data:image/png;base64,U1lOVEhFVElD'};source.soldier.productionPhotos={pesananOffline:[{items:[{id:'synthetic-display',gambar:'data:image/png;base64,U1lOVEhFVElD'}]}]};
  const migration=Scope.prepareOwnerSdkPhotoMigration({root:source,binding:f.native.f.binding,migrationId:'synthetic-owner-page-photos',expectedRootETag:'"synthetic-photo"'});assert.equal(migration.ok,true);let wire=clone(migration.nextRoot[Scope.KEY].photos);const nativeWatchers=new Set(),nativeRefs=new WeakSet(),app={name:'synthetic-native-parent',options:{projectId:f.cfg.projectId,databaseURL:f.cfg.databaseURL,apiKey:f.cfg.apiKey,authDomain:f.cfg.authDomain}},db={app};f.capability.auth.app=app;
  const sdk={getDatabase:a=>{assert.equal(a,app);return db;},ref(which,path){assert.equal(which,db);assert.equal(path,'soldierProtectedStorageV1/photos');const r={};nativeRefs.add(r);return r;},async get(r){assert.ok(nativeRefs.has(r));stats.reads++;return{val:()=>JSON.stringify(wire)};},onValue(r,callback){assert.ok(nativeRefs.has(r));nativeWatchers.add(callback);queueMicrotask(()=>{if(nativeWatchers.has(callback))callback({val:()=>JSON.stringify(wire)});});return()=>nativeWatchers.delete(callback);},async runTransaction(r,updater,settings){assert.ok(nativeRefs.has(r));assert.equal(Object.getOwnPropertyDescriptor(settings,'applyLocally').value,false);stats.transactions++;const text=updater(JSON.stringify(wire));if(text===undefined)return{committed:false,snapshot:{val:()=>JSON.stringify(wire)}};const proposal=JSON.parse(text),parsed=Scope.inspectOwnerSdkPhotoEnvelope({photos:proposal});assert.equal(parsed.ok,true);if(JSON.stringify(proposal)===JSON.stringify(wire))stats.noops++;else{const result=Scope.prepareOwnerSdkPhotoMutation({photos:wire,command:{requestId:proposal.lastReceipt.requestId,expectedRevision:wire.revision,expectedDataDigest:wire.dataDigest,...parsed.data}});assert.equal(result.ok,true);assert.deepEqual(proposal,result.nextPhotos);wire=clone(proposal);stats.writes++;}for(const callback of [...nativeWatchers])queueMicrotask(()=>{if(nativeWatchers.has(callback))callback({val:()=>JSON.stringify(wire)});});if(control.dropAck)throw Error('SYNTHETIC_NATIVE_ACK_LOST');return{committed:true,snapshot:{val:()=>JSON.stringify(wire)}};}};
  f.capability.loadPhotoSDK=async root=>{assert.equal(root,f.root);assert.deepEqual(f.calls,['read']);return{app,db,auth:f.capability.auth,sdk};};
  f.root.crypto={subtle:Crypto.webcrypto.subtle,randomUUID:()=>Crypto.randomUUID()};f.root.window=f.root;f.root.setTimeout=setTimeout;f.root.clearTimeout=clearTimeout;vm.createContext(f.root);
  for(const file of ['owner-business-storage-codec.js','owner-business-storage-journal.js','owner-business-storage-client.js','owner-production-photos-codec.js','owner-production-photos-client.js','apps-script-owner-legacy-bootstrap.js','production-materials.js','cutting-plan.js','production-sync.js','cutting-plan-reconcile.js'])vm.runInContext(fs.readFileSync(file,'utf8'),f.root,{filename:file});
  const text=Builder.createProgram('laporan',CONFIG).scripts.find(s=>s.includes('function mergeLaporanRoot('));vm.runInContext(/function laporanRoot\(raw\)\{[^\n]+\}/.exec(text)[0]+'\n'+/function mergeLaporanRoot\(base,local,remote\)\{[\s\S]*?\n\}/.exec(text)[0],f.root);
  f.root.syntheticCapability=f.capability;f.root.syntheticHost=f.host;f.root.syntheticProgramJSON=JSON.stringify(f.program);
  const evaluate=code=>vm.runInContext(code,f.root);
  return{...f,photoStats:stats,photoControl:control,nativeWatchers,evaluate,wire:()=>clone(wire),start:()=>evaluate('SoldierOwnerLegacyBootstrapAPI.startChild({document,host:syntheticHost,program:JSON.parse(syntheticProgramJSON),capability:syntheticCapability})')};
}
function documentFixture(root={}){
  const observations={scripts:[],html:[],events:[],frames:[],removed:0};
  class Element{constructor(tag){this.tagName=tag;this.ownerDocument=document;this.children=[];this.listeners=new Map();this.style={};this.attrs={};this.contentWindow={};}replaceChildren(...children){this.children=children;}append(...children){this.children.push(...children);}appendChild(child){this.append(child);if(child.tagName==='script'){observations.scripts.push(child.textContent);vm.runInNewContext(child.textContent,root);}return child;}setAttribute(k,v){this.attrs[k]=v;}removeAttribute(k){delete this.attrs[k];}remove(){observations.removed++;}addEventListener(k,fn){this.listeners.set(k,fn);}removeEventListener(k,fn){if(this.listeners.get(k)===fn)this.listeners.delete(k);}set innerHTML(v){observations.html.push(v);this._html=v;}get innerHTML(){return this._html;}set srcdoc(value){observations.frames.push(value);this._srcdoc=value;}get srcdoc(){return this._srcdoc;}}
  const document={defaultView:root,createElement:tag=>new Element(tag),querySelectorAll:()=>[],dispatchEvent:event=>observations.events.push(event.type),importNode:node=>node};document.head=new Element('head');document.body=new Element('body');document.documentElement=new Element('html');const host=new Element('main');document.body.append(host);
  root.document=document;root.DOMParser=class{parseFromString(){return{head:{children:[]}};}};root.Event=class{constructor(type){this.type=type;}};
  return{document,host,root,observations};
}
function childFixture(division='owner'){
  const native=createLifecycleRuntimeFixture(division),indexed=fakeIndexedDB(),authWatchers=new Set(),control={replyStatus:[]},calls=[];let counter=0,current;native.root.soldier.hpp={settings:{margin:10}};
  const user={uid:native.who.uid,emailVerified:true,providerData:[{providerId:'google.com'}],getIdToken:async()=>native.readInput().idToken};current=user;
  const cfg={...CONFIG,...native.f.binding,authDomain:native.f.binding.projectId+'.firebaseapp.com'};
  function runner(success,failure){return{withSuccessHandler(fn){return runner(fn,failure);},withFailureHandler(fn){return runner(success,fn);},soldierOwnerBusinessRpc(text){const kind=JSON.parse(text).kind;calls.push(kind);queueMicrotask(()=>{try{if(control.gate){control.gate(()=>this.soldierOwnerBusinessRpc(text));control.gate=null;return;}const gateway=Gateway.createAppsScriptOwnerBusinessRpcGateway({enabled:true,binding:native.f.binding,runtime:native.create()}),reply=gateway.dispatchJson(text),status=JSON.parse(reply);control.replyStatus.push({kind,ok:status.ok,error:status.error||null});if(control.dropReply&&kind==='execute'){failure(Error('SYNTHETIC_LOST_ACK'));return;}success(reply);}catch{failure(Error('SYNTHETIC_HOST_ERROR'));}});}};}
  const capability={configurationJSON:JSON.stringify(cfg),user,auth:{currentUser:user},getCurrentUser:()=>current,isCurrent:()=>current===user,subscribeAuth(callback){authWatchers.add(callback);return()=>authWatchers.delete(callback);},googleScriptRun:runner(),onReady(){control.ready=(control.ready||0)+1;},onClear(){control.clear=(control.clear||0)+1;}};
  const doc=documentFixture({SoldierOwnerBusinessStorage:Client,SoldierOwnerBusinessCodec:Codec,indexedDB:indexed.api,crypto:{randomUUID:()=> 'synthetic-owner-request-'+ ++counter}});
  const program={module:'hpp',head:'<title>Synthetic owner UI</title>',body:'<section>Original controls</section>',scripts:['globalThis.syntheticOwnerScriptExecuted=true;']};
  return{...doc,native,indexed,cfg,capability,program,control,calls,authWatchers,change(next){current=next;capability.auth.currentUser=next;for(const callback of [...authWatchers])callback(next);},start:()=>Bootstrap.startChild({document:doc.document,host:doc.host,program,capability})};
}
function parentFixture(photosEnabled=false){
  const doc=documentFixture(),auth={currentUser:null},control={photosLoaded:0,...(photosEnabled?{configuration:{...CONFIG,photosEnabled:true}}:{})},runner={withSuccessHandler(){},withFailureHandler(){}},apps=[];let callback,initializations=0,popups=0;
  const sdk={SDK_VERSION:'10.12.2',getApps:()=>apps,initializeApp(options,name){initializations++;const app={options,name};apps.push(app);auth.app=app;return app;},getAuth:()=>auth,setPersistence:async()=>{},browserSessionPersistence:{},onAuthStateChanged(a,fn){callback=fn;fn(a.currentUser);return()=>{control.off=(control.off||0)+1;};},signInWithPopup:async()=>{popups++;},GoogleAuthProvider:class{},signOut:async()=>{auth.currentUser=null;callback(null);}};
  const bootstrap=Bootstrap.createBootstrap({getConfiguration:()=>control.configuration||CONFIG,getChildHTML:()=>control.child||'<!doctype html><html><body>Synthetic child</body></html>',getScriptRun:()=>runner,sdkLoader:async()=>sdk,photoSDKLoader:async()=>{control.photosLoaded++;return{ref(){},get(){},onValue(){},runTransaction(){},getDatabase:app=>({app})};}});
  return{...doc,control,auth,runner,bootstrap,get initializations(){return initializations;},get popups(){return popups;},change(user){auth.currentUser=user;callback(user);}};
}
test('nine pinned owner pages assemble SOURCE OFF without loading any browser or server host',()=>{
  assert.equal(Object.keys(Builder.PAGES).length,9);
  for(const module of Object.keys(Builder.PAGES)){const p=Builder.createPage({module});assert.equal(p.metadata.sourceOff,true);assert.equal(p.metadata.originalDatabaseSdkRemoved,true);assert.equal(p.metadata.ownerReadBeforeOriginalScripts,true);assert.equal(p.metadata.nativeExecutionProven,false);assert.equal(p.metadata.photoWritesAvailable,false);assert.ok(Buffer.byteLength(p.html)<1024*1024);const inline=[...p.html.matchAll(/<script>([\s\S]*?)<\/script>/g)];assert.equal(inline.length,2);for(const m of inline)new vm.Script(m[1]);}
});
test('all original inline scripts and dependencies become inert reviewed program strings, without database loaders',()=>{
  for(const module of Object.keys(Builder.PAGES)){const program=Builder.createProgram(module,CONFIG);assert.ok(program.body.length>1000);assert.ok(program.scripts.length>0);assert.doesNotMatch(program.head+program.body,/<script\b|<iframe\b|http-equiv=/i);assert.doesNotMatch(program.scripts.join('\n'),/firebase-database\.js|app-install\.js|access-control\.js|import\(/);for(const script of program.scripts)new vm.Script(script);}
});
test('source drift, arbitrary paths/modules/options, source-on blank configuration and descriptors fail closed',()=>{
  const file='potong-command.html',raw=readReviewedLegacyHtml(file);assert.throws(()=>Builder.reviewedSource(file,raw+'\n'));assert.throws(()=>Builder.reviewedSource('../outside.html',raw));assert.throws(()=>Builder.createPage({module:'../../outside'}));assert.throws(()=>Builder.createPage({module:'stok',workerId:'synthetic-worker'}));assert.throws(()=>Builder.createPage({module:'stok',configuration:{...Bootstrap.DEFAULT_CONFIGURATION,enabled:true}}));let touched=0;const options={module:'stok'};Object.defineProperty(options,'configuration',{enumerable:true,get(){touched++;return CONFIG;}});assert.throws(()=>Builder.createPage(options));assert.equal(touched,0);
});
test('fixed connection transforms leave old draft/journal keys intact and prevent automatic catalogue migration',()=>{
  const potong=Builder.createProgram('potong',CONFIG).scripts.join('\n'),laporan=Builder.createProgram('laporan',CONFIG).scripts.join('\n'),jahit=Builder.createProgram('jahit',CONFIG).scripts.join('\n');assert.doesNotMatch(potong,/localStorage\.removeItem\('potong_deleted_tombstones'\)|if\(k\.startsWith\('potong_'\)\)/);assert.match(potong,/potong_sync_journal_v1/);assert.match(potong,/potong_meta_journal_v1/);assert.match(laporan,/SoldierOwnerLegacyInitialBusiness/);assert.doesNotMatch(laporan,/p\.bsInputs = \[\{|delete p\.poJumlah/);assert.match(laporan,/laporan_production_journal_v1/);assert.match(jahit,/jahit_production_journal_v1/);assert.match(jahit,/legacy\.present/);
});
test('menu routes stay in the fixed web app and local-only nota/retur status is explicit',()=>{
  const p=Builder.createProgram('laporan',CONFIG);assert.doesNotMatch(p.body,/href="(?:index|stok-bahan-command|potong-command)\.html/);assert.doesNotMatch(p.body,/location\.href='index\.html'/);const generated=Builder.createPage({module:'laporan',configuration:CONFIG});assert.match(generated.html,/\?division=owner&amp;ownerModule=/);for(const module of ['nota','retur'])assert.equal(Builder.createPage({module}).metadata.localOnly,true);assert.equal(Builder.createPage({module:'hpp'}).metadata.localOnly,false);
});
test('SOURCE OFF Auth bootstrap touches no loader, native runner, child source or DOM',async()=>{
  let touched=0;const api=Bootstrap.createBootstrap({getConfiguration:()=>Bootstrap.DEFAULT_CONFIGURATION,getChildHTML(){touched++;throw Error();},getScriptRun(){touched++;throw Error();},sdkLoader(){touched++;throw Error();}});assert.deepEqual(await api.start({}),{ok:false,error:'service_disabled'});assert.equal(touched,0);
});
test('parent does not mount a child for signed-out, password-only or unverified identities',async()=>{
  const f=parentFixture();void f.bootstrap.start({document:f.document,host:f.host});await tick();assert.equal(f.observations.frames.length,0);f.change({uid:'synthetic-user',emailVerified:true,providerData:[{providerId:'password'}],getIdToken:async()=>''});assert.equal(f.observations.frames.length,0);f.change({uid:'synthetic-user',emailVerified:false,providerData:[{providerId:'google.com'}],getIdToken:async()=>''});assert.equal(f.observations.frames.length,0);assert.equal(f.initializations,1);
});
test('parent capability is confined to captured Auth user and exact owned frame, and removed on account change',async()=>{
  const f=parentFixture(),pending=f.bootstrap.start({document:f.document,host:f.host});await tick();const user={uid:'synthetic-owner',emailVerified:true,providerData:[{providerId:'google.com'}],getIdToken:async()=>''};f.change(user);assert.equal(f.observations.frames.length,1);const frame=f.host.children.find(x=>x.tagName==='iframe'),take=f.root.SoldierOwnerLegacyHost.take;assert.equal(take({}),null);const cap=take(frame.contentWindow);assert.equal(cap.user,user);let cleared=0;cap.subscribeAuth(u=>{if(u===null)cleared++;});cap.onReady();assert.equal((await pending).ok,true);f.change({...user});assert.equal(cleared,1);assert.equal(f.observations.removed,1);assert.equal(take(frame.contentWindow),null);assert.equal(cap.getCurrentUser(),null);
});
test('changed fixed binding or runner during Auth initialization cannot mount original UI',async()=>{
  const f=parentFixture(),pending=f.bootstrap.start({document:f.document,host:f.host});f.control.configuration={...CONFIG};assert.deepEqual(await pending,{ok:false,error:'unavailable'});assert.equal(f.observations.frames.length,0);
});
test('child mounts originals only after real synthetic owner RPC read and durable journal verification',async()=>{
  const f=childFixture(),result=await f.start();assert.equal(result.ok,true);assert.equal(f.control.ready,1);assert.equal(f.root.syntheticOwnerScriptExecuted,true);assert.deepEqual(f.calls,['read']);assert.equal(f.observations.html.length,1);assert.deepEqual(f.observations.events,['DOMContentLoaded']);assert.equal(f.native.stats.writes,0);const access=await f.root.SoldierAccess.connect({apiKey:f.cfg.apiKey,projectId:f.cfg.projectId,databaseURL:f.cfg.databaseURL},'hpp');assert.equal(access.authorized,true);assert.equal(access.profile.owner,true);assert.equal(access.db,f.root.__firebase.getDatabase(access.app));assert.equal(f.root.SoldierOwnerLegacyInitialBusiness.soldier.produksi.images,undefined);result.dispose();
});
test('QC/partner owner-read denial never renders markup or starts a legacy script',async()=>{
  for(const division of ['qc','jahit']){const f=childFixture(division),result=await f.start();assert.equal(result.ok,false);assert.equal(f.observations.html.length,0);assert.equal(f.observations.scripts.length,0);assert.equal(f.root.syntheticOwnerScriptExecuted,undefined);assert.equal(f.native.stats.writes,0);}
});
test('account changes clear child finance DOM/listeners while retaining IndexedDB journals and fixed-target restrictions',async()=>{
  const f=childFixture(),ready=await f.start();assert.equal(ready.ok,true);const scope=await f.root.SoldierAccess.connect({apiKey:f.cfg.apiKey,projectId:f.cfg.projectId,databaseURL:f.cfg.databaseURL},'hpp');let cleanup=0;scope.registerCleanup(()=>cleanup++);await assert.rejects(f.root.SoldierAccess.connect({apiKey:f.cfg.apiKey,projectId:f.cfg.projectId,databaseURL:'https://foreign-demo.firebaseio.com'},'hpp'));await assert.rejects(f.root.SoldierAccess.publishPhotos({}),/Foto belum tersedia/);const stores=f.indexed.databases.size;f.change(null);assert.equal(cleanup,1);assert.equal(f.control.clear,1);assert.equal(f.authWatchers.size,0);assert.equal(f.indexed.databases.size,stores);assert.equal(f.native.stats.writes,0);await assert.rejects(f.root.SoldierAccess.connect({apiKey:f.cfg.apiKey,projectId:f.cfg.projectId,databaseURL:f.cfg.databaseURL},'hpp'));
});
test('visible recovery control resolves a lost original-owner save once without re-running its updater',async()=>{
  const f=childFixture(),mounted=await f.start();assert.equal(mounted.ok,true);const scope=await f.root.SoldierAccess.connect({apiKey:f.cfg.apiKey,projectId:f.cfg.projectId,databaseURL:f.cfg.databaseURL},'hpp'),node=f.root.__firebase.ref(scope.db,'soldier/hpp');let updates=0;f.control.dropReply=true;
  await assert.rejects(f.root.__firebase.runTransaction(node,value=>{updates++;value.settings.margin=20;return value;}),error=>error.code==='result_unknown');assert.equal(f.native.stats.writes,1);assert.equal(updates,1);
  const panel=f.document.body.children.find(child=>child.id==='soldier-owner-recovery'),button=panel.children.find(child=>child.tagName==='button');assert.equal(button.hidden,false);assert.match(panel.children[0].textContent,/perlu dikonfirmasi/);f.control.dropReply=false;await button.listeners.get('click')();assert.equal(f.native.stats.writes,1);assert.equal(updates,1);assert.equal(button.hidden,true,JSON.stringify({replyStatus:f.control.replyStatus,calls:f.calls,disabled:button.disabled,message:panel.children[0].textContent}));assert.equal(f.calls.filter(kind=>kind==='execute').length,1);assert.equal(f.calls.filter(kind=>kind==='resolve').length,1);mounted.dispose();
});
test('photosEnabled false never loads native Database SDK even when a photo factory exists',async()=>{
  const f=photoChildFixture();f.cfg.photosEnabled=false;f.capability.configurationJSON=JSON.stringify(f.cfg);assert.equal((await f.start()).ok,true);assert.equal(f.photoStats.loads,0);await assert.rejects(f.root.SoldierAccess.publishPhotos({}),/Foto belum tersedia/);
});
test('parent photo loader requires explicit enablement, exact owned frame and unchanged captured Auth',async()=>{
  for(const enabled of [false,true]){const f=parentFixture(enabled),started=f.bootstrap.start({document:f.document,host:f.host});await tick();const user={uid:'synthetic-owner',emailVerified:true,providerData:[{providerId:'google.com'}],getIdToken:async()=>''};f.change(user);const frame=f.host.children.find(x=>x.tagName==='iframe'),cap=f.root.SoldierOwnerLegacyHost.take(frame.contentWindow);await assert.rejects(cap.loadPhotoSDK({}));assert.equal(f.control.photosLoaded,0);if(enabled){const captured=await cap.loadPhotoSDK(frame.contentWindow);assert.equal(captured.auth,f.auth);assert.equal(captured.db.app,captured.app);assert.equal(f.control.photosLoaded,1);await cap.loadPhotoSDK(frame.contentWindow);assert.equal(f.control.photosLoaded,1);}else{await assert.rejects(cap.loadPhotoSDK(frame.contentWindow));assert.equal(f.control.photosLoaded,0);}cap.onReady();assert.equal((await started).ok,true);f.change(null);await assert.rejects(cap.loadPhotoSDK(frame.contentWindow));assert.equal(f.control.photosLoaded,enabled?1:0);}
});
test('dedicated photo SDK is acquired only after verified owner business read; partner denial acquires none',async()=>{
  for(const division of ['qc','jahit']){const f=photoChildFixture(division);assert.equal((await f.start()).ok,false);assert.equal(f.photoStats.loads,0);assert.equal(f.observations.scripts.length,0);}
  const f=photoChildFixture();assert.equal((await f.start()).ok,true);assert.deepEqual(f.calls,['read']);assert.equal(f.photoStats.loads,1);const scope=await f.root.SoldierAccess.connect(f.cfg,'hpp');assert.notEqual(scope.db,f.nativeDb);assert.notEqual(scope.sdk,f.photoStats.option.sdk);const ref=scope.sdk.ref(scope.db,'soldier/produksi/images');assert.equal((await scope.sdk.get(ref)).val()['SERIES|ITEM'],f.photoSlots.images.value['SERIES|ITEM']);assert.throws(()=>scope.sdk.ref(scope.db,'soldier/produksi/images/arbitrary'));await f.root.SoldierAccess.publishPhotos({pesananOffline:[]});assert.equal(f.photoStats.published,1);f.change(null);assert.equal(f.photoWatchers.size,0);
});
test('retained Laporan parent merge uploads and deletes a photo using only the fixed photo channel',async()=>{
  const f=photoChildFixture();assert.equal((await f.start()).ok,true);const scope=await f.root.SoldierAccess.connect(f.cfg,'laporan'),api=scope.sdk,r=api.ref(scope.db,'soldier/produksi');let before=(await api.get(r)).val(),next=JSON.parse(JSON.stringify(before)),calls=0;next.images['SERIES|ITEM']='data:image/png;base64,VVBMT0FE';
  let result=await api.runTransaction(r,current=>{calls++;return retainedLaporanMerge(before,next,current);},{applyLocally:false});assert.equal(result.committed,true);assert.equal(result.snapshot.val().images['SERIES|ITEM'],next.images['SERIES|ITEM']);assert.equal(f.photoStats.writes,1);assert.equal(f.native.stats.writes,0);
  before=result.snapshot.val();next=JSON.parse(JSON.stringify(before));delete next.images['SERIES|ITEM'];result=await api.runTransaction(r,current=>{calls++;return retainedLaporanMerge(before,next,current);},{applyLocally:false});assert.deepEqual(result.snapshot.val().images,{});assert.equal(calls,2);assert.equal(f.photoStats.writes,2);assert.equal(f.native.stats.writes,0);
});
test('Laporan business save preserves unchanged nonempty images and rejects compound changes before any write',async()=>{
  const f=photoChildFixture();assert.equal((await f.start()).ok,true);const scope=await f.root.SoldierAccess.connect(f.cfg,'laporan'),api=scope.sdk,r=api.ref(scope.db,'soldier/produksi'),before=(await api.get(r)).val(),next=JSON.parse(JSON.stringify(before));next.produksi[0].series='SYNTHETIC_REVIEWED';
  const result=await api.runTransaction(r,current=>retainedLaporanMerge(before,next,current),{applyLocally:false});assert.equal(result.committed,true);assert.equal(f.native.stats.writes,1);assert.equal(f.photoStats.writes,0);assert.deepEqual(result.snapshot.val().images,before.images);const latest=result.snapshot.val(),mixed=JSON.parse(JSON.stringify(latest));mixed.produksi[0].series='SYNTHETIC_COMPOUND';mixed.images['SERIES|ITEM']='data:image/png;base64,TUlYRUQ';const businessWrites=f.native.stats.writes;
  await assert.rejects(api.runTransaction(r,current=>retainedLaporanMerge(latest,mixed,current),{applyLocally:false}),/barang dan foto sekaligus/);assert.equal(f.native.stats.writes,businessWrites);assert.equal(f.photoStats.writes,0);assert.equal(mixed.produksi[0].series,'SYNTHETIC_COMPOUND');
});
test('real photo client and original Laporan merge work across the iframe realm without leaking native SDK or rewriting money',async()=>{
  const f=nativePhotoRealmFixture();assert.equal((await f.start()).ok,true);
  const proof=await f.evaluate(`(async()=>{const c=SoldierOwnerLegacyConfiguration,a=await SoldierAccess.connect(c,'laporan'),r=__firebase.ref(a.db,'soldier/produksi'),before=(await __firebase.get(r)).val(),local=JSON.parse(JSON.stringify(before));local.images.photo='data:image/png;base64,QUNUVUFM';let calls=0;const photo=await __firebase.runTransaction(r,remote=>{calls++;const result=mergeLaporanRoot(before,local,remote);if(!result.ok)throw Error('synthetic merge');return result.value;},{applyLocally:false});const after=photo.snapshot.val(),business=JSON.parse(JSON.stringify(after));business.produksi[0].series='SYNTHETIC_REALM_EDIT';const saved=await __firebase.runTransaction(r,remote=>{calls++;return mergeLaporanRoot(after,business,remote).value;},{applyLocally:false});return{photoCommitted:photo.committed,businessCommitted:saved.committed,calls,photoPreserved:saved.snapshot.val().images.photo===local.images.photo,nativeExposed:a.db===syntheticCapability.auth.app};})()`);
  assert.deepEqual(JSON.parse(JSON.stringify(proof)),{photoCommitted:true,businessCommitted:true,calls:2,photoPreserved:true,nativeExposed:false});assert.equal(f.photoStats.writes,1);assert.equal(f.native.stats.writes,1);assert.equal(f.wire().receiptCount,1);f.change(null);await tick();assert.equal(f.nativeWatchers.size,0);
});
test('real photo lost ACK is recovered by the visible button with a committed no-op and no repeated form updater',async()=>{
  const f=nativePhotoRealmFixture();assert.equal((await f.start()).ok,true);f.photoControl.dropAck=true;
  const result=await f.evaluate(`(async()=>{globalThis.syntheticUpdates=0;const a=await SoldierAccess.connect(SoldierOwnerLegacyConfiguration,'laporan'),r=__firebase.ref(a.db,'soldier/produksi'),before=(await __firebase.get(r)).val(),local=JSON.parse(JSON.stringify(before));local.images.photo='data:image/png;base64,TE9TVF9BQ0s=';try{await __firebase.runTransaction(r,remote=>{syntheticUpdates++;return mergeLaporanRoot(before,local,remote).value;},{applyLocally:false});return 'unexpected';}catch(error){return error.code;}})()`);assert.equal(result,'result_unknown');assert.equal(f.photoStats.writes,1);assert.equal(f.native.stats.writes,0);const panel=f.document.body.children.find(child=>child.id==='soldier-owner-recovery'),button=panel.children.find(child=>child.tagName==='button');assert.equal(button.hidden,false);f.photoControl.dropAck=false;await button.listeners.get('click')();assert.equal(button.hidden,true);assert.equal(f.photoStats.writes,1);assert.equal(f.photoStats.noops,1);assert.equal(f.evaluate('syntheticUpdates'),1);assert.equal(f.native.stats.writes,0);
});
