'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Http=require('../server/production-http-handler.cjs'),Runtime=require('../server/production-runtime.cjs'),Core=require('../server/production-legacy-operations.cjs'),State=require('../server/production-identity-state.cjs'),F=require('./fixtures/identity-tenant.cjs');
const ORIGIN='https://soldier.example.invalid',TOKEN='synthetic.legacy.token',READ='/v1/production/legacy/own',APPEND='/v1/production/legacy/jahit/append',RESOLVE='/v1/production/legacy/jahit/resolve';
const POLICY={version:'legacy-jahit-current-v1',reviewed:true,timeZone:'Asia/Jakarta',quantityBasis:'good-plus-reject'},scope=()=>({projectId:F.PROJECT,databaseURL:F.URL,tenantId:F.TENANT});
function storedRoot(){return {authorityTenants:{[F.TENANT]:F.copy(F.claimed())},soldier:{produksi:{produksi:[{id:'product-1',series:'Synthetic',namaBarang:'<img onerror=alert(1)>',size:'M',poAktif:true,poJumlah:20,poTanggal:'2026-10-01',assignJahit:[{id:'assignment-1',tukangId:'worker-1',qty:20,sisa:16}],jahit:[{id:'old-operation',tanggal:'2026-10-01',jumlah:4,lolos:3,rijek:1,tukangId:'worker-1',assignmentId:'assignment-1',tarif:10,total:999.75,dibayar:true}],arsip:[]}]},produksi_meta:{tukangJahit:[{id:'worker-1',nama:'Synthetic Partner',tarif:{'Synthetic|<img onerror=alert(1)>':12.5}}]},ownerOnly:{privateCanary:'SYNTHETIC_PRIVATE_OWNER'}}};}
function core(){return Core.createProductionLegacyOperations({enabled:true,binding:scope(),clock:()=>F.NOW,tariffPolicy:POLICY});}
function view(){const result=core().read({root:storedRoot(),identity:F.identity()});assert.equal(result.ok,true);return F.copy(result.view);}
function command(){return {kind:'appendJahit',requestId:'request-1',operationId:'operation-1',productId:'product-1',assignmentId:'assignment-1',expectedGrantRevision:1,expectedSourceVersion:view().products[0].sourceVersion,workDate:null,good:2,reject:1};}
function request(path=READ,c=command()){const get=path===READ,headers={origin:ORIGIN,authorization:'Bearer '+TOKEN,...(!get?{'content-type':'application/json'}:{})},rawBody=get?undefined:Buffer.from(JSON.stringify({command:c}));return {method:get?'GET':'POST',url:path,headers,rawHeaders:Object.entries(headers).flat(),...(rawBody?{rawBody}:{})};}
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},end(v){this.body=v===undefined?null:JSON.parse(v);this.writableEnded=true;}};}
async function run(f,req=request()){const res=response();await f.handler(req,res);return res;}
function fixture(extra={}){const calls=[],service={read:async q=>{calls.push({method:'read',request:q});return {ok:true,view:view()};},execute:async q=>{calls.push({method:'execute',request:q});return {ok:true,replayed:false,operationId:q.command.operationId};},resolve:async q=>{calls.push({method:'resolve',request:q});return {ok:true,replayed:true,operationId:q.command.operationId};}},options={enabled:true,service:{execute:async()=>{throw Error('WRONG_SERVICE');}},legacyOperationsService:service,legacyOperationsBinding:scope(),allowedOrigins:[ORIGIN],deadlineMs:1000,maxInFlight:1,...extra};return {calls,service,options,handler:Http.createProductionHttpHandler(options)};}
test('compatible own GET reconstructs only scoped operational fields with no token/money/private extras',async()=>{const f=fixture(),r=await run(f);assert.equal(r.statusCode,200);assert.deepEqual(r.body,{ok:true,view:view()});assert.deepEqual(f.calls,[{method:'read',request:{idToken:TOKEN}}]);assert.equal(r.headers['Cache-Control'],'no-store');assert.equal(r.headers['X-Content-Type-Options'],'nosniff');for(const s of [TOKEN,'999.75','SYNTHETIC_PRIVATE_OWNER','googleSubject'])assert.equal(JSON.stringify(r).includes(s),false);});
test('compatible append and resolve expose only matching minimal retained operation results',async()=>{const f=fixture();assert.deepEqual((await run(f,request(APPEND))).body,{ok:true,replayed:false,operationId:'operation-1'});assert.deepEqual((await run(f,request(RESOLVE))).body,{ok:true,replayed:true,operationId:'operation-1'});assert.deepEqual(f.calls.map(c=>c.method),['execute','resolve']);assert.ok(Object.isFrozen(f.calls[0].request.command));assert.deepEqual(f.calls[0].request,{idToken:TOKEN,command:command()});});
test('unregistered compatible routes reject before body access and never call any service',async()=>{const f=fixture();delete f.options.legacyOperationsService;f.handler=Http.createProductionHttpHandler(f.options);for(const path of [READ,APPEND,RESOLVE]){const req=request(path);Object.defineProperty(req,'rawBody',{get(){throw Error('BODY_MUST_NOT_BE_READ');}});assert.equal((await run(f,req)).statusCode,400);}assert.equal(f.calls.length,0);});
test('fixed compatible routes accept neither queries, trailing slash nor caller source selectors',async()=>{for(const path of [READ+'?workerId=other',READ+'?source=soldier',APPEND+'?tenant=foreign',RESOLVE+'/']){const f=fixture();assert.equal((await run(f,request(path))).statusCode,400);assert.equal(f.calls.length,0);}});
test('GET rejects bodies, content encodings and write methods without calling identity service',async()=>{for(const change of [r=>r.rawBody=Buffer.from('{}'),r=>r.headers['content-type']='application/json',r=>r.headers['content-length']='2',r=>r.headers['content-encoding']='gzip',r=>r.method='POST']){const f=fixture(),r=request();change(r);assert.ok([400,405].includes((await run(f,r)).statusCode));assert.equal(f.calls.length,0);}});
test('compatible origin, bearer grammar and duplicate control headers fail before dispatch',async()=>{for(const change of [r=>r.headers.origin='https://foreign.example.invalid',r=>r.headers.authorization='Bearer invalid',r=>r.rawHeaders.push('authorization','Bearer different.token.value'),r=>r.headers['content-encoding']='gzip']){const f=fixture(),r=request(APPEND);change(r);assert.ok([400,403].includes((await run(f,r)).statusCode));assert.equal(f.calls.length,0);}});
test('GET versus POST preflight is fixed and performs no identity verification',async()=>{for(const path of [READ,APPEND,RESOLVE]){const f=fixture(),req=request(path);req.method='OPTIONS';delete req.rawBody;req.headers={origin:ORIGIN,'access-control-request-method':path===READ?'GET':'POST','access-control-request-headers':path===READ?'Authorization':'Authorization, Content-Type'};req.rawHeaders=Object.entries(req.headers).flat();assert.equal((await run(f,req)).statusCode,204);req.headers['access-control-request-method']=path===READ?'POST':'GET';req.rawHeaders=Object.entries(req.headers).flat();assert.equal((await run(f,req)).statusCode,400);assert.equal(f.calls.length,0);}});
test('command body is exact and forbids worker/rate/total/role/UID/archive/source fields',async()=>{for(const [k,v]of [['workerId','worker-2'],['rate',1],['total',0],['role','owner'],['uid','owner-1'],['snapshotVersion','old'],['source','soldier']]){const f=fixture(),c=command();c[k]=v;assert.equal((await run(f,request(APPEND,c))).statusCode,400);assert.equal(f.calls.length,0);}});
test('command kind, identity, version, date and quantities are bounded before service',async()=>{for(const mutate of [c=>c.kind='setGrant',c=>c.requestId='1',c=>c.operationId='2',c=>c.productId='bad/path',c=>c.expectedGrantRevision=0,c=>c.expectedSourceVersion='A'.repeat(64),c=>c.workDate='2026-02-30',c=>c.good=0.5,c=>c.good=-1,c=>c.good=Number.MAX_SAFE_INTEGER,c=>{c.good=0;c.reject=0;}]){const f=fixture(),c=command();mutate(c);assert.equal((await run(f,request(APPEND,c))).statusCode,400);assert.equal(f.calls.length,0);}const f=fixture(),r=request(APPEND);r.rawBody=Buffer.from(r.rawBody.toString().replace('"good":2','"good":-0'));assert.equal((await run(f,r)).statusCode,400);assert.equal(f.calls.length,0);});
test('escaped duplicate JSON keys cannot replace an append quantity or command wrapper',async()=>{for(const text of [JSON.stringify({command:command()}).replace('"good":2','"good":2,"\\u0067ood":3'),' {"command":{},"\\u0063ommand":'+JSON.stringify(command())+'}']){const f=fixture(),r=request(APPEND);r.rawBody=Buffer.from(text);assert.equal((await run(f,r)).statusCode,400);assert.equal(f.calls.length,0);}});
test('foreign scope, financial/private fields, inconsistent quantities and unknown assignment reports reject all views',async()=>{for(const mutate of [v=>v.binding.projectId='demo-other',v=>v.binding.databaseURL='https://demo-other.firebaseio.com',v=>v.binding.tenantId='other',v=>v.binding.division='qc',v=>v.binding.email='PRIVATE',v=>v.products[0].rate=1,v=>v.products[0].assignments[0].remaining=99,v=>v.products[0].reports[0].assignmentId='foreign',v=>v.products[0].reports[0].total=777,v=>v.products[0].reports[0].completed=99]){const v=view();mutate(v);const f=fixture({legacyOperationsService:{read:async()=>({ok:true,view:v}),execute:async()=>{},resolve:async()=>{}}}),r=await run(f);assert.deepEqual(r.body,{ok:false,error:'unavailable'});assert.equal(JSON.stringify(r).includes('PRIVATE'),false);}});
test('view aliases, duplicates, sparse arrays and malformed field types cannot be partially returned',async()=>{for(const mutate of [v=>v.products.push(F.copy(v.products[0])),v=>v.products[0].assignments.push(F.copy(v.products[0].assignments[0])),v=>v.products[0].reports.push(F.copy(v.products[0].reports[0])),v=>v.products[0].reports[0].good='3',v=>v.products[0].hasUnlistedLegacy='true',v=>delete v.products[0].reports[0],v=>v.products[0].sourceVersion='bad']){const v=view();mutate(v);const f=fixture({legacyOperationsService:{read:async()=>({ok:true,view:v}),execute:async()=>{},resolve:async()=>{}}});assert.deepEqual((await run(f)).body,{ok:false,error:'unavailable'});}});
test('private result/config/method getters are rejected without invocation',async()=>{let touched=0;const result={ok:true};Object.defineProperty(result,'view',{enumerable:true,get(){touched++;throw Error('PRIVATE');}});const f=fixture({legacyOperationsService:{read:async()=>result,execute:async()=>{},resolve:async()=>{}}});assert.deepEqual((await run(f)).body,{ok:false,error:'unavailable'});for(const key of ['legacyOperationsService','legacyOperationsBinding']){const g=fixture();Object.defineProperty(g.options,key,{enumerable:true,get(){touched++;throw Error('PRIVATE');}});assert.equal((await run({handler:Http.createProductionHttpHandler(g.options)})).statusCode,503);}const g=fixture();Object.defineProperty(g.service,'read',{get(){touched++;throw Error('PRIVATE');}});assert.equal((await run({handler:Http.createProductionHttpHandler(g.options)})).statusCode,503);const b=fixture();b.options.legacyOperationsBinding.databaseURL={toString(){touched++;throw Error('PRIVATE_ORIGIN');}};assert.equal((await run({handler:Http.createProductionHttpHandler(b.options)})).statusCode,503);assert.equal(touched,0);});
test('captured trusted HTTP binding cannot be changed after factory assembly',async()=>{const f=fixture();f.options.legacyOperationsBinding.projectId='demo-mutated';assert.equal((await run(f)).statusCode,200);});
test('empty own view remains a valid available operational result',async()=>{const v=view();v.products=[];const f=fixture({legacyOperationsService:{read:async()=>({ok:true,view:v}),execute:async()=>{},resolve:async()=>{}}});assert.deepEqual((await run(f)).body,{ok:true,view:v});});
test('oversized own operational views reject completely within the same byte bound as the core',async()=>{const v=view(),p=v.products[0];v.products=Array.from({length:1500},(_,i)=>({...F.copy(p),productId:'product-'+i,series:'x'.repeat(256),namaBarang:'y'.repeat(256),size:'z'.repeat(256)}));const f=fixture({legacyOperationsService:{read:async()=>({ok:true,view:v}),execute:async()=>{},resolve:async()=>{}}});const r=await run(f);assert.deepEqual(r.body,{ok:false,error:'unavailable'});assert.equal(Object.hasOwn(r.body,'view'),false);});
test('wrong or enriched write receipts never acknowledge a different operation',async()=>{for(const result of [{ok:true,replayed:false,operationId:'foreign'},{ok:true,replayed:false,operationId:'operation-1',uid:'PRIVATE'},{ok:true,replayed:'true',operationId:'operation-1'}]){const f=fixture({legacyOperationsService:{read:async()=>{},execute:async()=>result,resolve:async()=>result}});assert.deepEqual((await run(f,request(APPEND))).body,{ok:false,error:'result_unknown',retrySameCommand:true});}const f=fixture({legacyOperationsService:{read:async()=>{},execute:async()=>{},resolve:async()=>({ok:true,replayed:false,operationId:'operation-1'})}});assert.deepEqual((await run(f,request(RESOLVE))).body,{ok:false,error:'result_unknown',retrySameCommand:true});});
test('compatible fixed errors and uncertain ACKs never expose service details',async()=>{for(const [error,status]of [['access_denied',403],['not_ready',409],['conflict',409],['capacity_limit',409],['rate_limited',429],['unavailable',503]]){const f=fixture({legacyOperationsService:{read:async()=>({ok:false,error}),execute:async()=>({ok:false,error}),resolve:async()=>({ok:false,error})}});const read=await run(f),write=await run(f,request(APPEND));assert.equal(read.statusCode,status);assert.deepEqual(read.body,{ok:false,error});assert.equal(write.statusCode,status);assert.equal(Object.hasOwn(write.body,'retrySameCommand'),error==='unavailable');}const f=fixture({legacyOperationsService:{read:async()=>{throw Error('PRIVATE');},execute:async()=>({ok:false,error:'result_unknown',retrySameCommand:true}),resolve:async()=>({ok:false,error:'result_unknown',retrySameCommand:true})}});assert.deepEqual((await run(f)).body,{ok:false,error:'unavailable'});assert.deepEqual((await run(f,request(APPEND))).body,{ok:false,error:'result_unknown',retrySameCommand:true});});
test('compatible service capacity denial preserves a fixed busy response and the original write retry contract',async()=>{const f=fixture({legacyOperationsService:{read:async()=>({ok:false,error:'busy'}),execute:async()=>({ok:false,error:'busy'}),resolve:async()=>({ok:false,error:'busy'})}});assert.deepEqual((await run(f)).body,{ok:false,error:'busy'});for(const path of [APPEND,RESOLVE])assert.deepEqual((await run(f,request(path))).body,{ok:false,error:'busy',retrySameCommand:true});});
test('late compatible read/write retain shared capacity until settlement and discard late acknowledgment',async()=>{for(const path of [READ,APPEND]){let release;const p=new Promise(r=>release=r),f=fixture({deadlineMs:5,legacyOperationsService:{read:()=>p,execute:()=>p,resolve:()=>p}}),res=response(),first=f.handler(request(path),res);await new Promise(r=>setTimeout(r,15));assert.equal(res.writableEnded,undefined);assert.equal((await run(f,request(RESOLVE))).body.error,'busy');release(path===READ?{ok:true,view:view()}:{ok:true,replayed:false,operationId:'operation-1'});await first;assert.deepEqual(res.body,path===READ?{ok:false,error:'unavailable'}:{ok:false,error:'result_unknown',retrySameCommand:true});}});

function runtimeFixture(){
  let root=storedRoot();const stats={auth:0,users:0,rootReads:0,rootWrites:0,quotaWrites:0},hooks={},control={uid:'partner-1',subject:'1000123456789',email:F.EMAIL,disabled:false},app={options:{projectId:F.PROJECT,databaseURL:F.URL}},refs=new Map();
  const readPath=path=>{let value=root;for(const p of path.split('/').filter(Boolean))value=value&&Object.hasOwn(value,p)?value[p]:null;return F.copy(value);};
  const writePath=(path,value)=>{if(path==='/'){root=F.copy(value);return;}const parts=path.split('/'),last=parts.pop();let parent=root;for(const p of parts){if(!parent[p])parent[p]={};parent=parent[p];}parent[last]=F.copy(value);};
  const database={app,ref(path){assert.equal(typeof path,'string');assert.notEqual(path,'');if(refs.has(path))return refs.get(path);let ref;const snap=value=>({ref,val:()=>F.copy(value)});ref={toString:()=>F.URL+(path==='/'?'/':'/'+path),async get(){if(path==='/'){stats.rootReads++;if(hooks.rootRead)await hooks.rootRead(stats.rootReads);}return snap(readPath(path));},on(_event,fn){queueMicrotask(()=>fn(snap(readPath(path))));},off(){},async transaction(update,_complete,_local){if(path==='/'&&hooks.beforeRootCas)await hooks.beforeRootCas();const next=update(readPath(path));if(next===undefined)return {committed:false,snapshot:snap(readPath(path))};writePath(path,next);if(path==='/')stats.rootWrites++;else if(path.startsWith('serverRateLimits/'))stats.quotaWrites++;const result={committed:true,snapshot:snap(next)};if(path==='/'&&hooks.afterRootCas)await hooks.afterRootCas();if(path==='/'&&hooks.lostAck)throw Error('PRIVATE_ACK');return result;}};refs.set(path,ref);return ref;}};
  const second=Date.parse(F.NOW)/1000,auth={app,async verifyIdToken(token,revoked){stats.auth++;assert.equal(token,TOKEN);assert.equal(revoked,true);return {uid:control.uid,sub:control.uid,aud:F.PROJECT,iss:'https://securetoken.google.com/'+F.PROJECT,email:control.email,email_verified:true,auth_time:second-86400,iat:second-60,exp:second+3600,firebase:{sign_in_provider:'google.com',identities:{'google.com':[control.subject]}}};},async getUser(uid){stats.users++;return {uid,email:control.email,emailVerified:true,disabled:control.disabled,providerData:[{providerId:'google.com',uid:control.subject,email:control.email}]};}};
  const options={enabled:true,legacyOperationsEnabled:true,legacyOperationsTariffPolicy:F.copy(POLICY),...scope(),database,auth,allowedOrigins:[ORIGIN],clock:()=>F.NOW,policy:{rateWindowMs:60000,rateLimit:30,deadlineMs:1000,maxInFlight:1}};
  return {options,control,stats,hooks,get root(){return root;},set root(value){root=F.copy(value);}};
}
test('assembled compatible read uses current Google identity, retained v2 grant and same private UID bucket',async()=>{const f=runtimeFixture(),before=F.copy(f.root.authorityTenants),r=await run(Runtime.createProductionRuntime(f.options));assert.equal(r.statusCode,200);assert.deepEqual(r.body,{ok:true,view:view()});assert.equal(f.stats.auth,2);assert.equal(f.stats.users,2);assert.equal(f.stats.quotaWrites,1);assert.equal(f.stats.rootWrites,0);assert.deepEqual(f.root.authorityTenants,before);assert.equal(f.root.serverRateLimits[F.TENANT]['partner-1'].count,1);for(const marker of [TOKEN,F.EMAIL,'999.75','1000123456789','SYNTHETIC_PRIVATE_OWNER'])assert.equal(JSON.stringify(r).includes(marker),false);});
test('assembled compatible append and readonly resolve preserve source and durable replay without owner app',async()=>{const f=runtimeFixture(),runtime=Runtime.createProductionRuntime(f.options),before=F.copy(f.root.soldier.produksi.produksi[0].jahit[0]);assert.deepEqual((await run(runtime,request(APPEND))).body,{ok:true,replayed:false,operationId:'operation-1'});assert.deepEqual((await run(runtime,request(RESOLVE))).body,{ok:true,replayed:true,operationId:'operation-1'});assert.deepEqual((await run(runtime,request(APPEND))).body,{ok:true,replayed:true,operationId:'operation-1'});assert.equal(f.stats.rootWrites,1);assert.equal(f.stats.quotaWrites,3);assert.deepEqual(f.root.soldier.produksi.produksi[0].jahit[0],before);assert.equal(f.root.soldier.produksi.produksi[0].jahit[1].total,25);});
test('runtime absent/false flag leaves all compatible paths unregistered and never inspects tariff policy',async()=>{for(const flag of [false,undefined]){const f=runtimeFixture();if(flag===undefined)delete f.options.legacyOperationsEnabled;else f.options.legacyOperationsEnabled=false;let touched=0;Object.defineProperty(f.options,'legacyOperationsTariffPolicy',{get(){touched++;throw Error('PRIVATE_POLICY');}});const runtime=Runtime.createProductionRuntime(f.options);for(const path of [READ,APPEND,RESOLVE]){const req=request(path);Object.defineProperty(req,'rawBody',{get(){throw Error('BODY_MUST_NOT_BE_READ');}});assert.equal((await run(runtime,req)).statusCode,400);}assert.equal(touched,0);assert.equal(f.stats.auth,0);assert.equal(f.stats.rootReads,0);assert.equal(f.stats.rootWrites,0);}});
test('runtime malformed/accessor legacy flags and unreviewed policies fail before Google/private root access',async()=>{for(const mutate of [f=>f.options.legacyOperationsEnabled='true',f=>Object.defineProperty(f.options,'legacyOperationsEnabled',{get(){throw Error('PRIVATE_FLAG');}}),f=>delete f.options.legacyOperationsTariffPolicy,f=>f.options.legacyOperationsTariffPolicy.reviewed=false,f=>f.options.legacyOperationsTariffPolicy.quantityBasis='good-only',f=>f.options.legacyOperationsTariffPolicy.timeZone='UTC',f=>Object.defineProperty(f.options,'legacyOperationsTariffPolicy',{get(){throw Error('PRIVATE_POLICY');}})]){const f=runtimeFixture();mutate(f);const r=await run(Runtime.createProductionRuntime(f.options));assert.deepEqual(r.body,{ok:false,error:'unavailable'});assert.equal(f.stats.auth,0);assert.equal(f.stats.rootReads,0);}});
test('runtime unknown, disabled, owner, QC and replaced subject fail before private quota or writes',async()=>{for(const mutate of [f=>f.control.uid='unknown',f=>f.control.disabled=true,f=>{f.control.uid='owner-1';f.control.email='syntheticowner@gmail.com';f.control.subject='owner-google';},f=>f.control.subject='replacement',f=>{const root=f.root;root.authorityTenants[F.TENANT]=State.claimIdentityEnrollment(root.authorityTenants[F.TENANT],F.identity({uid:'quality-1',email:F.QC_EMAIL,googleSubject:'quality-google'}),F.NOW).next;f.root=root;f.control.uid='quality-1';f.control.email=F.QC_EMAIL;f.control.subject='quality-google';}]){const f=runtimeFixture();mutate(f);const r=await run(Runtime.createProductionRuntime(f.options),request(APPEND));assert.equal(r.body.error,'access_denied');assert.equal(f.stats.quotaWrites,0);assert.equal(f.stats.rootWrites,0);}});
test('runtime retained grant revoked between admission and root CAS cannot save a report',async()=>{const f=runtimeFixture();f.hooks.beforeRootCas=()=>{const root=f.root;root.authorityTenants[F.TENANT]=State.revokeIdentityEnrollment(root.authorityTenants[F.TENANT],F.revokeCommand(),F.NOW).next;f.root=root;};const r=await run(Runtime.createProductionRuntime(f.options),request(APPEND));assert.equal(r.body.ok,false);assert.equal(f.stats.rootWrites,0);assert.equal(f.root.soldier.produksi.produksi[0].jahit.length,1);});
test('runtime one private quota is shared by canonical session and compatible own read',async()=>{const f=runtimeFixture();f.options.policy.rateLimit=1;const runtime=Runtime.createProductionRuntime(f.options);assert.equal((await run(runtime,{...request(),url:'/v1/production/session'})).statusCode,200);assert.deepEqual((await run(runtime)).body,{ok:false,error:'rate_limited'});assert.equal(f.stats.quotaWrites,1);assert.equal(f.stats.rootWrites,0);});
test('runtime actual root commit with injected ACK loss stays unknown and exact resolve reads only',async()=>{const f=runtimeFixture(),runtime=Runtime.createProductionRuntime(f.options);f.hooks.lostAck=true;assert.deepEqual((await run(runtime,request(APPEND))).body,{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(f.stats.rootWrites,1);delete f.hooks.lostAck;assert.deepEqual((await run(runtime,request(RESOLVE))).body,{ok:true,replayed:true,operationId:'operation-1'});assert.equal(f.stats.rootWrites,1);});
test('runtime captures reviewed policy and exposes no root seed, owner role or arbitrary operation endpoint',async()=>{const f=runtimeFixture(),runtime=Runtime.createProductionRuntime(f.options);f.options.legacyOperationsTariffPolicy.version='mutated';assert.equal((await run(runtime,request(APPEND))).statusCode,200);for(const path of ['/v1/production/legacy/root','/v1/production/legacy/grants','/v1/production/legacy/jahit/cancel'])assert.equal((await run(runtime,request(path))).statusCode,400);assert.equal(f.stats.rootWrites,1);});
test('compatible opt-in cannot repurpose the separate canonical v1 command endpoint',async()=>{const f=runtimeFixture(),r=await run(Runtime.createProductionRuntime(f.options),request('/v1/production/commands'));assert.equal(r.body.ok,false);assert.equal(f.stats.rootWrites,0);assert.equal(f.root.soldier.produksi.produksi[0].jahit.length,1);});
