'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Authority=require('../server/production-authority.cjs'),Admin=require('../server/production-tenant-admin.cjs'),Ledger=require('../server/production-tariff-ledger.cjs'),Http=require('../server/production-http-handler.cjs'),Runtime=require('../server/production-runtime.cjs');
const PROJECT='demo-tariff-resolution',TENANT='synthetic-tenant',URL='https://'+PROJECT+'.firebaseio.com',NOW='2026-10-06T03:00:00.000Z',FUTURE='2026-10-07T03:00:00.000Z',TOKEN='header.payload.signature',ORIGIN='https://soldier.example.invalid';
const RESOLVE='/v1/production/owner/tariffs/resolve',APPEND='/v1/production/owner/tariffs/append',VIEW='/v1/production/owner/tariffs/view';
const copy=v=>structuredClone(v);
function prune(v){if(v===null)return undefined;if(v&&typeof v==='object'){const out={};for(const [k,value]of Object.entries(v)){const item=prune(value);if(item!==undefined)out[k]=item;}return Object.keys(out).length?out:undefined;}return v;}
const command=changes=>({kind:'appendTariffVersion',requestId:'draft-1',productId:'product-1',cycleId:'cycle-1',expectedConfigRevision:1,expectedTariffRevision:1,workerId:'worker-1',tariffVersion:'rate-2',effectiveAt:FUTURE,currency:'IDR',rate:200,...changes});
function product(id){const state=Authority.createAuthority({product:{id,series:'Synthetic',namaBarang:'Example only',size:'M',cutQuantity:10},cycleId:'cycle-1',workers:[{id:'worker-1',nama:'Synthetic partner'},{id:'unassigned-worker',nama:'Synthetic unassigned'}],assignments:[{id:'assignment-1',workerId:'worker-1',qty:10}],now:NOW});return {cycles:{'cycle-1':{config:{revision:1,active:true,reviewedEmptyCycle:true,tariffPolicy:'explicit-historical-jakarta-v1'},tariffInputs:{revision:1,policy:{version:'policy-1',kind:'jakarta-fixed-local-time',hour:8,minute:0},historyByWorker:{'worker-1':{'rate-1':{effectiveAt:'2026-01-01T00:00:00.000Z',currency:'IDR',rate:100}}}},wire:prune(Authority.encodeStorage(state))}}};}
function setup(changes={}){
  const path='authorityTenants/'+TENANT,store={tenant:{schemaVersion:1,projectId:PROJECT,tenantId:TENANT,grants:{'owner-1':{revision:1,profile:{active:true,owner:true}},'partner-1':{revision:1,profile:{active:true,owner:false,workerId:'worker-1',modules:{jahit:true}}}},products:{'product-1':product('product-1'),'product-2':product('product-2')}}},buckets=new Map(),stats={reads:0,auth:0,admit:0,on:0,off:0,transactions:0,writes:0,quota:0},listeners=new Set(),hooks={before:null,after:null,result:null,cold:false};
  const snapshot=v=>({val:()=>copy(v)}),app={options:{projectId:PROJECT,databaseURL:URL}},token={uid:'owner-1',sub:'owner-1',aud:PROJECT,iss:'https://securetoken.google.com/'+PROJECT,email_verified:true,firebase:{sign_in_provider:'google.com'},exp:Date.parse(FUTURE)/1000+3600};
  const database={app,ref(key){assert.ok(key===path||key.startsWith('serverRateLimits/'+TENANT+'/'));const business=key===path,read=()=>business?store.tenant:buckets.get(key)??null;return {toString:()=>URL+'/'+key,async get(){stats.reads++;return snapshot(read());},on(event,listener){assert.equal(event,'value');stats.on++;listeners.add(listener);listener(snapshot(read()));},off(event,listener){assert.equal(event,'value');assert.ok(listeners.has(listener));listeners.delete(listener);stats.off++;},async transaction(update,complete,local){assert.equal(complete,undefined);assert.equal(local,false);if(business)stats.transactions++;
    if(business&&hooks.before){const change=hooks.before;hooks.before=null;await change();}
    let value=business&&hooks.cold?null:copy(read());if(business)hooks.cold=false;const original=copy(value);let next=update(value);assert.deepEqual(value,original);
    if(business&&next!==undefined&&hooks.after){const change=hooks.after;hooks.after=null;await change();value=copy(read());const fresh=copy(value);next=update(value);assert.deepEqual(value,fresh);}
    if(business&&hooks.result)return hooks.result(next);
    if(next===undefined)return {committed:false,snapshot:snapshot(read())};
    if(business){store.tenant=prune(copy(next));stats.writes++;}else{buckets.set(key,copy(next));stats.quota++;}return {committed:true,snapshot:snapshot(read())};}};}};
  const auth={app,async verifyIdToken(value,revoke){assert.equal(value,TOKEN);assert.equal(revoke,true);stats.auth++;return copy(token);}},options={enabled:true,projectId:PROJECT,tenantId:TENANT,databaseURL:URL,database,auth,clock:()=>NOW,admit:async()=>{stats.admit++;return true;},...changes};
  const create=()=>Admin.createProductionTenantAdmin(options),request=c=>({idToken:TOKEN,command:c}),cycle=()=>store.tenant.products['product-1'].cycles['cycle-1'];
  const runtime=(policy={rateWindowMs:60000,rateLimit:30,deadlineMs:1000,maxInFlight:2})=>Runtime.createProductionRuntime({...options,allowedOrigins:[ORIGIN],policy});return {store,buckets,stats,listeners,hooks,token,options,create,request,cycle,runtime};
}
function frozenCycle(f){let state=Authority.decodeStorage(f.cycle().wire);const actor={uid:'owner-1',emailVerified:true,provider:'google.com',profile:{active:true,owner:true},now:NOW};state=Authority.applyCommand(state,actor,{requestId:'sew-frozen',productId:'product-1',cycleId:'cycle-1',expectedRevision:0,kind:'sewing',payload:{id:'sew-1',assignmentId:'assignment-1',tanggal:'2026-10-06',good:10,reject:0}}).state;const selection={source:'private-verified-tariff',verified:true,workerId:'worker-1',productId:'product-1',cycleId:'cycle-1',countId:'count-1',workDate:'2026-10-06',basisAt:NOW,effectiveAt:'2026-01-01T00:00:00.000Z',tariffVersion:'rate-1',currency:'IDR',rate:100,selectedAt:NOW};state=Authority.applyCommand(state,{...actor,selectedTariffs:{'count-1':selection}},{requestId:'count-frozen',productId:'product-1',cycleId:'cycle-1',expectedRevision:1,kind:'count',payload:{id:'count-1',assignmentId:'assignment-1',tanggal:'2026-10-06',jumlah:10}}).state;f.cycle().wire=prune(Authority.encodeStorage(state));}
function retiredReceipt(c=command(),at=NOW){return {requestId:c.requestId,kind:'retireTariffDraft',productId:c.productId,cycleId:c.cycleId,workerId:c.workerId,tariffVersion:c.tariffVersion,retiredAt:at};}
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},end(v){this.raw=v;this.body=v===undefined?null:JSON.parse(v);this.writableEnded=true;}};}
function request(path=RESOLVE,c=command()){const rawBody=Buffer.from(JSON.stringify({command:c})),headers={origin:ORIGIN,authorization:'Bearer '+TOKEN,'content-type':'application/json','content-length':String(rawBody.length)};return {method:'POST',url:path,headers,rawHeaders:Object.entries(headers).flat(),rawBody};}
async function run(handler,req=request()){const res=response();await handler(req,res);return res;}
function transport(writer,changes={}){const stub={execute:async()=>({ok:false,error:'unavailable'})};return Http.createProductionHttpHandler({enabled:true,service:stub,sessionService:stub,ownerTariffService:stub,ownerTariffWriter:writer,ownerBinding:{projectId:PROJECT,tenantId:TENANT},allowedOrigins:[ORIGIN],deadlineMs:1000,maxInFlight:1,...changes});}

test('draft resolution is OFF by default without token, admission, DB reads or listeners',async()=>{const f=setup();f.options.enabled=false;assert.deepEqual(await f.create().resolveTariffDraft(f.request(command())),{ok:false,error:'service_disabled'});assert.ok(Object.values(f.stats).every(n=>n===0));});
test('retirement commits only an immutable private fence and preserves original rates, wire, frozen wages and all siblings',async()=>{const f=setup();frozenCycle(f);const before=copy(f.store.tenant),c=command(),r=await f.create().resolveTariffDraft(f.request(c));assert.deepEqual(r,{ok:true,outcome:'retired',receipt:retiredReceipt(c),replayed:false});const without=copy(f.store.tenant);delete without.tariffCommandLedger;assert.deepEqual(without,before);assert.equal(f.stats.writes,1);assert.equal(f.stats.on,f.stats.off);assert.equal(f.listeners.size,0);assert.equal(Object.isFrozen(r.receipt),true);for(const value of ['owner-1',TOKEN,'commandJson','rate','profile','grants','privateAuthority'])assert.equal(JSON.stringify(r).includes(value==='rate'?'"rate"':value),false);assert.equal(Ledger.validateTariffLedger(f.store.tenant.tariffCommandLedger,f.store.tenant.products).schemaVersion,1);});
test('retired draft is replayed read-only after restart and any late original append is blocked',async()=>{const f=setup(),c=command(),first=await f.create().resolveTariffDraft(f.request(c)),before=copy(f.store.tenant),transactions=f.stats.transactions;assert.deepEqual(await f.create().resolveTariffDraft(f.request(copy(c))),{...first,replayed:true});assert.deepEqual(await f.create().execute(f.request(c)),{ok:false,error:'draft_retired'});assert.deepEqual(f.store.tenant,before);assert.equal(f.stats.transactions,transactions);assert.equal(f.stats.writes,1);assert.throws(()=>Ledger.getTariffReceipt(f.store.tenant.tariffCommandLedger,'owner-1',c),e=>e.code==='draft_retired');});
test('accepted draft resolves to its original receipt without writing, even after stale config and effective date',async()=>{let now=NOW;const f=setup({clock:()=>now}),c=command(),first=await f.create().execute(f.request(c));assert.equal(first.ok,true);f.cycle().config.revision++;f.cycle().config.active=false;frozenCycle(f);now='2026-10-07T03:30:00.000Z';const before=copy(f.store.tenant),transactions=f.stats.transactions;assert.deepEqual(await f.create().resolveTariffDraft(f.request(c)),{ok:true,outcome:'accepted',receipt:first.receipt,replayed:true});assert.deepEqual(f.store.tenant,before);assert.equal(f.stats.transactions,transactions);});
test('unaccepted expired draft resolves despite newer tariff/config revisions and occupied tariff target',async()=>{let now=NOW;const f=setup({clock:()=>now}),original=command(),other=command({requestId:'winner',rate:300});assert.equal((await f.create().execute(f.request(other))).ok,true);f.cycle().config.revision++;f.cycle().config.active=false;frozenCycle(f);now='2026-10-07T03:30:00.000Z';const before=copy(f.store.tenant),r=await f.create().resolveTariffDraft(f.request(original));assert.deepEqual(r,{ok:true,outcome:'retired',receipt:retiredReceipt(original,now),replayed:false});const without=copy(f.store.tenant);delete without.tariffCommandLedger;delete before.tariffCommandLedger;assert.deepEqual(without,before);assert.equal(f.cycle().tariffInputs.historyByWorker['worker-1']['rate-2'].rate,300);assert.equal(Object.keys(f.store.tenant.tariffCommandLedger.entries).length,2);});
test('request ID body collisions fail before retirement or append and never replace either kind of receipt',async()=>{for(const accepted of [false,true]){const f=setup(),c=command();await f.create()[accepted?'execute':'resolveTariffDraft'](f.request(c));const before=copy(f.store.tenant),writes=f.stats.writes;for(const changes of [{rate:201},{effectiveAt:'2026-10-08T03:00:00.000Z'},{expectedConfigRevision:2},{expectedTariffRevision:2},{workerId:'unassigned-worker'},{tariffVersion:'other-version'},{cycleId:'missing-cycle'}])for(const method of ['execute','resolveTariffDraft'])assert.deepEqual(await f.create()[method](f.request({...c,...changes})),{ok:false,error:'conflict'});assert.deepEqual(f.store.tenant,before);assert.equal(f.stats.writes,writes);}});
test('append wins a resolver race and original accepted receipt is returned only after fresh owner/Auth reread',async()=>{const f=setup(),c=command();let accepted;f.hooks.before=async()=>{accepted=await f.create().execute(f.request(c));};const r=await f.create().resolveTariffDraft(f.request(c));assert.deepEqual(r,{ok:true,outcome:'accepted',receipt:accepted.receipt,replayed:true});assert.equal(f.stats.writes,1);assert.equal(f.stats.auth,3);assert.equal(f.listeners.size,0);});
test('resolver wins an append race and no late rate can cross its same-ancestor CAS fence',async()=>{const f=setup(),c=command(),before=copy(f.store.tenant);let retired;f.hooks.before=async()=>{retired=await f.create().resolveTariffDraft(f.request(c));};assert.deepEqual(await f.create().execute(f.request(c)),{ok:false,error:'draft_retired'});assert.equal(retired.outcome,'retired');assert.equal(f.stats.writes,1);assert.deepEqual(f.store.tenant.products,before.products);assert.equal(Object.keys(f.store.tenant.tariffCommandLedger.entries).length,1);});
test('two resolver instances converge on one retained fence with no no-op or replacement write',async()=>{const f=setup(),c=command();let winning;f.hooks.before=async()=>{winning=await f.create().resolveTariffDraft(f.request(c));};const r=await f.create().resolveTariffDraft(f.request(c));assert.deepEqual(r,{...winning,replayed:true});assert.equal(f.stats.writes,1);assert.equal(f.stats.auth,3);assert.equal(f.stats.on,f.stats.off);});
test('unknown or corrupt retirement acknowledgment retains the fence for exact replay',async()=>{for(const corrupt of [false,true]){const f=setup(),c=command();f.hooks.result=next=>{f.store.tenant=prune(copy(next));f.stats.writes++;if(!corrupt)throw Error('synthetic-private-lost-ack');return {committed:true,snapshot:{val:()=>null}};};assert.deepEqual(await f.create().resolveTariffDraft(f.request(c)),{ok:false,error:'unavailable'});assert.equal(f.stats.writes,1);f.hooks.result=null;const before=copy(f.store.tenant),r=await f.create().resolveTariffDraft(f.request(c));assert.equal(r.outcome,'retired');assert.equal(r.replayed,true);assert.deepEqual(f.store.tenant,before);assert.deepEqual(await f.create().execute(f.request(c)),{ok:false,error:'draft_retired'});assert.equal(f.stats.writes,1);}});
test('every fresh and replayed accepted/retired outcome needs fresh verified Google identity and current active owner',async()=>{for(const phase of ['fresh','retired','accepted'])for(const mutate of [f=>f.store.tenant.grants['owner-1'].profile.active=false,f=>f.store.tenant.grants['owner-1'].profile.owner=false,f=>delete f.store.tenant.grants['owner-1'],f=>f.token.email_verified=false,f=>f.token.firebase.sign_in_provider='password',f=>f.token.exp=0,f=>{f.options.auth.verifyIdToken=async()=>{throw Error('synthetic-revoked');};}]){const f=setup(),c=command();if(phase!=='fresh')await f.create()[phase==='retired'?'resolveTariffDraft':'execute'](f.request(c));mutate(f);const before=copy(f.store.tenant),writes=f.stats.writes;assert.deepEqual(await f.create().resolveTariffDraft(f.request(c)),{ok:false,error:'access_denied'});assert.deepEqual(f.store.tenant,before);assert.equal(f.stats.writes,writes);}});
test('internal SDK retry rechecks owner/Auth, preserves concurrent work/config/tariffs and aborts revoked authority',async()=>{const f=setup(),c=command();f.hooks.after=()=>{f.cycle().config.revision++;frozenCycle(f);};assert.equal((await f.create().resolveTariffDraft(f.request(c))).outcome,'retired');assert.equal(f.stats.auth,2);assert.equal(f.stats.writes,1);assert.equal(f.cycle().config.revision,2);assert.equal(Authority.decodeStorage(f.cycle().wire).frozenPayroll['count-1'].rate,100);for(const position of ['before','after']){const revoked=setup();revoked.hooks[position]=()=>revoked.store.tenant.grants['owner-1'].profile.active=false;assert.deepEqual(await revoked.create().resolveTariffDraft(revoked.request(c)),{ok:false,error:'access_denied'});assert.equal(revoked.stats.writes,0);assert.equal(revoked.listeners.size,0);if(position==='after')assert.equal(revoked.stats.auth,2);}});
test('retirement rejects unknown/unassigned targets and unsafe money instead of persisting unverifiable fences',async()=>{for(const changes of [{workerId:'unassigned-worker'},{workerId:'missing-worker'},{productId:'missing-product'},{cycleId:'missing-cycle'},{rate:Number.MAX_SAFE_INTEGER}]){const f=setup(),before=copy(f.store.tenant);assert.equal((await f.create().resolveTariffDraft(f.request(command(changes)))).ok,false);assert.deepEqual(f.store.tenant,before);assert.equal(f.stats.writes,0);}});
test('resolver rejects non-tariff commands, unknown claims, malformed dates, fractional money and getters before Auth',async()=>{for(const c of [{kind:'setGrant',uid:'partner-1',expectedRevision:1,profile:{active:true,owner:true}},command({kind:'appendTariff'}),command({rate:1.5}),command({effectiveAt:'2026-02-30T00:00:00.000Z'}),command({owner:true}),command({pin:'synthetic-private-pin'}),command({currency:'USD'})]){const f=setup();assert.deepEqual(await f.create().resolveTariffDraft(f.request(c)),{ok:false,error:'invalid_request'});assert.equal(f.stats.auth,0);assert.equal(f.stats.writes,0);}const f=setup(),c=command();let called=0;Object.defineProperty(c,'rate',{enumerable:true,get(){called++;return 200;}});assert.equal((await f.create().resolveTariffDraft(f.request(c))).error,'invalid_request');assert.equal(called,0);});
test('retired ledger union rejects mixed shapes, wrong keys, hashes, command echoes and receipt kinds',async()=>{const f=setup();await f.create().resolveTariffDraft(f.request(command()));const ledger=copy(f.store.tenant.tariffCommandLedger);for(const mutate of [l=>Object.values(l.entries)[0].acceptedAt=NOW,l=>Object.values(l.entries)[0].receipt.acceptedAt=NOW,l=>Object.values(l.entries)[0].receipt.kind='appendTariffVersion',l=>Object.values(l.entries)[0].receipt.requestId='other',l=>Object.values(l.entries)[0].retiredAt='invalid',l=>Object.values(l.entries)[0].commandJson='{}',l=>Object.values(l.entries)[0].commandHash='a'.repeat(64),l=>{l.entries={bad:Object.values(l.entries)[0]};},l=>Object.values(l.entries)[0].extra=true]){const bad=copy(ledger);mutate(bad);assert.throws(()=>Ledger.validateTariffLedger(bad,f.store.tenant.products),Ledger.TariffLedgerError);}const before=copy(f.store.tenant);assert.throws(()=>Ledger.appendTariffRetirement(ledger,{uid:'owner-1',command:command(),retiredAt:NOW},f.store.tenant.products),e=>e.code==='conflict');assert.deepEqual(f.store.tenant,before);});
test('accepted targets remain unique while many retired drafts may refer to the same stale target',async()=>{const f=setup();assert.equal((await f.create().execute(f.request(command()))).ok,true);for(let i=0;i<3;i++)assert.equal((await f.create().resolveTariffDraft(f.request(command({requestId:'retired-'+i,rate:201+i})))).outcome,'retired');assert.equal(Object.keys(Ledger.validateTariffLedger(f.store.tenant.tariffCommandLedger,f.store.tenant.products).entries).length,4);assert.equal(f.cycle().tariffInputs.historyByWorker['worker-1']['rate-2'].rate,200);});
test('accepted and retired entries share one strict capacity with no purge and no partial write',async()=>{const f=setup(),c=command();assert.equal((await f.create().execute(f.request(c))).ok,true);const ledger=copy(f.store.tenant.tariffCommandLedger);for(let i=0;i<255;i++)Object.assign(ledger.entries,Ledger.appendTariffRetirement(undefined,{uid:'owner-1',command:command({requestId:'retired-'+i}),retiredAt:NOW},f.store.tenant.products).entries);f.store.tenant.tariffCommandLedger=ledger;const before=copy(f.store.tenant),writes=f.stats.writes;assert.deepEqual(await f.create().resolveTariffDraft(f.request(command({requestId:'over-cap'}))),{ok:false,error:'capacity_limit'});assert.deepEqual(f.store.tenant,before);assert.equal(f.stats.writes,writes);assert.equal(Object.keys(ledger.entries).length,256);assert.throws(()=>Ledger.validateTariffLedger({...ledger,padding:'x'.repeat(1024*1024)},f.store.tenant.products),e=>e.code==='capacity_limit');});
test('cold and speculative SDK results cannot invent a successful retirement receipt',async()=>{const f=setup(),before=copy(f.store.tenant);f.hooks.result=()=>({committed:true,snapshot:{val:()=>copy(before)}});assert.deepEqual(await f.create().resolveTariffDraft(f.request(command())),{ok:false,error:'unavailable'});assert.deepEqual(f.store.tenant,before);const cold=setup();cold.hooks.cold=true;assert.equal((await cold.create().resolveTariffDraft(cold.request(command()))).outcome,'retired');assert.equal(cold.stats.auth,2);assert.equal(cold.stats.writes,1);});
test('strict HTTP resolver accepts only exact POST original tariff draft and never routes general admin commands',async()=>{let calls=0;const writer={execute:async()=>{throw Error('wrong-operation');},resolveTariffDraft:async()=>{calls++;return {ok:true,outcome:'retired',receipt:retiredReceipt(),replayed:false};}},handler=transport(writer);for(const req of [request(RESOLVE+'?uid=owner-1'),request(RESOLVE,{kind:'setGrant'}),request(RESOLVE,command({rate:1.5})),request(RESOLVE,command({profile:{owner:true}})),request('/v1/production/owner/grants')])assert.equal((await run(handler,req)).statusCode,400);const get=request();get.method='GET';assert.equal((await run(handler,get)).statusCode,405);assert.equal(calls,0);assert.deepEqual((await run(handler)).body,{ok:true,outcome:'retired',receipt:retiredReceipt(),replayed:false});assert.equal(calls,1);const legacy=transport({execute:async()=>({})});assert.equal((await run(legacy)).statusCode,400);});
test('resolver rejects duplicate body/security keys, invalid UTF8 and oversized bodies before executing',async()=>{let calls=0;const handler=transport({execute:async()=>({}),resolveTariffDraft:async()=>{calls++;return {};}});for(const rawBody of [Buffer.from('{"command":{},"command":{}}'),Buffer.from('{"command":{"kind":"appendTariffVersion","kind":"setGrant"}}'),Buffer.from([0xc3,0x28]),Buffer.alloc(32769,32)]){const req=request();req.rawBody=rawBody;req.headers['content-length']=String(rawBody.length);req.rawHeaders=Object.entries(req.headers).flat();assert.equal((await run(handler,req)).statusCode,400);}const duplicate=request();duplicate.rawHeaders.push('Authorization',duplicate.headers.authorization);assert.equal((await run(handler,duplicate)).statusCode,400);assert.equal(calls,0);});
test('resolver HTTP result is exact, scope-matched and excludes rates, actor identifiers and private fields',async()=>{const base={ok:true,outcome:'retired',receipt:retiredReceipt(),replayed:false};for(const mutate of [r=>r.outcome='missing',r=>r.receipt.kind='setGrant',r=>r.receipt.workerId='foreign',r=>r.receipt.retiredAt='invalid',r=>r.receipt.rate=200,r=>r.receipt.uid='owner-1',r=>r.replayed=1,r=>r.extra='synthetic-secret']){const result=copy(base);mutate(result);const handler=transport({execute:async()=>({}),resolveTariffDraft:async()=>result});assert.deepEqual((await run(handler)).body,{ok:false,error:'result_unknown',retrySameCommand:true});}let gets=0;const result=copy(base);Object.defineProperty(result.receipt,'retiredAt',{enumerable:true,get(){gets++;return NOW;}});assert.equal((await run(transport({execute:async()=>({}),resolveTariffDraft:async()=>result}))).statusCode,503);assert.equal(gets,0);const f=setup(),accepted=await f.create().execute(f.request(command())),out={ok:true,outcome:'accepted',receipt:accepted.receipt,replayed:true};assert.deepEqual((await run(transport({execute:async()=>({}),resolveTariffDraft:async()=>out}))).body,out);out.replayed=false;assert.equal((await run(transport({execute:async()=>({}),resolveTariffDraft:async()=>out}))).statusCode,503);});
test('resolver preflight is exact POST JSON and execution shares one bounded inFlight slot until settlement',async()=>{let release,calls=0;const blocked=new Promise(resolve=>{release=resolve;}),writer={execute:async()=>({ok:false,error:'unavailable'}),resolveTariffDraft:async()=>{calls++;await blocked;return {ok:true,outcome:'retired',receipt:retiredReceipt(),replayed:false};}},handler=transport(writer),preflight=request();preflight.method='OPTIONS';preflight.headers={origin:ORIGIN,'access-control-request-method':'POST','access-control-request-headers':'authorization, content-type'};preflight.rawHeaders=Object.entries(preflight.headers).flat();delete preflight.rawBody;assert.equal((await run(handler,preflight)).statusCode,204);assert.equal(calls,0);preflight.headers['access-control-request-method']='GET';preflight.rawHeaders=Object.entries(preflight.headers).flat();assert.equal((await run(handler,preflight)).statusCode,400);const pending=run(handler);await new Promise(resolve=>setImmediate(resolve));assert.deepEqual((await run(handler)).body,{ok:false,error:'busy',retrySameCommand:true});assert.deepEqual((await run(handler,request(APPEND))).body,{ok:false,error:'busy',retrySameCommand:true});release();assert.equal((await pending).statusCode,200);});
test('late or throwing resolver preserves unknown-result instructions and draft_retired maps to append409',async()=>{const writer={execute:async()=>({ok:false,error:'draft_retired'}),resolveTariffDraft:async()=>{await new Promise(resolve=>setTimeout(resolve,15));return {ok:true,outcome:'retired',receipt:retiredReceipt(),replayed:false};}},handler=transport(writer,{deadlineMs:1});assert.deepEqual((await run(handler)).body,{ok:false,error:'result_unknown',retrySameCommand:true});const append=await run(handler,request(APPEND));assert.equal(append.statusCode,409);assert.deepEqual(append.body,{ok:false,error:'draft_retired'});writer.resolveTariffDraft=async()=>{throw Error('synthetic-private-secret');};assert.deepEqual((await run(transport(writer))).body,{ok:false,error:'result_unknown',retrySameCommand:true});});
test('assembled resolver persists a fence once, replays lost ACK and blocks append across runtime instances',async()=>{const f=setup(),a=f.runtime(),b=f.runtime(),before=copy(f.store.tenant.products);f.hooks.result=next=>{f.store.tenant=prune(copy(next));f.stats.writes++;throw Error('synthetic-lost-ack');};assert.deepEqual((await run(a.handler)).body,{ok:false,error:'unavailable',retrySameCommand:true});f.hooks.result=null;const replay=await run(b.handler);assert.equal(replay.statusCode,200);assert.deepEqual(replay.body,{ok:true,outcome:'retired',receipt:retiredReceipt(),replayed:true});assert.equal((await run(a.handler,request(APPEND))).statusCode,409);assert.equal(f.stats.writes,1);assert.equal(f.stats.quota,3);assert.equal(f.buckets.size,1);assert.deepEqual(f.store.tenant.products,before);});
test('assembled resolver admission uses current owner and the same private bucket as view/append',async()=>{for(const mutate of [f=>f.store.tenant.grants['owner-1'].profile.owner=false,f=>f.store.tenant.grants['owner-1'].profile.active=false,f=>delete f.store.tenant.grants['owner-1']]){const f=setup();mutate(f);assert.equal((await run(f.runtime().handler)).body.ok,false);assert.equal(f.stats.quota,0);assert.equal(f.stats.writes,0);assert.equal(f.buckets.size,0);}const f=setup(),policy={rateWindowMs:60000,rateLimit:1,deadlineMs:1000,maxInFlight:1};assert.equal((await run(f.runtime(policy).handler)).statusCode,200);const view=request(VIEW);view.rawBody=Buffer.from('{"selection":{"productId":"product-1","cycleId":"cycle-1"}}');view.headers['content-length']=String(view.rawBody.length);view.rawHeaders=Object.entries(view.headers).flat();assert.equal((await run(f.runtime(policy).handler,view)).statusCode,429);assert.equal((await run(f.runtime(policy).handler,request(APPEND))).statusCode,429);assert.equal(f.stats.quota,1);assert.equal(f.stats.writes,1);});
