'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Http=require('../server/production-http-handler.cjs');
const ORIGIN='https://soldier.example.invalid',PROJECT='demo-session-proof',PATH='/v1/production/session';
const session=()=>({schemaVersion:1,projectId:PROJECT,databaseURL:'https://'+PROJECT+'.firebaseio.com',tenantId:'tenant-1',uid:'caller-1',grantRevision:1,profile:{active:true,owner:false,workerId:'worker-1',modules:{jahit:true}},cycles:[{productId:'product-1',cycleId:'cycle-1'}]});
function request(){const headers={origin:ORIGIN,authorization:'Bearer header.payload.signature'};return {method:'GET',url:PATH,headers,rawHeaders:Object.entries(headers).flat(),rawBody:Buffer.alloc(0)};}
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},end(raw){this.body=raw===undefined?null:JSON.parse(raw);this.writableEnded=true;}};}
function fixture(options={}){const calls=[];return {calls,handler:Http.createProductionHttpHandler({enabled:true,service:{execute:async()=>{throw Error('command forbidden');}},sessionService:{execute:async args=>{calls.push(args);return {ok:true,session:session()};}},allowedOrigins:[ORIGIN],deadlineMs:1000,maxInFlight:2,...options})};}
async function run(f,req=request()){const res=response();await f.handler(req,res);return res;}
test('session HTTP permits optional owner product labels, raw whitespace and empty metadata without weakening v1',async()=>{
  for(const workers of [false,true]){const s=session();s.profile={active:true,owner:true};s.cycleLabels=[{productId:'product-1',cycleId:'cycle-1',series:'  Synthetic  ',namaBarang:'Example',size:''}];if(workers)s.workerLabels=[{productId:'product-1',cycleId:'cycle-1',workers:[]}];const res=await run(fixture({sessionService:{execute:async()=>({ok:true,session:s})}}));assert.equal(res.statusCode,200);assert.deepEqual(res.body.session,s);assert.equal(res.headers['Cache-Control'],'no-store');}
});
test('session HTTP rejects malformed or non-owner product labels and never evaluates an accessor',async()=>{
  const base=()=>{const s=session();s.profile={active:true,owner:true};s.cycleLabels=[{productId:'product-1',cycleId:'cycle-1',series:'Synthetic',namaBarang:'Example',size:'M'}];return s;};
  for(const mutate of [s=>s.profile.owner=false,s=>s.cycleLabels=[],s=>s.cycleLabels[0].cycleId='other',s=>s.cycleLabels.push({...s.cycleLabels[0]}),s=>s.cycleLabels[0].rate=1,s=>s.cycleLabels[0].namaBarang='x'.repeat(257),s=>s.cycleLabels[0].size='bad\u0085control',s=>delete s.cycleLabels[0]]){const s=base();mutate(s);const res=await run(fixture({sessionService:{execute:async()=>({ok:true,session:s})}}));assert.equal(res.statusCode,503);assert.deepEqual(res.body,{ok:false,error:'unavailable'});}
  const s=base();let touched=0;Object.defineProperty(s.cycleLabels[0],'series',{enumerable:true,get(){touched++;return 'Example';}});assert.equal((await run(fixture({sessionService:{execute:async()=>({ok:true,session:s})}}))).statusCode,503);assert.equal(touched,0);
});
test('GET returns only fixed own-profile and cycle identifiers with no-store and header-only token',async()=>{const f=fixture(),req=request();Object.defineProperty(req,'body',{get(){throw Error('parsed body forbidden');}});const res=await run(f,req);assert.equal(res.statusCode,200);assert.deepEqual(f.calls,[{idToken:'header.payload.signature'}]);assert.deepEqual(res.body,{ok:true,session:session()});assert.equal(res.headers['Cache-Control'],'no-store');assert.equal(res.headers['Access-Control-Allow-Origin'],ORIGIN);});
test('optional cycle labels are allowlisted display strings; base-v1 and global visible catalog labels remain compatible',async()=>{
  for(const profile of [session().profile,{active:true,owner:true},{active:true,owner:false,modules:{qc:true}},{active:true,owner:false,modules:{laporan:true}},{active:true,owner:false,modules:{stok:true}}]){
    const s=session();s.profile=profile;s.workerLabels=[{productId:'product-1',cycleId:'cycle-1',workers:[{workerId:profile.owner||!profile.workerId?'worker-2':'worker-1',label:'<b>Synthetic name</b>'}]}];
    const res=await run(fixture({sessionService:{execute:async()=>({ok:true,session:s})}}));assert.equal(res.statusCode,200);assert.deepEqual(res.body,{ok:true,session:s});
  }
});
test('label response cannot expose a foreign cycle/partner worker, private metadata, duplicates, controls or executable getters',async()=>{
  const base=()=>{const s=session();s.workerLabels=[{productId:'product-1',cycleId:'cycle-1',workers:[{workerId:'worker-1',label:'Synthetic'}]}];return s;};
  for(const mutate of [s=>s.workerLabels=[],s=>s.workerLabels.push({...s.workerLabels[0]}),s=>s.workerLabels[0].productId='foreign-product',s=>s.workerLabels[0].workers=[],s=>s.workerLabels[0].workers[0].workerId='worker-2',s=>s.workerLabels[0].workers.push({...s.workerLabels[0].workers[0]}),s=>s.workerLabels[0].workers[0].label='bad\u0085control',s=>s.workerLabels[0].workers[0].label='x'.repeat(257),s=>s.workerLabels[0].workers[0].label=' spaces ',s=>s.workerLabels[0].workers[0].pin='synthetic-secret',s=>s.workerLabels[0].workers[0].rate=123,s=>{s.profile.owner=true;s.workerLabels[0].workers=Array.from({length:129},(_,i)=>({workerId:'worker-'+i,label:'Synthetic'}));}]){
    const s=base();mutate(s);const res=await run(fixture({sessionService:{execute:async()=>({ok:true,session:s})}}));assert.equal(res.statusCode,503);assert.deepEqual(res.body,{ok:false,error:'unavailable'});assert.equal(JSON.stringify(res).includes('synthetic-secret'),false);
  }
  const s=base();let touched=0;Object.defineProperty(s.workerLabels[0].workers[0],'label',{enumerable:true,get(){touched++;return 'Synthetic';}});assert.equal((await run(fixture({sessionService:{execute:async()=>({ok:true,session:s})}}))).statusCode,503);assert.equal(touched,0);
});
test('session preflight permits only GET and authorization; command preflight cannot select it',async()=>{for(const method of ['GET','POST']){const f=fixture(),req=request();req.method='OPTIONS';req.headers['access-control-request-method']=method;req.headers['access-control-request-headers']='authorization';const res=await run(f,req);assert.equal(res.statusCode,method==='GET'?204:400);assert.equal(f.calls.length,0);}const f=fixture(),req=request();req.method='OPTIONS';req.headers['access-control-request-method']='GET';req.headers['access-control-request-headers']='authorization,content-type';assert.equal((await run(f,req)).statusCode,400);});
test('session query/body/compression/duplicateheaders/wrongmethod never executes',async()=>{for(const mutate of [r=>{r.url+='?uid=other';},r=>{r.rawBody=Buffer.from('{}');},r=>{r.headers['content-type']='application/json';},r=>{r.headers['content-encoding']='gzip';},r=>{r.rawHeaders.push('Authorization','Bearer other.token.value');},r=>{r.headers['content-length']='1';},r=>{r.method='POST';}]){const f=fixture(),req=request();mutate(req);assert.ok([400,405].includes((await run(f,req)).statusCode));assert.equal(f.calls.length,0);}});
test('extra private or money fields, corrupt scope and duplicate/oversized manifest are not emitted',async()=>{for(const mutate of [s=>{s.privateAuthority='synthetic-secret';},s=>{s.profile.pin='synthetic-secret';},s=>{s.cycles[0].rate=123;},s=>{s.databaseURL='http://invalid';},s=>{s.cycles.push({...s.cycles[0]});},s=>{s.cycles=Array.from({length:257},(_,i)=>({productId:'product-'+i,cycleId:'cycle-1'}));}]){const s=session();mutate(s);const f=fixture({sessionService:{execute:async()=>({ok:true,session:s})}}),res=await run(f);assert.equal(res.statusCode,503);assert.deepEqual(res.body,{ok:false,error:'unavailable'});assert.equal(JSON.stringify(res).includes('synthetic-secret'),false);}});
test('a session read shares HTTP capacity with writes and retains slots until settlement',async()=>{let resolve;const f=fixture({maxInFlight:1,deadlineMs:5,sessionService:{execute:()=>new Promise(r=>{resolve=r;})}}),res=response(),task=f.handler(request(),res);await new Promise(r=>setTimeout(r,20));assert.equal(res.body,undefined);const req=request();req.url='/v1/production/commands';req.method='POST';req.headers['content-type']='application/json';req.rawBody=Buffer.from('{"command":{}}');const busy=await run(f,req);assert.equal(busy.body.error,'busy');resolve({ok:true,session:session()});await task;assert.deepEqual(res.body,{ok:false,error:'unavailable'});});
test('session service failures are fixed codes without command replay instruction or error text',async()=>{for(const execute of [async()=>({ok:false,error:'access_denied'}),async()=>({ok:false,error:'unavailable'}),async()=>{throw Error('synthetic-private-token');}]){const res=await run(fixture({sessionService:{execute}}));assert.ok([403,503].includes(res.statusCode));assert.equal(res.body.retrySameCommand,undefined);assert.equal(JSON.stringify(res).includes('synthetic-private-token'),false);}});
