'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Bridge=require('../production-bridge.js'),Authority=require('../server/production-authority.cjs'),Runtime=require('../server/production-runtime.cjs'),{fakeIndexedDB}=require('./helpers/command-indexeddb-fixture.cjs');
const PROJECT='demo-bridge-proof',URL='https://'+PROJECT+'.firebaseio.com',ENDPOINT='https://server.example.invalid/v1/production/commands',ORIGIN='https://soldier.example.invalid',NOW='2026-10-05T03:00:00.000Z';
const copy=v=>v===undefined?null:JSON.parse(JSON.stringify(v)),tick=()=>new Promise(r=>setImmediate(r));
function fixture(role='jahit'){
  const state=Authority.createAuthority({product:{id:'product-1',series:'Synthetic',namaBarang:'Example',size:'M',cutQuantity:10},cycleId:'cycle-1',workers:[{id:'worker-1',nama:'Synthetic partner'}],assignments:[{id:'assignment-1',workerId:'worker-1',qty:10}],now:NOW});
  const profile=role==='jahit'?{active:true,owner:false,workerId:'worker-1',modules:{jahit:true}}:{active:true,owner:false,modules:{qc:true}};
  const tenant={schemaVersion:1,projectId:PROJECT,tenantId:'tenant-1',grants:{'caller-1':{revision:0,profile}},products:{'product-1':{cycles:{'cycle-1':{config:{revision:0,active:true,reviewedEmptyCycle:true,tariffPolicy:'explicit-historical-jakarta-v1'},tariffInputs:{revision:0,policy:{version:'policy-1',kind:'jakarta-fixed-local-time',hour:8,minute:0},historyByWorker:{'worker-1':{'tariff-1':{effectiveAt:'2026-01-01T00:00:00.000Z',currency:'IDR',rate:100}}}},wire:Authority.encodeStorage(state)}}}}};
  const roots=new Map([['authorityTenants/tenant-1',tenant]]),subscribers=new Map(),authSubscribers=new Set(),stats={fetch:0,tokens:0,refs:0,posts:0},controls={loseResponse:false,sessionGate:null,sessionMutate:null,rawSession:null,tokenGate:null};
  const read=path=>{const parts=path.split('/'),root=roots.get(parts.splice(0,2).join('/'));let value=root;for(const p of parts)value=value&&value[p];return copy(value);};
  const notify=()=>{for(const [path,callbacks]of subscribers)for(const cb of callbacks)queueMicrotask(()=>cb({val:()=>read(path)}));};
  const snapshot=v=>({val:()=>copy(v)}),app={options:{projectId:PROJECT,databaseURL:URL}};
  const database={app,ref(path){return {toString:()=>URL+'/'+path,get:async()=>snapshot(roots.get(path)??null),on(event,callback){callback(snapshot(roots.get(path)??null));},off(){},async transaction(update){const next=update(copy(roots.get(path)??null));if(next===undefined)return {committed:false,snapshot:snapshot(roots.get(path)??null)};roots.set(path,copy(next));notify();return {committed:true,snapshot:snapshot(next)};}};}};
  const serverAuth={app,verifyIdToken:async(token,revoked)=>{assert.equal(revoked,true);assert.equal(token,'header.payload.signature');return {uid:'caller-1',sub:'caller-1',aud:PROJECT,iss:'https://securetoken.google.com/'+PROJECT,email_verified:true,firebase:{sign_in_provider:'google.com'},exp:Date.parse(NOW)/1000+3600};}};
  const runtime=Runtime.createProductionRuntime({enabled:true,projectId:PROJECT,databaseURL:URL,tenantId:'tenant-1',database,auth:serverAuth,allowedOrigins:[ORIGIN],clock:()=>NOW,policy:{rateWindowMs:60000,rateLimit:100,deadlineMs:1000,maxInFlight:4}});
  const user={uid:'caller-1',emailVerified:true,providerData:[{providerId:'google.com'}],async getIdToken(force){assert.equal(force,true);stats.tokens++;if(controls.tokenGate)await controls.tokenGate();return 'header.payload.signature';}};
  const auth={app,currentUser:user};
  const sdk={ref(db,path){stats.refs++;assert.equal(db,database);return {path,toString:()=>db.app.options.databaseURL+'/'+path};},onValue(ref,callback){if(!subscribers.has(ref.path))subscribers.set(ref.path,new Set());const group=subscribers.get(ref.path);group.add(callback);queueMicrotask(()=>callback({val:()=>read(ref.path)}));return ()=>{group.delete(callback);if(!group.size)subscribers.delete(ref.path);};},onAuthStateChanged(a,callback){assert.equal(a,auth);authSubscribers.add(callback);queueMicrotask(()=>callback(auth.currentUser));return ()=>authSubscribers.delete(callback);}};
  const response=(url,status,raw)=>{const bytes=new TextEncoder().encode(raw);return {url,status,type:'cors',redirected:false,headers:new Headers({'Content-Type':'application/json; charset=utf-8','Content-Length':String(bytes.length)}),body:new ReadableStream({start(c){c.enqueue(bytes);c.close();}})};};
  const fetch=async(url,init)=>{
    stats.fetch++;if(init.method==='POST')stats.posts++;else if(controls.sessionGate)await controls.sessionGate();
    assert.equal(init.credentials,'omit');assert.equal(init.redirect,'error');const headers={origin:ORIGIN,authorization:init.headers.Authorization};if(init.headers['Content-Type'])headers['content-type']=init.headers['Content-Type'];const req={url:new globalThis.URL(url).pathname,method:init.method,headers,rawHeaders:Object.entries(headers).flat(),rawBody:init.body===undefined?Buffer.alloc(0):Buffer.from(init.body)};
    const res={setHeader(){},end(raw){this.raw=raw;this.writableEnded=true;}};await runtime.handler(req,res);stats.lastStatus=res.statusCode;stats.lastError=JSON.parse(res.raw).error||'none';
    if(init.method==='POST'&&controls.loseResponse){controls.loseResponse=false;throw Error('synthetic-lost-response');}
    if(init.method==='GET'&&controls.sessionMutate){const result=JSON.parse(res.raw);controls.sessionMutate(result);res.raw=JSON.stringify(result);}
    const raw=init.method==='GET'&&controls.rawSession!==null?(typeof controls.rawSession==='function'?controls.rawSession(res.raw):controls.rawSession):res.raw;
    return response(url,res.statusCode,raw);
  };
  const idb=fakeIndexedDB(),views=[],clears=[];
  const options={enabled:true,projectId:PROJECT,databaseURL:URL,tenantId:'tenant-1',endpointURL:ENDPOINT,auth,database,sdk,indexedDB:idb.api,fetch,isCurrent:()=>true,onView:v=>views.push(v),onClear:code=>clears.push(code)};
  const create=(extra={})=>Bridge.createProductionBridge({...options,...extra}),decoded=()=>Authority.decodeStorage(roots.get('authorityTenants/tenant-1').products['product-1'].cycles['cycle-1'].wire);
  const command=()=>({requestId:'request-1',productId:'product-1',cycleId:'cycle-1',expectedRevision:0,kind:'sewing',payload:{id:'sewing-1',assignmentId:'assignment-1',tanggal:'2026-10-05',good:10,reject:0}});
  function switchUser(){auth.currentUser={...user,uid:'caller-2'};for(const cb of authSubscribers)cb(auth.currentUser);}
  return {create,options,roots,tenant,stats,controls,idb,views,clears,subscribers,authSubscribers,auth,database,command,decoded,notify,switchUser,response};
}
test('disabled bridge has no token, network, storage or listener side effects',async()=>{const f=fixture(),b=f.create({enabled:false});assert.equal((await b.connect()).error,'service_disabled');assert.equal((await b.prepare(f.command())).error,'service_disabled');assert.deepEqual(f.stats,{fetch:0,tokens:0,refs:0,posts:0});assert.equal(f.idb.stats.opens,0);});
test('assembled bridge loads a server manifest, exact views and own wage without any legacy ref',async()=>{const f=fixture(),b=f.create();const result=await b.connect();assert.equal(result.ok,true,JSON.stringify({result,clears:f.clears,stats:f.stats,storage:f.idb.stats}));await tick();assert.ok(f.views.some(v=>v.complete));const last=f.views.at(-1);assert.equal(last.cycles[0].operations.id,'product-1');assert.equal(last.cycles[0].wage.workerId,'worker-1');assert.equal(last.consistency,'independent-listeners');assert.ok([...f.subscribers.keys()].every(p=>p.startsWith('authorityTenants/tenant-1/')));assert.deepEqual(f.clears,['loading']);b.dispose();assert.equal(f.subscribers.size,0);assert.equal(f.authSubscribers.size,0);});
test('command persistence + runtime lost response + exact replay commits one operation and retains accepted receipt',async()=>{const f=fixture(),b=f.create();assert.equal((await b.connect()).ok,true);const c=f.command();assert.equal((await b.prepare(c)).ok,true);c.payload.good=1;f.controls.loseResponse=true;assert.equal((await b.send('request-1')).error,'result_unknown');assert.equal(f.decoded().revision,1);assert.equal((await b.pending()).commands[0].payload.good,10);const retry=await b.send('request-1');assert.equal(retry.ok,true);assert.equal(retry.replayed,true);assert.equal(f.decoded().revision,1);assert.equal(Object.keys(f.decoded().sewing).length,1);assert.deepEqual((await b.pending()).commands,[]);assert.equal(f.stats.tokens,3);b.dispose();});
test('QC uses canonical commands with no wage read or money command payload',async()=>{const f=fixture('qc'),b=f.create();assert.equal((await b.connect()).ok,true);await tick();assert.ok(f.views.some(v=>v.complete));assert.equal(f.views.at(-1).cycles[0].wage,null);assert.equal([...f.subscribers.keys()].some(p=>p.includes('earningsByWorker')),false);const c=f.command();c.payload.tarif=100;assert.equal((await b.prepare(c)).error,'invalid_request');assert.equal(f.stats.posts,0);b.dispose();});
test('foreign UID/project/tenant session, unknown fields and escaped duplicate keys never open a production listener',async()=>{for(const mutate of [r=>{r.session.uid='caller-2';},r=>{r.session.tenantId='tenant-2';},r=>{r.session.projectId='demo-other-proof';},r=>{r.session.profile.pin='synthetic-secret';}]){const f=fixture();f.controls.sessionMutate=mutate;const b=f.create();assert.equal((await b.connect()).ok,false);assert.equal(f.subscribers.size,0);assert.equal(f.views.length,0);}const f=fixture();f.controls.rawSession='{"ok":false,"\\u006fk":true,"session":{}}';assert.equal((await f.create().connect()).ok,false);assert.equal(f.idb.stats.opens,0);});
test('auth change during initial network wait stops without exposing cached success or drafts',async()=>{const f=fixture();let ready,release;const started=new Promise(r=>{ready=r;});f.controls.sessionGate=()=>{ready();return new Promise(r=>{release=r;});};const b=f.create(),pending=b.connect();await started;f.switchUser();release();assert.equal((await pending).error,'access_denied');assert.equal((await b.connect()).error,'access_denied');assert.equal(f.views.length,0);assert.equal(f.idb.stats.opens,0);});
test('database/auth binding changes during token wait and after connect stop before refs or commands',async()=>{for(const target of ['database','auth']){const f=fixture();let ready,release;const started=new Promise(r=>{ready=r;});f.controls.tokenGate=()=>{ready();return new Promise(r=>{release=r;});};const b=f.create(),pending=b.connect();await started;if(target==='database')f.database.app={options:{...f.database.app.options,projectId:'demo-other-proof'}};else f.auth.app={options:{...f.auth.app.options,projectId:'demo-other-proof'}};release();assert.equal((await pending).error,'access_denied');assert.equal(f.stats.fetch,0);assert.equal(f.stats.refs,0);assert.equal(f.idb.stats.opens,0);}const f=fixture(),b=f.create();assert.equal((await b.connect()).ok,true);f.database.app={options:{...f.database.app.options,databaseURL:'https://demo-other-proof.firebaseio.com'}};assert.equal((await b.prepare(f.command())).error,'access_denied');assert.equal(f.stats.posts,0);assert.equal(f.subscribers.size,0);});
test('live profile revocation clears views and holds pending journal for original scope; dispose never returns cached connect success',async()=>{const f=fixture(),b=f.create();assert.equal((await b.connect()).ok,true);assert.equal((await b.prepare(f.command())).ok,true);await tick();f.roots.get('authorityTenants/tenant-1').grants['caller-1'].profile.active=false;f.notify();await tick();assert.equal((await b.send('request-1')).error,'access_denied');assert.equal((await b.connect()).error,'access_denied');assert.equal(f.stats.posts,0);assert.equal(f.subscribers.size,0);assert.ok(f.clears.includes('access_changed'));assert.equal(JSON.stringify([...f.idb.databases.values()][0].stores.get('journals').values().next().value).includes('request-1'),true);const g=fixture(),d=g.create();assert.equal((await d.connect()).ok,true);d.dispose();assert.equal((await d.connect()).error,'access_denied');});
test('manifest membership cannot be manufactured by command fields or a getter',async()=>{const f=fixture(),b=f.create();await b.connect();const c=f.command();c.productId='other-product';assert.equal((await b.prepare(c)).error,'invalid_request');let calls=0;Object.defineProperty(c,'productId',{get(){calls++;return 'product-1';}});assert.equal((await b.prepare(c)).error,'invalid_request');assert.equal(calls,0);assert.equal(f.stats.posts,0);b.dispose();});
test('invalid/inactive session is rejected before journal hydration and before listeners',async()=>{for(const mutate of [r=>{r.session.schemaVersion=2;},r=>{r.session.profile.active=false;},r=>{r.session.cycles[0].rate=100;}]){const f=fixture();f.controls.sessionMutate=mutate;const result=await f.create().connect();assert.equal(result.ok,false);assert.equal(f.idb.stats.opens,0);assert.equal(f.stats.refs,0);assert.equal(f.views.length,0);}});
test('concurrent connect waits for journal and views; commands cannot pass early readiness',async()=>{const f=fixture();let ready,release;const started=new Promise(r=>{ready=r;});f.idb.control.beforeCommit=()=>{ready();return new Promise(r=>{release=r;});};const b=f.create(),one=b.connect();await started;let settled=false;const two=b.connect().then(r=>{settled=true;return r;});await tick();assert.equal(settled,false);assert.equal((await b.prepare(f.command())).error,'not_ready');assert.equal(f.stats.posts,0);assert.equal(f.views.length,0);f.idb.control.beforeCommit=null;release();assert.equal((await one).ok,true);assert.equal((await two).ok,true);assert.ok(f.views.at(-1).complete);b.dispose();});
test('escaped duplicate keys with an otherwise valid session are rejected without hydration',async()=>{const f=fixture();f.controls.rawSession=raw=>raw.replace('"ok":true','"ok":false,"\\u006fk":true');assert.equal((await f.create().connect()).ok,false);assert.equal(f.idb.stats.opens,0);assert.equal(f.views.length,0);});
test('Fetch decoded response may differ from Content-Length while decoded byte cap remains strict',async()=>{const f=fixture();const b=f.create({fetch:async(...args)=>{const res=await f.options.fetch(...args);res.headers.set('Content-Length','8');return res;}});assert.equal((await b.connect()).ok,true);b.dispose();const g=fixture();g.controls.rawSession=' '.repeat(65537);assert.equal((await g.create().connect()).ok,false);assert.equal(g.idb.stats.opens,0);});
test('empty or malformed endless session stream is bounded and cancelled before hydration',async()=>{const f=fixture();let reads=0,cancels=0;const b=f.create({fetch:async url=>({url,status:200,type:'cors',redirected:false,headers:new Headers({'Content-Type':'application/json'}),body:{getReader(){return {async read(){reads++;return {done:false,value:new Uint8Array(0)};},async cancel(){cancels++;},releaseLock(){}};}}})});assert.equal((await b.connect()).ok,false);assert.equal(reads,65537);assert.equal(cancels,1);assert.equal(f.idb.stats.opens,0);});
test('synchronous view failure consumes readiness rejection and cleans every listener',async()=>{for(const extra of [f=>({sdk:{...f.options.sdk,ref(){return {toString:()=>URL+'/foreign/path'};}}}),f=>({sdk:{...f.options.sdk,onValue(ref,value,error){error();return ()=>{};}}}),f=>({onClear(){throw Error('synthetic-ui-failure');}})]){const f=fixture(),b=f.create(extra(f));assert.equal((await b.connect()).error,'unavailable');await tick();assert.equal(f.subscribers.size,0);assert.equal(f.authSubscribers.size,0);assert.equal(f.stats.posts,0);}});
test('view readiness timeout reports temporary unavailability and closes registrations',async()=>{const f=fixture(),b=f.create({requestTimeoutMs:100,sdk:{...f.options.sdk,onValue(){return ()=>{};}}});assert.equal((await b.connect()).error,'unavailable');assert.ok(f.clears.includes('unavailable'));assert.equal(f.subscribers.size,0);assert.equal(f.authSubscribers.size,0);assert.equal((await b.connect()).error,'unavailable');});
