'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const Deployment=require('../server/deployment/functions-adapter.cjs'),Prepare=require('../server/deployment/prepare-package.cjs');
const PROJECT='soldier-test-proof',DATABASE='https://soldier-test-proof-default-rtdb.firebaseio.com',ORIGIN='https://soldier.example.invalid';
const configuration=()=>({enabled:true,projectId:PROJECT,databaseURL:DATABASE,tenantId:'tenant-proof',allowedOrigins:[ORIGIN],serviceAccount:'soldier-production-runtime@'+PROJECT+'.iam.gserviceaccount.com'});
const environment=()=>({GOOGLE_CLOUD_PROJECT:PROJECT,GCLOUD_PROJECT:PROJECT,FUNCTION_TARGET:'soldierProduction',K_SERVICE:'soldierproduction'});
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},end(v){this.raw=v;this.body=JSON.parse(v);this.writableEnded=true;}};}
function request(session=false){const rawBody=session?Buffer.alloc(0):Buffer.from('{"command":{"requestId":"synthetic-request"}}');const headers={origin:ORIGIN,authorization:'Bearer header.payload.signature',...(!session?{'content-type':'application/json','content-length':String(rawBody.length)}:{})};return {method:session?'GET':'POST',url:session?'/v1/production/session':'/v1/production/commands',headers,rawHeaders:Object.entries(headers).flat(),rawBody};}
function fixture(changes={}){
  const env=environment(),counts={load:0,adc:0,init:0,runtime:0,requests:0},calls={};
  const sdk={getApps:()=>[],applicationDefault:()=>{counts.adc++;return {managedIdentity:true};},initializeApp:(opts,name)=>{counts.init++;calls.init={opts,name};return {name,options:opts};},getAuth:app=>({app,verifyIdToken:async()=>{throw Error('not_used');}}),getDatabase:app=>({app,ref(){throw Error('not_used');}})};
  const opts={configuration:configuration(),environment:()=>env,loadAdminSdk:()=>{counts.load++;return sdk;},createRuntime:args=>{counts.runtime++;calls.runtime=args;return {handler:async(req,res)=>{counts.requests++;calls.request=req;res.statusCode=200;res.setHeader('Cache-Control','no-store');res.end('{"ok":true}');}};},...changes};
  const deployment=Deployment.createProductionDeployment(opts);
  const run=async(req=request())=>{const res=response();await deployment.handler(req,res);return res;};return {env,counts,calls,sdk,opts,deployment,run};
}
test('source package is OFF, imports no SDK and exports no deployable function',()=>{const config=require('../server/deployment/configuration.cjs');assert.equal(config.enabled,false);assert.ok(Object.isFrozen(config));assert.ok(Object.isFrozen(config.allowedOrigins));assert.deepEqual(require('../server/deployment/index.cjs'),{});assert.equal(Object.keys(require.cache).some(k=>/node_modules[\\/]firebase-(admin|functions)/.test(k)),false);});
test('OFF and malformed configuration stop before inspecting environment or importing Admin',async()=>{for(const config of [undefined,{}, {...configuration(),enabled:false},{...configuration(),secret:'synthetic-forbidden-field'}]){let touched=0;const d=Deployment.createProductionDeployment({configuration:config,environment:()=>{touched++;throw Error('should_not_read');},loadAdminSdk:()=>{touched++;throw Error('should_not_import');}});const r=response();await d.handler(request(),r);assert.equal(r.statusCode,503);assert.equal(r.body.error,'service_disabled');assert.equal(touched,0);}});
test('configuration getters, prototypes, sparse/duplicate/wildcard origins and malformed binding are not adopted',()=>{let getter=0;const get=configuration();Object.defineProperty(get,'enabled',{enumerable:true,get(){getter++;return true;}});const sparse=configuration();sparse.allowedOrigins=new Array(1);for(const c of [get,sparse,Object.assign(Object.create({extra:true}),configuration()),{...configuration(),allowedOrigins:[ORIGIN,ORIGIN]},{...configuration(),allowedOrigins:['*']},{...configuration(),allowedOrigins:['http://localhost']},{...configuration(),allowedOrigins:[ORIGIN+'/']},{...configuration(),allowedOrigins:[ORIGIN+':443']},{...configuration(),databaseURL:DATABASE+'/'},{...configuration(),databaseURL:DATABASE+'?key=value'},{...configuration(),databaseURL:'https://foreign.example.invalid'},{...configuration(),serviceAccount:'owner@example.invalid'},{...configuration(),serviceAccount:'soldier-production-runtime@foreign-project.iam.gserviceaccount.com'},{...configuration(),projectId:'demo-soldier-proof'},{...configuration(),tenantId:'constructor'}])assert.equal(Deployment.validateConfiguration(c),null);assert.equal(getter,0);});
test('source configuration is snapshotted and cannot be changed by the caller after assembly',async()=>{const c=configuration(),f=fixture({configuration:c});c.allowedOrigins.push('https://other.example.invalid');c.projectId='foreign-project';c.tenantId='foreign-tenant';assert.equal((await f.run()).statusCode,200);assert.equal(f.calls.runtime.projectId,PROJECT);assert.equal(f.calls.runtime.tenantId,'tenant-proof');const req=request();req.headers.origin='https://other.example.invalid';req.rawHeaders=Object.entries(req.headers).flat();assert.equal((await f.run(req)).statusCode,403);assert.equal(f.counts.requests,1);});
test('fixed Functions options and policy cannot grow through caller fields',()=>{const f=fixture({maxInstances:999,concurrency:99,policy:{rateLimit:999999}});assert.deepEqual(f.deployment.functionOptions,{region:'asia-southeast1',memory:'512MiB',cpu:1,minInstances:0,maxInstances:1,concurrency:1,timeoutSeconds:60,serviceAccount:configuration().serviceAccount,cors:false,invoker:'public',preserveExternalChanges:false});assert.ok(Object.isFrozen(f.deployment.functionOptions));assert.deepEqual(Deployment.POLICY,{rateWindowMs:60000,rateLimit:30,deadlineMs:25000,maxInFlight:1});});
test('registering one onRequest function neither imports Admin nor initializes it',()=>{let registered=0;const f=fixture();const exports=Deployment.createFunctionsExports({...f.opts,onRequest:(options,handler)=>{registered++;assert.deepEqual(options,f.deployment.functionOptions);assert.equal(typeof handler,'function');return {preparedFunction:true};}});assert.deepEqual(Object.keys(exports),['soldierProduction']);assert.equal(registered,1);assert.equal(f.counts.load,0);assert.equal(f.counts.init,0);assert.deepEqual(Deployment.createFunctionsExports({configuration:{...configuration(),enabled:false},onRequest:()=>{throw Error('must_not_register');}}),{});assert.throws(()=>Deployment.createFunctionsExports({configuration:{...configuration(),allowedOrigins:['*']},onRequest(){}}),/invalid_deployment_configuration/);});
test('wrong host project, absent managed host, credential overrides and emulator flags fail before Admin',async()=>{const cases=[{GOOGLE_CLOUD_PROJECT:'foreign-project'},{GCLOUD_PROJECT:'foreign-project'},{K_SERVICE:undefined},{K_SERVICE:'Invalid_Name'},{FUNCTION_TARGET:'otherFunction'},{GOOGLE_CLOUD_PROJECT:undefined,GCLOUD_PROJECT:undefined},{GOOGLE_APPLICATION_CREDENTIALS:'synthetic-key-file.json'},{GOOGLE_APPLICATION_CREDENTIALS:''},{CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE:'synthetic-file'},{FIREBASE_DATABASE_EMULATOR_HOST:'127.0.0.1:9000'},{FIREBASE_AUTH_EMULATOR_HOST:'127.0.0.1:9099'},{FUNCTIONS_EMULATOR:'true'}];for(const change of cases){const f=fixture();Object.assign(f.env,change);const r=await f.run();assert.equal(r.statusCode,503);assert.equal(r.body.error,'unavailable');assert.equal(f.counts.load,0);assert.equal(f.counts.adc,0);assert.equal(JSON.stringify(r.body).includes('synthetic'),false);}});
test('unknown admin/bootstrap routes and query paths cannot initialize Admin or acquire an SDK binding',async()=>{const f=fixture();for(const url of ['/','/v1/production/admin','/v1/production/bootstrap','/v1/production/commands?tenantId=other','/v1/production/session?debug=true','/soldierProduction/v1/production/commands']){const req=request();req.url=url;assert.equal((await f.run(req)).statusCode,400);}assert.equal(f.counts.load,0);assert.equal(f.counts.requests,0);});
test('unapproved origins, wrong methods, missing tokens and unsafe body transport are rejected before ADC',async()=>{const changes=[r=>{r.headers.origin='https://other.example.invalid';},r=>{r.method='PUT';},r=>{delete r.headers.authorization;},r=>{r.headers.authorization='Bearer broken';},r=>{r.rawBody=Buffer.alloc(32769);r.headers['content-length']='32769';},r=>{r.rawBody=undefined;},r=>{r.rawBody=Buffer.alloc(0);r.headers['content-length']='0';},r=>{r.headers['content-encoding']='gzip';},r=>{r.headers['content-type']='text/plain';},r=>{r.headers['content-length']='001';}];for(const change of changes){const f=fixture(),req=request();change(req);req.rawHeaders=Object.entries(req.headers).flat();const r=await f.run(req);assert.ok([400,403,405].includes(r.statusCode));assert.equal(f.counts.load,0);}});
test('oversized headers, duplicate security headers and invalid raw header structure are bounded before SDK',async()=>{for(const change of [r=>{r.rawHeaders.push('x-large','a'.repeat(32768));},r=>{r.rawHeaders.push('Authorization',r.headers.authorization);},r=>{r.rawHeaders.push('origin',ORIGIN);},r=>{r.rawHeaders.push('x-header','bad\r\nheader');},r=>{r.rawHeaders.push('x');},r=>{r.rawHeaders=new Array(260).fill('x');}]){const f=fixture(),req=request();change(req);assert.ok([400,431].includes((await f.run(req)).statusCode));assert.equal(f.counts.load,0);}});
test('valid preflight is handled without Admin initialization and never enables wildcard CORS',async()=>{for(const session of [false,true]){const f=fixture(),req=request(session);req.method='OPTIONS';req.headers={origin:ORIGIN,'access-control-request-method':session?'GET':'POST','access-control-request-headers':session?'authorization':'authorization, content-type'};req.rawHeaders=Object.entries(req.headers).flat();delete req.rawBody;const res={headers:{},setHeader(k,v){this.headers[k]=v;},end(v){this.raw=v;this.writableEnded=true;}};await f.deployment.handler(req,res);assert.equal(res.statusCode,204);assert.equal(res.headers['Access-Control-Allow-Origin'],ORIGIN);assert.equal(f.counts.load,0);assert.equal(f.counts.adc,0);}});
test('valid request binds ADC app, auth and DB explicitly once and forwards original raw request',async()=>{const f=fixture(),req=request();assert.equal(f.counts.load,0);assert.equal((await f.run(req)).statusCode,200);assert.deepEqual(f.calls.init,{opts:{projectId:PROJECT,databaseURL:DATABASE,credential:{managedIdentity:true}},name:'soldier-production-runtime-v1'});assert.equal(f.calls.runtime.enabled,true);assert.equal(f.calls.runtime.database.app,f.calls.runtime.auth.app);assert.equal(f.calls.runtime.projectId,PROJECT);assert.equal(f.calls.runtime.databaseURL,DATABASE);assert.equal(f.calls.runtime.tenantId,'tenant-proof');assert.equal(f.calls.runtime.policy,Deployment.POLICY);assert.equal(f.calls.request,req);assert.equal((await f.run(request(true))).statusCode,200);assert.equal(f.counts.load,1);assert.equal(f.counts.init,1);assert.equal(f.counts.runtime,1);assert.equal(f.counts.requests,2);});
test('single-flight cold initialization is shared by concurrent adapter requests',async()=>{const f=fixture();const results=await Promise.all([f.run(),f.run(request(true))]);assert.ok(results.every(r=>r.statusCode===200));assert.equal(f.counts.init,1);assert.equal(f.counts.runtime,1);});
test('factory awaits the runtime promise and does not return while a command operation is unsettled',async()=>{let release,settled=false;const blocked=new Promise(resolve=>{release=resolve;}),f=fixture({createRuntime:()=>({handler:async(req,res)=>{await blocked;res.statusCode=200;res.end('{"ok":true}');}})});const running=f.run().then(r=>{settled=true;return r;});await new Promise(resolve=>setImmediate(resolve));assert.equal(settled,false);release();assert.equal((await running).statusCode,200);assert.equal(settled,true);});
test('SDK initialization failures are fixed errors, latched, and never expose credential or exception content',async()=>{const f=fixture({loadAdminSdk:()=>{throw Error('synthetic-private-key-do-not-return');}});for(let i=0;i<2;i++){const r=await f.run();assert.deepEqual(r.body,{ok:false,error:'unavailable',retrySameCommand:true});assert.equal(r.raw.includes('private-key'),false);}const s=await f.run(request(true));assert.deepEqual(s.body,{ok:false,error:'unavailable'});});
test('foreign/preexisting app or mismatched Auth/DB app cannot be adopted',async()=>{for(const change of [sdk=>{sdk.getApps=()=>[{name:'soldier-production-runtime-v1',options:{projectId:'foreign-project'}}];},sdk=>{sdk.initializeApp=(opts,name)=>({name,options:{...opts,databaseURL:'https://other.firebaseio.com'}});},sdk=>{sdk.getAuth=()=>({app:{options:{projectId:PROJECT}}});},sdk=>{sdk.getDatabase=()=>({app:{options:{projectId:PROJECT,databaseURL:DATABASE}}});}]){const f=fixture();change(f.sdk);assert.equal((await f.run()).statusCode,503);assert.equal(f.counts.runtime,0);}});
test('environment drift after warm binding blocks further forwarding without creating another app',async()=>{const f=fixture();assert.equal((await f.run()).statusCode,200);f.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';assert.equal((await f.run()).statusCode,503);assert.equal(f.counts.requests,1);assert.equal(f.counts.init,1);});
test('package manifest pins compatible SDKs, exact gaxios UUID child override and Node22 without install/deploy hooks',async()=>{const p=JSON.parse(await fs.readFile(path.join(__dirname,'../server/deployment/package.json'),'utf8'));assert.deepEqual(p.engines,{node:'22'});assert.deepEqual(p.dependencies,{'firebase-admin':'14.5.0','firebase-functions':'7.3.0'});assert.deepEqual(p.overrides,{gaxios:{uuid:'11.1.1'}});assert.equal(p.private,true);assert.equal(p.scripts,undefined);assert.equal(p.main,'server/deployment/index.cjs');const firebase=JSON.parse(await fs.readFile(path.join(__dirname,'../server/deployment/firebase.prepared.json'),'utf8'));assert.equal(firebase.functions[0].runtime,'nodejs22');assert.equal(firebase.functions[0].source,'functions');assert.equal(firebase.hosting,undefined);assert.equal(firebase.database,undefined);});
test('review-only Hosting fragment lists six exact routes without pinTag; claim still requires server opt-in',async()=>{const value=JSON.parse(await fs.readFile(path.join(__dirname,'../server/deployment/hosting-rewrites.prepared.json'),'utf8'));assert.deepEqual(value,{rewrites:[{source:'/v1/production/session',function:{functionId:'soldierProduction',region:'asia-southeast1'}},{source:'/v1/production/commands',function:{functionId:'soldierProduction',region:'asia-southeast1'}},{source:'/v1/production/owner/tariffs/view',function:{functionId:'soldierProduction',region:'asia-southeast1'}},{source:'/v1/production/owner/tariffs/append',function:{functionId:'soldierProduction',region:'asia-southeast1'}},{source:'/v1/production/owner/tariffs/resolve',function:{functionId:'soldierProduction',region:'asia-southeast1'}},{source:'/v1/production/enrollment/claim',function:{functionId:'soldierProduction',region:'asia-southeast1'}}]});});
test('local OFF package copies 21 runtime sources and the exact validated lock in 25 files without claiming install or audit',async()=>{const result=await Prepare.preparePackage(),expected=path.resolve(__dirname,'../server/deployment/.prepared'),dir=path.resolve(result.directory);assert.equal(path.dirname(dir),expected);try{const manifest=JSON.parse(await fs.readFile(path.join(dir,'preparation-manifest.json'),'utf8'));assert.equal(manifest.preparedOnly,true);assert.equal(manifest.configurationEnabled,false);assert.equal(manifest.dependenciesInstalled,false);assert.equal(manifest.dependencyLockReviewed,false);assert.equal(manifest.dependencyAuditReviewed,false);assert.equal(manifest.dependencyLockValidated,true);assert.equal(manifest.dependencyLockSha256,Prepare.PINNED_LOCK_SHA256);assert.equal(manifest.sourceFiles,21);assert.equal(manifest.files.length,25);assert.equal(manifest.dependencyPackageCount,275);assert.equal(manifest.dependencyOptionalPackageCount,118);assert.equal(manifest.dependencyRegistryAliasCount,3);assert.deepEqual(manifest.dependencyInstallScriptPackages,['@firebase/util','protobufjs']);const expectedFiles=[...Prepare.SOURCES.map(p=>'functions/'+p),'functions/package.json','functions/package-lock.json','firebase.json','hosting-rewrites.review-only.json'];assert.deepEqual(manifest.files.map(f=>f.path),expectedFiles);for(const item of manifest.files){const bytes=await fs.readFile(path.join(dir,...item.path.split('/')));assert.equal(bytes.length,item.bytes);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),item.sha256);assert.equal(/(backup|\.env|credential|\.html|production-ledger-admin|node_modules)/i.test(item.path),false);}const lock=manifest.files.find(f=>f.path==='functions/package-lock.json');assert.equal(lock.sha256,Prepare.PINNED_LOCK_SHA256);assert.equal(lock.bytes,123658);assert.deepEqual(await fs.readFile(path.join(dir,'functions/package-lock.json')),await fs.readFile(path.resolve(__dirname,'../server/deployment/package-lock.json')));const entry=path.join(dir,'functions/server/deployment/index.cjs');assert.deepEqual(require(entry),{});const closure=Prepare.SOURCES.filter(p=>p.endsWith('.cjs'));for(const file of closure){const text=await fs.readFile(path.join(dir,'functions',...file.split('/')),'utf8');for(const match of text.matchAll(/require\(['"](\.[^'"]+)['"]\)/g)){const dependency=path.resolve(path.dirname(path.join(dir,'functions',...file.split('/'))),match[1]);assert.ok(dependency.startsWith(path.join(dir,'functions')+path.sep));assert.ok((await fs.stat(dependency)).isFile());}}assert.equal(Prepare.SOURCES.some(p=>p.includes('validate-dependency-lock')),false);}finally{assert.equal(path.dirname(dir),expected);await fs.rm(dir,{recursive:true,force:false});}});
function blockOutput(t){const writes={mkdir:0,write:0};t.mock.method(fs,'mkdir',async()=>{writes.mkdir++;throw Error('unexpected_output_creation');});t.mock.method(fs,'writeFile',async()=>{writes.write++;throw Error('unexpected_output_write');});return writes;}
test('missing dependency lock aborts before any prepared output is created',async t=>{
  const lock=path.resolve(__dirname,'../server/deployment/package-lock.json'),stat=fs.lstat.bind(fs),writes=blockOutput(t);t.mock.method(fs,'lstat',async target=>{if(target===lock)throw Object.assign(Error('synthetic_missing_lock'),{code:'ENOENT'});return stat(target);});await assert.rejects(Prepare.preparePackage(),error=>error.code==='ENOENT');assert.deepEqual(writes,{mkdir:0,write:0});
});
test('even a structurally valid lock byte change requires explicit repinning before preparation',async t=>{
  const lock=path.resolve(__dirname,'../server/deployment/package-lock.json'),read=fs.readFile.bind(fs),writes=blockOutput(t);t.mock.method(fs,'readFile',async(target,...args)=>target===lock?Buffer.concat([await read(target),Buffer.from(' ')]):read(target,...args));await assert.rejects(Prepare.preparePackage(),error=>error.message==='invalid_package_lock');assert.deepEqual(writes,{mkdir:0,write:0});
});
test('invalid lock provenance fails validation before creating or copying any package output',async t=>{
  const lock=path.resolve(__dirname,'../server/deployment/package-lock.json'),read=fs.readFile.bind(fs),raw=JSON.parse((await read(lock)).toString('utf8'));raw.packages['node_modules/firebase-admin'].resolved='https://foreign.example.invalid/firebase-admin.tgz';const writes=blockOutput(t);t.mock.method(fs,'readFile',async(target,...args)=>target===lock?Buffer.from(JSON.stringify(raw)):read(target,...args));await assert.rejects(Prepare.preparePackage(),error=>error.message==='invalid_dependency_lock');assert.deepEqual(writes,{mkdir:0,write:0});
});
test('dependency lock symlink is rejected without following or reading it',async t=>{
  const lock=path.resolve(__dirname,'../server/deployment/package-lock.json'),stat=fs.lstat.bind(fs),read=fs.readFile.bind(fs),writes=blockOutput(t);let lockReads=0;t.mock.method(fs,'lstat',async target=>target===lock?{isSymbolicLink:()=>true,isFile:()=>true,size:123658}:stat(target));t.mock.method(fs,'readFile',async(target,...args)=>{if(target===lock)lockReads++;return read(target,...args);});await assert.rejects(Prepare.preparePackage(),error=>error.message==='invalid_package_source');assert.equal(lockReads,0);assert.deepEqual(writes,{mkdir:0,write:0});
});
test('owner tariff paths have POST-only bounded gates, exact preflights and no general owner/admin route',async()=>{
  for(const url of ['/v1/production/owner/tariffs/view','/v1/production/owner/tariffs/append','/v1/production/owner/tariffs/resolve']){
    const f=fixture(),req=request();req.url=url;req.method='GET';assert.equal((await f.run(req)).statusCode,405);assert.equal(f.counts.load,0);
    req.method='POST';req.url=url+'?uid=other';assert.equal((await f.run(req)).statusCode,400);assert.equal(f.counts.load,0);
    req.url=url;req.method='OPTIONS';req.headers={origin:ORIGIN,'access-control-request-method':'POST','access-control-request-headers':'authorization, content-type'};req.rawHeaders=Object.entries(req.headers).flat();delete req.rawBody;
    const res={headers:{},setHeader(k,v){this.headers[k]=v;},end(v){this.raw=v;this.writableEnded=true;}};await f.deployment.handler(req,res);assert.equal(res.statusCode,204);assert.equal(f.counts.load,0);assert.equal(res.headers['Access-Control-Allow-Methods'],'POST');
    req.headers['access-control-request-method']='GET';req.rawHeaders=Object.entries(req.headers).flat();assert.equal((await f.run(req)).statusCode,400);assert.equal(f.counts.load,0);
  }
  const f=fixture();for(const url of ['/v1/production/owner','/v1/production/owner/tariffs','/v1/production/owner/grants','/v1/production/owner/cycles']){const req=request();req.url=url;assert.equal((await f.run(req)).statusCode,400);}assert.equal(f.counts.load,0);
});
test('deployment errors on owner views are read-only; append and resolve retain exact replay instruction',async()=>{
  const f=fixture({loadAdminSdk:()=>{throw Error('synthetic-private-error');}});for(const path of ['/v1/production/owner/tariffs/view','/v1/production/owner/tariffs/append','/v1/production/owner/tariffs/resolve']){const req=request();req.url=path;const r=await f.run(req);assert.deepEqual(r.body,path.endsWith('/view')?{ok:false,error:'unavailable'}:{ok:false,error:'unavailable',retrySameCommand:true});}
  assert.equal(Prepare.SOURCES.includes('server/production-tenant-admin.cjs'),true);assert.equal(Prepare.SOURCES.length,21);
});
