'use strict';
const { test } = require('node:test'), assert = require('node:assert/strict'), Crypto = require('node:crypto');
const Runtime = require('../server/apps-script/legacy-lifecycle-runtime.cjs');
const State = require('../server/production-identity-state.cjs');
const { fixture: production, POLICY } = require('./fixtures/legacy-lifecycle.cjs');
const F = require('./fixtures/identity-tenant.cjs');
const KEY = 'SYNTHETIC_PUBLIC_KEY_0000000000000', OAUTH = 'SYNTHETIC_MANAGED_OAUTH';
const encode = v => Buffer.from(JSON.stringify(v)).toString('base64url');
function fixture(division = 'qc') {
  const f = production(), who = division === 'qc' ? f.qc : f.partner, stats = { google: 0, reads: 0, puts: 0, writes: 0, oauth: 0, budget: 0 }, hooks = {}, sec = Date.parse(F.NOW) / 1000;
  const payload = { sub: who.uid, aud: F.PROJECT, iss: 'https://securetoken.google.com/' + F.PROJECT, email: who.email, email_verified: true, firebase: { sign_in_provider: 'google.com', identities: { 'google.com': [who.googleSubject] } }, auth_time: sec - 1, iat: sec - 1, exp: sec + 3600 };
  const account = { localId: who.uid, email: who.email, emailVerified: true, disabled: false, validSince: String(sec - 300), providerUserInfo: [{ providerId: 'google.com', rawId: who.googleSubject, email: who.email }] };
  let root = F.copy(f.root), time = F.NOW;
  const token = () => encode({ alg: 'RS256', kid: 'synthetic-key', typ: 'JWT' }) + '.' + encode(payload) + '.' + Buffer.alloc(256, 19).toString('base64url');
  const etag = () => Crypto.createHash('sha1').update(JSON.stringify(root)).digest('base64');
  const response = (code = 200, body = JSON.stringify(root), headers = { 'Content-Type': 'application/json', ETag: etag() }) => ({ getResponseCode: () => code, getAllHeaders: () => headers, getContent: () => Array.from(Buffer.from(body), v => v > 127 ? v - 256 : v) });
  const host = { fetch(url, args) {
    if (url === 'https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=' + KEY) { stats.google++; assert.equal(JSON.parse(args.payload).idToken, token()); if (hooks.google) hooks.google(stats.google); return response(200, JSON.stringify({ users: [account] }), { 'Content-Type': 'application/json' }); }
    assert.equal(url, F.URL + '/.json'); assert.equal(args.headers.Authorization, 'Bearer ' + OAUTH);
    if (args.method === 'get') { stats.reads++; if (hooks.read) hooks.read(stats.reads); return response(); }
    assert.equal(args.method, 'put'); stats.puts++; if (hooks.beforePut) hooks.beforePut(); if (args.headers['If-Match'] !== etag()) return response(412, '{}'); root = JSON.parse(args.payload); stats.writes++; if (hooks.afterPut) hooks.afterPut(); return response();
  } };
  const script = { getOAuthToken() { stats.oauth++; return OAUTH; } };
  const options = { enabled: true, binding: { ...f.binding, apiKey: KEY }, urlFetchApp: host, scriptApp: script, clock: () => time, tariffPolicy: POLICY, requestAdmission(q) { stats.budget++; return hooks.budget ? hooks.budget(q) : true; }, identityAdmission(q) { return hooks.identity ? hooks.identity(q) : true; } };
  const create = () => Runtime.createAppsScriptLegacyLifecycleRuntime(options), readInput = () => ({ idToken: token() });
  let sequence = 0;
  const command = (kind, operationId, extra = {}) => { const r = create().read(readInput()); assert.equal(r.ok, true, JSON.stringify(r)); return { kind, requestId: 'native-request-' + (++sequence), operationId, productId: 'product-1', expectedGrantRevision: 1, expectedSourceVersion: r.view.products[0].sourceVersion, ...extra }; };
  const input = cmd => ({ idToken: token(), command: cmd });
  return { f, who, stats, hooks, payload, account, host, script, options, create, readInput, command, input, get root() { return root; }, set root(v) { root = F.copy(v); }, setTime(v) { time = v; } };
}
function count(f, quantity = 8, operationId = 'count-1', workerId = 'worker-1') { const cmd = f.command('appendCount', operationId, { workerId, quantity, workDate: '2026-10-06' }); const result = f.create().execute(f.input(cmd)); assert.equal(result.ok, true, JSON.stringify(result)); return cmd; }
test('lifecycle runtime is SOURCE OFF and initializes no native service or request getters', () => { let hits = 0; const options = { enabled: false }; Object.defineProperty(options, 'binding', { get() { hits++; throw Error(); } }); const request = new Proxy({}, { ownKeys() { hits++; throw Error(); }, get() { hits++; throw Error(); } }); for (const fn of Object.values(Runtime.createAppsScriptLegacyLifecycleRuntime(options))) assert.deepEqual(fn(request), { ok: false, error: 'service_disabled' }); assert.equal(hits, 0); const f = fixture(); f.create(); assert.equal(f.stats.google, 0); assert.equal(f.stats.reads, 0); assert.equal(f.stats.oauth, 0); });
test('actual synthetic account/root adapter returns only QC quantities and explicitly denies QC finance', () => { const f = fixture(), r = f.create().read(f.readInput()); assert.equal(r.ok, true); assert.equal(r.view.binding.division, 'qc'); assert.equal(f.stats.google, 4); assert.equal(f.stats.reads, 2); for (const value of ['SYNTHETIC_PIN', OAUTH, KEY, f.who.email, 'privateCost', 'authorityTenants', 'tarif', 'payroll']) assert.equal(JSON.stringify(r).includes(value), false); assert.deepEqual(f.create().readFinance(f.readInput()), { ok: false, error: 'access_denied' }); assert.equal(f.stats.puts, 0); });
test('one full-root conditional count write contains frozen wages and durable receipt, then independent confirmation', () => { const f = fixture(), cmd = f.command('appendCount', 'count-1', { workerId: 'worker-1', quantity: 8, workDate: '2026-10-06' }), before = { ...f.stats }; assert.deepEqual(f.create().execute(f.input(cmd)), { ok: true, replayed: false, operationId: 'count-1' }); assert.equal(f.stats.puts - before.puts, 1); assert.equal(f.stats.google - before.google, 14); assert.equal(f.stats.reads - before.reads, 2); assert.equal(f.root.soldier.produksi.produksi[0].hitungFisik[0].payroll.rate, 3.25); assert.equal(f.root.soldier.produksi.produksi[0].potong[0].total, 999.75); assert.equal(Object.hasOwn(f.root.legacyLifecycleReceipts[F.TENANT].commands, cmd.requestId), true); });
test('fresh runtime exact replay and resolve issue no second PUT and do not double provisional wages', () => { const f = fixture(), cmd = count(f); for (const method of ['execute', 'resolve']) assert.deepEqual(f.create()[method](f.input(cmd)), { ok: true, replayed: true, operationId: 'count-1' }); assert.equal(f.stats.puts, 1); assert.equal(f.root.soldier.produksi.produksi[0].hitungFisik.length, 1); });
test('lost write acknowledgement resolves exact retained command after reload without another write', () => { const f = fixture(), cmd = f.command('appendCount', 'count-1', { workerId: 'worker-1', quantity: 8, workDate: '2026-10-06' }); f.hooks.afterPut = () => { throw Error('SYNTHETIC_PRIVATE_ACK'); }; assert.deepEqual(f.create().execute(f.input(cmd)), { ok: false, error: 'result_unknown', retrySameCommand: true }); assert.equal(f.stats.writes, 1); delete f.hooks.afterPut; assert.deepEqual(f.create().resolve(f.input(cmd)), { ok: true, replayed: true, operationId: 'count-1' }); assert.equal(f.stats.puts, 1); });
test('conditional 412 preserves concurrent owner data and never retries a mutation', () => { const f = fixture(), cmd = f.command('appendCount', 'count-1', { workerId: 'worker-1', quantity: 8, workDate: '2026-10-06' }); f.hooks.beforePut = () => { f.root.privateRoot = 'Concurrent owner change'; }; assert.deepEqual(f.create().execute(f.input(cmd)), { ok: false, error: 'conflict' }); assert.equal(f.stats.writes, 0); assert.equal(f.stats.puts, 1); assert.equal(f.root.privateRoot, 'Concurrent owner change'); });
test('all untrusted financial/identity/host selectors fail before budget or Google lookup', () => { const f = fixture(), cmd = f.command('appendCount', 'count-1', { workerId: 'worker-1', quantity: 8, workDate: '2026-10-06' }); for (const extra of [{ rate: 1 }, { total: 1 }, { uid: 'owner-1' }, { role: 'owner' }, { databaseURL: 'https://foreign.invalid' }, { payroll: { rate: 0 } }]) { const before = { ...f.stats }; assert.deepEqual(f.create().execute(f.input({ ...cmd, ...extra })), { ok: false, error: 'invalid_request' }); assert.deepEqual(f.stats, before); } });
test('shared request admission runs before service calls, private admission runs before managed OAuth', () => { const f = fixture(); f.hooks.budget = q => { assert.equal(f.stats.google, 0); assert.equal(f.stats.oauth, 0); assert.equal(q.maxDatabaseDownloadBytes, 2 * 8 * 1024 * 1024); return false; }; assert.deepEqual(f.create().read(f.readInput()), { ok: false, error: 'rate_limited' }); const g = fixture(); g.hooks.identity = () => { assert.equal(g.stats.google, 2); assert.equal(g.stats.oauth, 0); return false; }; assert.deepEqual(g.create().read(g.readInput()), { ok: false, error: 'access_denied' }); assert.equal(g.stats.reads, 0); });
test('current disabled/provider/project accounts cannot release QC data or use managed OAuth', () => { for (const change of [f => f.account.disabled = true, f => f.payload.aud = 'demo-other-project', f => f.payload.firebase.sign_in_provider = 'password', f => f.account.providerUserInfo[0].rawId = 'foreign-subject']) { const f = fixture(); change(f); assert.equal(f.create().read(f.readInput()).ok, false); assert.equal(f.stats.oauth, 0); assert.equal(f.stats.reads, 0); } });
test('valid account without current retained grant and revoked QC enrollment cannot read source', () => { const f = fixture(), t = f.root.authorityTenants[F.TENANT]; f.root.authorityTenants[F.TENANT] = State.revokeIdentityEnrollment(t, { requestId: 'revoke-q', approvalId: 'approval-q', expectedApprovalRevision: 2, expectedGrantRevision: 1 }, F.NOW).next; assert.deepEqual(f.create().read(f.readInput()), { ok: false, error: 'access_denied' }); assert.equal(f.stats.puts, 0); });
test('signout/revocation or record change after possible PUT returns uncertainty and keeps durable evidence', () => { for (const alter of [f => f.account.disabled = true, f => f.root.soldier.produksi.produksi[0].hitungFisik[0].jumlah = 7]) { const f = fixture(), cmd = f.command('appendCount', 'count-1', { workerId: 'worker-1', quantity: 8, workDate: '2026-10-06' }); f.hooks.afterPut = () => alter(f); assert.deepEqual(f.create().execute(f.input(cmd)), { ok: false, error: 'result_unknown', retrySameCommand: true }); assert.equal(f.stats.writes, 1); assert.equal(Object.hasOwn(f.root.legacyLifecycleReceipts[F.TENANT].commands, cmd.requestId), true); } });
test('full QC inspect, repair and cascade delete use one CAS each and earlier accepted count still resolves', () => { const f = fixture(), original = count(f); count(f, 2, 'count-2', 'worker-2'); for (const cmd of [f.command('inspectCount', 'quality-row-1', { countId: 'count-1', workDate: '2026-10-06', totals: { ok: 5, perbaikan: 2, reject: 1, offline: 0 }, note: '' })]) assert.equal(f.create().execute(f.input(cmd)).ok, true); assert.equal(f.create().execute(f.input(f.command('repairQC', 'quality-row-1', { quantity: 1, workDate: '2026-10-06' }))).ok, true); assert.equal(f.create().execute(f.input(f.command('deleteCount', 'count-1'))).ok, true); assert.equal(f.stats.puts, 5); assert.equal(f.root.soldier.produksi.produksi[0].hitungFisik.length, 1); assert.deepEqual(f.create().resolve(f.input(original)), { ok: true, replayed: true, operationId: 'count-1' }); assert.equal(f.stats.puts, 5); });
test('partner runtime retains own stored total and cannot invoke QC actions', () => { const f = fixture('jahit'); assert.equal(f.create().readFinance(f.readInput()).view.storedJahit.records[0].stored.total, 20); const cmd = f.command('appendCount', 'count-new', { workerId: 'worker-1', quantity: 1, workDate: '2026-10-06' }); assert.deepEqual(f.create().execute(f.input(cmd)), { ok: false, error: 'access_denied' }); const edit = f.command('editJahit', 'sewn-1', { workDate: '2026-10-05', good: 7, reject: 0 }); assert.equal(f.create().execute(f.input(edit)).ok, true); assert.equal(f.root.soldier.produksi.produksi[0].jahit[0].total, 17.5); });
test('partner append, edit and delete share one durable history so original append resolves after later correction', () => { const f = fixture('jahit'); f.root.soldier.produksi.produksi[0].jahit[0].jumlah = f.root.soldier.produksi.produksi[0].jahit[0].lolos = 6; f.root.soldier.produksi.produksi[0].jahit[0].total = 15; const append = f.command('appendJahit', 'new-sewn', { assignmentId: 'assignment-1', good: 2, reject: 0, workDate: null }); assert.equal(f.create().execute(f.input(append)).ok, true); const edit = f.command('editJahit', 'new-sewn', { good: 1, reject: 0, workDate: '2026-10-06' }); assert.equal(f.create().execute(f.input(edit)).ok, true); const remove = f.command('deleteJahit', 'new-sewn'); assert.equal(f.create().execute(f.input(remove)).ok, true); assert.deepEqual(f.create().resolve(f.input(append)), { ok: true, replayed: true, operationId: 'new-sewn' }); assert.equal(f.stats.puts, 3); assert.equal(f.root.soldier.produksi.produksi[0].jahit.some(r => r.id === 'new-sewn'), false); });
test('native handle drift latches, reentrant request returns busy and error text never leaks', () => { const f = fixture(), api = f.create(); f.hooks.budget = () => { assert.deepEqual(api.read(f.readInput()), { ok: false, error: 'busy' }); return true; }; assert.equal(api.read(f.readInput()).ok, true); const original = f.host.fetch; f.host.fetch = () => { throw Error(OAUTH); }; assert.deepEqual(api.read(f.readInput()), { ok: false, error: 'unavailable' }); f.host.fetch = original; delete f.hooks.budget; assert.deepEqual(api.read(f.readInput()), { ok: false, error: 'unavailable' }); });
