'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const Http=require('../server/production-http-handler.cjs');
const ORIGIN='https://soldier.example.invalid',PATH='/v1/production/enrollment/claim';
function request(body='{}',patch={}){const raw=Buffer.isBuffer(body)?body:Buffer.from(body),headers={origin:ORIGIN,authorization:'Bearer header.payload.signature','content-type':'application/json','content-length':String(raw.length)};return {method:'POST',url:PATH,headers,rawHeaders:Object.entries(headers).flat(),rawBody:raw,...patch};}
function response(){return {statusCode:0,headers:{},body:null,setHeader(k,v){this.headers[k]=v;},end(v){this.writableEnded=true;this.body=v===undefined?null:JSON.parse(v);}};}
function fixture(extra={}){const calls=[];const enrollmentService={execute:async q=>{calls.push(q);return {ok:true};}};const handler=Http.createProductionHttpHandler({enabled:true,service:{execute:async()=>{throw Error('wrong-service');}},enrollmentService,allowedOrigins:[ORIGIN],deadlineMs:1000,maxInFlight:1,...extra});return {calls,handler};}
async function run(f,req=request()){const res=response();await f.handler(req,res);return res;}
test('claim accepts only an empty JSON object and passes the token internally without selectors',async()=>{const f=fixture(),res=await run(f,request(' \n{ }\t'));assert.equal(res.statusCode,200);assert.deepEqual(res.body,{ok:true});assert.deepEqual(f.calls,[{idToken:'header.payload.signature'}]);assert.equal(res.headers['Cache-Control'],'no-store');assert.equal(res.headers['Vary'],'Origin');assert.equal(JSON.stringify(res).includes('header.payload.signature'),false);});
test('profile, email, UID, role, worker, tenant and command fields cannot select enrollment',async()=>{for(const body of ['{"email":"synthetic@gmail.com"}','{"uid":"worker-1"}','{"workerId":"worker-1"}','{"role":"owner"}','{"tenantId":"tenant-1"}','{"profile":{"owner":true}}','{"command":{}}','{"selection":{}}','[]','null','true','"{}"']){const f=fixture(),res=await run(f,request(body));assert.equal(res.statusCode,400);assert.equal(f.calls.length,0);}});
test('malformed, duplicate, forbidden, overdeep and invalid UTF8 bodies cannot invoke identity verification',async()=>{for(const body of ['{','{}{}','{"uid":"a","uid":"b"}','{"uid":"a","\\u0075id":"b"}','{"__proto__":{}}','{"constructor":{}}','{"x":'+ '['.repeat(65)+'0'+']'.repeat(65)+'}',Buffer.from([0x7b,0xff,0x7d]),Buffer.alloc(32769,32),'']){const f=fixture();assert.equal((await run(f,request(body))).statusCode,400);assert.equal(f.calls.length,0);}});
test('claim stays unregistered when no explicit service was assembled',async()=>{const f=fixture();const handler=Http.createProductionHttpHandler({enabled:true,service:{execute:async()=>{throw Error('wrong-service');}},allowedOrigins:[ORIGIN],deadlineMs:1000,maxInFlight:1});assert.equal((await run({handler})).statusCode,400);assert.equal(f.calls.length,0);});
test('claim origin, query, method, token shape, compression and framing checks run before execute',async()=>{for(const mutate of [r=>r.url=PATH+'?email=private',r=>r.url=PATH+'/',r=>r.method='GET',r=>r.headers.origin='https://foreign.example.invalid',r=>r.headers.authorization='Bearer invalid',r=>r.headers['content-encoding']='gzip',r=>r.headers['content-length']='3',r=>r.headers['content-type']='text/plain',r=>r.rawHeaders.push('Authorization','Bearer second.token.value')]){const f=fixture(),req=request();mutate(req);assert.ok([400,403,405].includes((await run(f,req)).statusCode));assert.equal(f.calls.length,0);}});
test('claim preflight allows exact POST Authorization/Content-Type only without authentication',async()=>{const f=fixture(),req=request('',{method:'OPTIONS'});req.headers={'origin':ORIGIN,'access-control-request-method':'POST','access-control-request-headers':'Authorization, Content-Type'};req.rawHeaders=Object.entries(req.headers).flat();const res=await run(f,req);assert.equal(res.statusCode,204);assert.equal(res.body,null);assert.equal(f.calls.length,0);for(const headers of [{'access-control-request-method':'GET'},{'access-control-request-headers':'Authorization, X-Role'}]){const q={...req,headers:{...req.headers,...headers}};q.rawHeaders=Object.entries(q.headers).flat();assert.equal((await run(f,q)).statusCode,400);}});
test('successful service results must be exactly minimal; private metadata and command receipts are refused',async()=>{for(const result of [{ok:true,identity:{email:'synthetic@gmail.com'}},{ok:true,uid:'worker-1'},{ok:true,profile:{owner:true}},{ok:true,receipt:{requestId:'req',revision:1,acceptedAt:'2026-10-06T00:00:00.000Z'},replayed:false},{ok:false,error:'private-error-text'},null]){const f=fixture({enrollmentService:{execute:async()=>result}}),res=await run(f);assert.equal(res.statusCode,503);assert.deepEqual(res.body,{ok:false,error:'result_unknown',retrySameIdentity:true});assert.equal(JSON.stringify(res).includes('synthetic@gmail.com'),false);}});
test('result accessors and exception detail are never read or returned',async()=>{let touched=0;const getter={};Object.defineProperty(getter,'ok',{enumerable:true,get(){touched++;throw Error('private-error');}});for(const execute of [async()=>getter,async()=>{throw Error('private-error');}]){const res=await run(fixture({enrollmentService:{execute}}));assert.equal(res.statusCode,503);assert.deepEqual(res.body,{ok:false,error:'result_unknown',retrySameIdentity:true});}assert.equal(touched,0);});
test('service execution and service option accessors fail closed without invocation',async()=>{let touched=0;const s={};Object.defineProperty(s,'execute',{enumerable:true,get(){touched++;throw Error('private');}});assert.equal((await run(fixture({enrollmentService:s}))).statusCode,503);const options={enabled:true,service:{execute:async()=>({ok:true})},allowedOrigins:[ORIGIN],deadlineMs:1000,maxInFlight:1};Object.defineProperty(options,'enrollmentService',{get(){touched++;throw Error('private');}});assert.equal((await run({handler:Http.createProductionHttpHandler(options)})).statusCode,503);assert.equal(touched,0);});
test('fixed denial codes have exact responses and uncertain outcomes require the same verified identity',async()=>{for(const [error,status] of [['access_denied',403],['invalid_request',400],['not_ready',409],['rate_limited',429],['result_unknown',503],['unavailable',503]]){const res=await run(fixture({enrollmentService:{execute:async()=>({ok:false,error})}}));assert.equal(res.statusCode,status);assert.deepEqual(res.body,{ok:false,error,...(['unavailable','result_unknown'].includes(error)?{retrySameIdentity:true}:{})});}});
test('shared HTTP slot and deadline retain admission until the claim settles',async()=>{let release;const pending=new Promise(resolve=>release=resolve),f=fixture({enrollmentService:{execute:()=>pending},deadlineMs:5});const res=response(),first=f.handler(request(),res);await new Promise(resolve=>setTimeout(resolve,15));assert.equal(res.writableEnded,undefined);const second=await run(f);assert.deepEqual(second.body,{ok:false,error:'busy',retrySameIdentity:true});release({ok:true});await first;assert.deepEqual(res.body,{ok:false,error:'result_unknown',retrySameIdentity:true});assert.equal((await run(f)).statusCode,200);});
test('disconnect does not free the shared slot or expose a late identity result',async()=>{let release;const pending=new Promise(resolve=>release=resolve),f=fixture({enrollmentService:{execute:()=>pending}}),res=response(),task=f.handler(request(),res);res.destroyed=true;assert.equal((await run(f)).body.error,'busy');release({ok:true});await task;assert.equal(res.writableEnded,undefined);});
