'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Store=require('../production-command-store.js'),{fakeIndexedDB}=require('./helpers/command-indexeddb-fixture.cjs');
const scope=()=>({projectId:'demo-store-proof',databaseURL:'https://demo-store-proof.firebaseio.com',tenantId:'tenant-1',uid:'caller-1',grantRevision:0}),endpointURL='https://server.example.invalid/v1/production/commands';
function create(f,extra={}){return Store.createCommandStore({enabled:true,indexedDB:f.api,scope:scope(),endpointURL,isCurrent:()=>true,...extra});}
test('disabled and invalid scope never open storage',async()=>{const f=fakeIndexedDB();await assert.rejects(Store.createCommandStore().read(),/service_disabled/);for(const change of [{uid:'other/uid'},{grantRevision:-1},{databaseURL:'http://invalid'}])assert.throws(()=>create(f,{scope:{...scope(),...change}}),/invalid_storage/);assert.equal(f.stats.opens,0);});
test('native-shaped transaction completes durable raw CAS before returning; known conflict retains exact prior bytes',async()=>{const f=fakeIndexedDB(),a=create(f),b=create(f);assert.equal(await a.read(),null);assert.equal(await a.write('{"a":1}',null),true);assert.equal(await b.read(),'{"a":1}');assert.equal(await b.write('{"a":2}',null),false);assert.equal(await a.read(),'{"a":1}');assert.equal(await b.write('{"a":2}','{"a":1}'),true);assert.equal(await a.read(),'{"a":2}');});
test('two handles cannot both replace the same prior raw snapshot',async()=>{const f=fakeIndexedDB(),a=create(f),b=create(f);const results=await Promise.all([a.write('first',null),b.write('second',null)]);assert.deepEqual(results,[true,false]);assert.equal(await b.read(),'first');});
test('account, tenant, revision and endpoint bind independent keys without enumeration or adoption',async()=>{const f=fakeIndexedDB(),a=create(f);await a.write('old-scope',null);for(const extra of [{scope:{...scope(),uid:'caller-2'}},{scope:{...scope(),tenantId:'tenant-2'}},{scope:{...scope(),grantRevision:1}},{endpointURL:'https://other.example.invalid/v1/production/commands'}])assert.equal(await create(f,extra).read(),null);assert.equal(await a.read(),'old-scope');});
test('aborted writes and malformed stored values hold without replacing source',async()=>{const f=fakeIndexedDB(),a=create(f);await a.write('old',null);f.control.putFail=true;await assert.rejects(a.write('new','old'),/storage_unavailable/);f.control.putFail=false;assert.equal(await a.read(),'old');await assert.rejects(a.write('x'.repeat(262145),'old'),/invalid_storage/);assert.equal(await a.read(),'old');});
test('invalidation before open and after a commit cannot expose another account; old bytes remain',async()=>{const f=fakeIndexedDB();let current=true;const a=create(f,{isCurrent:()=>current});await a.write('old',null);let release,started;const ready=new Promise(r=>{started=r;});f.control.beforeCommit=()=>{started();return new Promise(r=>{release=r;});};const writing=a.write('late','old');await ready;current=false;release();await assert.rejects(writing,/storage_inactive/);f.control.beforeCommit=null;assert.equal(await create(f).read(),'late');const b=create(f,{isCurrent:()=>false});await assert.rejects(b.read(),/storage_inactive/);assert.equal(f.stats.opens,2);});
test('blocked late-open handle is closed and never adopted; errors expose no native exception detail',async()=>{const f=fakeIndexedDB();f.control.blocked=true;const a=create(f);await assert.rejects(a.read(),/storage_unavailable/);assert.equal(f.stats.closes,1);const b=fakeIndexedDB();b.control.openFail=true;await assert.rejects(create(b).read(),e=>e.message==='storage_unavailable');});
test('dispose and browser version change close handles, preserve source and prohibit future reads/writes',async()=>{const f=fakeIndexedDB(),a=create(f);await a.write('retain',null);a.dispose();await assert.rejects(a.read(),/storage_inactive/);await assert.rejects(a.write('new','retain'),/storage_inactive/);assert.equal(await create(f).read(),'retain');});
