'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),net=require('node:net');
const Host=require('../server/deployment/cloud-run-server.cjs');
const Entry=require('../server/deployment/cloud-run-entry.cjs');
const PROJECT='soldier-host-test',ORIGIN='https://soldier-host-test.web.app',TOKEN='synthetic.token.signature',PATH='/v1/production/commands';
const configuration={enabled:true,projectId:PROJECT,databaseURL:'https://'+PROJECT+'.firebaseio.com',tenantId:'tenant-1',allowedOrigins:[ORIGIN],serviceAccount:'soldier-production-runtime@'+PROJECT+'.iam.gserviceaccount.com'};
const environment={GOOGLE_CLOUD_PROJECT:PROJECT,K_SERVICE:'soldier-production',K_CONFIGURATION:'soldier-production',K_REVISION:'soldier-production-00001-synthetic',PORT:'8080'};
const tick=()=>new Promise(r=>setImmediate(r));
function fixture(){
  const stats={environments:0,loads:0,adc:0,apps:0,runtimes:0,calls:0,bodies:[]},controls={runtimeGate:null,loadFail:false,handlerFail:false,gateBeforeReply:null};let app;
  const options={configuration,environment:()=>{stats.environments++;return {...environment};},loadAdminSdk(){stats.loads++;if(controls.loadFail)throw Error('synthetic-private-sdk-error');return {applicationDefault(){stats.adc++;return {};},getApps:()=>[],initializeApp(o,name){stats.apps++;app={name,options:o};return app;},getAuth:()=>({app}),getDatabase:()=>({app})};},createRuntime(){stats.runtimes++;return {async handler(req,res){stats.calls++;stats.bodies.push(Buffer.from(req.rawBody));if(controls.runtimeGate)await controls.runtimeGate();if(controls.handlerFail)throw Error('synthetic-private-handler-error');if(controls.gateBeforeReply)controls.gateBeforeReply();if(res.destroyed||res.writableEnded)return;res.statusCode=200;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify({ok:true,synthetic:true}));}};}};
  return {options,stats,controls,create:extra=>Host.createCloudRunServer({...options,...extra})};
}
async function opened(t,f=fixture()){const result=f.create();assert.equal(result.enabled,true);const server=result.server;await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});t.after(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));});return {...f,server,waitForIdle:result.waitForIdle,port:server.address().port};}
function headers(extra={}){return {Origin:ORIGIN,Authorization:'Bearer '+TOKEN,'Content-Type':'application/json',...extra};}
function request(port,{path=PATH,method='POST',body=Buffer.from('{"command":{"synthetic":true}}'),header=headers(),flushOnly=false}={}){
  let req;const response=new Promise((resolve,reject)=>{req=http.request({host:'127.0.0.1',port,path,method,headers:header,agent:false},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('error',reject);res.on('end',()=>{const raw=Buffer.concat(chunks).toString();let value;try{value=JSON.parse(raw);}catch{value=raw;}resolve({status:res.statusCode,headers:res.headers,value});});});req.on('error',reject);if(flushOnly)req.flushHeaders();else req.end(body);});return {req,response};
}
function raw(port,bytes,afterConnect){return new Promise((resolve,reject)=>{const socket=net.connect(port,'127.0.0.1'),chunks=[];let settled=false;const done=()=>{if(settled)return;settled=true;resolve(Buffer.concat(chunks).toString());};socket.setTimeout(2000,()=>{socket.destroy();reject(Error('synthetic-response-timeout'));});socket.on('error',reject);socket.on('data',c=>chunks.push(c));socket.once('end',done);socket.once('close',done);socket.once('connect',()=>{socket.write(bytes);if(afterConnect)afterConnect(socket);});});}
const rawHead=(path=PATH,extra='')=>'POST '+path+' HTTP/1.1\r\nHost: localhost\r\nOrigin: '+ORIGIN+'\r\nAuthorization: Bearer '+TOKEN+'\r\nContent-Type: application/json\r\n'+extra;
test('import and OFF host are unbound and never read configuration or environment getters',()=>{
  let reads=0;for(const options of [{configuration:{enabled:false},get environment(){reads++;throw Error();}},{get configuration(){reads++;throw Error();}},{configuration:{get enabled(){reads++;return true;}}}])assert.deepEqual(Host.createCloudRunServer(options),{enabled:false,server:null});assert.equal(reads,0);const f=fixture(),result=f.create();assert.equal(result.enabled,true);assert.equal(result.server.listening,false);assert.equal(f.stats.environments,0);assert.equal(f.stats.loads,0);assert.equal(Host.BODY_TIMEOUT_MS,10000);assert.equal(Host.RESPONSE_TIMEOUT_MS,30000);result.server.close();
});
test('unknown executable host options fail without running getters or initializing ADC',()=>{
  const f=fixture();assert.deepEqual(f.create({port:9000}),{enabled:false,server:null});let reads=0;const options={...f.options};Object.defineProperty(options,'environment',{enumerable:true,get(){reads++;throw Error();}});assert.deepEqual(Host.createCloudRunServer(options),{enabled:false,server:null});assert.equal(reads,0);assert.equal(f.stats.loads,0);
});
test('complete valid Node HTTP request reaches existing runtime with exact bounded raw bytes',async t=>{
  const f=await opened(t),body=Buffer.from('{"command":{"synthetic":"é"}}'),result=await request(f.port,{body,header:headers({'Content-Length':String(body.length)})}).response;assert.equal(result.status,200);assert.deepEqual(result.value,{ok:true,synthetic:true});assert.equal(result.headers.connection,'close');assert.equal(f.stats.loads,1);assert.equal(f.stats.adc,1);assert.equal(f.stats.apps,1);assert.equal(f.stats.runtimes,1);assert.deepEqual(f.stats.bodies,[body]);assert.equal(f.server.requestTimeout,10000);assert.equal(f.server.headersTimeout,10000);assert.equal(f.server.maxHeadersCount,129);assert.equal(f.server.maxConnections,8);
});
test('fixed connection saturation closes a ninth header-incomplete peer without SDK work',async t=>{
  const f=await opened(t),sockets=[];t.after(()=>sockets.forEach(s=>s.destroy()));
  for(let i=0;i<8;i++){const socket=net.connect(f.port,'127.0.0.1');sockets.push(socket);socket.on('error',()=>{});await new Promise(resolve=>socket.once('connect',resolve));socket.write('POST /v1/production/commands HTTP/1.1\r\n');}
  await tick();const count=()=>new Promise((resolve,reject)=>f.server.getConnections((error,value)=>error?reject(error):resolve(value)));assert.equal(await count(),8);const ninth=net.connect(f.port,'127.0.0.1');ninth.on('error',()=>{});await new Promise(resolve=>ninth.once('close',resolve));assert.equal(await count(),8);assert.equal(f.stats.loads,0);assert.equal(f.stats.calls,0);sockets[0].destroy();await new Promise(resolve=>sockets[0].once('close',resolve));await tick();assert.equal((await request(f.port).response).status,200);assert.equal(f.stats.calls,1);
});
test('wrong environment, origin, path, method, token and content type reject before SDK and body reads',async t=>{
  const f=await opened(t);for(const options of [{header:headers({Origin:'https://foreign.example.invalid'})},{path:PATH+'?private=synthetic'},{method:'PUT'},{header:headers({Authorization:'Bearer synthetic-private-token'})},{header:headers({'Content-Type':'text/html'})},{header:headers({'Content-Encoding':'gzip'})},{header:headers({'Content-Length':'32769'}),flushOnly:true}]){const result=await request(f.port,options).response;assert.ok([400,403,405].includes(result.status));assert.equal(result.headers.connection,'close');assert.equal(f.stats.loads,0);assert.equal(f.stats.calls,0);}
});
test('Cloud Run environment cannot silently use Functions binding, foreign project or key-file ADC',async t=>{
  for(const extra of [{FUNCTION_TARGET:'soldierProduction'},{FUNCTION_SIGNATURE_TYPE:'http'},{K_SERVICE:'foreign-service'},{K_CONFIGURATION:'foreign-service'},{K_REVISION:'foreign-service-00001-x'},{GOOGLE_CLOUD_PROJECT:'foreign-project'},{PORT:'08080'},{GOOGLE_APPLICATION_CREDENTIALS:'synthetic-private-file'},{FIREBASE_DATABASE_EMULATOR_HOST:'localhost:9000'}]){const f=await opened(t,fixture());f.options.environment=()=>({...environment,...extra});/* Factory already captured options: create a fresh guarded server. */const guarded=f.create();await new Promise(resolve=>guarded.server.listen(0,'127.0.0.1',resolve));try{const result=await request(guarded.server.address().port).response;assert.equal(result.status,503);assert.equal(result.value.error,'unavailable');assert.equal(f.stats.loads,0);}finally{guarded.server.closeAllConnections();await new Promise(resolve=>guarded.server.close(resolve));}}
});
test('chunked body retains at most the fixed 32 KiB before rejecting and never initializes SDK',async t=>{
  const f=await opened(t),result=await request(f.port,{body:Buffer.alloc(32769,32),header:headers({'Transfer-Encoding':'chunked'})}).response;assert.equal(result.status,400);assert.deepEqual(result.value,{ok:false,error:'invalid_request'});assert.equal(f.stats.loads,0);assert.equal(f.stats.calls,0);const accepted=await request(f.port,{body:Buffer.alloc(32768,32),header:headers({'Transfer-Encoding':'chunked'})}).response;assert.equal(accepted.status,200);assert.equal(f.stats.bodies.at(-1).length,32768);
});
test('header parser overflow, duplicate authorization and malformed framing return static JSON',async t=>{
  const f=await opened(t);for(const bytes of [rawHead(PATH,'Authorization: Bearer different.token.signature\r\nContent-Length: 2\r\n\r\n{}'),rawHead(PATH,'Content-Length: 2\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\n'),rawHead(PATH,'X-Long: '+ 'synthetic-canary'.repeat(3000)+'\r\n\r\n')]){const output=await raw(f.port,bytes);assert.match(output,/HTTP\/1\.1 (400|431)/);assert.match(output,/\{"ok":false,"error":"invalid_request"\}/);assert.equal(output.includes('synthetic-canary'),false);assert.equal(output.includes('different.token'),false);assert.equal(f.stats.loads,0);}
});
test('header pair saturation cannot hide a sensitive duplicate beyond the accepted limit',async t=>{
  const f=await opened(t),many=Array.from({length:130},(_,i)=>'X-Synthetic-'+i+': harmless\r\n').join(''),output=await raw(f.port,rawHead(PATH,many+'Authorization: Bearer other.token.signature\r\nContent-Length: 2\r\n\r\n{}'));assert.match(output,/HTTP\/1\.1 (400|431)/);assert.equal(f.stats.loads,0);assert.equal(f.stats.calls,0);
});
test('actual chunked trailers, including undeclared Authorization, are refused before SDK dispatch',async t=>{
  const f=await opened(t);for(const trailer of ['Authorization: Bearer other.synthetic.signature','X-Synthetic: synthetic-private-trailer']){const output=await raw(f.port,rawHead(PATH,'Transfer-Encoding: chunked\r\n\r\n')+'2\r\n{}\r\n0\r\n'+trailer+'\r\n\r\n');assert.match(output,/400 Bad Request/);assert.match(output,/\{"ok":false,"error":"invalid_request"\}/);assert.equal(output.includes('other.synthetic'),false);assert.equal(output.includes('synthetic-private-trailer'),false);assert.equal(f.stats.loads,0);assert.equal(f.stats.calls,0);}assert.equal((await request(f.port,{body:Buffer.from('{}'),header:headers({'Transfer-Encoding':'chunked'})}).response).status,200);assert.equal(f.stats.calls,1);
});
test('preflight and GET session reject framing bodies and never initialize ADC',async t=>{
  const f=await opened(t);const preflight=await request(f.port,{method:'OPTIONS',body:null,header:{Origin:ORIGIN,'Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'Authorization, Content-Type'}}).response;assert.equal(preflight.status,204);assert.equal(f.stats.loads,0);
  for(const options of [{path:'/v1/production/session',method:'GET',body:Buffer.from('x'),header:{Origin:ORIGIN,Authorization:'Bearer '+TOKEN,'Transfer-Encoding':'chunked'}},{method:'OPTIONS',body:Buffer.from('x'),header:{Origin:ORIGIN,'Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'Authorization, Content-Type','Content-Length':'1'}}]){assert.equal((await request(f.port,options).response).status,400);assert.equal(f.stats.loads,0);}
});
test('Expect continue is issued only after admission and slot reservation',async t=>{
  const f=await opened(t),body='{}',good=await raw(f.port,rawHead(PATH,'Expect: 100-continue\r\nContent-Length: 2\r\n\r\n'),socket=>{let sent=false;socket.on('data',c=>{if(!sent&&c.toString().includes('100 Continue')){sent=true;socket.end(body);}});});assert.match(good,/100 Continue/);assert.match(good,/200 OK/);assert.equal(f.stats.calls,1);
  const rejected=await raw(f.port,rawHead('/unknown','Expect: 100-continue\r\nContent-Length: 2\r\n\r\n'));assert.equal(rejected.includes('100 Continue'),false);assert.match(rejected,/400 Bad Request/);assert.equal(f.stats.calls,1);
});
test('unknown expectations, upgrade and CONNECT cannot enter the runtime',async t=>{
  const f=await opened(t);for(const bytes of [rawHead(PATH,'Expect: private-synthetic-expectation\r\nContent-Length: 2\r\n\r\n{}'),rawHead(PATH,'Connection: Upgrade\r\nUpgrade: private-synthetic-protocol\r\n\r\n'),'CONNECT example.invalid:443 HTTP/1.1\r\nHost: example.invalid\r\n\r\n']){const output=await raw(f.port,bytes);assert.match(output,/HTTP\/1\.1 (400|417)/);assert.equal(output.includes('private-synthetic'),false);assert.equal(f.stats.loads,0);}
});
test('aborted incomplete stream never dispatches and releases the buffering slot',async t=>{
  const f=await opened(t),socket=net.connect(f.port,'127.0.0.1');await new Promise(resolve=>socket.once('connect',resolve));socket.write(rawHead(PATH,'Content-Length: 100\r\n\r\n{}'));await tick();const busy=await request(f.port).response;assert.equal(busy.status,503);assert.equal(busy.value.error,'busy');assert.equal(f.stats.loads,0);socket.destroy();await new Promise(resolve=>socket.once('close',resolve));await tick();const next=await request(f.port).response;assert.equal(next.status,200);assert.equal(f.stats.calls,1);
});
test('client disconnect after dispatch retains the sole slot until runtime settles',async t=>{
  const f=await opened(t);let entered,release;const arrived=new Promise(resolve=>{entered=resolve;});f.controls.runtimeGate=()=>{entered();return new Promise(resolve=>{release=resolve;});};const first=request(f.port);first.response.catch(()=>{});await arrived;first.req.destroy();await tick();const busy=await request(f.port).response;assert.equal(busy.status,503);assert.deepEqual(busy.value,{ok:false,error:'busy',retrySameCommand:true});assert.deepEqual((await request(f.port,{path:'/v1/production/owner/tariffs/view'}).response).value,{ok:false,error:'busy'});assert.equal(f.stats.calls,1);release();await tick();f.controls.runtimeGate=null;assert.equal((await request(f.port).response).status,200);assert.equal(f.stats.calls,2);
});
test('explicit idle wait remains pending after detached dispatch even when Node sockets close',async t=>{
  const f=await opened(t);assert.equal(typeof f.waitForIdle,'function');await f.waitForIdle();let entered,release,drained=false;const arrived=new Promise(resolve=>{entered=resolve;});f.controls.runtimeGate=()=>{entered();return new Promise(resolve=>{release=resolve;});};const first=request(f.port);first.response.catch(()=>{});await arrived;first.req.destroy();await new Promise(resolve=>first.req.once('close',resolve));await tick();const idle=f.waitForIdle().then(()=>{drained=true;});await new Promise(resolve=>f.server.close(resolve));await tick();assert.equal(drained,false);assert.equal(f.stats.calls,1);release();await idle;assert.equal(drained,true);await f.waitForIdle();assert.equal(f.stats.calls,1);
});
test('explicit idle wait includes admitted buffering and resolves when an incomplete peer aborts',async t=>{
  const f=await opened(t),socket=net.connect(f.port,'127.0.0.1');socket.on('error',()=>{});await new Promise(resolve=>socket.once('connect',resolve));socket.write(rawHead(PATH,'Content-Length: 100\r\n\r\n{}'));await tick();await tick();let drained=false;const idle=f.waitForIdle().then(()=>{drained=true;});await tick();assert.equal(drained,false);assert.equal(f.stats.loads,0);socket.destroy();await idle;assert.equal(drained,true);assert.equal(f.stats.loads,0);
});
test('actual entry and native host await a detached dispatched operation after all sockets close',async t=>{
  const probe=http.createServer();await new Promise((resolve,reject)=>{probe.once('error',reject);probe.listen(0,'127.0.0.1',resolve);});const port=probe.address().port;await new Promise(resolve=>probe.close(resolve));
  const f=fixture(),signals=new Map(),exits=[];let host,entered,release;const arrived=new Promise(resolve=>{entered=resolve;});f.controls.runtimeGate=()=>{entered();return new Promise(resolve=>{release=resolve;});};
  const entry=Entry.createEntrypoint({configuration:f.options.configuration,environment:()=>({...environment,PORT:String(port)}),loadHost:()=>({createCloudRunServer:options=>{
    host=Host.createCloudRunServer({...options,loadAdminSdk:f.options.loadAdminSdk,createRuntime:f.options.createRuntime});
    const listen=host.server.listen.bind(host.server);host.server.listen=(number,address,callback)=>{assert.equal(address,'0.0.0.0');return listen(number,'127.0.0.1',callback);};return host;
  }}),process:{version:'v22.20.0',on:(name,fn)=>signals.set(name,fn),removeListener:name=>signals.delete(name),exit:code=>exits.push(code),setTimeout,clearTimeout}});
  t.after(async()=>{release?.();await entry.dispose();});assert.deepEqual(await entry.start(),{ok:true});assert.equal(f.stats.loads,0);const first=request(port);first.response.catch(()=>{});await arrived;first.req.destroy();await new Promise(resolve=>first.req.once('close',resolve));await tick();const socketClosed=new Promise(resolve=>host.server.once('close',resolve));let drained=false;const stopping=entry.dispose().then(()=>{drained=true;});await socketClosed;await tick();assert.equal(host.server.listening,false);assert.equal(drained,false);assert.equal(f.stats.calls,1);assert.equal(exits.length,0);release();await stopping;assert.equal(drained,true);assert.equal(signals.size,0);assert.equal(exits.length,0);assert.equal(f.stats.calls,1);
});
test('SDK startup and late runtime exception expose only generic envelopes',async t=>{
  for(const fail of ['loadFail','handlerFail']){const f=await opened(t);f.controls[fail]=true;const result=await request(f.port).response;assert.equal(result.status,503);assert.ok(['unavailable','result_unknown'].includes(result.value.error));assert.equal(JSON.stringify(result).includes('synthetic-private'),false);assert.equal(result.value.retrySameCommand,true);}
});
test('client parser error never invokes a provided error getter or emits its raw bytes',async t=>{
  const f=await opened(t);let reads=0,output;const error={code:'HPE_HEADER_OVERFLOW',get message(){reads++;return 'synthetic-private-message';},get rawPacket(){reads++;return Buffer.from('synthetic-private-packet');}},socket={destroyed:false,writable:true,writableEnded:false,on(){},end(value){output=value;}};f.server.emit('clientError',error,socket);assert.equal(reads,0);assert.match(output,/431 Request Header Fields Too Large/);assert.equal(output.includes('synthetic-private'),false);assert.equal(f.stats.loads,0);
});
test('fixed native deadlines bound HTTP responses while preserving uncertain write admission',{concurrency:true},async t=>{
  await Promise.all([
    t.test('incomplete body expires at ten seconds without SDK and frees its slot',{concurrency:true},async t=>{
      const f=await opened(t),start=Date.now(),result=await request(f.port,{header:headers({'Content-Length':'100'}),flushOnly:true}).response;assert.equal(result.status,408);assert.deepEqual(result.value,{ok:false,error:'invalid_request'});assert.ok(Date.now()-start>=9000);assert.equal(f.stats.loads,0);assert.equal(f.stats.calls,0);assert.equal((await request(f.port).response).status,200);
    }),
    t.test('dispatched write times out as result_unknown and remains busy until settlement',{concurrency:true},async t=>{
      const f=await opened(t);let entered,release;const arrived=new Promise(resolve=>{entered=resolve;});f.controls.runtimeGate=()=>{entered();return new Promise(resolve=>{release=resolve;});};const first=request(f.port),start=Date.now();await arrived;
      try{const result=await first.response;assert.ok(Date.now()-start>=29000);assert.equal(result.status,503);assert.deepEqual(result.value,{ok:false,error:'result_unknown',retrySameCommand:true});assert.deepEqual((await request(f.port).response).value,{ok:false,error:'busy',retrySameCommand:true});assert.equal(f.stats.calls,1);}finally{release();await tick();f.controls.runtimeGate=null;}assert.equal((await request(f.port).response).status,200);assert.equal(f.stats.calls,2);
    }),
    t.test('dispatched read expires unavailable while retaining the same request slot',{concurrency:true},async t=>{
      const f=await opened(t);let entered,release;const arrived=new Promise(resolve=>{entered=resolve;});f.controls.runtimeGate=()=>{entered();return new Promise(resolve=>{release=resolve;});};const get={path:'/v1/production/session',method:'GET',body:null,header:{Origin:ORIGIN,Authorization:'Bearer '+TOKEN}},first=request(f.port,get);await arrived;
      try{const result=await first.response;assert.equal(result.status,503);assert.deepEqual(result.value,{ok:false,error:'unavailable'});assert.deepEqual((await request(f.port,get).response).value,{ok:false,error:'busy'});assert.equal(f.stats.calls,1);}finally{release();await tick();f.controls.runtimeGate=null;}assert.equal((await request(f.port,get).response).status,200);
    })
  ]);
});
