'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Bridge=require('../production-bridge.js'),History=require('../legacy-stored-history.js'),Controller=require('../production-form-controller.js');
const {fixture,PROJECT,URL,ENDPOINT,tick}=require('./helpers/production-bridge-fixture.cjs');
const HISTORY_URL='https://server.example.invalid/v1/production/history/own';
function storedView(){return History.createLegacyStoredHistoryProjector({enabled:true,binding:{projectId:PROJECT,databaseURL:URL,tenantId:'tenant-1',uid:'caller-1',workerId:'worker-1',division:'jahit',grantRevision:1}}).project({snapshotVersion:'synthetic-version',products:[{id:'product-1',series:'Synthetic',namaBarang:'<img onerror=alert(1)>',size:'M',jahit:[{id:'old-row',tukangId:'worker-1',jumlah:3,lolos:null,tarif:12.5,total:999.75,dibayar:false}],arsip:[]}]}).view;}
function setup(role='jahit'){
 const f=fixture(role);f.tenant.grants['caller-1'].revision=1;const original=f.options.fetch,control={gate:null,status:200,result:{ok:true,view:JSON.parse(JSON.stringify(storedView()))},raw:null,transform:null},calls=[];
 f.options.fetch=async(url,init)=>{if(url!==HISTORY_URL)return original(url,init);calls.push({url,init});if(control.gate)await control.gate();const raw=control.raw===null?JSON.stringify(control.result):control.raw,r=f.response(url,control.status,raw);return control.transform?control.transform(r):r;};
 return {...f,history:control,historyCalls:calls};
}
test('history OFF is inert and an unopened bridge cannot request stored financial data',async()=>{let touched=0;const off=Bridge.createProductionBridge({enabled:false,get auth(){touched++;throw Error();}});assert.equal((await off.readOwnHistory()).error,'service_disabled');assert.equal(touched,0);const f=setup(),b=f.create();assert.equal((await b.readOwnHistory()).error,'not_ready');assert.equal(f.historyCalls.length,0);b.dispose();});
test('explicit history read uses one fixed GET and fresh header token with no selectors, writes or storage mutation',async()=>{const f=setup(),b=f.create();await b.connect();const before=JSON.stringify([...f.idb.databases].map(([k,v])=>[k,[...v.stores].map(([n,m])=>[n,[...m]])]));const r=await b.readOwnHistory();assert.equal(r.ok,true);assert.deepEqual(r.view,storedView());assert.equal(r.view.records[0].stored.total,999.75);assert.equal(r.view.records[0].stored.lolos,null);assert.equal(f.historyCalls.length,1);const q=f.historyCalls[0];assert.equal(q.url,HISTORY_URL);assert.equal(q.init.method,'GET');assert.deepEqual(q.init.headers,{Authorization:'Bearer header.payload.signature'});assert.equal(Object.hasOwn(q.init,'body'),false);assert.equal(q.init.credentials,'omit');assert.equal(q.init.cache,'no-store');assert.equal(q.init.redirect,'error');assert.equal(q.init.referrerPolicy,'no-referrer');assert.equal(f.stats.posts,0);assert.equal(JSON.stringify([...f.idb.databases].map(([k,v])=>[k,[...v.stores].map(([n,m])=>[n,[...m]])])),before);b.dispose();});
test('worker, archive and UID selectors cannot invoke the read endpoint',async()=>{const f=setup(),b=f.create();await b.connect();for(const q of ['worker-2',{workerId:'worker-2'},{snapshotVersion:'other'},undefined])assert.equal((await b.readOwnHistory(q)).error,'invalid_request');assert.equal(f.historyCalls.length,0);b.dispose();});
test('QC, owner and mixed-module accounts do not request partner history',async()=>{for(const profile of [{active:true,owner:false,modules:{qc:true}},{active:true,owner:true},{active:true,owner:false,workerId:'worker-1',modules:{jahit:true,qc:true}}]){const f=setup();f.tenant.grants['caller-1'].profile=profile;const b=f.create();assert.equal((await b.connect()).ok,true);assert.equal((await b.readOwnHistory()).error,'access_denied');assert.equal(f.historyCalls.length,0);b.dispose();}});
test('foreign UID, worker, grant revision, project or extra private fields reject history and clear the session',async()=>{for(const change of [v=>v.binding.uid='foreign-user',v=>v.binding.workerId='worker-2',v=>v.binding.grantRevision=2,v=>v.binding.projectId='demo-other',v=>v.records[0].stored.password='PRIVATE_CANARY']){const f=setup(),b=f.create();await b.connect();change(f.history.result.view);const r=await b.readOwnHistory();assert.deepEqual(r,{ok:false,error:'unavailable'});assert.equal(f.clears.at(-1),'unavailable');assert.equal(f.subscribers.size,0);}});
test('duplicate escaped response keys, redirect and oversized streams never reach the financial view',async()=>{for(const change of [f=>f.history.raw='{"ok":true,"\\u006fk":true,"view":{}}',f=>f.history.transform=r=>({...r,redirected:true}),f=>f.history.raw=' '.repeat(1048705),f=>f.history.transform=r=>({...r,url:HISTORY_URL+'?debug=true'})]){const f=setup(),b=f.create();await b.connect();change(f);assert.equal((await b.readOwnHistory()).ok,false);assert.equal(f.clears.at(-1),'unavailable');}});
test('history single-flight denies another request while the same read is unresolved',async()=>{const f=setup(),b=f.create();await b.connect();let release;f.history.gate=()=>new Promise(r=>release=r);const first=b.readOwnHistory();await tick();assert.equal((await b.readOwnHistory()).error,'busy');assert.equal(f.historyCalls.length,1);release();assert.equal((await first).ok,true);b.dispose();});
test('account changes during read abort the request and discard all late money',async()=>{const f=setup(),b=f.create();await b.connect();let release;f.history.gate=()=>new Promise(r=>release=r);const first=b.readOwnHistory();await tick();f.switchUser();assert.equal(f.historyCalls[0].init.signal.aborted,true);release();assert.deepEqual(await first,{ok:false,error:'access_denied'});assert.equal(f.subscribers.size,0);});
test('grant revision changes during read clear views before a late response can be returned',async()=>{const f=setup(),b=f.create();await b.connect();let release;f.history.gate=()=>new Promise(r=>release=r);const first=b.readOwnHistory();await tick();f.tenant.grants['caller-1'].revision=2;f.notify();await tick();release();assert.equal((await first).error,'access_denied');assert.ok(f.clears.length>0);assert.equal(f.subscribers.size,0);});
test('host scope drift during archive response cannot authorize or display stored data',async()=>{const f=setup(),b=f.create();await b.connect();f.history.transform=r=>{f.auth.app.options.projectId='demo-other';return r;};assert.equal((await b.readOwnHistory()).ok,false);b.dispose();});
test('fixed not-ready/rate/unavailable responses leave commands current; access denial clears the session',async()=>{for(const [status,error,expected]of [[400,'invalid_request','not_ready'],[429,'rate_limited','rate_limited'],[503,'unavailable','unavailable'],[403,'access_denied','access_denied']]){const f=setup(),b=f.create();await b.connect();f.history.status=status;f.history.result={ok:false,error};assert.equal((await b.readOwnHistory()).error,expected);assert.equal(f.subscribers.size>0,status!==403);b.dispose();}});
test('controller reads own history without requiring a product selection or creating an operation ID',async()=>{const f=setup(),states=[],ids={n:0},c=Controller.createProductionFormController({enabled:true,module:'jahit',endpointURL:ENDPOINT,createBridge:callbacks=>f.create(callbacks),isCurrent:()=>true,onState:s=>states.push(s),newId:()=>{ids.n++;return 'new';}});assert.equal((await c.connect()).ok,true);assert.equal(states.at(-1).selectedCycle,null);const r=await c.readOwnHistory();assert.equal(r.ok,true);assert.deepEqual(r.view,storedView());assert.equal(ids.n,0);assert.equal(f.stats.posts,0);for(const s of states)assert.equal(Object.hasOwn(s,'storedHistory'),false);c.dispose();});
test('controller role gates and explicit argument rejection precede the history request',async()=>{for(const module of ['jahit','qc']){const f=setup(module),c=Controller.createProductionFormController({enabled:true,module,endpointURL:ENDPOINT,createBridge:callbacks=>f.create(callbacks),isCurrent:()=>true,onState:()=>{}});await c.connect();if(module==='qc')assert.equal((await c.readOwnHistory()).error,'access_denied');else assert.equal((await c.readOwnHistory({workerId:'other'})).error,'invalid_request');assert.equal(f.historyCalls.length,0);c.dispose();}});
test('controller rejects a foreign view from a faulty injected bridge even after verified connect',async()=>{const f=setup(),foreign=JSON.parse(JSON.stringify(storedView()));foreign.binding.uid='foreign';const c=Controller.createProductionFormController({enabled:true,module:'jahit',endpointURL:ENDPOINT,createBridge:callbacks=>({...f.create(callbacks),readOwnHistory:async()=>({ok:true,view:foreign})}),isCurrent:()=>true,onState:()=>{}});await c.connect();assert.equal((await c.readOwnHistory()).error,'unavailable');c.dispose();});
