'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createLifecycleRuntimeFixture}=require('./helpers/lifecycle-runtime-fixture.cjs');
const S=require('../server/apps-script/protected-storage-scope.cjs');
const State=require('../server/production-identity-state.cjs');
function fixture(division='qc'){
  const f=createLifecycleRuntimeFixture(division),original=f.root;original.soldier.produksi.images={example:'SYNTHETIC_PHOTO_PRIVATE'};
  const binding={projectId:f.options.binding.projectId,databaseURL:f.options.binding.databaseURL,tenantId:f.options.binding.tenantId};
  const plan=S.prepareProtectedMigration({root:original,binding,migrationId:'lifecycle-migration',expectedRootETag:'"root-old"'});assert.equal(plan.ok,true);
  const scope=S.createProtectedStorageScope({enabled:true,binding,migration:plan.migration}),photos=JSON.stringify(plan.nextRoot[S.KEY].photos),urls=[],reservations=[];
  f.root=plan.nextRoot[S.KEY].working;f.options.storageMigration=plan.migration;
  const originalFetch=f.host.fetch;f.host.fetch=function(url,args){urls.push(url);return originalFetch(url===binding.databaseURL+S.PATHS.working+'.json'?binding.databaseURL+'/.json':url,args);};
  f.hooks.budget=q=>{reservations.push(q);return true;};
  return {f,plan,scope,urls,reservations,photos,root:()=>scope.readWorking({working:f.root}).root};
}
test('QC and partner reads use the fixed protected working node and only 2 MiB response reservations',()=>{for(const division of ['qc','jahit']){const x=fixture(division),r=x.f.create().read(x.f.readInput());assert.equal(r.ok,true);assert.equal(JSON.stringify(r).includes('SYNTHETIC_PHOTO_PRIVATE'),false);assert.equal(x.urls.filter(u=>u.endsWith('/.json')).length,0);assert.equal(x.urls.filter(u=>u.endsWith(S.PATHS.working+'.json')).length,2);assert.equal(x.reservations[0].maxDatabaseDownloadBytes,4*1024*1024);}});
test('protected count command and finance compose the actual coordinator, ETag transport and native identity verifier',()=>{const x=fixture(),f=x.f,cmd=f.command('appendCount','protected-count-1',{workerId:'worker-1',quantity:8,workDate:'2026-10-06'});assert.equal(f.create().execute(f.input(cmd)).ok,true);assert.equal(x.root().soldier.produksi.produksi[0].hitungFisik.length,1);assert.equal(f.stats.writes,1);assert.equal(x.reservations.find(q=>q.kind==='execute').maxDatabaseDownloadBytes,6*1024*1024);assert.equal(JSON.stringify(x.root()).includes('SYNTHETIC_PHOTO_PRIVATE'),false);});
test('owner maintenance is still authorized through fresh retained grants in the unwrapped root',()=>{const x=fixture('owner'),r=x.f.create().readOwner(x.f.readInput());assert.equal(r.ok,true);assert.equal(r.view.binding.division,'owner');assert.equal(JSON.stringify(r).includes('SYNTHETIC_PHOTO_PRIVATE'),false);});
test('lost protected PUT acknowledgement resolves the same stored command without duplicate work',()=>{const x=fixture(),f=x.f,cmd=f.command('appendCount','protected-lost-1',{workerId:'worker-1',quantity:8,workDate:'2026-10-06'});f.hooks.afterPut=()=>{throw Error('synthetic-lost-ack');};assert.deepEqual(f.create().execute(f.input(cmd)),{ok:false,error:'result_unknown',retrySameCommand:true});delete f.hooks.afterPut;const r=f.create().resolve(f.input(cmd));assert.equal(r.ok,true);assert.equal(r.replayed,true);assert.equal(f.stats.writes,1);assert.equal(x.root().soldier.produksi.produksi[0].hitungFisik.length,1);});
test('protected migration mismatch and tampered payload cannot disclose a scoped view',()=>{for(const mode of ['migration','digest']){const x=fixture();if(mode==='migration')x.f.options.storageMigration={...x.plan.migration,sourceRootDigest:'0'.repeat(64)};else{const changed=x.f.root;changed.dataDigest='0'.repeat(64);x.f.root=changed;}assert.equal(x.f.create().read(x.f.readInput()).ok,false);assert.equal(x.f.stats.writes,0);}});
test('unknown browser path/cap selectors reject before request admission or native access',()=>{const x=fixture();assert.equal(x.f.create().read({...x.f.readInput(),maxRootBytes:8*1024*1024}).error,'invalid_request');assert.equal(x.f.stats.google,0);assert.equal(x.f.stats.budget,0);assert.equal(x.f.stats.reads,0);});
test('invalid source-controlled migration is rejected before request admission and Google lookup',()=>{for(const migration of [{migrationId:'invalid/path',sourceRootDigest:'0'.repeat(64)},{migrationId:'okay',sourceRootDigest:'bad'}]){const x=fixture();x.f.options.storageMigration=migration;assert.equal(x.f.create().read(x.f.readInput()).error,'unavailable');assert.equal(x.f.stats.google,0);assert.equal(x.f.stats.budget,0);assert.equal(x.f.stats.reads,0);}});
test('owner production and original business reads retain two working GETs but use only initial and final paired Google verification',()=>{
  for(const method of ['readOwner','readBusiness']){const x=fixture('owner');x.f.options.enrollmentEnabled=true;const result=x.f.create()[method](x.f.readInput());assert.equal(result.ok,true);assert.equal(result.view.binding.division,'owner');assert.equal(x.f.stats.google,4);assert.equal(x.f.stats.reads,2);assert.equal(x.f.stats.puts,0);assert.equal(x.reservations[0].maxDatabaseDownloadBytes,4*1024*1024);assert.equal(x.reservations[0].maxGoogleLookupCount,10);}
});
test('fresh final Google checks catch disabled, changed-provider and revoked tokens after both working reads without emitting a view',()=>{
  for(const alter of [f=>{f.account.disabled=true;},f=>{f.account.providerUserInfo[0].rawId='synthetic-foreign-subject';},f=>{f.account.validSince=String(f.payload.auth_time+1);}]){
    const x=fixture('owner');x.f.hooks.read=n=>{if(n===2)alter(x.f);};const result=x.f.create().readBusiness(x.f.readInput());assert.deepEqual(result,{ok:false,error:'access_denied'});assert.equal(Object.hasOwn(result,'view'),false);assert.equal(x.f.stats.reads,2);assert.equal(x.f.stats.puts,0);assert.equal(x.f.stats.google,3);
  }
  const x=fixture('owner');x.f.hooks.google=n=>{if(n===4)x.f.account.disabled=true;};assert.deepEqual(x.f.create().readOwner(x.f.readInput()),{ok:false,error:'access_denied'});assert.equal(x.f.stats.google,4);assert.equal(x.f.stats.reads,2);
});
test('grant changes in the second fresh working snapshot and protected binding drift still prevent disclosure',()=>{
  const x=fixture('owner');x.f.hooks.read=n=>{if(n!==2)return;const working=x.f.root,root=JSON.parse(JSON.stringify(x.root()));root.authorityTenants[x.f.f.binding.tenantId].grants[x.f.who.uid].profile.active=false;const next=x.scope.prepareWorkingWrite({working,nextRoot:root,expectedRevision:working.revision});assert.equal(next.ok,true);x.f.root=next.nextWorking;};const denied=x.f.create().readBusiness(x.f.readInput());assert.equal(denied.ok,false);assert.equal(Object.hasOwn(denied,'view'),false);assert.equal(x.f.stats.reads,2);assert.equal(x.f.stats.puts,0);
  const revoked=fixture();revoked.f.hooks.read=n=>{if(n!==2)return;const working=revoked.f.root,root=JSON.parse(JSON.stringify(revoked.root())),tenant=revoked.f.f.binding.tenantId;root.authorityTenants[tenant]=State.revokeIdentityEnrollment(root.authorityTenants[tenant],{requestId:'synthetic-mid-read-revocation',approvalId:'approval-q',expectedApprovalRevision:2,expectedGrantRevision:1},revoked.f.who.verifiedAt).next;const next=revoked.scope.prepareWorkingWrite({working,nextRoot:root,expectedRevision:working.revision});assert.equal(next.ok,true);revoked.f.root=next.nextWorking;};assert.deepEqual(revoked.f.create().read(revoked.f.readInput()),{ok:false,error:'access_denied'});assert.equal(revoked.f.stats.reads,2);assert.equal(revoked.f.stats.puts,0);
  const y=fixture('owner');y.f.hooks.read=n=>{if(n===2){const working=y.f.root;working.binding.tenantId='synthetic-foreign-tenant';y.f.root=working;}};assert.equal(y.f.create().readOwner(y.f.readInput()).ok,false);assert.equal(y.f.stats.puts,0);
});
test('request-local read proof never survives success or rejection and does not accept a later changed account',()=>{
  const x=fixture('owner'),api=x.f.create();assert.equal(api.readBusiness(x.f.readInput()).ok,true);assert.equal(x.f.stats.google,4);const reads=x.f.stats.reads;x.f.account.disabled=true;assert.deepEqual(api.readBusiness(x.f.readInput()),{ok:false,error:'access_denied'});assert.equal(x.f.stats.reads,reads);assert.equal(x.f.stats.google,5);x.f.account.disabled=false;x.f.payload.iat++;assert.equal(api.readBusiness(x.f.readInput()).ok,true);assert.equal(x.f.stats.google,9);assert.equal(x.f.stats.reads,reads+2);
});
test('transport drift and token expiry during a reused read proof fail closed before disclosure',()=>{
  const x=fixture('owner'),api=x.f.create(),original=x.f.host.fetch;x.f.hooks.read=n=>{if(n===1)x.f.host.fetch=()=>{throw Error('synthetic-sensitive-error');};};const result=api.readOwner(x.f.readInput());assert.deepEqual(result,{ok:false,error:'unavailable'});x.f.host.fetch=original;delete x.f.hooks.read;assert.deepEqual(api.readOwner(x.f.readInput()),{ok:false,error:'unavailable'});assert.equal(x.f.stats.puts,0);
  const y=fixture('owner');y.f.hooks.read=n=>{if(n===1)y.f.setTime(new Date(y.f.payload.exp*1000).toISOString());};assert.deepEqual(y.f.create().readBusiness(y.f.readInput()),{ok:false,error:'access_denied'});assert.equal(y.f.stats.reads,1);assert.equal(y.f.stats.puts,0);
});
test('owner writes keep every original Google checkpoint and enrollment-capable partner reads remain unchanged',()=>{
  const x=fixture('owner'),f=x.f,command=f.command('ownerSetPO','owner-po-checkpoints',{active:true,quantity:30,workDate:'2026-10-06',note:'Synthetic reviewed PO'}),before={...f.stats};assert.equal(f.create().executeOwner(f.input(command)).ok,true);assert.equal(f.stats.google-before.google,14);assert.equal(f.stats.reads-before.reads,2);assert.equal(f.stats.puts-before.puts,1);
  const api=f.create(),view=api.readBusiness(f.readInput()).view,business={kind:'ownerBusinessWrite',requestId:'synthetic-owner-business-checkpoints',expectedGrantRevision:view.binding.grantRevision,expectedSourceVersion:view.sourceVersion,changes:[{path:'soldier/hpp',action:'set',value:{settings:{margin:11}}}]},businessBefore={...f.stats};assert.equal(api.executeOwnerBusiness(f.input(business)).ok,true);assert.equal(f.stats.google-businessBefore.google,14);assert.equal(f.stats.reads-businessBefore.reads,2);assert.equal(f.stats.puts-businessBefore.puts,1);
  const y=fixture('jahit');y.f.options.enrollmentEnabled=true;assert.equal(y.f.create().read(y.f.readInput()).ok,true);assert.equal(y.f.stats.google,10);assert.equal(y.f.stats.reads,2);assert.equal(y.f.stats.puts,0);
});
