'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const A=require('../server/apps-script/protected-rest-wire.cjs');
const NOW='2026-10-06T06:00:00.000Z',TOKEN='SYNTHETIC_MANAGED_OAUTH_TOKEN';
function fixture(){const source={soldier:{produksi:{produksi:[{id:'synthetic-product',total:87.125,unknown:{preserved:true}}]}},unknown:{nulls:[null,{x:'雪😀'}]}},identity={projectId:'demo-soldier-rest',uid:'synthetic-partner',email:'synthetic.partner@gmail.com',googleSubject:'1000123456789',authTimeMs:Date.parse(NOW)-2000,issuedAtMs:Date.parse(NOW)-1000,expiresAtMs:Date.parse(NOW)+60000,verifiedAt:NOW};let time=NOW;const calls=[],stats={oauth:0,verify:0},hooks={};
  function response(status=200,body=JSON.stringify(source),headers={'Content-Type':'application/json; charset=utf-8',ETag:'"synthetic-old"'}){return {getResponseCode(){return status;},getAllHeaders(){return headers;},getContent(){return Array.from(Buffer.from(body,'utf8'),v=>v>127?v-256:v);}};}
  const script={getOAuthToken(){stats.oauth++;if(hooks.oauth)return hooks.oauth();return TOKEN;}},host={fetch(url,params){calls.push({url,params});return hooks.fetch?hooks.fetch(url,params):response();}},options={enabled:true,binding:{projectId:identity.projectId,databaseURL:'https://demo-soldier-rest.firebaseio.com',tenantId:'synthetic-tenant'},urlFetchApp:host,scriptApp:script,verifyCurrentIdentity(){stats.verify++;if(hooks.verify)return hooks.verify();return {...identity};},clock:()=>time};
  return {source,identity,calls,stats,hooks,host,script,options,response,setTime(v){time=v;},create:()=>A.createAppsScriptProtectedRestWire(options)};
}
test('trusted scoped transport uses only the fixed working path and rejects caller paths/caps',()=>{const f=fixture();const a=A.createAppsScriptProtectedRestWire(f.options);assert.equal(a.read().ok,true);assert.equal(f.calls[0].url,f.options.binding.databaseURL+'/soldierProtectedStorageV1/working.json');for(const extra of [{storageScope:'photos',maxBytes:2*1024*1024},{maxBytes:2*1024*1024},{storageScope:'protected-working-v1',maxBytes:1},{storageScope:'protected-working-v1',path:'/.json'}]){const x=fixture();assert.equal(A.createAppsScriptProtectedRestWire({...x.options,...extra}).read().error,'unavailable');assert.equal(x.stats.oauth,0);assert.equal(x.calls.length,0);}});
test('trusted 2 MiB cap rejects candidate before identity/OAuth and enforces native body bound',()=>{const f=fixture(),a=A.createAppsScriptProtectedRestWire(f.options);assert.equal(a.compareAndSwap({expectedETag:'"old"',next:{x:'x'.repeat(2*1024*1024)}}).error,'capacity_limit');assert.equal(f.stats.verify,0);assert.equal(f.stats.oauth,0);assert.equal(f.calls.length,0);f.hooks.fetch=()=>f.response(200,JSON.stringify({x:'x'.repeat(2*1024*1024)}));assert.equal(a.read().error,'capacity_limit');});
