'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Crypto=require('node:crypto');
const A=require('../server/apps-script/protected-working-adapter.cjs'),S=require('../server/apps-script/protected-storage-scope.cjs');
const NOW='2026-10-07T09:00:00.000Z';
function fixture(){
  const binding={projectId:'demo-soldier-working',databaseURL:'https://demo-soldier-working.firebaseio.com',tenantId:'synthetic-tenant'},source={soldier:{produksi:{produksi:[{id:'product-1',storedTotal:87.125}],images:{photo:'SYNTHETIC_PHOTO_PAYLOAD'}},stokBahan:{unknown:true}},unknown:[null,'雪😀']};
  const plan=S.prepareProtectedMigration({root:source,binding,migrationId:'migration-test',expectedRootETag:'"old"'});assert.equal(plan.ok,true);
  let protectedRoot=structuredClone(plan.nextRoot),calls=[],hooks={};
  const etag=()=>Crypto.createHash('sha1').update(JSON.stringify(protectedRoot[S.KEY].working)).digest('base64');
  const response=(status=200,body=JSON.stringify(protectedRoot[S.KEY].working),headers={ETag:etag(),'Content-Type':'application/json'})=>({getResponseCode:()=>status,getAllHeaders:()=>headers,getContent:()=>Array.from(Buffer.from(body),v=>v>127?v-256:v)});
  const host={fetch(url,args){calls.push({url,args});assert.equal(url,binding.databaseURL+S.PATHS.working+'.json');if(hooks.fetch)return hooks.fetch(args);if(args.method==='put'){if(args.headers['If-Match']!==etag())return response(412,'{}');protectedRoot[S.KEY].working=JSON.parse(args.payload);if(hooks.afterPut)hooks.afterPut();}return response();}};
  const identity={projectId:binding.projectId,uid:'synthetic-owner',email:'syntheticowner@gmail.com',googleSubject:'10001234',authTimeMs:Date.parse(NOW)-2000,issuedAtMs:Date.parse(NOW)-1000,expiresAtMs:Date.parse(NOW)+60000,verifiedAt:NOW};
  const options={enabled:true,binding,migration:plan.migration,urlFetchApp:host,scriptApp:{getOAuthToken:()=> 'SYNTHETIC_OAUTH'},verifyCurrentIdentity:()=>identity,clock:()=>NOW};
  return {options,source,plan,calls,hooks,response,create:()=>A.createAppsScriptProtectedWorkingAdapter(options),get protectedRoot(){return protectedRoot;}};
}
test('OFF does not inspect host getters and malformed scope never dispatches',()=>{let hits=0;const off={enabled:false};Object.defineProperty(off,'urlFetchApp',{get(){hits++;throw Error('private');}});assert.equal(A.createAppsScriptProtectedWorkingAdapter(off).read().error,'service_disabled');assert.equal(hits,0);const f=fixture();f.options.migration={...f.options.migration,migrationId:'invalid/path'};assert.equal(f.create().read().error,'unavailable');assert.equal(f.calls.length,0);});
test('only fixed working node is downloaded; photos are absent from internal root',()=>{const f=fixture(),r=f.create().read();assert.equal(r.ok,true);assert.equal(Object.hasOwn(r.root.soldier.produksi,'images'),false);assert.deepEqual(JSON.parse(JSON.stringify(r.root.unknown)),f.source.unknown);assert.equal(f.calls.length,1);assert.equal(JSON.stringify(r).includes('SYNTHETIC_PHOTO_PAYLOAD'),false);});
test('working CAS preserves every unknown field and concurrent photos without downloading or overwriting them',()=>{const f=fixture(),a=f.create(),r=a.read(),next=structuredClone(r.root);next.soldier.produksi.produksi[0].storedTotal=91.375;const photos=f.protectedRoot[S.KEY].photos,image=JSON.parse(photos.data);image.value.photo='CONCURRENT_PHOTO';photos.data=JSON.stringify(image);photos.dataDigest=Crypto.createHash('sha256').update(photos.data).digest('hex');photos.revision++;const photoBefore=JSON.stringify(photos);assert.equal(a.compareAndSwap({expectedETag:r.etag,next}).ok,true);assert.equal(JSON.stringify(f.protectedRoot[S.KEY].photos),photoBefore);assert.equal(f.protectedRoot[S.KEY].working.revision,2);assert.equal(JSON.parse(f.protectedRoot[S.KEY].working.data).unknown[1],'雪😀');assert.equal(f.calls.length,2);assert.equal(JSON.stringify(f.calls).includes('CONCURRENT_PHOTO'),false);assert.equal(S.prepareProtectedRollback({protectedRoot:f.protectedRoot,expectedRootETag:'"latest"'}).ok,true);});
test('missing read, stale ETag and caller scope selectors cannot dispatch a write',()=>{const f=fixture(),a=f.create();assert.equal(a.compareAndSwap({expectedETag:'"old"',next:f.source}).error,'not_ready');const r=a.read();assert.equal(a.compareAndSwap({expectedETag:'"stale"',next:r.root}).error,'conflict');assert.equal(a.compareAndSwap({expectedETag:r.etag,next:r.root,storageScope:'photos'}).error,'invalid_request');assert.equal(f.calls.length,1);});
test('photos accidentally restored to a working proposal and oversized proposals fail before PUT',()=>{const f=fixture(),a=f.create(),r=a.read();const next=structuredClone(r.root);next.soldier.produksi.images={leak:'photo'};assert.equal(a.compareAndSwap({expectedETag:r.etag,next}).ok,false);delete next.soldier.produksi.images;next.oversized='x'.repeat(S.MAX_WORKING_BYTES);assert.equal(a.compareAndSwap({expectedETag:r.etag,next}).error,'capacity_limit');assert.equal(f.calls.length,1);});
test('unknown PUT acknowledgement invalidates retained state; fresh read sees exactly one committed revision',()=>{const f=fixture(),a=f.create(),r=a.read(),next=structuredClone(r.root);next.ownerNote='example';f.hooks.afterPut=()=>{throw Error('SYNTHETIC_OAUTH');};const written=a.compareAndSwap({expectedETag:r.etag,next});assert.deepEqual(written,{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(a.compareAndSwap({expectedETag:r.etag,next}).error,'not_ready');delete f.hooks.afterPut;const observed=a.read();assert.equal(observed.ok,true);assert.equal(observed.root.ownerNote,'example');assert.equal(f.protectedRoot[S.KEY].working.revision,2);assert.equal(f.calls.filter(c=>c.args.method==='put').length,1);});
test('malformed working envelope and unbounded native response clear retained state',()=>{for(const mode of ['digest','large']){const f=fixture(),a=f.create();assert.equal(a.read().ok,true);if(mode==='digest')f.protectedRoot[S.KEY].working.dataDigest='0'.repeat(64);else f.hooks.fetch=()=>f.response(200,JSON.stringify({x:'x'.repeat(S.MAX_WORKING_BYTES)}));assert.equal(a.read().ok,false);assert.equal(a.compareAndSwap({expectedETag:'"old"',next:{}}).error,'not_ready');assert.equal(f.calls.length,2);}});
test('HTTP conflict does not repeat write; next read supplies a new authority snapshot',()=>{const f=fixture(),a=f.create(),r=a.read();f.hooks.fetch=args=>args.method==='put'?f.response(412,'{}'):f.response();assert.equal(a.compareAndSwap({expectedETag:r.etag,next:r.root}).error,'conflict');assert.equal(a.compareAndSwap({expectedETag:r.etag,next:r.root}).error,'not_ready');assert.equal(a.read().ok,true);assert.equal(f.calls.filter(c=>c.args.method==='put').length,1);});
