'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const Gate=require('../server/apps-script/shared-request-admission.cjs');
const NOW='2026-10-07T03:00:00.000Z',START='2026-10-07T02:00:00.000Z',END='2026-10-08T02:00:00.000Z',B=Gate.ROOT_BYTES;
const policy=()=>({projectId:'demo-soldier',policyId:'synthetic-reservation-1',reviewed:true,startsAt:START,expiresAt:END,requestLimit:10,lookupLimit:140,downloadLimitBytes:30*B,burstWindowMs:60000,burstLimit:3});
function fixture(p=policy()){
  let stored=Gate.createAdmissionSeed(p),time=NOW,owner=null,nextId=0;const hooks={},stats={reads:0,writes:0,acquires:0,releases:0};
  const clock=()=>time,properties={getProperty(key){assert.equal(key,Gate.PROPERTY_KEY);stats.reads++;return hooks.read?hooks.read(stored):stored;},setProperty(key,value){assert.equal(key,Gate.PROPERTY_KEY);assert.equal(typeof value,'string');stats.writes++;if(hooks.write)return hooks.write(value,v=>{stored=v;});stored=value;return properties;}};
  function create(){const id=++nextId,lock={tryLock(ms){assert.equal(ms,250);stats.acquires++;if(hooks.acquire)return hooks.acquire(lock);if(owner!==null&&owner!==id)return false;owner=id;return true;},hasLock(){return hooks.held?hooks.held(owner===id):owner===id;},releaseLock(){stats.releases++;if(hooks.release)return hooks.release(()=>{owner=null;});assert.equal(owner,id);owner=null;}};
    const options={enabled:true,binding:{projectId:p.projectId,policyId:p.policyId},policy:p,scriptLock:lock,scriptProperties:properties,clock};return {gate:Gate.createAppsScriptSharedRequestAdmission(options),lock,options,id};}
  const request=(kind='read')=>({projectId:p.projectId,kind,now:time,maxDatabaseDownloadBytes:(kind==='execute'?3:2)*B,maxGoogleLookupCount:kind==='execute'?14:10});
  return {create,request,hooks,stats,properties,p,get raw(){return stored;},set raw(v){stored=v;},get state(){return JSON.parse(stored);},get owner(){return owner;},set owner(v){owner=v;},get time(){return time;},setTime(v){time=v;}};
}
function clean(state){for(const word of ['idToken','OAuth','email','uid','googleSubject','workerId','command','root','tariff','wage'])assert.equal(JSON.stringify(state).includes(word),false);}
test('default admission is OFF and does not inspect dependencies, request or native hosts',()=>{assert.deepEqual(Gate.DEFAULT_CONFIGURATION,{enabled:false,binding:{projectId:'',policyId:''},policy:null});let hits=0;const o={enabled:false};for(const k of ['binding','policy','scriptLock','scriptProperties','clock'])Object.defineProperty(o,k,{get(){hits++;throw Error('PRIVATE');}});const q=new Proxy({},{get(){hits++;throw Error('PRIVATE');},ownKeys(){hits++;throw Error('PRIVATE');}});assert.equal(Gate.createAppsScriptSharedRequestAdmission(o).admit(q),false);assert.equal(hits,0);});
test('seed is a pure canonical finite reservation and never persists itself',()=>{const f=fixture();assert.deepEqual(f.state,{schemaVersion:1,policy:policy(),sequence:0,requests:0,lookups:0,downloadBytes:0,lastAt:Date.parse(START),burst:[]});assert.equal(f.stats.writes,0);assert.equal(f.raw.length<Gate.MAX_STATE_CHARS,true);clean(f.state);});
test('factory makes no native call and snapshots reviewed options and policy',()=>{const f=fixture(),v=f.create();assert.deepEqual(f.stats,{reads:0,writes:0,acquires:0,releases:0});v.options.binding.projectId='demo-other';v.options.policy.burstLimit=32;v.options.scriptProperties=null;v.options.clock=()=>END;assert.equal(v.gate.admit(f.request()),true);assert.equal(f.state.policy.burstLimit,3);});
test('invalid or extra configuration cannot touch shared state',()=>{for(const change of [o=>delete o.scriptLock,o=>o.policy.reviewed=false,o=>o.policy.requestLimit=0,o=>o.policy.lookupLimit=9,o=>o.policy.downloadLimitBytes=1,o=>o.policy.expiresAt=o.policy.startsAt,o=>o.policy.burstLimit=33,o=>o.binding.policyId='another',o=>o.budgetKey='new-key',o=>o.policy.quota=1]){const f=fixture(),v=f.create();change(v.options);const gate=Gate.createAppsScriptSharedRequestAdmission(v.options);assert.equal(gate.admit(f.request()),false);assert.equal(f.stats.acquires,0);assert.equal(f.stats.reads,0);}});
test('one accepted request persists full envelope and confirms it before lock release',()=>{const f=fixture(),v=f.create();assert.equal(v.gate.admit(f.request('execute')),true);assert.equal(f.state.requests,1);assert.equal(f.state.sequence,1);assert.equal(f.state.lookups,14);assert.equal(f.state.downloadBytes,3*B);assert.deepEqual(f.state.burst,[Date.parse(NOW)]);assert.equal(f.stats.reads,2);assert.equal(f.stats.writes,1);assert.equal(f.owner,null);assert.equal(f.stats.releases,1);clean(f.state);});
test('independent factories retain the same global budget instead of resetting on invocation',()=>{const f=fixture({...policy(),requestLimit:2});for(const kind of ['readFinance','resolve'])assert.equal(f.create().gate.admit(f.request(kind)),true);const before=f.raw;assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.raw,before);assert.equal(f.state.lookups,20);assert.equal(f.state.downloadBytes,4*B);assert.equal(f.owner,null);});
test('request, lookup and byte exhaustion each deny before another property write',()=>{for(const limits of [{requestLimit:1},{lookupLimit:14},{downloadLimitBytes:3*B}]){const f=fixture({...policy(),...limits}),v=f.create();assert.equal(v.gate.admit(f.request('execute')),true);const before=f.raw;assert.equal(v.gate.admit(f.request()),false);assert.equal(f.raw,before);assert.equal(f.stats.writes,1);assert.equal(f.owner,null);}});
test('rolling burst counts persist across factories and only expired entries leave the window',()=>{const f=fixture({...policy(),burstLimit:2});assert.equal(f.create().gate.admit(f.request()),true);f.setTime('2026-10-07T03:00:30.000Z');assert.equal(f.create().gate.admit(f.request()),true);f.setTime('2026-10-07T03:00:59.999Z');assert.equal(f.create().gate.admit(f.request()),false);f.setTime('2026-10-07T03:01:00.000Z');assert.equal(f.create().gate.admit(f.request()),true);assert.deepEqual(f.state.burst,[Date.parse('2026-10-07T03:00:30.000Z'),Date.parse('2026-10-07T03:01:00.000Z')]);assert.equal(f.state.requests,3);});
test('missing state is denied and cannot bootstrap or refill itself',()=>{for(const raw of [null,undefined,'','{}']){const f=fixture();f.raw=raw;assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.raw,raw);assert.equal(f.stats.writes,0);assert.equal(f.owner,null);}});
test('policy changes, period expiration and later dates never reset stored counters',()=>{const f=fixture();assert.equal(f.create().gate.admit(f.request()),true);const before=f.raw;f.setTime(END);assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.raw,before);f.setTime('2026-10-09T03:00:00.000Z');assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.raw,before);const g=fixture();g.p.policyId='replacement';assert.equal(g.create().gate.admit(g.request()),false);assert.equal(g.stats.writes,0);});
test('malformed, duplicate, oversized or inconsistent stored counters fail without repair',()=>{const cases=[s=>JSON.stringify({...s,sequence:1}),s=>JSON.stringify({...s,requests:1,sequence:1}),s=>JSON.stringify({...s,lookups:1}),s=>JSON.stringify({...s,downloadBytes:1}),s=>JSON.stringify({...s,foreign:true}),s=>JSON.stringify({...s,burst:[Date.parse(NOW)]}),s=>'{"schemaVersion":1,'+JSON.stringify(s).slice(1),s=>JSON.stringify(s,null,2),()=> 'x'.repeat(Gate.MAX_STATE_CHARS+1)];for(const change of cases){const f=fixture();f.raw=change(f.state);const before=f.raw;assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.raw,before);assert.equal(f.stats.writes,0);assert.equal(f.owner,null);}});
test('request selectors, smaller invented budgets, getters and extra arguments fail before native access',()=>{for(const change of [q=>q.projectId='demo-other',q=>q.kind='pay',q=>q.maxDatabaseDownloadBytes=B,q=>q.maxGoogleLookupCount=2,q=>q.uid='owner',q=>q.policyId='override',q=>q.now='yesterday']){const f=fixture(),v=f.create(),q=f.request();change(q);assert.equal(v.gate.admit(q),false);assert.equal(f.stats.acquires,0);}const f=fixture(),v=f.create(),q=f.request();let hits=0;Object.defineProperty(q,'kind',{enumerable:true,get(){hits++;throw Error('PRIVATE');}});assert.equal(v.gate.admit(q),false);assert.equal(hits,0);assert.equal(v.gate.admit(f.request(),{}),false);assert.equal(f.stats.acquires,0);});
test('backwards, future, stale and out-of-period clocks do not create a fresh allowance',()=>{const f=fixture(),v=f.create();assert.equal(v.gate.admit(f.request()),true);const before=f.raw;f.setTime('2026-10-07T02:59:59.999Z');assert.equal(v.gate.admit(f.request()),false);assert.equal(f.raw,before);for(const time of ['2026-10-07T01:59:59.999Z',END,'2026-10-07T03:00:00Z']){const g=fixture();g.setTime(time);assert.equal(g.create().gate.admit(g.request()),false);assert.equal(g.stats.writes,0);}const g=fixture(),w=g.create();const q=g.request();q.now='2026-10-07T03:00:00.001Z';assert.equal(w.gate.admit(q),false);q.now='2026-10-07T02:59:54.999Z';assert.equal(w.gate.admit(q),false);});
test('another invocation cannot spend the last allowance while its shared lock is held',()=>{const f=fixture({...policy(),requestLimit:1}),a=f.create(),b=f.create();let nested;f.hooks.write=(value,store)=>{nested=b.gate.admit(f.request());store(value);return f.properties;};assert.equal(a.gate.admit(f.request()),true);assert.equal(nested,false);assert.equal(f.state.requests,1);assert.equal(f.stats.writes,1);assert.equal(f.owner,null);delete f.hooks.write;assert.equal(b.gate.admit(f.request()),false);});
test('pre-held lock is not borrowed or released by admission',()=>{const f=fixture(),v=f.create();f.owner=v.id;assert.equal(v.gate.admit(f.request()),false);assert.equal(f.owner,v.id);assert.equal(f.stats.writes,0);assert.equal(f.stats.releases,0);});
test('lost write acknowledgement never admits and retained reservation is not refunded',()=>{const f=fixture(),v=f.create();f.hooks.write=(value,store)=>{store(value);throw Error('PRIVATE_WRITE_ACK');};assert.equal(v.gate.admit(f.request()),false);assert.equal(f.state.requests,1);assert.equal(f.owner,null);delete f.hooks.write;assert.equal(f.create().gate.admit(f.request()),true);assert.equal(f.state.requests,2);});
test('dropped writes and post-write readback changes cannot authorize a request',()=>{for(const hook of [()=>undefined,(value,store)=>{store(value.replace('"sequence":1','"sequence":0'));}]){const f=fixture(),v=f.create();f.hooks.write=hook;assert.equal(v.gate.admit(f.request()),false);assert.equal(f.owner,null);}const f=fixture(),v=f.create();f.hooks.read=raw=>f.stats.reads===2?null:raw;assert.equal(v.gate.admit(f.request()),false);assert.equal(f.state.requests,1);});
test('expired finishing clock, failed release and missing ownership suppress acceptance after reservation',()=>{for(const kind of ['time','release','ownership']){const f=fixture(),v=f.create();f.hooks.write=(value,store)=>{store(value);if(kind==='time')f.setTime(END);if(kind==='ownership')f.owner=null;return f.properties;};if(kind==='release')f.hooks.release=()=>{throw Error('PRIVATE_RELEASE');};assert.equal(v.gate.admit(f.request()),false);assert.equal(f.state.requests,1);}});
test('reentrant callbacks and replaced native methods are denied without counter reset',()=>{const f=fixture(),v=f.create();f.hooks.write=(value,store)=>{assert.equal(v.gate.admit(f.request()),false);store(value);return f.properties;};assert.equal(v.gate.admit(f.request()),true);const original=f.properties.getProperty;f.properties.getProperty=()=>null;assert.equal(v.gate.admit(f.request()),false);f.properties.getProperty=original;delete f.hooks.write;assert.equal(v.gate.admit(f.request()),false);assert.equal(f.state.requests,1);});
test('exceptions and ambiguous lock replies escape only as false and do not log or expose state',()=>{for(const hook of ['read','write','acquire','held','release']){const f=fixture(),v=f.create();f.hooks[hook]=()=>{throw Error('PRIVATE_CREDENTIAL_OR_RECORD');};assert.equal(v.gate.admit(f.request()),false);}for(const reply of [1,'true',null,Promise.resolve(true)]){const f=fixture(),v=f.create();f.hooks.acquire=()=>reply;assert.equal(v.gate.admit(f.request()),false);assert.equal(f.stats.writes,0);}const source=fs.readFileSync(require.resolve('../server/apps-script/shared-request-admission.cjs'),'utf8');for(const forbidden of [/\bconsole\./,/\bLogger\b/,/\bdoGet\s*\(/,/\bdoPost\s*\(/,/\bUrlFetchApp\./,/\bScriptApp\./,/\bdeleteProperty\s*\(/,/\bsetTimeout\(/])assert.equal(forbidden.test(source),false,String(forbidden));});
