'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createLifecycleRuntimeFixture}=require('./helpers/lifecycle-runtime-fixture.cjs');
const S=require('../server/apps-script/protected-storage-scope.cjs');
function fixture(division='qc'){
  const f=createLifecycleRuntimeFixture(division),original=f.root;original.soldier.produksi.images={example:'SYNTHETIC_PHOTO_PRIVATE'};
  const binding={projectId:f.options.binding.projectId,databaseURL:f.options.binding.databaseURL,tenantId:f.options.binding.tenantId};
  const plan=S.prepareProtectedMigration({root:original,binding,migrationId:'lifecycle-migration',expectedRootETag:'"root-old"'});assert.equal(plan.ok,true);
  const scope=S.createProtectedStorageScope({enabled:true,binding,migration:plan.migration}),photos=JSON.stringify(plan.nextRoot[S.KEY].photos),urls=[],reservations=[];
  f.root=plan.nextRoot[S.KEY].working;f.options.storageMigration=plan.migration;
  const originalFetch=f.host.fetch;f.host.fetch=function(url,args){urls.push(url);return originalFetch(url===binding.databaseURL+S.PATHS.working+'.json'?binding.databaseURL+'/.json':url,args);};
  f.hooks.budget=q=>{reservations.push(q);return true;};
  return {f,plan,scope,urls,reservations,photos,root:()=>scope.readWorking({working:f.root}).root};
}
test('QC and partner reads use the fixed protected working node and only 2 MiB response reservations',()=>{for(const division of ['qc','jahit']){const x=fixture(division),r=x.f.create().read(x.f.readInput());assert.equal(r.ok,true);assert.equal(JSON.stringify(r).includes('SYNTHETIC_PHOTO_PRIVATE'),false);assert.equal(x.urls.filter(u=>u.endsWith('/.json')).length,0);assert.equal(x.urls.filter(u=>u.endsWith(S.PATHS.working+'.json')).length,2);assert.equal(x.reservations[0].maxDatabaseDownloadBytes,4*1024*1024);}});
test('protected count command and finance compose the actual coordinator, ETag transport and native identity verifier',()=>{const x=fixture(),f=x.f,cmd=f.command('appendCount','protected-count-1',{workerId:'worker-1',quantity:8,workDate:'2026-10-06'});assert.equal(f.create().execute(f.input(cmd)).ok,true);assert.equal(x.root().soldier.produksi.produksi[0].hitungFisik.length,1);assert.equal(f.stats.writes,1);assert.equal(x.reservations.find(q=>q.kind==='execute').maxDatabaseDownloadBytes,6*1024*1024);assert.equal(JSON.stringify(x.root()).includes('SYNTHETIC_PHOTO_PRIVATE'),false);});
test('owner maintenance is still authorized through fresh retained grants in the unwrapped root',()=>{const x=fixture('owner'),r=x.f.create().readOwner(x.f.readInput());assert.equal(r.ok,true);assert.equal(r.view.binding.division,'owner');assert.equal(JSON.stringify(r).includes('SYNTHETIC_PHOTO_PRIVATE'),false);});
test('lost protected PUT acknowledgement resolves the same stored command without duplicate work',()=>{const x=fixture(),f=x.f,cmd=f.command('appendCount','protected-lost-1',{workerId:'worker-1',quantity:8,workDate:'2026-10-06'});f.hooks.afterPut=()=>{throw Error('synthetic-lost-ack');};assert.deepEqual(f.create().execute(f.input(cmd)),{ok:false,error:'result_unknown',retrySameCommand:true});delete f.hooks.afterPut;const r=f.create().resolve(f.input(cmd));assert.equal(r.ok,true);assert.equal(r.replayed,true);assert.equal(f.stats.writes,1);assert.equal(x.root().soldier.produksi.produksi[0].hitungFisik.length,1);});
test('protected migration mismatch and tampered payload cannot disclose a scoped view',()=>{for(const mode of ['migration','digest']){const x=fixture();if(mode==='migration')x.f.options.storageMigration={...x.plan.migration,sourceRootDigest:'0'.repeat(64)};else{const changed=x.f.root;changed.dataDigest='0'.repeat(64);x.f.root=changed;}assert.equal(x.f.create().read(x.f.readInput()).ok,false);assert.equal(x.f.stats.writes,0);}});
test('unknown browser path/cap selectors reject before request admission or native access',()=>{const x=fixture();assert.equal(x.f.create().read({...x.f.readInput(),maxRootBytes:8*1024*1024}).error,'invalid_request');assert.equal(x.f.stats.google,0);assert.equal(x.f.stats.budget,0);assert.equal(x.f.stats.reads,0);});
test('invalid source-controlled migration is rejected before request admission and Google lookup',()=>{for(const migration of [{migrationId:'invalid/path',sourceRootDigest:'0'.repeat(64)},{migrationId:'okay',sourceRootDigest:'bad'}]){const x=fixture();x.f.options.storageMigration=migration;assert.equal(x.f.create().read(x.f.readInput()).error,'unavailable');assert.equal(x.f.stats.google,0);assert.equal(x.f.stats.budget,0);assert.equal(x.f.stats.reads,0);}});
