'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Http=require('../server/production-http-handler.cjs');
const ORIGIN='https://soldier.example.invalid',PATH='/v1/production/commands',NOW='2026-10-05T03:00:00.000Z';
const command=()=>({requestId:'request-1',productId:'product-1',cycleId:'cycle-1',expectedRevision:0,kind:'sewing',payload:{id:'sewing-1',assignmentId:'assignment-1',tanggal:'2026-10-05',good:10,reject:0}});
function request(raw=JSON.stringify({command:command()}),headers={}){const body=Buffer.isBuffer(raw)?raw:Buffer.from(raw);const h={origin:ORIGIN,authorization:'Bearer header.payload.signature','content-type':'application/json','content-length':String(body.length),...headers};return {method:'POST',url:PATH,headers:h,rawHeaders:Object.entries(h).flat(),rawBody:body};}
function response(){return {headers:{},ended:0,statusCode:0,setHeader(k,v){this.headers[k]=v;},end(v){this.ended++;this.writableEnded=true;this.body=v===undefined?null:JSON.parse(v);}};}
const ok=r=>({ok:true,receipt:{requestId:r.command.requestId,revision:1,acceptedAt:NOW},replayed:false});
function setup(extra={}){const calls=[],service={execute:async r=>{calls.push(r);return ok(r);}};return {calls,service,handler:Http.createProductionHttpHandler({enabled:true,allowedOrigins:[ORIGIN],path:PATH,deadlineMs:1000,maxInFlight:2,service,...extra})};}
async function run(f,req=request()){const res=response();await f.handler(req,res);return res;}
test('disabled/unconfigured handler never calls the command service',async()=>{for(const extra of [{enabled:false},{allowedOrigins:['*']},{deadlineMs:0},{maxInFlight:33}]){const f=setup(extra),r=await run(f);assert.equal(r.statusCode,503);assert.equal(f.calls.length,0);}});
test('valid raw request uses token header only and emits a limited no-store receipt',async()=>{const f=setup(),req=request();Object.defineProperty(req,'body',{get(){throw Error('parsed body must not be used');}});const r=await run(f,req);assert.equal(r.statusCode,200);assert.deepEqual(f.calls[0],{idToken:'header.payload.signature',command:command()});assert.deepEqual(Object.keys(r.body).sort(),['ok','receipt','replayed']);assert.equal(r.headers['Cache-Control'],'no-store');assert.equal(r.headers['Access-Control-Allow-Origin'],ORIGIN);assert.equal(r.headers['Access-Control-Allow-Credentials'],undefined);});
test('unknown/missing origin, other paths/query and wrong methods cannot execute',async()=>{for(const change of [r=>{delete r.headers.origin;},r=>{r.headers.origin='https://other.example.invalid';},r=>{r.url=PATH+'?token=private';},r=>{r.url='/other';},r=>{r.method='GET';}]){const f=setup(),req=request();change(req);const r=await run(f,req);assert.ok([400,403,405].includes(r.statusCode));assert.equal(f.calls.length,0);assert.equal(JSON.stringify(r).includes('token=private'),false);}});
test('preflight is exact allowlist and never verifies a token or runs the service',async()=>{const f=setup(),req=request('',{'access-control-request-method':'POST','access-control-request-headers':'authorization,content-type'});req.method='OPTIONS';const r=await run(f,req);assert.equal(r.statusCode,204);assert.equal(r.headers['Access-Control-Allow-Methods'],'POST');assert.equal(f.calls.length,0);req.headers['access-control-request-headers']='authorization,x-owner';assert.equal((await run(f,req)).statusCode,400);});
test('duplicate and escaped duplicate JSON keys or forbidden prototype keys fail before execute',async()=>{for(const raw of ['{"command":{},"command":{}}','{"command":{},"\\u0063ommand":{}}','{"command":{"payload":{"id":"a","\\u0069d":"b"}}}','{"command":{"payload":{"__proto__":{}}}}']){const f=setup(),r=await run(f,request(raw));assert.equal(r.statusCode,400);assert.equal(f.calls.length,0);}});
test('invalid UTF8, arrays, empty/oversized/deep bodies and money/profile envelope cannot execute',async()=>{for(const raw of [Buffer.from([0xc3,0x28]),'[]','',JSON.stringify({command:command(),profile:{owner:true}}),'x'.repeat(32769),'{"command":'+ '['.repeat(65)+'0'+']'.repeat(65)+'}']){const f=setup(),r=await run(f,request(raw));assert.equal(r.statusCode,400);assert.equal(f.calls.length,0);}});
test('ambiguous authorization/origin/content headers, compressed JSON and mismatched length cannot execute',async()=>{for(const change of [r=>r.rawHeaders.push('Authorization','Bearer another.token.value'),r=>r.rawHeaders.push('ORIGIN',ORIGIN),r=>{r.headers.authorization='Bearer wrong';},r=>{r.headers['content-type']='text/plain';},r=>{r.headers['content-encoding']='gzip';},r=>{r.headers['content-length']='1';}]){const f=setup(),req=request();change(req);const r=await run(f,req);assert.equal(r.statusCode,400);assert.equal(f.calls.length,0);}});
test('private fields and mismatched receipt cannot become a successful response',async()=>{for(const execute of [async r=>({...ok(r),privateAuthority:'synthetic-secret'}),async r=>({...ok(r),receipt:{...ok(r).receipt,requestId:'other-request'}}),async r=>({...ok(r),receipt:{...ok(r).receipt,rate:999}})]){const f=setup({service:{execute}}),r=await run(f);assert.equal(r.statusCode,503);assert.deepEqual(r.body,{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(JSON.stringify(r).includes('synthetic-secret'),false);}});
test('service errors expose only fixed codes; ambiguous unavailability instructs exact command replay',async()=>{for(const [error,status]of [['access_denied',403],['rate_limited',429],['conflict',409],['unavailable',503]]){const f=setup({service:{execute:async()=>({ok:false,error})}}),r=await run(f);assert.equal(r.statusCode,status);assert.equal(r.body.retrySameCommand,error==='unavailable'?true:undefined);}const f=setup({service:{execute:async()=>{throw Error('synthetic-token-pin-money');}}}),r=await run(f);assert.equal(JSON.stringify(r).includes('synthetic-token-pin-money'),false);assert.equal(r.body.retrySameCommand,true);});
test('deadline never ends a response before late commit settles and retains capacity',async()=>{let resolve,calls=0;const service={execute:()=>{calls++;return new Promise(r=>{resolve=r;});}},f=setup({service,deadlineMs:5,maxInFlight:1}),res=response(),task=f.handler(request(),res);await new Promise(r=>setTimeout(r,20));assert.equal(res.ended,0);const busy=await run(f);assert.equal(busy.body.error,'busy');assert.equal(calls,1);resolve(ok({command:command()}));await task;assert.equal(res.statusCode,503);assert.equal(res.body.error,'result_unknown');assert.equal(res.ended,1);service.execute=async r=>{calls++;return ok(r);};assert.equal((await run(f)).statusCode,200);assert.equal(calls,2);});
test('disconnect does not release an unresolved transaction or attempt a response',async()=>{let resolve;const f=setup({service:{execute:()=>new Promise(r=>{resolve=r;})},maxInFlight:1}),res=response();res.destroyed=true;const task=f.handler(request(),res);assert.equal((await run(f)).body.error,'busy');resolve(ok({command:command()}));await task;assert.equal(res.ended,0);});
