'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),Crypto=require('node:crypto');
const S=require('../server/apps-script/protected-storage-scope.cjs'),R=require('../security/build-protected-photo-rules.cjs');
const binding={projectId:'demo-soldier-owner-photos',databaseURL:'https://demo-soldier-owner-photos.firebaseio.com',tenantId:'synthetic-photo-tenant'};
const copy=v=>JSON.parse(JSON.stringify(v));
function source(){return{soldier:{produksi:{produksi:[{id:'synthetic-product',jahit:[],unknown:{empty:[],nullable:null}}],images:{'synthetic-\u2603':{url:'data:image/png;base64,AA==',unknown:[null,{},[]]}}},productionPhotos:{pesananOffline:[{id:'synthetic-order',items:[{id:'synthetic-item',gambar:'synthetic-photo'}]}]},stokBahan:{unknown:null}},authorityTenants:{synthetic:{unchanged:true}},unknown:{numericMap:{'0':null,'2':[]}}};}
function fixture(root=source()){const original=copy(root),p=S.prepareOwnerSdkPhotoMigration({root,binding,migrationId:'synthetic-sdk-photos',expectedRootETag:'"synthetic-root"'});assert.equal(p.ok,true);assert.deepEqual(root,original);return{original,protected:copy(p.nextRoot),migration:p.migration};}
function command(photos,id='synthetic-request'){const i=S.inspectOwnerSdkPhotoEnvelope({photos});assert.equal(i.ok,true);return{requestId:id,expectedRevision:photos.revision,expectedDataDigest:photos.dataDigest,...copy(i.data)};}
function rollback(root){const r=S.prepareProtectedRollback({protectedRoot:root,expectedRootETag:'"synthetic-protected"'});assert.equal(r.ok,true);return r.nextRoot;}
test('schema2 trusted migration partitions exactly two photo roots and source stays unchanged',()=>{const f=fixture(),s=f.protected[S.KEY],w=JSON.parse(s.working.data);assert.equal(s.manifest.schemaVersion,2);assert.equal(s.working.schemaVersion,1);assert.equal(s.photos.schemaVersion,2);assert.equal(s.photos.lastReceipt,false);assert.equal(s.photos.receiptCount,0);assert.equal(s.photos.receipts,'');assert.equal(Object.hasOwn(w.soldier.produksi,'images'),false);assert.equal(Object.hasOwn(w.soldier,'productionPhotos'),false);assert.deepEqual(rollback(f.protected),f.original);});
for(const [label,value,present]of [['absent',undefined,false],['null',null,true],['empty-array',[],true],['empty-map',{},true],['numeric-map',{'0':null,'2':{empty:[]}},true]])test('schema2 exact independent image/projection presence '+label,()=>{const root=source();if(present){root.soldier.produksi.images=copy(value);root.soldier.productionPhotos=copy(value);}else{delete root.soldier.produksi.images;delete root.soldier.productionPhotos;}const f=fixture(root),read=S.inspectOwnerSdkPhotoEnvelope({photos:f.protected[S.KEY].photos});assert.equal(read.data.images.present,present);assert.equal(read.data.productionPhotos.present,present);assert.deepEqual(rollback(f.protected),root);});
test('schema1 migration/read/rollback retains the original separate projection behavior',()=>{const root=source(),p=S.prepareProtectedMigration({root,binding,migrationId:'synthetic-old-photos',expectedRootETag:'"synthetic"'});assert.equal(p.ok,true);assert.equal(p.nextRoot[S.KEY].photos.schemaVersion,1);assert.deepEqual(rollback(p.nextRoot),root);assert.deepEqual(JSON.parse(p.nextRoot[S.KEY].working.data).soldier.productionPhotos,root.soldier.productionPhotos);assert.equal(S.inspectOwnerSdkPhotoEnvelope({photos:p.nextRoot[S.KEY].photos}).ok,false);});
test('ASCII data preserves Unicode, astral, DEL, escaped strings and exact unknown fields',()=>{const root=source();root.soldier.productionPhotos={'astral-\ud83d\ude80':'\u007f\\"\n',unknown:{nullable:null,list:[]}};const f=fixture(root),p=f.protected[S.KEY].photos;assert.match(p.data,/^[\x20-\x7e]*$/);assert.match(p.data,/\\ud83d\\ude80/);assert.match(p.data,/\\u007f/);assert.deepEqual(rollback(f.protected),root);});
test('one photo mutation changes neither working nor manifest and restores both slots exactly',()=>{const f=fixture(),s=f.protected[S.KEY],before=copy(s),c=command(s.photos);c.images={present:true,value:{newImage:'synthetic'}};const result=S.prepareOwnerSdkPhotoMutation({photos:s.photos,command:c});assert.equal(result.ok,true);assert.equal(result.replayed,false);assert.equal(result.nextPhotos.revision,2);assert.equal(result.nextPhotos.receiptCount,1);assert.equal(result.nextPhotos.lastReceipt.requestId,c.requestId);assert.deepEqual(s,before);s.photos=copy(result.nextPhotos);const restored=rollback(f.protected);assert.deepEqual(restored.soldier.productionPhotos,f.original.soldier.productionPhotos);assert.deepEqual(restored.soldier.produksi.images,c.images.value);assert.deepEqual(s.working,before.working);assert.deepEqual(s.manifest,before.manifest);});
test('request digest is exact sorted logical command and retained receipt is not repriced',()=>{const f=fixture(),p=f.protected[S.KEY].photos,c=command(p),r=S.prepareOwnerSdkPhotoMutation({photos:p,command:c});function stable(v){return v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(stable).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}';}assert.equal(r.receipt.payloadDigest,Crypto.createHash('sha256').update(stable(c)).digest('hex'));assert.equal(r.receipt.revision,2);assert.equal(r.receipt.dataDigest,p.dataDigest);});
test('lost ACK resolves and replays original receipt even after later photo commands',()=>{const f=fixture(),p=f.protected[S.KEY].photos,c=command(p,'synthetic-first'),a=S.prepareOwnerSdkPhotoMutation({photos:p,command:c});const d=command(a.nextPhotos,'synthetic-later');d.productionPhotos={present:false};const b=S.prepareOwnerSdkPhotoMutation({photos:a.nextPhotos,command:d});assert.equal(b.ok,true);assert.deepEqual(S.resolveOwnerSdkPhotoMutation({photos:b.nextPhotos,command:c}),{ok:true,replayed:true,receipt:a.receipt});const replay=S.prepareOwnerSdkPhotoMutation({photos:b.nextPhotos,command:c});assert.deepEqual(replay,{ok:true,replayed:true,receipt:a.receipt});assert.equal(Object.hasOwn(replay,'nextPhotos'),false);});
test('same request with changed payload conflicts and unretained request remains unknown',()=>{const f=fixture(),p=f.protected[S.KEY].photos,c=command(p),r=S.prepareOwnerSdkPhotoMutation({photos:p,command:c}),other=copy(c);other.images={present:false};assert.equal(S.resolveOwnerSdkPhotoMutation({photos:r.nextPhotos,command:other}).error,'conflict');assert.equal(S.prepareOwnerSdkPhotoMutation({photos:r.nextPhotos,command:other}).error,'conflict');assert.equal(S.resolveOwnerSdkPhotoMutation({photos:p,command:c}).error,'result_unknown');});
test('stale photo revision or digest rejects a new command before any mutation',()=>{const f=fixture(),p=f.protected[S.KEY].photos;for(const key of ['expectedRevision','expectedDataDigest']){const c=command(p);c[key]=key==='expectedRevision'?2:'a'.repeat(64);assert.equal(S.prepareOwnerSdkPhotoMutation({photos:p,command:c}).error,'conflict');assert.equal(p.revision,1);}});
test('removing last images and independently retaining explicit projection null survives rollback',()=>{const f=fixture(),p=f.protected[S.KEY].photos,c=command(p);c.images={present:false};c.productionPhotos={present:true,value:null};const r=S.prepareOwnerSdkPhotoMutation({photos:p,command:c});assert.equal(r.ok,true);f.protected[S.KEY].photos=copy(r.nextPhotos);const root=rollback(f.protected);assert.equal(Object.hasOwn(root.soldier.produksi,'images'),false);assert.equal(Object.hasOwn(root.soldier,'productionPhotos'),true);assert.equal(root.soldier.productionPhotos,null);});
test('receipt removal, malformed tail, duplicate map identities and digest drift fail closed',()=>{const f=fixture(),p=f.protected[S.KEY].photos,r=S.prepareOwnerSdkPhotoMutation({photos:p,command:command(p)});for(const change of [e=>e.receipts='',e=>e.lastReceipt=false,e=>e.receipts+=e.receipts,e=>e.dataDigest='a'.repeat(64),e=>e.receiptCount=0,e=>e.data+=' ',e=>e.data=e.data.replace('\\u2603','\u2603')]){const bad=copy(r.nextPhotos);change(bad);assert.equal(S.inspectOwnerSdkPhotoEnvelope({photos:bad}).ok,false);}});
test('photo envelope, sparse arrays, getters, reserved keys and excess command fields reject',()=>{const f=fixture(),p=f.protected[S.KEY].photos;const cases=[()=>{const c=command(p);c.role='owner';return c;},()=>{const c=command(p);c.images={present:true,value:new Array(2)};return c;},()=>{const c=command(p);Object.defineProperty(c.images,'value',{get(){throw Error('synthetic getter');},enumerable:true});return c;},()=>{const c=command(p);c.images={present:true,value:JSON.parse('{"__proto__":1}')};return c;}];for(const make of cases)assert.equal(S.prepareOwnerSdkPhotoMutation({photos:p,command:make()}).ok,false);const c=command(p);c.images={present:true,value:'x'.repeat(S.MAX_PHOTO_BYTES)};assert.equal(S.prepareOwnerSdkPhotoMutation({photos:p,command:c}).error,'capacity_limit');});
test('finite receipt capacity rejects rather than deleting retained ACK history',()=>{const f=fixture();let p=f.protected[S.KEY].photos,first;for(let i=0;i<S.MAX_PHOTO_RECEIPTS;i++){const c=command(p,'synthetic-'+i);if(i===0)first=c;const r=S.prepareOwnerSdkPhotoMutation({photos:p,command:c});assert.equal(r.ok,true);p=copy(r.nextPhotos);}assert.equal(S.prepareOwnerSdkPhotoMutation({photos:p,command:command(p,'synthetic-overflow')}).error,'capacity_limit');assert.equal(S.resolveOwnerSdkPhotoMutation({photos:p,command:first}).ok,true);});
test('Rules generator defaults OFF and rejects malformed private bindings without export',()=>{assert.deepEqual(R.buildProtectedOwnerPhotoRules(),{rules:{'.read':false,'.write':false}});assert.deepEqual(R.buildProtectedOwnerPhotoRules({enabled:false,ownerUid:'synthetic-owner'}),{rules:{'.read':false,'.write':false}});assert.throws(()=>R.buildProtectedOwnerPhotoRules({enabled:true,ownerUid:"synthetic'escape",projectId:binding.projectId}),/invalid_private_binding/);});
test('generated Rules target only fixed photos, no legacy read/working/client authority gate',()=>{const rules=R.buildProtectedOwnerPhotoRules({enabled:true,ownerUid:'synthetic-owner',projectId:binding.projectId}).rules,p=rules[S.KEY].photos;assert.equal(rules['.read'],false);assert.equal(rules['.write'],false);assert.equal(rules[S.KEY].working['.read'],false);assert.equal(rules[S.KEY].working['.write'],false);assert.equal(rules[S.KEY].manifest['.read'],false);assert.match(p['.write'],/newData\.exists\(\)/);assert.match(p['.write'],/google\.com/);assert.match(p['.write'],/email_verified/);assert.match(p['.write'],/receiptCount.*\+ 1/);assert.equal(JSON.stringify(rules).includes('accessControl'),false);assert.equal(JSON.stringify(rules).includes('replace(/'),false);});
