'use strict';
// Synthetic fixtures only. No production database, credential or business data.
const test = require('node:test');
const assert = require('node:assert/strict');
const Scope = require('../server/apps-script/protected-storage-scope.cjs');
const Lifecycle = require('../server/production-legacy-lifecycle.cjs');
const Finance = require('../server/production-legacy-finance.cjs');
const Snapshot = require('../server/production-legacy-operations.cjs');
const F = require('./fixtures/identity-tenant.cjs');
const Production = require('./fixtures/legacy-lifecycle.cjs');
const copy = F.copy;
function fixture() {
  const p = Production.fixture(), before = copy(p.root), prepared = Scope.prepareProtectedMigration({ root: p.root, binding: p.binding, migrationId: 'migration-synthetic-1', expectedRootETag: '"synthetic-root-1"' });
  assert.equal(prepared.ok, true); const root = copy(prepared.nextRoot), s = root[Scope.KEY], api = Scope.createProtectedStorageScope({ enabled: true, binding: p.binding, migration: prepared.migration });
  const owner = F.identity({ uid: 'owner-1', email: 'syntheticowner@gmail.com', googleSubject: '1000099999999' });
  const readPhotos = (identity = owner) => api.readOwnerPhotos({ working: s.working, photos: s.photos, identity, now: F.NOW });
  const writePhotos = (images, changes = {}) => api.prepareOwnerPhotoWrite({ working: s.working, photos: s.photos, identity: owner, now: F.NOW, expectedWorkingRevision: s.working.revision, expectedPhotoRevision: s.photos.revision, images, ...changes });
  const writeWork = (nextRoot, changes = {}) => api.prepareWorkingWrite({ working: s.working, nextRoot, expectedRevision: s.working.revision, ...changes });
  const rollback = () => Scope.prepareProtectedRollback({ protectedRoot: root, expectedRootETag: '"synthetic-root-current"' });
  return { p, before, prepared, root, s, api, owner, readPhotos, writePhotos, writeWork, rollback };
}
test('disabled storage never inspects private options or input', () => { let calls = 0; const options = { get binding() { calls++; throw Error('SYNTHETIC_PRIVATE'); } }, input = { get working() { calls++; throw Error('SYNTHETIC_PRIVATE'); } }; const api = Scope.createProtectedStorageScope(options); for (const method of Object.values(api)) assert.deepEqual(method(input), { ok: false, error: 'service_disabled' }); assert.equal(calls, 0); });
test('enabled configuration rejects unreviewed or client-selected bindings', () => { const f = fixture(); for (const options of [{ enabled: true }, { enabled: true, binding: f.p.binding, migration: f.prepared.migration, role: 'owner' }, { enabled: true, binding: { ...f.p.binding, databaseURL: 'https://foreign.invalid' }, migration: f.prepared.migration }]) assert.deepEqual(Scope.createProtectedStorageScope(options).readWorking({ working: f.s.working }), { ok: false, error: 'unavailable' }); });
test('fixed protected paths carry no tenant or browser path selector', () => { assert.deepEqual(Scope.PATHS, { root: '/soldierProtectedStorageV1', working: '/soldierProtectedStorageV1/working', photos: '/soldierProtectedStorageV1/photos' }); assert.equal(Object.isFrozen(Scope.PATHS), true); });
test('partition and reconstruction preserve unknown fields, original wages, PIN fields and archives', () => { const f = fixture(), split = Scope.splitLegacyRoot({ root: f.before }); assert.equal(split.ok, true); assert.equal(Object.hasOwn(split.workingRoot.soldier.produksi, 'images'), false); const rebuilt = Scope.reassembleLegacyRoot({ workingRoot: split.workingRoot, images: split.images }); assert.deepEqual(rebuilt, { ok: true, root: f.before }); assert.deepEqual(f.p.root, f.before); });
test('absence, null, empty collections and map or array photo values retain their exact original state', () => { for (const photo of [{ present: false }, { present: true, value: null }, { present: true, value: {} }, { present: true, value: [] }, { present: true, value: { 'Legacy.Name|Item': 'SYNTHETIC_IMAGE' } }, { present: true, value: ['SYNTHETIC_IMAGE', null] }]) { const root = copy(fixture().before); if (photo.present) root.soldier.produksi.images = photo.value; else delete root.soldier.produksi.images; const split = Scope.splitLegacyRoot({ root }); assert.equal(split.ok, true); assert.deepEqual(split.images, photo); assert.deepEqual(Scope.reassembleLegacyRoot(split.ok ? { workingRoot: split.workingRoot, images: split.images } : {}).root, root); } });
test('original photo key cannot be silently dropped, overwritten or accepted in working writes', () => { const f = fixture(); assert.deepEqual(f.writeWork(f.before), { ok: false, error: 'not_ready' }); const split = Scope.splitLegacyRoot({ root: f.before }); assert.deepEqual(Scope.reassembleLegacyRoot({ workingRoot: f.before, images: split.images }), { ok: false, error: 'not_ready' }); assert.deepEqual(f.rollback().nextRoot, f.before); });
test('cutover candidate relocates every root field into one complete protected scope and binds the root ETag', () => { const f = fixture(); assert.deepEqual(Object.keys(f.root), [Scope.KEY]); assert.equal(f.prepared.expectedRootETag, '"synthetic-root-1"'); assert.deepEqual(Scope.inspectProtectedRoot({ protectedRoot: f.root }), { ok: true, binding: f.p.binding, migration: f.prepared.migration, workingRevision: 1, photoRevision: 1 }); assert.deepEqual(f.rollback().nextRoot, f.before); });
test('occupied protected namespace is never overwritten or migrated twice', () => { const f = fixture(), occupied = copy(f.before); occupied[Scope.KEY] = { retain: 'SYNTHETIC_UNKNOWN' }; for (const root of [occupied, f.root]) assert.deepEqual(Scope.prepareProtectedMigration({ root, binding: f.p.binding, migrationId: 'migration-synthetic-2', expectedRootETag: '"synthetic-root-2"' }), { ok: false, error: 'not_ready' }); assert.equal(occupied[Scope.KEY].retain, 'SYNTHETIC_UNKNOWN'); });
test('mismatched schemas, incomplete migrations and outside legacy branches cannot be rolled back by guessing', () => { const f = fixture(); for (const alter of [r => delete r[Scope.KEY].photos, r => delete r[Scope.KEY].manifest, r => delete r[Scope.KEY].working.data, r => r[Scope.KEY].photos.schemaVersion = 2, r => r[Scope.KEY].manifest.imagesPath = 'foreign/images', r => r.soldier = { unexpected: true }]) { const root = copy(f.root); alter(root); assert.deepEqual(Scope.inspectProtectedRoot({ protectedRoot: root }), { ok: false, error: 'not_ready' }); assert.deepEqual(Scope.prepareProtectedRollback({ protectedRoot: root, expectedRootETag: '"s"' }), { ok: false, error: 'not_ready' }); } });
test('wrong migration, source fingerprint, database and tenant envelopes never enter the legacy core', () => { const f = fixture(); for (const alter of [w => w.migrationId = 'other-migration', w => w.sourceRootDigest = '0'.repeat(64), w => w.binding.projectId = 'demo-other-project', w => w.binding.databaseURL = 'https://demo-other-project.firebaseio.com', w => w.binding.tenantId = 'other-tenant', w => w.phase = 'prepared', w => w.schemaVersion = 2]) { const w = copy(f.s.working); alter(w); assert.deepEqual(f.api.readWorking({ working: w }), { ok: false, error: 'not_ready' }); } });
test('working and photo checksums reject accidental data corruption without releasing values', () => { const f = fixture(), w = copy(f.s.working), p = copy(f.s.photos); w.data = w.data.replace('SYNTHETIC_CASH_PRIVATE', 'SYNTHETIC_CORRUPTION'); p.data = p.data.replace('SYNTHETIC_IMAGE', 'SYNTHETIC_CORRUPTION'); assert.deepEqual(f.api.readWorking({ working: w }), { ok: false, error: 'not_ready' }); assert.deepEqual(f.api.readOwnerPhotos({ working: f.s.working, photos: p, identity: f.owner, now: F.NOW }), { ok: false, error: 'not_ready' }); });
test('initial mixed partitions from different snapshots fail complete migration verification', () => { const f = fixture(), other = copy(f.before); other.soldier.produksi.images = { private: 'OTHER_SYNTHETIC_IMAGE' }; const prepared = Scope.prepareProtectedMigration({ root: other, binding: f.p.binding, migrationId: f.prepared.migration.migrationId, expectedRootETag: '"other"' }); const mixed = copy(f.root); mixed[Scope.KEY].photos = copy(prepared.nextRoot[Scope.KEY].photos); assert.deepEqual(Scope.inspectProtectedRoot({ protectedRoot: mixed }), { ok: false, error: 'not_ready' }); });
test('descriptor-only validation never runs getters, coercion hooks or inherited serializers', () => { let calls = 0; const f = fixture(), root = copy(f.before); Object.defineProperty(root, 'private', { enumerable: true, get() { calls++; return 'SYNTHETIC_PRIVATE'; } }); assert.deepEqual(Scope.splitLegacyRoot({ root }), { ok: false, error: 'not_ready' }); const input = { get working() { calls++; return f.s.working; } }; assert.deepEqual(f.api.readWorking(input), { ok: false, error: 'invalid_request' }); assert.equal(calls, 0); });
test('sparse arrays, cycles, symbols and reserved keys fail without changing the source', () => { const f = fixture(); for (const value of [new Array(2), { [Symbol('private')]: 1 }, JSON.parse('{"__proto__":{"private":true}}')]) { const root = copy(f.before); root.unknown = value; assert.deepEqual(Scope.splitLegacyRoot({ root }), { ok: false, error: 'not_ready' }); } const cycle = copy(f.before); cycle.unknown = cycle; assert.deepEqual(Scope.splitLegacyRoot({ root: cycle }), { ok: false, error: 'not_ready' }); assert.deepEqual(f.p.root, f.before); });
test('large image content is absent from routine working envelopes', () => { const f = fixture(), root = copy(f.before); root.soldier.produksi.images = { private: 'S'.repeat(1024 * 1024) }; const prepared = Scope.prepareProtectedMigration({ root, binding: f.p.binding, migrationId: 'migration-large-photo', expectedRootETag: '"photo"' }); assert.equal(prepared.ok, true); assert.ok(Buffer.byteLength(JSON.stringify(prepared.nextRoot[Scope.KEY].working)) < 100000); assert.equal(JSON.parse(prepared.nextRoot[Scope.KEY].photos.data).value.private.length, 1024 * 1024); assert.equal(JSON.stringify(prepared.nextRoot[Scope.KEY].working).includes('S'.repeat(100)), false); });
test('complete working envelope metadata counts toward the fixed 2 MiB cap on migration and write', () => { const f = fixture(), base = JSON.parse(f.s.working.data), empty = copy(base); empty.padding = ''; const envelopeBase = copy(f.s.working); envelopeBase.data = Snapshot.serializeLegacyRoot(empty); const room = Scope.MAX_WORKING_BYTES - Buffer.byteLength(JSON.stringify(envelopeBase)); base.padding = 'x'.repeat(room + 1); assert.ok(Buffer.byteLength(JSON.stringify(base)) < Scope.MAX_WORKING_BYTES); assert.deepEqual(f.writeWork(base), { ok: false, error: 'capacity_limit' }); const legacy = copy(base); legacy.soldier.produksi.images = {}; assert.deepEqual(Scope.prepareProtectedMigration({ root: legacy, binding: f.p.binding, migrationId: f.prepared.migration.migrationId, expectedRootETag: '"large"' }), { ok: false, error: 'capacity_limit' }); });
test('oversized complete working reads and photo migration reject before returning any data', () => { const f = fixture(), w = copy(f.s.working); w.data = JSON.stringify({ ...JSON.parse(w.data), padding: 'x'.repeat(Scope.MAX_WORKING_BYTES) }); assert.deepEqual(f.api.readWorking({ working: w }), { ok: false, error: 'capacity_limit' }); const root = copy(f.before); root.soldier.produksi.images = { private: 'x'.repeat(Scope.MAX_PHOTO_BYTES) }; assert.deepEqual(Scope.prepareProtectedMigration({ root, binding: f.p.binding, migrationId: 'migration-large', expectedRootETag: '"large"' }), { ok: false, error: 'capacity_limit' }); });
test('stale working revision cannot overwrite a concurrent payroll or grant update', () => { const f = fixture(), root = JSON.parse(f.s.working.data); root.soldier.privateCash = 'CONCURRENT_SYNTHETIC_CHANGE'; const next = f.writeWork(root); assert.equal(next.ok, true); f.s.working = copy(next.nextWorking); const before = copy(f.s.working); assert.deepEqual(f.writeWork(JSON.parse(f.prepared.nextRoot[Scope.KEY].working.data), { expectedRevision: 1 }), { ok: false, error: 'conflict' }); assert.deepEqual(f.s.working, before); });
test('actual compatible lifecycle and own finance still operate on unwrapped data with frozen wages intact', () => { const f = fixture(), read = f.api.readWorking({ working: f.s.working }), core = Lifecycle.createProductionLegacyLifecycle({ enabled: true, binding: f.p.binding, clock: () => F.NOW, tariffPolicy: Production.POLICY }); assert.equal(read.ok, true); const view = core.read({ root: read.root, identity: f.p.qc }); assert.equal(view.ok, true); const command = { kind: 'appendCount', requestId: 'synthetic-count-request', operationId: 'synthetic-count', productId: 'product-1', expectedGrantRevision: 1, expectedSourceVersion: view.view.products[0].sourceVersion, workerId: 'worker-1', quantity: 8, workDate: '2026-10-06' }; const proposal = core.execute({ root: read.root, identity: f.p.qc, command }); assert.equal(proposal.ok, true); const next = f.writeWork(proposal.next); assert.equal(next.ok, true); f.s.working = copy(next.nextWorking); const restored = f.rollback().nextRoot; assert.deepEqual(restored.soldier.produksi.images, f.before.soldier.produksi.images); assert.deepEqual(restored.soldier.produksi.produksi[0].potong, f.before.soldier.produksi.produksi[0].potong); assert.deepEqual(restored.soldier.produksi.produksi[0].jahit, f.before.soldier.produksi.produksi[0].jahit); const finance = Finance.createProductionLegacyFinance({ enabled: true, binding: f.p.binding, clock: () => F.NOW, tariffPolicy: Production.POLICY }).read({ root: JSON.parse(next.nextWorking.data), identity: f.p.partner }); assert.equal(finance.ok, true); assert.equal(finance.view.slip.entries[0].total, 26); assert.equal(finance.view.storedJahit.records[0].stored.total, 20); });
test('working update has no photo payload and preserves a photo change made after its original read', () => { const f = fixture(), original = copy(f.s.working), root = JSON.parse(original.data); root.privateRoot = 'NEW_SYNTHETIC_WORK'; const work = f.writeWork(root), photo = f.writePhotos({ present: true, value: { private: 'NEW_SYNTHETIC_PHOTO', second: 'SYNTHETIC_SECOND' } }); assert.equal(work.ok, true); assert.equal(photo.ok, true); f.s.photos = copy(photo.nextPhotos); f.s.working = copy(work.nextWorking); assert.deepEqual(f.rollback().nextRoot.soldier.produksi.images, JSON.parse(photo.nextPhotos.data).value); assert.equal(f.rollback().nextRoot.privateRoot, 'NEW_SYNTHETIC_WORK'); assert.equal(Object.hasOwn(work, 'photos'), false); assert.equal(Object.hasOwn(JSON.parse(work.nextWorking.data).soldier.produksi, 'images'), false); });
test('only the initialized current owner can receive photo values', () => { const f = fixture(); assert.deepEqual(f.readPhotos(), { ok: true, images: { present: true, value: f.before.soldier.produksi.images }, photoRevision: 1, workingRevision: 1 }); for (const identity of [f.p.partner, f.p.qc, F.identity({ uid: 'unlisted-1' }), { ...f.owner, owner: true }]) assert.equal(f.readPhotos(identity).ok, false); });
test('photo reads reject expired, future, wrong-project and malformed verified identities', () => { const f = fixture(); for (const identity of [{ ...f.owner, expiresAtMs: Date.parse(F.NOW) }, { ...f.owner, issuedAtMs: Date.parse(F.AFTER) }, { ...f.owner, projectId: 'demo-foreign-project' }, { ...f.owner, verifiedAt: 'bad-date' }, { ...f.owner, authTimeMs: -0 }, { ...f.owner, email: 'private@example.invalid' }]) assert.equal(f.readPhotos(identity).ok, false); });
test('current retained owner grant is rechecked instead of trusting cached owner role', () => { const f = fixture(), next = JSON.parse(f.s.working.data); next.authorityTenants[F.TENANT].grants['owner-1'].profile.active = false; const changed = f.writeWork(next); assert.equal(changed.ok, true); f.s.working = copy(changed.nextWorking); assert.equal(f.readPhotos().ok, false); assert.equal(f.writePhotos({ present: true, value: {} }).ok, false); });
test('partner or QC photo mutation returns a fixed denial without any photo or financial data', () => { const f = fixture(); for (const identity of [f.p.partner, f.p.qc]) { const before = copy(f.root); assert.deepEqual(f.writePhotos({ present: true, value: { forged: 'SYNTHETIC_FORGED' } }, { identity }), { ok: false, error: 'access_denied' }); assert.deepEqual(f.root, before); } });
test('photo changes require current working and photo revisions without silently rebasing', () => { const f = fixture(); for (const changes of [{ expectedWorkingRevision: 2 }, { expectedPhotoRevision: 2 }]) assert.deepEqual(f.writePhotos({ present: false }, changes), { ok: false, error: 'conflict' }); assert.deepEqual(f.rollback().nextRoot, f.before); });
test('photo-only update preserves all working data and rollback restores the latest photo state', () => { const f = fixture(), beforeWork = copy(f.s.working), photo = f.writePhotos({ present: true, value: { 'Renamed.Model': 'SYNTHETIC_REPLACEMENT', unknown: { nested: true } } }); assert.equal(photo.ok, true); assert.deepEqual(photo.authorization, { ownerUid: 'owner-1', grantRevision: 1, workingRevision: 1 }); assert.equal(photo.nextPhotos.revision, 2); f.s.photos = copy(photo.nextPhotos); assert.deepEqual(f.s.working, beforeWork); const restored = f.rollback(); assert.equal(restored.ok, true); const expected = copy(f.before); expected.soldier.produksi.images = JSON.parse(photo.nextPhotos.data).value; assert.deepEqual(restored.nextRoot, expected); });
test('owner removal of an image branch retains absence instead of inventing an empty map', () => { const f = fixture(), removed = f.writePhotos({ present: false }); assert.equal(removed.ok, true); assert.deepEqual(JSON.parse(removed.nextPhotos.data), { present: false }); f.s.photos = copy(removed.nextPhotos); assert.equal(Object.hasOwn(f.rollback().nextRoot.soldier.produksi, 'images'), false); const added = f.writePhotos({ present: true, value: null }); assert.equal(added.ok, true); f.s.photos = copy(added.nextPhotos); assert.equal(f.rollback().nextRoot.soldier.produksi.images, null); });
test('rollback requires a whole-root conditional token and carries no guessed historical snapshot', () => { const f = fixture(), work = JSON.parse(f.s.working.data); work.unknownRootBranch = { newest: true }; f.s.working = copy(f.writeWork(work).nextWorking); const rollback = f.rollback(); assert.equal(rollback.expectedRootETag, '"synthetic-root-current"'); assert.equal(rollback.nextRoot.unknownRootBranch.newest, true); for (const tag of ['', 'null_etag', '"s"\r\nAuthorization:secret', 'https://foreign.invalid']) assert.deepEqual(Scope.prepareProtectedRollback({ protectedRoot: f.root, expectedRootETag: tag }), { ok: false, error: 'invalid_request' }); });
test('invalid selectors cannot choose storage paths, other schemas, identities or credentials', () => { const f = fixture(); for (const extra of [{ path: '/foreign' }, { secret: 'SYNTHETIC_SECRET' }, { migrationId: 'foreign' }, { role: 'owner' }]) assert.deepEqual(f.api.prepareWorkingWrite({ working: f.s.working, nextRoot: JSON.parse(f.s.working.data), expectedRevision: 1, ...extra }), { ok: false, error: 'invalid_request' }); });
test('results are immutable and byte-safe copies rather than aliases of caller data', () => { const f = fixture(), next = JSON.parse(f.s.working.data); next.newUnknown = { retain: [1, null, 'synthetic'] }; const proposed = f.writeWork(next); assert.equal(proposed.ok, true); next.newUnknown.retain[0] = 2; assert.equal(f.api.readWorking({ working: proposed.nextWorking }).root.newUnknown.retain[0], 1); assert.equal(Object.isFrozen(f.api.readWorking({ working: proposed.nextWorking }).root.newUnknown.retain), true); assert.deepEqual(f.rollback().nextRoot, f.before); });
test('revision overflow and unsupported image states fail without manufacturing data', () => { const f = fixture(), w = copy(f.s.working); w.revision = Number.MAX_SAFE_INTEGER; assert.deepEqual(f.api.prepareWorkingWrite({ working: w, nextRoot: JSON.parse(w.data), expectedRevision: w.revision }), { ok: false, error: 'capacity_limit' }); for (const images of [{ present: false, value: {} }, { present: 'true', value: {} }, { present: true }, { present: false, path: 'other' }]) assert.equal(f.writePhotos(images).ok, false); });
test('working payload stays below its enforced cap after JSON rendering', () => { const f = fixture(), root = JSON.parse(f.s.working.data); root.unicodePadding = '😀'.repeat(100000); const proposed = f.writeWork(root); assert.equal(proposed.ok, true); assert.ok(Buffer.byteLength(Snapshot.serializeLegacyRoot(proposed.nextWorking), 'utf8') <= Scope.MAX_WORKING_BYTES); assert.deepEqual(f.api.readWorking({ working: proposed.nextWorking }).root, root); });
test('strict stored text rejects duplicate or escaped-alias keys, whitespace and alternate numbers even with the original valid digest', () => { const f = fixture(); for (const text of [f.s.working.data.replace('"soldier":', '"soldier":null,"soldier":'), f.s.working.data.replace('"soldier":', '"soldier":null,"\\u0073oldier":'), ' ' + f.s.working.data, f.s.working.data.replace('"jumlah":8', '"jumlah":8.0')]) { assert.notEqual(text, f.s.working.data); const w = copy(f.s.working); w.data = text; assert.deepEqual(f.api.readWorking({ working: w }), { ok: false, error: 'not_ready' }); } });
test('stored scalar text preserves null and empty legacy collections through a null-pruning database wire roundtrip', () => {
  // Firebase removes null nodes and empty trees. The protected wire structure
  // has nonempty metadata and scalar JSON text; its business content is never
  // sent as independently prunable child nodes.
  const prune = v => { if (v === null) return undefined; if (!v || typeof v !== 'object') return v; const out = {}; for (const [k, value] of Object.entries(v)) { const next = prune(value); if (next !== undefined) out[k] = next; } return Object.keys(out).length ? out : undefined; };
  const f = fixture(), root = copy(f.before); root.unknownNull = null; root.emptyArray = []; root.emptyMap = {}; root.denseNulls = [null, { field: null, empty: [] }]; root.soldier.produksi.images = null;
  const migrated = Scope.prepareProtectedMigration({ root, binding: f.p.binding, migrationId: 'migration-null-wire', expectedRootETag: '"wire"' }); assert.equal(migrated.ok, true); const wire = prune(JSON.parse(JSON.stringify(migrated.nextRoot))); assert.deepEqual(wire, migrated.nextRoot); const restored = Scope.prepareProtectedRollback({ protectedRoot: wire, expectedRootETag: '"wire-current"' }); assert.deepEqual(restored.nextRoot, root);
  for (const value of [{}, [], [null], { image: 'SYNTHETIC_IMAGE', unknown: null }]) { const candidate = copy(root); candidate.soldier.produksi.images = value; const plan = Scope.prepareProtectedMigration({ root: candidate, binding: f.p.binding, migrationId: 'migration-null-wire', expectedRootETag: '"wire"' }); assert.equal(plan.ok, true); assert.deepEqual(Scope.prepareProtectedRollback({ protectedRoot: prune(copy(plan.nextRoot)), expectedRootETag: '"wire-current"' }).nextRoot, candidate); }
});
