'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Service=require('../server/production-legacy-operations-service.cjs'),Core=require('../server/production-legacy-operations.cjs'),State=require('../server/production-identity-state.cjs');
const F=require('./fixtures/identity-tenant.cjs');
const POLICY={version:'legacy-jahit-current-v1',reviewed:true,timeZone:'Asia/Jakarta',quantityBasis:'good-plus-reject'},TOKEN='synthetic.session.token';
function rootFixture(){return {authorityTenants:{[F.TENANT]:F.copy(F.claimed())},soldier:{produksi:{produksi:[{id:'product-1',series:'Synthetic',namaBarang:'Shirt',size:'M',poAktif:true,poJumlah:20,poTanggal:'2026-10-01',assignJahit:[{id:'assignment-1',tukangId:'worker-1',qty:20,sisa:16}],jahit:[{id:'old-operation',tanggal:'2026-10-01',jumlah:4,lolos:3,rijek:1,tukangId:'worker-1',assignmentId:'assignment-1',tarif:10,total:999.75,dibayar:true}],arsip:[]}]},produksi_meta:{tukangJahit:[{id:'worker-1',nama:'Synthetic Partner',tarif:{'Synthetic|Shirt':12.5}},{id:'worker-2',nama:'Other Partner',tarif:{'Synthetic|Shirt':20}}]},otherModule:{preserved:'synthetic private owner-only canary'}},unrelatedRoot:{preserved:true}};}
function fixture(){
  let root=rootFixture(),time=F.NOW;const stats={verify:0,users:0,reads:0,transactions:0,callbacks:0,writes:0,on:0,off:0,admit:0},hooks={},scopes=[];
  const app={options:{projectId:F.PROJECT,databaseURL:F.URL}},reference={toString:()=>F.URL+'/',get:async()=>{stats.reads++;if(hooks.get)await hooks.get(stats.reads);return snapshot(root);},on(type,listener,failed){assert.equal(type,'value');stats.on++;if(hooks.on)return hooks.on(listener,failed);queueMicrotask(()=>listener(snapshot(root)));},off(type,listener){assert.equal(type,'value');assert.equal(typeof listener,'function');stats.off++;if(hooks.off)hooks.off();},transaction:async(updater,completion,applyLocally)=>{
    assert.equal(completion,undefined);assert.equal(applyLocally,false);stats.transactions++;if(hooks.beforeTransaction)await hooks.beforeTransaction();
    stats.callbacks++;let next=updater(F.copy(root));if(hooks.retry&&next!==undefined){hooks.retry();stats.callbacks++;next=updater(F.copy(root));}
    if(next===undefined)return {committed:false,snapshot:snapshot(root)};
    root=Core.copyLegacyRoot(next);stats.writes++;const committed=snapshot(root);if(hooks.afterCommit)await hooks.afterCommit();if(hooks.lostAck)throw Error('SYNTHETIC_PRIVATE_ACK');
    return hooks.response?hooks.response({committed:true,snapshot:committed}):{committed:true,snapshot:committed};
  }};
  function snapshot(value){const captured=F.copy(value);return {ref:reference,val:()=>F.copy(captured)};}
  const database={app,ref(path){assert.equal(path,'');return reference;}},token={uid:'partner-1',sub:'partner-1',aud:F.PROJECT,iss:'https://securetoken.google.com/'+F.PROJECT,email:F.EMAIL,email_verified:true,auth_time:Math.floor(Date.parse(F.NOW)/1000)-3600,iat:Math.floor(Date.parse(F.NOW)/1000)-1,exp:Math.floor(Date.parse(F.NOW)/1000)+3600,firebase:{sign_in_provider:'google.com',identities:{'google.com':['1000123456789']}}},user={uid:'partner-1',disabled:false,emailVerified:true,email:F.EMAIL,providerData:[{providerId:'google.com',uid:'1000123456789',email:F.EMAIL}]};
  const auth={app,verifyIdToken:async(value,checkRevoked)=>{assert.equal(value,TOKEN);assert.equal(checkRevoked,true);stats.verify++;if(hooks.verify)await hooks.verify(stats.verify);return F.copy(token);},getUser:async uid=>{assert.equal(uid,token.uid);stats.users++;if(hooks.user)await hooks.user(stats.users);return F.copy(user);}};
  const options={enabled:true,projectId:F.PROJECT,databaseURL:F.URL,tenantId:F.TENANT,database,auth,tariffPolicy:F.copy(POLICY),clock:()=>{if(hooks.clock)hooks.clock();return time;},admit:async q=>{stats.admit++;scopes.push(q);if(hooks.admit)return hooks.admit(q);return true;}};
  const core=Core.createProductionLegacyOperations({enabled:true,binding:{projectId:F.PROJECT,databaseURL:F.URL,tenantId:F.TENANT},clock:()=>time,tariffPolicy:POLICY}),view=core.read({root,identity:F.identity()});assert.equal(view.ok,true);
  const command={kind:'appendJahit',requestId:'request-1',operationId:'operation-1',productId:'product-1',assignmentId:'assignment-1',expectedGrantRevision:1,expectedSourceVersion:view.view.products[0].sourceVersion,workDate:null,good:2,reject:1};
  return {stats,hooks,scopes,app,database,auth,reference,token,user,options,command,core,create:()=>Service.createProductionLegacyOperationsService(options),input:()=>({idToken:TOKEN,command:F.copy(command)}),get root(){return root;},set root(v){root=F.copy(v);},setTime(v){time=v;}};
}
const noDetails=r=>{assert.equal(r.ok,false);assert.equal(Object.hasOwn(r,'view'),false);assert.equal(Object.hasOwn(r,'next'),false);assert.equal(Object.hasOwn(r,'receipt'),false);assert.equal(JSON.stringify(r).includes('PRIVATE'),false);};
function revoke(f){f.root={...f.root,authorityTenants:{[F.TENANT]:State.revokeIdentityEnrollment(f.root.authorityTenants[F.TENANT],F.revokeCommand(),F.NOW).next}};}
test('OFF does not inspect request/options/SDK getters or initialize dependencies',async()=>{let touched=0;const options={enabled:false};for(const k of ['auth','database','clock','tariffPolicy','admit'])Object.defineProperty(options,k,{get(){touched++;throw Error('PRIVATE');}});const raw={get idToken(){touched++;throw Error('PRIVATE');}},service=Service.createProductionLegacyOperationsService(options);for(const method of ['read','execute','resolve'])assert.deepEqual(await service[method](raw),{ok:false,error:'service_disabled'});assert.equal(touched,0);});
test('ordinary older Google authentication reads scoped quantities without financial source or receipt leakage',async()=>{const f=fixture(),r=await f.create().read({idToken:TOKEN});assert.equal(r.ok,true);assert.equal(r.view.binding.workerId,'worker-1');assert.equal(r.view.products[0].assignments[0].remaining,16);assert.equal(JSON.stringify(r).includes('999.75'),false);assert.equal(JSON.stringify(r).includes('Other Partner'),false);assert.equal(JSON.stringify(r).includes('owner-only canary'),false);assert.equal(f.stats.transactions,0);assert.equal(f.stats.writes,0);assert.equal(f.stats.verify,2);assert.deepEqual(f.scopes,[{projectId:F.PROJECT,uid:'partner-1'}]);});
test('fixed root CAS writes one compatible report and durable external receipt while preserving old money and other modules',async()=>{const f=fixture(),before=F.copy(f.root),r=await f.create().execute(f.input());assert.deepEqual(r,{ok:true,replayed:false,operationId:'operation-1'});assert.equal(f.stats.transactions,1);assert.equal(f.stats.writes,1);assert.equal(f.stats.on,1);assert.equal(f.stats.off,1);assert.deepEqual(f.root.soldier.produksi.produksi[0].jahit[0],before.soldier.produksi.produksi[0].jahit[0]);assert.deepEqual(f.root.soldier.otherModule,before.soldier.otherModule);assert.deepEqual(f.root.unrelatedRoot,before.unrelatedRoot);assert.deepEqual(f.root.authorityTenants,before.authorityTenants);const row=f.root.soldier.produksi.produksi[0].jahit[1];assert.equal(row.total,25);assert.equal(row.tarif,12.5);assert.equal(row.quantityBasis,'good-plus-reject');assert.equal(row.jumlah,3);assert.ok(f.root.legacyOperationReceipts[F.TENANT].commands['request-1']);assert.equal(JSON.stringify(r).includes('googleSubject'),false);});
test('execute retry and readonly resolve retain the exact request and create no duplicate report',async()=>{const f=fixture(),s=f.create();assert.equal((await s.execute(f.input())).replayed,false);assert.deepEqual(await s.execute(f.input()),{ok:true,replayed:true,operationId:'operation-1'});const before=JSON.stringify(f.root);assert.deepEqual(await s.resolve(f.input()),{ok:true,replayed:true,operationId:'operation-1'});assert.equal(JSON.stringify(f.root),before);assert.equal(f.stats.transactions,1);assert.equal(f.stats.writes,1);});
test('lost acknowledgement is result_unknown and readonly resolve confirms only the matching retained command',async()=>{const f=fixture(),s=f.create();f.hooks.lostAck=true;assert.deepEqual(await s.execute(f.input()),{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(f.stats.writes,1);delete f.hooks.lostAck;assert.deepEqual(await s.resolve(f.input()),{ok:true,replayed:true,operationId:'operation-1'});const changed=f.input();changed.command.good=3;assert.deepEqual(await s.resolve(changed),{ok:false,error:'conflict'});assert.equal(f.stats.writes,1);});
test('missing durable receipt cannot be synthesized by resolve',async()=>{const f=fixture(),before=JSON.stringify(f.root);assert.deepEqual(await f.create().resolve(f.input()),{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(JSON.stringify(f.root),before);assert.equal(f.stats.transactions,0);});
test('caller worker/rate/total/UID/source/version fields and descriptor getters are rejected before writes',async()=>{for(const [k,v]of [['workerId','worker-2'],['rate',1],['total',0],['uid','owner-1'],['source','soldier'],['snapshotVersion','old']]){const f=fixture(),q=f.input();q.command[k]=v;noDetails(await f.create().execute(q));assert.equal(f.stats.transactions,0);}let touched=0;const f=fixture(),q=f.input();Object.defineProperty(q.command,'good',{enumerable:true,get(){touched++;return 2;}});assert.deepEqual(await f.create().execute(q),{ok:false,error:'invalid_request'});assert.equal(touched,0);assert.equal(f.stats.verify,0);});
test('disabled, revoked token, wrong provider, subject/project/UID and timing fail before quota or CAS',async()=>{for(const mutate of [f=>f.user.disabled=true,f=>f.token.firebase.sign_in_provider='password',f=>f.token.firebase.identities['google.com'][0]='other-subject',f=>f.token.aud='demo-other',f=>f.token.sub='other-user',f=>f.token.exp=Math.floor(Date.parse(F.NOW)/1000),f=>f.hooks.verify=()=>{throw Error('PRIVATE_AUTH');}]){const f=fixture();mutate(f);assert.deepEqual(await f.create().execute(f.input()),{ok:false,error:'access_denied'});assert.equal(f.stats.admit,0);assert.equal(f.stats.transactions,0);}});
test('owner/QC/orphan/revoked current v2 grants do not authorize compatible production writes',async()=>{for(const mutate of [f=>{f.token.uid='owner-1';f.token.sub='owner-1';f.user.uid='owner-1';},f=>{const r=f.root;r.authorityTenants[F.TENANT].grants['partner-1'].profile.workerId='worker-2';f.root=r;},f=>{const r=f.root;r.authorityTenants[F.TENANT]=State.claimIdentityEnrollment(r.authorityTenants[F.TENANT],F.identity({uid:'qc-1',email:F.QC_EMAIL,googleSubject:'qc-subject'}),F.NOW).next;f.root=r;f.token.uid=f.token.sub=f.user.uid='qc-1';f.token.email=f.user.email=f.user.providerData[0].email=F.QC_EMAIL;f.token.firebase.identities['google.com'][0]=f.user.providerData[0].uid='qc-subject';},revoke]){const f=fixture();mutate(f);noDetails(await f.create().execute(f.input()));assert.equal(f.stats.transactions,0);}});
test('admission uses only verified private UID and cannot grant authority or allow changed v2 context',async()=>{const denied=fixture();denied.hooks.admit=()=>false;assert.deepEqual(await denied.create().execute(denied.input()),{ok:false,error:'rate_limited'});assert.equal(denied.stats.transactions,0);const changed=fixture();changed.hooks.admit=q=>{assert.deepEqual(Object.keys(q),['projectId','uid']);assert.ok(Object.isFrozen(q));revoke(changed);return true;};noDetails(await changed.create().execute(changed.input()));assert.equal(changed.stats.writes,0);});
test('root CAS rechecks grant and expected source after races and safely aborts invalid callbacks',async()=>{for(const mutate of [revoke,f=>{const r=f.root;r.soldier.produksi.produksi[0].assignJahit[0].qty=1;f.root=r;},f=>{const r=f.root;r.soldier.produksi.produksi[0].poAktif=false;f.root=r;}]){const f=fixture();f.hooks.beforeTransaction=()=>mutate(f);noDetails(await f.create().execute(f.input()));assert.equal(f.stats.writes,0);assert.equal(f.stats.transactions,1);assert.equal(f.stats.off,1);}});
test('CAS retries validate latest root and preserve unrelated legitimate changes',async()=>{const f=fixture();f.hooks.retry=()=>{const r=f.root;r.unrelatedRoot.reviewed=true;f.root=r;};assert.deepEqual(await f.create().execute(f.input()),{ok:true,replayed:false,operationId:'operation-1'});assert.equal(f.stats.callbacks,2);assert.equal(f.root.unrelatedRoot.reviewed,true);assert.equal(f.stats.writes,1);});
test('private scope, shared app/root URL or method drift closes the adapter before dispatch',async()=>{for(const mutate of [f=>f.auth.app={options:{projectId:F.PROJECT,databaseURL:F.URL}},f=>f.app.options.projectId='demo-other',f=>f.app.options.databaseURL='https://demo-other.firebaseio.com',f=>f.reference.toString=()=>F.URL+'/soldier']){const f=fixture();mutate(f);assert.deepEqual(await f.create().execute(f.input()),{ok:false,error:'unavailable'});assert.equal(f.stats.verify,0);assert.equal(f.stats.transactions,0);}});
test('SDK snapshot paths and method drift after awaited reads reject all private data',async()=>{for(const mutate of [f=>f.reference.toString=()=>F.URL+'/soldier',f=>f.database.ref=()=>f.reference,f=>f.auth.getUser=async()=>f.user]){const f=fixture(),s=f.create();f.hooks.get=n=>{if(n===1)mutate(f);};noDetails(await s.read({idToken:TOKEN}));assert.equal(f.stats.transactions,0);}});
test('warm listener failure never dispatches root CAS and private errors remain fixed',async()=>{const f=fixture();f.hooks.on=(_listener,failed)=>failed(Error('PRIVATE_LISTENER'));assert.deepEqual(await f.create().execute(f.input()),{ok:false,error:'unavailable'});assert.equal(f.stats.transactions,0);assert.equal(f.stats.off,1);});
test('malformed ACK or post-commit Auth/catalog changes remain unknown rather than falsely unsaved',async()=>{for(const mutate of [f=>f.hooks.response=()=>({committed:'true'}),f=>f.hooks.afterCommit=()=>{f.user.disabled=true;},f=>f.hooks.afterCommit=()=>{const r=f.root;r.authorityTenants[F.TENANT].workerCatalog.revision=2;f.root=r;}]){const f=fixture();mutate(f);assert.deepEqual(await f.create().execute(f.input()),{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(f.stats.writes,1);}});
test('expiry or clock reversal across callbacks cannot dispatch or disclose a result',async()=>{const expired=fixture();expired.hooks.admit=()=>{expired.setTime(F.AFTER);return true;};noDetails(await expired.create().execute(expired.input()));assert.equal(expired.stats.transactions,0);const reverse=fixture();reverse.hooks.get=()=>reverse.setTime(F.BEFORE);noDetails(await reverse.create().read({idToken:TOKEN}));assert.equal(reverse.stats.transactions,0);});
test('one unresolved operation keeps local capacity and prevents overlapping read/write/resolve',async()=>{const f=fixture(),s=f.create();let release;f.hooks.beforeTransaction=()=>new Promise(r=>release=r);const first=s.execute(f.input());while(!release)await new Promise(r=>setImmediate(r));for(const method of ['read','execute','resolve'])assert.deepEqual(await s[method](method==='read'?{idToken:TOKEN}:f.input()),{ok:false,error:'busy'});release();assert.equal((await first).ok,true);});
test('strict whole-root budget and unsafe descriptors reject without replacing existing source',async()=>{const large=fixture(),r=large.root;r.unrelatedRoot.tooLarge='x'.repeat(Core.MAX_ROOT_BYTES);large.root=r;noDetails(await large.create().execute(large.input()));assert.equal(large.stats.transactions,0);const f=fixture();f.reference.get=async()=>({ref:f.reference,val:()=>{const root=rootFixture();Object.defineProperty(root.unrelatedRoot,'private',{enumerable:true,get(){throw Error('PRIVATE');}});return root;}});noDetails(await f.create().execute(f.input()));assert.equal(f.stats.transactions,0);});
test('Database/Auth emulator environment is rejected before dispatch and if changed while warm',async()=>{for(const key of ['FIREBASE_DATABASE_EMULATOR_HOST','FIREBASE_AUTH_EMULATOR_HOST']){const prior=process.env[key];try{process.env[key]='127.0.0.1:9099';const f=fixture();assert.deepEqual(await f.create().execute(f.input()),{ok:false,error:'unavailable'});assert.equal(f.stats.verify,0);delete process.env[key];const warm=fixture(),s=warm.create();warm.hooks.on=listener=>{process.env[key]='127.0.0.1:9099';listener();};noDetails(await s.execute(warm.input()));assert.equal(warm.stats.transactions,0);}finally{if(prior===undefined)delete process.env[key];else process.env[key]=prior;}}});
test('unsupported tariff policy, config accessors and caller-selected extra options cannot open the root reference',async()=>{for(const mutate of [f=>f.options.tariffPolicy.reviewed=false,f=>f.options.tariffPolicy.timeZone='UTC',f=>f.options.tariffPolicy.quantityBasis='good-only',f=>f.options.tariffPolicy.version='other',f=>f.options.testOnlyEmulator=true]){const f=fixture();let refs=0;f.database.ref=()=>{refs++;return f.reference;};mutate(f);assert.deepEqual(await f.create().execute(f.input()),{ok:false,error:'unavailable'});assert.equal(refs,0);}const f=fixture();let touched=0;Object.defineProperty(f.options,'tariffPolicy',{enumerable:true,get(){touched++;throw Error('PRIVATE_POLICY');}});assert.deepEqual(await f.create().read({idToken:TOKEN}),{ok:false,error:'unavailable'});assert.equal(touched,0);});
test('trusted clock drift is checked before dispatching Auth or root methods',async()=>{const f=fixture(),s=f.create();f.hooks.clock=()=>{f.app.options.projectId='demo-other';};assert.deepEqual(await s.execute(f.input()),{ok:false,error:'unavailable'});assert.equal(f.stats.verify,0);assert.equal(f.stats.reads,0);});
test('wrong SDK snapshot root URL rejects reads and a wrong committed URL makes the write unknown',async()=>{const read=fixture();read.reference.get=async()=>({ref:{toString:()=>F.URL+'/soldier'},val:()=>rootFixture()});noDetails(await read.create().read({idToken:TOKEN}));const write=fixture();write.hooks.response=r=>({...r,snapshot:{...r.snapshot,ref:{toString:()=>F.URL+'/soldier'}}});assert.deepEqual(await write.create().execute(write.input()),{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(write.stats.writes,1);});
test('retained operation tamper cannot resolve or replay an existing write as a different result',async()=>{const f=fixture(),s=f.create();assert.equal((await s.execute(f.input())).ok,true);const r=f.root;r.soldier.produksi.produksi[0].jahit[1].total=777;f.root=r;assert.deepEqual(await s.resolve(f.input()),{ok:false,error:'conflict'});assert.deepEqual(await s.execute(f.input()),{ok:false,error:'conflict'});assert.equal(f.stats.writes,1);});
test('fresh final Auth or grant revocation during a read discards all late operational fields',async()=>{for(const mutate of [f=>f.hooks.verify=n=>{if(n===2)throw Error('PRIVATE_FINAL_AUTH');},f=>f.hooks.admit=()=>{revoke(f);return true;}]){const f=fixture();mutate(f);noDetails(await f.create().read({idToken:TOKEN}));assert.equal(f.stats.writes,0);}});
test('grant revocation after a real CAS cannot turn the committed report into a claimed failure',async()=>{const f=fixture();f.hooks.afterCommit=()=>revoke(f);assert.deepEqual(await f.create().execute(f.input()),{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(f.stats.writes,1);assert.equal(f.root.soldier.produksi.produksi[0].jahit[1].id,'operation-1');});
test('request payload and reviewed policy are captured before asynchronous callbacks',async()=>{const f=fixture(),s=f.create(),q=f.input();let release;f.hooks.beforeTransaction=()=>new Promise(r=>release=r);const pending=s.execute(q);while(!release)await new Promise(r=>setImmediate(r));q.command.good=999;f.options.tariffPolicy.quantityBasis='caller-edited';release();assert.deepEqual(await pending,{ok:true,replayed:false,operationId:'operation-1'});assert.equal(f.root.soldier.produksi.produksi[0].jahit[1].lolos,2);});
test('credential-file/token override presence cannot redirect the isolated SDK adapter',async()=>{for(const key of ['GOOGLE_APPLICATION_CREDENTIALS','FIREBASE_TOKEN','GOOGLE_OAUTH_ACCESS_TOKEN','CLOUDSDK_AUTH_ACCESS_TOKEN','CLOUDSDK_AUTH_ACCESS_TOKEN_FILE','CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE','CLOUDSDK_AUTH_IMPERSONATE_SERVICE_ACCOUNT']){const prior=process.env[key];try{process.env[key]='synthetic-presence-only';const f=fixture();assert.deepEqual(await f.create().execute(f.input()),{ok:false,error:'unavailable'});assert.equal(f.stats.verify,0);assert.equal(f.stats.reads,0);}finally{if(prior===undefined)delete process.env[key];else process.env[key]=prior;}}});
test('warm cache timeout is bounded and never invokes a root transaction',async()=>{const f=fixture();f.hooks.on=()=>{};assert.deepEqual(await f.create().execute(f.input()),{ok:false,error:'unavailable'});assert.equal(f.stats.transactions,0);assert.equal(f.stats.off,1);});
test('acknowledgment object key order is semantic and cannot strand a successful equal root',async()=>{const reverse=v=>{if(v===null||typeof v!=='object')return v;if(Array.isArray(v))return v.map(reverse);return Object.fromEntries(Object.entries(v).reverse().map(([k,x])=>[k,reverse(x)]));};const f=fixture();f.hooks.response=r=>({...r,snapshot:{ref:f.reference,val:()=>reverse(r.snapshot.val())}});assert.deepEqual(await f.create().execute(f.input()),{ok:true,replayed:false,operationId:'operation-1'});assert.equal(f.stats.writes,1);});
test('only SDK snapshot and CAS numeric-array holes become explicit null placeholders',async()=>{const f=fixture(),source=f.root;source.unrelatedRoot.sdkNumeric=[{keep:'first'},null,{keep:'third'}];f.root=source;const holey=()=>{const r=F.copy(f.root);delete r.unrelatedRoot.sdkNumeric[1];return r;};f.reference.get=async()=>({ref:f.reference,val:holey});f.reference.transaction=async updater=>{f.stats.transactions++;const next=updater(holey());assert.notEqual(next,undefined);f.root=next;f.stats.writes++;return {committed:true,snapshot:{ref:f.reference,val:holey}};};const s=f.create();assert.deepEqual(await s.execute(f.input()),{ok:true,replayed:false,operationId:'operation-1'});assert.deepEqual(f.root.unrelatedRoot.sdkNumeric,[{keep:'first'},null,{keep:'third'}]);assert.deepEqual(await s.resolve(f.input()),{ok:true,replayed:true,operationId:'operation-1'});const q=f.input();q.command.good=[1,,2];assert.deepEqual(await s.execute(q),{ok:false,error:'invalid_request'});assert.equal(f.stats.writes,1);});
test('emulator opt-in cannot accept another project/origin/host, Auth emulator or arbitrary credential function',async()=>{const prior=process.env.FIREBASE_DATABASE_EMULATOR_HOST;try{process.env.FIREBASE_DATABASE_EMULATOR_HOST='127.0.0.1:9000';for(const mutate of [f=>f.options.testOnlyEmulator='true',f=>f.options.testOnlyEmulator=true]){const f=fixture();mutate(f);assert.deepEqual(await f.create().execute(f.input()),{ok:false,error:'unavailable'});assert.equal(f.stats.verify,0);}const f=fixture();f.options.projectId=f.app.options.projectId='demo-soldier-security';f.options.databaseURL=f.app.options.databaseURL='https://demo-soldier-security.firebaseio.com';f.options.testOnlyEmulator=true;f.app.options.credential={getAccessToken:async()=>({access_token:'arbitrary',expires_in:3600})};assert.deepEqual(await f.create().execute(f.input()),{ok:false,error:'unavailable'});assert.equal(f.stats.verify,0);}finally{if(prior===undefined)delete process.env.FIREBASE_DATABASE_EMULATOR_HOST;else process.env.FIREBASE_DATABASE_EMULATOR_HOST=prior;}});
test('pinned demo hook accepts only its fixed fake credential and latches replacement identity',async()=>{const prior=process.env.FIREBASE_DATABASE_EMULATOR_HOST;try{process.env.FIREBASE_DATABASE_EMULATOR_HOST='127.0.0.1:9000';const f=fixture(),project='demo-soldier-security';f.options.projectId=f.app.options.projectId=f.token.aud=project;f.token.iss='https://securetoken.google.com/'+project;f.options.databaseURL=f.app.options.databaseURL='https://'+project+'.firebaseio.com';f.options.testOnlyEmulator=true;f.app.options.credential={getAccessToken:async()=>({access_token:'owner',expires_in:3600})};f.reference.toString=()=> 'http://127.0.0.1:9000/';const r=f.root;r.authorityTenants[F.TENANT].projectId=project;f.root=r;const s=f.create();assert.equal((await s.read({idToken:TOKEN})).ok,true);f.app.options.credential.getAccessToken=async()=>({access_token:'owner',expires_in:3600});assert.deepEqual(await s.read({idToken:TOKEN}),{ok:false,error:'unavailable'});assert.equal(f.stats.transactions,0);}finally{if(prior===undefined)delete process.env.FIREBASE_DATABASE_EMULATOR_HOST;else process.env.FIREBASE_DATABASE_EMULATOR_HOST=prior;}});
