'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Http=require('../server/production-http-handler.cjs'),Runtime=require('../server/production-runtime.cjs'),Deployment=require('../server/deployment/deployment-runtime.cjs');
const F=require('./fixtures/identity-tenant.cjs');
const ORIGIN='https://soldier.example.invalid',PATH='/v1/production/owner/access/revoke',RESOLVE='/v1/production/owner/access/resolve',TOKEN='synthetic.owner.token';
function request(command=F.revokeCommand(),url=PATH){const raw=Buffer.from(JSON.stringify({command})),headers={origin:ORIGIN,authorization:'Bearer '+TOKEN,'content-type':'application/json','content-length':String(raw.length)};return {method:'POST',url,headers,rawHeaders:Object.entries(headers).flat(),rawBody:raw};}
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},end(v){this.body=v===undefined?null:JSON.parse(v);this.writableEnded=true;}};}
async function run(f,req=request()){const res=response();await f.handler(req,res);return res;}
function fixture(extra={}){const calls=[],service={execute:async q=>{calls.push(['execute',q]);return {ok:true,replayed:false,approvalRevision:3,grantRevision:2};},resolve:async q=>{calls.push(['resolve',q]);return {ok:true,replayed:true,approvalRevision:3,grantRevision:2};}};const options={enabled:true,service:{execute:async()=>{throw Error('wrong-service');}},identityRevocationService:service,allowedOrigins:[ORIGIN],deadlineMs:1000,maxInFlight:1,...extra};return {calls,options,handler:Http.createProductionHttpHandler(options)};}
test('owner access paths expose exact minimal receipts and forward the same command internally',async()=>{const f=fixture();for(const path of [PATH,RESOLVE]){const r=await run(f,request(F.revokeCommand(),path));assert.equal(r.statusCode,200);assert.deepEqual(r.body,{ok:true,replayed:path===RESOLVE,approvalRevision:3,grantRevision:2});assert.equal(r.headers['Cache-Control'],'no-store');for(const value of [TOKEN,'approval-1','owner-1'])assert.equal(JSON.stringify(r).includes(value),false);}assert.deepEqual(f.calls.map(c=>c[0]),['execute','resolve']);assert.deepEqual(f.calls[0][1],{idToken:TOKEN,command:F.revokeCommand()});});
test('pending approval commands omit grant revision in both request and result',async()=>{const command={requestId:'pending-1',approvalId:'approval-1',expectedApprovalRevision:1};const f=fixture({identityRevocationService:{execute:async()=>({ok:true,replayed:false,approvalRevision:2}),resolve:async()=>({ok:true,replayed:true,approvalRevision:2})}});for(const path of [PATH,RESOLVE])assert.deepEqual((await run(f,request(command,path))).body,{ok:true,replayed:path===RESOLVE,approvalRevision:2});});
test('owner access paths stay unregistered without an explicit assembled service',async()=>{const f=fixture();delete f.options.identityRevocationService;const h={handler:Http.createProductionHttpHandler(f.options)};for(const path of [PATH,RESOLVE])assert.equal((await run(h,request(F.revokeCommand(),path))).statusCode,400);assert.equal(f.calls.length,0);});
test('body authority, scope selectors, reserved IDs and invalid revisions fail before service invocation',async()=>{for(const command of [{...F.revokeCommand(),owner:true},{...F.revokeCommand(),uid:'other'},{...F.revokeCommand(),workerId:'other'},{...F.revokeCommand(),tenantId:'other'},{...F.revokeCommand(),profile:{}},{...F.revokeCommand(),expectedApprovalRevision:0},{...F.revokeCommand(),expectedGrantRevision:1.5},{...F.revokeCommand(),requestId:'__proto__'},{...F.revokeCommand(),approvalId:'approval/path'}]){const f=fixture();assert.equal((await run(f,request(command))).statusCode,400);assert.equal(f.calls.length,0);}});
test('duplicate escaped keys, unexpected top-level fields, malformed UTF8 and oversized bodies fail before service',async()=>{for(const body of ['{"command":{},"command":{}}','{"command":{"requestId":"a","\\u0072equestId":"b"}}','{"command":{},"role":"owner"}','{}','[]',Buffer.from([0x7b,0xff,0x7d]),Buffer.alloc(32769,32)]){const f=fixture(),req=request();req.rawBody=Buffer.isBuffer(body)?body:Buffer.from(body);req.headers['content-length']=String(req.rawBody.length);req.rawHeaders=Object.entries(req.headers).flat();assert.equal((await run(f,req)).statusCode,400);assert.equal(f.calls.length,0);}});
test('query, origin, method, token, duplicate headers and compression reject before revocation',async()=>{for(const change of [r=>r.url=PATH+'?uid=other',r=>r.method='GET',r=>r.headers.origin='https://other.example.invalid',r=>r.headers.authorization='Bearer invalid',r=>r.rawHeaders.push('Authorization','Bearer other.token.value'),r=>r.headers['content-encoding']='gzip']){const f=fixture(),req=request();change(req);assert.ok([400,403,405].includes((await run(f,req)).statusCode));assert.equal(f.calls.length,0);}});
test('POST-only access preflights neither verify identity nor call the writer',async()=>{for(const url of [PATH,RESOLVE]){const f=fixture(),req=request(F.revokeCommand(),url);req.method='OPTIONS';req.headers={origin:ORIGIN,'access-control-request-method':'POST','access-control-request-headers':'Authorization, Content-Type'};req.rawHeaders=Object.entries(req.headers).flat();delete req.rawBody;assert.equal((await run(f,req)).statusCode,204);req.headers['access-control-request-method']='GET';req.rawHeaders=Object.entries(req.headers).flat();assert.equal((await run(f,req)).statusCode,400);assert.equal(f.calls.length,0);}});
test('changed receipt revisions, extraneous private metadata and command receipts never become success',async()=>{for(const result of [{ok:true,replayed:false,approvalRevision:4,grantRevision:2},{ok:true,replayed:false,approvalRevision:3,grantRevision:1},{ok:true,replayed:false,approvalRevision:3,grantRevision:2,email:'syntheticprivate@gmail.com'},{ok:true,replayed:false,approvalRevision:3},{ok:true,replayed:false,receipt:{requestId:'revoke-1',revision:3,acceptedAt:F.NOW}},null]){const f=fixture({identityRevocationService:{execute:async()=>result,resolve:async()=>result}});const r=await run(f);assert.equal(r.statusCode,503);assert.deepEqual(r.body,{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(JSON.stringify(r).includes('syntheticprivate'),false);}});
test('resolve requires a replayed receipt and cannot acknowledge a new mutation',async()=>{const f=fixture({identityRevocationService:{execute:async()=>({ok:true,replayed:false,approvalRevision:3,grantRevision:2}),resolve:async()=>({ok:true,replayed:false,approvalRevision:3,grantRevision:2})}});assert.equal((await run(f,request(F.revokeCommand(),RESOLVE))).body.error,'result_unknown');});
test('access service options, methods and returned metadata accessors are not invoked',async()=>{let touched=0;const options=fixture().options;Object.defineProperty(options,'identityRevocationService',{get(){touched++;throw Error('private');}});assert.equal((await run({handler:Http.createProductionHttpHandler(options)})).statusCode,503);const service={resolve:async()=>({ok:true})};Object.defineProperty(service,'execute',{get(){touched++;throw Error('private');}});assert.equal((await run(fixture({identityRevocationService:service}))).statusCode,503);const result={};Object.defineProperty(result,'ok',{enumerable:true,get(){touched++;throw Error('private');}});assert.equal((await run(fixture({identityRevocationService:{execute:async()=>result,resolve:async()=>result}}))).statusCode,503);assert.equal(touched,0);});
test('fixed errors and unknown committed outcomes disclose no private exception detail',async()=>{for(const [error,status]of [['access_denied',403],['invalid_request',400],['conflict',409],['not_ready',409],['rate_limited',429],['result_unknown',503],['unavailable',503]]){const result={ok:false,error,...(error==='result_unknown'?{retrySameCommand:true}:{})},f=fixture({identityRevocationService:{execute:async()=>result,resolve:async()=>result}});const r=await run(f);assert.equal(r.statusCode,status);assert.deepEqual(r.body,{ok:false,error,...(['result_unknown','unavailable'].includes(error)?{retrySameCommand:true}:{})});}const r=await run(fixture({identityRevocationService:{execute:async()=>{throw Error('PRIVATE_EXCEPTION_CANARY');},resolve:async()=>{throw Error('PRIVATE_EXCEPTION_CANARY');}}}));assert.equal(JSON.stringify(r).includes('PRIVATE_EXCEPTION_CANARY'),false);});
test('deadline and shared slot wait for actual settlement and require the same command',async()=>{let release;const p=new Promise(r=>release=r),f=fixture({deadlineMs:5,identityRevocationService:{execute:()=>p,resolve:()=>p}}),res=response(),first=f.handler(request(),res);await new Promise(r=>setTimeout(r,15));assert.equal(res.writableEnded,undefined);assert.deepEqual((await run(f,request(F.revokeCommand(),RESOLVE))).body,{ok:false,error:'busy',retrySameCommand:true});release({ok:true,replayed:false,approvalRevision:3,grantRevision:2});await first;assert.deepEqual(res.body,{ok:false,error:'result_unknown',retrySameCommand:true});});
test('disconnect retains the slot until settlement without sending a late receipt',async()=>{let release;const p=new Promise(r=>release=r),f=fixture({identityRevocationService:{execute:()=>p,resolve:()=>p}}),res=response(),first=f.handler(request(),res);res.destroyed=true;assert.equal((await run(f)).body.error,'busy');release({ok:true,replayed:false,approvalRevision:3,grantRevision:2});await first;assert.equal(res.writableEnded,undefined);});
const PROJECT='soldier-revocation-proof',URL='https://'+PROJECT+'.firebaseio.com';
const config=()=>({enabled:true,projectId:PROJECT,databaseURL:URL,tenantId:'synthetic-tenant',allowedOrigins:[ORIGIN],serviceAccount:'soldier-production-runtime@'+PROJECT+'.iam.gserviceaccount.com'});
function deployment(configuration=config()){
 const stats={load:0,adc:0,init:0,forward:0},calls={},env={GOOGLE_CLOUD_PROJECT:PROJECT,GCLOUD_PROJECT:PROJECT,FUNCTION_TARGET:'soldierProduction',K_SERVICE:'soldierproduction'};
 const sdk={getApps:()=>[],applicationDefault:()=>{stats.adc++;return {};},initializeApp:(options,name)=>{stats.init++;return {options,name};},getDatabase:app=>({app}),getAuth:app=>({app})};
 const instance=Deployment.createDeployment({host:'functions',configuration,environment:()=>env,loadAdminSdk:()=>{stats.load++;return sdk;},createRuntime:options=>{calls.options=options;return {handler:async(_req,res)=>{stats.forward++;res.statusCode=200;res.end('{"ok":true}');}};}});return {...instance,stats,calls,env};
}
test('source OFF and absent, false or inherited owner controls never acquire ADC',async()=>{assert.equal(require('../server/deployment/configuration.cjs').identityRevocationEnabled,false);for(const configuration of [config(),{...config(),identityRevocationEnabled:false},Object.assign(Object.create({identityRevocationEnabled:true}),config())]){const f=deployment(configuration);for(const path of [PATH,RESOLVE])assert.ok([400,503].includes((await run(f,request(F.revokeCommand(),path))).statusCode));assert.equal(f.stats.load,0);}});
test('malformed or accessor source flags fail without invoking getters',async()=>{let touched=0;const accessor=config();Object.defineProperty(accessor,'identityRevocationEnabled',{enumerable:true,get(){touched++;return true;}});for(const c of [accessor,{...config(),identityRevocationEnabled:'true'}]){const f=deployment(c);assert.equal((await run(f)).statusCode,503);assert.equal(f.stats.load,0);}assert.equal(touched,0);});
test('disabled access gate rejects before body access and environment opt-in has no effect',async()=>{const f=deployment();f.env.IDENTITY_REVOCATION_ENABLED='true';let touched=0;const req=request();Object.defineProperty(req,'rawBody',{get(){touched++;throw Error('private');}});assert.equal(f.gate(req).status,400);assert.equal((await run(f,req)).statusCode,400);assert.equal(touched,0);assert.equal(f.stats.load,0);});
test('explicit trusted opt-in is snapshotted independently of enrollment and forwarded once',async()=>{const c={...config(),identityRevocationEnabled:true,enrollmentEnabled:false},f=deployment(c);c.identityRevocationEnabled=false;c.tenantId='foreign';for(const path of [PATH,RESOLVE])assert.equal((await run(f,request(F.revokeCommand(),path))).statusCode,200);assert.equal(f.calls.options.identityRevocationEnabled,true);assert.equal(f.calls.options.enrollmentEnabled,false);assert.equal(f.calls.options.tenantId,'synthetic-tenant');assert.equal(f.stats.init,1);});
test('opted-in access preflight is POST-only and handled without SDK loading',async()=>{for(const url of [PATH,RESOLVE]){const f=deployment({...config(),identityRevocationEnabled:true}),req=request(F.revokeCommand(),url);req.method='OPTIONS';req.headers={origin:ORIGIN,'access-control-request-method':'POST','access-control-request-headers':'authorization, content-type'};req.rawHeaders=Object.entries(req.headers).flat();delete req.rawBody;assert.equal((await run(f,req)).statusCode,204);req.headers['access-control-request-method']='GET';req.rawHeaders=Object.entries(req.headers).flat();assert.equal((await run(f,req)).statusCode,400);assert.equal(f.stats.load,0);}});
test('host binding failures retain exact same-command replay instruction',async()=>{const f=deployment({...config(),identityRevocationEnabled:true});f.env.GOOGLE_APPLICATION_CREDENTIALS='PRIVATE_CREDENTIAL_CANARY';for(const path of [PATH,RESOLVE]){const r=await run(f,request(F.revokeCommand(),path));assert.deepEqual(r.body,{ok:false,error:'unavailable',retrySameCommand:true});assert.equal(JSON.stringify(r).includes('PRIVATE_CREDENTIAL_CANARY'),false);}assert.equal(f.stats.adc,0);});
function runtimeFixture(){
 const root=new Map([['authorityTenants/'+F.TENANT,F.copy(F.claimed())]]),stats={auth:0,users:0,identityWrites:0,rateWrites:0},control={uid:'owner-1',subject:'owner-google-subject',disabled:false,loseAck:false};
 const app={options:{projectId:F.PROJECT,databaseURL:F.URL}},refs=new Map();
 const database={app,ref(path){if(refs.has(path))return refs.get(path);let reference;const snap=value=>({ref:reference,val:()=>F.copy(value)});reference={toString:()=>F.URL+'/'+path,get:async()=>snap(root.get(path)??null),on(_event,fn){queueMicrotask(()=>fn(snap(root.get(path)??null)));},off(){},async transaction(update){const next=update(F.copy(root.get(path)??null));if(next===undefined)return {committed:false,snapshot:snap(root.get(path)??null)};root.set(path,F.copy(next));if(path.startsWith('authorityTenants/')){stats.identityWrites++;if(control.loseAck){control.loseAck=false;throw Error('PRIVATE_LOST_ACK');}}else stats.rateWrites++;return {committed:true,snapshot:snap(next)};}};refs.set(path,reference);return reference;}};
 const seconds=Date.parse(F.NOW)/1000,auth={app,async verifyIdToken(token,revoked){stats.auth++;assert.equal(token,TOKEN);assert.equal(revoked,true);return {uid:control.uid,sub:control.uid,aud:F.PROJECT,iss:'https://securetoken.google.com/'+F.PROJECT,email:'syntheticowner@gmail.com',email_verified:true,auth_time:seconds-86400,iat:seconds-60,exp:seconds+3600,firebase:{sign_in_provider:'google.com',identities:{'google.com':[control.subject]}}};},async getUser(uid){stats.users++;return {uid,email:'syntheticowner@gmail.com',emailVerified:true,disabled:control.disabled,providerData:[{providerId:'google.com',uid:control.subject,email:'syntheticowner@gmail.com'}]};}};
 const options={enabled:true,identityRevocationEnabled:true,projectId:F.PROJECT,databaseURL:F.URL,tenantId:F.TENANT,database,auth,allowedOrigins:[ORIGIN],clock:()=>F.NOW,policy:{rateWindowMs:60000,rateLimit:30,deadlineMs:1000,maxInFlight:1}};return {root,stats,control,options};
}
test('real runtime default and accessor controls cannot invoke owner Auth or mutation',async()=>{for(const flag of [undefined,false]){const f=runtimeFixture();delete f.options.identityRevocationEnabled;if(flag!==undefined)f.options.identityRevocationEnabled=flag;assert.equal((await run(Runtime.createProductionRuntime(f.options))).statusCode,400);assert.equal(f.stats.auth,0);assert.equal(f.stats.identityWrites,0);}const f=runtimeFixture();let touched=0;Object.defineProperty(f.options,'identityRevocationEnabled',{enumerable:true,get(){touched++;return true;}});assert.equal((await run(Runtime.createProductionRuntime(f.options))).statusCode,503);assert.equal(touched,0);assert.equal(f.stats.auth,0);});
test('assembled ordinary owner session uses a shared private permit and retains canonical identity history',async()=>{const f=runtimeFixture(),before=F.copy(f.root.get('authorityTenants/'+F.TENANT)),instance=Runtime.createProductionRuntime(f.options),r=await run(instance);assert.equal(r.statusCode,200);assert.deepEqual(r.body,{ok:true,replayed:false,approvalRevision:3,grantRevision:2});assert.equal(f.stats.identityWrites,1);assert.equal(f.stats.rateWrites,1);const after=f.root.get('authorityTenants/'+F.TENANT);assert.equal(after.grants['partner-1'].profile.active,false);assert.deepEqual(after.initialization,before.initialization);assert.deepEqual(after.workerCatalog,before.workerCatalog);assert.deepEqual(after.enrollmentRegistry.approvals['approval-q'],before.enrollmentRegistry.approvals['approval-q']);assert.equal((await run(instance,request(F.revokeCommand(),RESOLVE))).body.replayed,true);assert.equal((await run(instance)).body.replayed,true);assert.equal(f.stats.identityWrites,1);assert.equal(f.stats.rateWrites,1);});
test('assembled lost acknowledgment resolves only the same retained command without another mutation',async()=>{const f=runtimeFixture(),instance=Runtime.createProductionRuntime(f.options);f.control.loseAck=true;assert.deepEqual((await run(instance)).body,{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal((await run(instance,request(F.revokeCommand(),RESOLVE))).statusCode,200);assert.equal(f.stats.identityWrites,1);assert.equal(f.stats.rateWrites,1);});
test('assembled partner, unknown or disabled owner cannot acquire a permit or revoke a grant',async()=>{for(const change of [f=>f.control.uid='partner-1',f=>f.control.uid='unknown-1',f=>f.control.disabled=true]){const f=runtimeFixture();change(f);const r=await run(Runtime.createProductionRuntime(f.options));assert.equal(r.statusCode,403);assert.equal(f.stats.identityWrites,0);assert.equal(f.stats.rateWrites,0);}});
test('assembled pending revocation retains owner-only grant set without granting a new account',async()=>{const f=runtimeFixture();f.root.set('authorityTenants/'+F.TENANT,F.copy(F.tenant()));const instance=Runtime.createProductionRuntime(f.options),r=await run(instance,request({requestId:'pending-1',approvalId:'approval-1',expectedApprovalRevision:1}));assert.equal(r.statusCode,200);assert.deepEqual(r.body,{ok:true,replayed:false,approvalRevision:2});assert.deepEqual(Object.keys(f.root.get('authorityTenants/'+F.TENANT).grants),['owner-1']);});
