'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const A=require('../server/apps-script/current-google-identity.cjs');
const Old=require('../server/production-enrollment-identity.cjs');
const NOW='2026-10-07T03:00:00.000Z',MS=Date.parse(NOW),SECOND=MS/1000,PROJECT='demo-current-identity',EMAIL='synthetic.current@gmail.com',UID='synthetic-firebase-uid',SUBJECT='synthetic-google-subject',KEY='SYNTHETIC_PUBLIC_PROJECT_KEY_000000000000';
const ENROLL=A.createAppsScriptEnrollmentGoogleIdentityVerifier,SESSION=A.createAppsScriptSessionGoogleIdentityVerifier;
const clone=v=>structuredClone(v),enc=v=>Buffer.from(typeof v==='string'?v:JSON.stringify(v),'utf8').toString('base64url');
function jwt(payload,header={alg:'RS256',kid:'synthetic-key',typ:'JWT'},signature=Buffer.alloc(256,19).toString('base64url')){return enc(header)+'.'+enc(payload)+'.'+signature;}
function fixture(){
  const state={clock:NOW,payload:{sub:UID,aud:PROJECT,iss:'https://securetoken.google.com/'+PROJECT,email:EMAIL,email_verified:true,firebase:{sign_in_provider:'google.com',identities:{'google.com':[SUBJECT]}},auth_time:SECOND-120,iat:SECOND-60,exp:SECOND+3540},record:{localId:UID,email:EMAIL,emailVerified:true,disabled:false,validSince:String(SECOND-300),providerUserInfo:[{providerId:'google.com',rawId:SUBJECT,federatedId:'https://accounts.google.com/'+SUBJECT,email:EMAIL}],passwordHash:'SYNTHETIC_PRIVATE_HASH',customAttributes:'SYNTHETIC_PRIVATE_ATTRIBUTES'}},calls=[],hooks={},stats={body:0,clock:0};
  function response(status=200,body=JSON.stringify({users:[state.record]}),headers={'Content-Type':'application/json; charset=utf-8'}){return {getResponseCode(){return status;},getAllHeaders(){return headers;},getContent(){stats.body++;return Array.from(Buffer.from(body,'utf8'),v=>v>127?v-256:v);}};}
  const host={fetch(url,params){calls.push({url,params:clone(params)});if(hooks.fetch)return hooks.fetch(calls.length,url,params);return response();}},options={enabled:true,binding:{projectId:PROJECT,apiKey:KEY},urlFetchApp:host,clock(){stats.clock++;if(hooks.clock)return hooks.clock();return state.clock;}};
  return {state,calls,hooks,stats,host,options,response,token:()=>jwt(state.payload),create:(factory=ENROLL)=>factory(options),verify(factory=ENROLL){return factory(options).verify({idToken:jwt(state.payload)});}};
}
function denied(result,error='access_denied'){assert.deepEqual(result,{ok:false,error});assert.equal(Object.isFrozen(result),true);for(const canary of [EMAIL,UID,SUBJECT,KEY,'SYNTHETIC_PRIVATE_HASH','SYNTHETIC_PRIVATE_ERROR'])assert.equal(JSON.stringify(result).includes(canary),false);}
function expected(f){return {projectId:PROJECT,uid:UID,email:EMAIL,googleSubject:SUBJECT,authTimeMs:f.state.payload.auth_time*1000,issuedAtMs:f.state.payload.iat*1000,expiresAtMs:f.state.payload.exp*1000,verifiedAt:f.state.clock};}

test('default configuration and both default factories are OFF with empty trusted binding',()=>{assert.deepEqual(A.DEFAULT_CONFIGURATION,{enabled:false,binding:{projectId:'',apiKey:''}});assert.equal(Object.isFrozen(A.DEFAULT_CONFIGURATION.binding),true);for(const factory of [ENROLL,SESSION])denied(factory().verify(), 'service_disabled');});
test('OFF inspects neither hostile request nor other option/native descriptors',()=>{let hits=0;const request=new Proxy({},{get(){hits++;throw Error('private');},ownKeys(){hits++;throw Error('private');}});for(const enabled of [false,1,undefined]){const options={enabled};for(const k of ['binding','urlFetchApp','clock'])Object.defineProperty(options,k,{get(){hits++;throw Error('private');}});for(const factory of [ENROLL,SESSION])denied(factory(options).verify(request),'service_disabled');}for(const factory of [ENROLL,SESSION])denied(factory({get enabled(){hits++;return true;}}).verify(request),'service_disabled');assert.equal(hits,0);});
test('factory has no native calls; malformed/extra/foreign options fail before clock or fetch',()=>{const f=fixture();f.create();assert.equal(f.calls.length,0);assert.equal(f.stats.clock,0);for(const change of [o=>{o.binding.projectId='bad';},o=>{o.binding.apiKey='injected?key=x';},o=>{o.binding.apiKey='';},o=>{o.binding.extra=true;},o=>{o.url='https://foreign.invalid';},o=>{o.fresh=false;},o=>{o.idToken='private';},o=>{o.scriptApp={getOAuthToken(){throw Error('never');}};},o=>{delete o.clock;},o=>{Object.defineProperty(o.binding,'apiKey',{enumerable:true,get(){throw Error('never');}});},o=>{Object.defineProperty(o.urlFetchApp,'fetch',{get(){throw Error('never');}});}]){const q=fixture();change(q.options);denied(q.verify(),'unavailable');assert.equal(q.calls.length,0);assert.equal(q.stats.clock,0);}});
test('fixed endpoint uses the original token in two fresh bodies without owner OAuth or token URLs',()=>{const f=fixture(),token=f.token(),a=f.create(),r=a.verify({idToken:token});assert.deepEqual(r,{ok:true,identity:expected(f)});assert.equal(Object.isFrozen(r.identity),true);assert.equal(r instanceof Promise,false);assert.equal(f.calls.length,2);for(const call of f.calls){assert.deepEqual(call,{url:'https://identitytoolkit.googleapis.com/v1/accounts:lookup?key='+KEY,params:{method:'post',contentType:'application/json; charset=utf-8',headers:{Accept:'application/json','Accept-Encoding':'identity'},payload:JSON.stringify({idToken:token}),followRedirects:false,muteHttpExceptions:true,validateHttpsCertificates:true,timeoutSeconds:20}});assert.equal(call.url.includes(token),false);assert.equal(Object.hasOwn(call.params.headers,'Authorization'),false);}for(const key of ['passwordHash','customAttributes','firebase','providerUserInfo','validSince','disabled','emailVerified','apiKey'])assert.equal(Object.hasOwn(r.identity,key),false);assert.equal(JSON.stringify(r).includes(token),false);});
test('synthetic DTO parity with current canonical enrollment/session verifier does not require raw uid',async()=>{for(const factory of [ENROLL,SESSION]){const f=fixture();if(factory===SESSION)f.state.payload.auth_time=SECOND-86400;f.state.record.validSince=String(SECOND-86401);const token=f.token(),oldFactory=factory===ENROLL?Old.createProductionEnrollmentIdentityVerifier:Old.createProductionSessionIdentityVerifier;const auth={app:{options:{projectId:PROJECT}},async verifyIdToken(value,revoked){assert.equal(value,token);assert.equal(revoked,true);return {...f.state.payload,uid:UID};},async getUser(id){assert.equal(id,UID);return {uid:UID,email:EMAIL,emailVerified:true,disabled:false,providerData:[{providerId:'google.com',uid:SUBJECT,email:EMAIL}]};}};assert.deepEqual(f.verify(factory),await oldFactory({enabled:true,projectId:PROJECT,auth,clock:()=>NOW}).verify({idToken:token}));}});
test('request argument count, shape, descriptors and bounds reject before native calls',()=>{for(const request of [undefined,null,{},[],{idToken:'x',uid:UID},{idToken:'x',workerId:'worker'},{idToken:''},{idToken:1},{idToken:'x'.repeat(A.MAX_TOKEN_BYTES+1)},{idToken:'x\r\ny'},{get idToken(){throw Error('private');}},Object.defineProperty({idToken:'x'},'hidden',{value:true}),Object.assign({idToken:'x'},{[Symbol('private')]:true}),Object.assign(Object.create({inherited:true}),{idToken:'x'})]){const f=fixture();denied(f.create().verify(request),'invalid_request');assert.equal(f.calls.length,0);assert.equal(f.stats.clock,0);}const f=fixture();denied(f.create().verify({idToken:f.token()},{}),'invalid_request');assert.equal(f.calls.length,0);});
test('tokens need canonical base64url and bounded RS256 header/signature before Google dispatch',()=>{const f=fixture(),valid=f.token();const malformed=['not-jwt',valid+'.extra',valid.replace(/^./,'!'),valid+'=',enc({alg:'none',kid:'x'})+'.'+enc(f.state.payload)+'.'+enc('sig'),jwt(f.state.payload,{alg:'HS256',kid:'x'}),jwt(f.state.payload,{alg:'RS256',kid:'x',jku:'https://foreign.invalid'}),jwt(f.state.payload,{alg:'RS256',kid:'x',typ:'other'}),jwt(f.state.payload,{alg:'RS256'}),jwt(f.state.payload,{alg:'RS256',kid:'../unsafe'}),jwt(f.state.payload,{alg:'RS256',kid:'k'.repeat(129)}),jwt(f.state.payload,undefined,'AB'),jwt(f.state.payload,undefined,'A'.repeat(1368)),enc('{"alg":"RS256","alg":"none","kid":"x"}')+'.'+enc(f.state.payload)+'.'+valid.split('.')[2]];for(const token of malformed){const q=fixture();denied(q.create().verify({idToken:token}));assert.equal(q.calls.length,0);}});
test('wrong audience/issuer/aliases/email/provider/tenant never become current identity',()=>{for(const mutate of [p=>{p.aud='demo-other-project';},p=>{p.iss='https://foreign.invalid';},p=>{p.sub='bad/path';},p=>{p.uid='different';},p=>{p.user_id='different';},p=>{p.email_verified=false;},p=>{p.email_verified='true';},p=>{p.email='Synthetic@gmail.com';},p=>{p.email='synthetic@example.invalid';},p=>{p.firebase.sign_in_provider='password';},p=>{p.firebase.tenant=null;},p=>{p.firebase.identities['google.com']=[];},p=>{p.firebase.identities['google.com']=[SUBJECT,'another'];},p=>{delete p.firebase.identities['google.com'];}]){const f=fixture();mutate(f.state.payload);denied(f.verify());assert.equal(f.calls.length,0);}const f=fixture();f.state.payload.user_id=UID;f.state.payload.uid=UID;assert.equal(f.verify().ok,true);});
test('duplicate decoded claims keys and prototype controls are never accepted',()=>{const f=fixture(),parts=f.token().split('.');for(const raw of [JSON.stringify(f.state.payload).replace('"sub":','"sub":"duplicate", "sub":'),JSON.stringify(f.state.payload).replace('"sub":','"\\u0073ub":"duplicate", "sub":'),'{"__proto__":{}}','{"firebase":{"identities":{"google.com":[],"google.com":[]}}}']){const q=fixture();denied(q.create().verify({idToken:parts[0]+'.'+enc(raw)+'.'+parts[2]}));assert.equal(q.calls.length,0);}});
test('safe integer token seconds and chronology apply before lookup and after native waits',()=>{for(const patch of [{auth_time:0},{iat:'1'},{iat:SECOND-0.5},{exp:Number.MAX_SAFE_INTEGER},{auth_time:SECOND-60,iat:SECOND-120},{iat:SECOND+1},{auth_time:SECOND+1,iat:SECOND+1},{exp:SECOND},{iat:SECOND,exp:SECOND},{exp:SECOND-60}]){const f=fixture();Object.assign(f.state.payload,patch);denied(f.verify());assert.equal(f.calls.length,0);}});
test('enrollment requires recent authentication; an ID refresh alone cannot satisfy it',()=>{const f=fixture();f.state.payload.auth_time=SECOND-301;f.state.payload.iat=SECOND;f.state.record.validSince=String(SECOND-302);denied(f.verify());assert.equal(f.calls.length,0);assert.equal(f.verify(SESSION).ok,true);const q=fixture();q.state.payload.auth_time=SECOND-300;q.state.payload.iat=SECOND-300;q.state.record.validSince=String(SECOND-300);assert.equal(q.verify().ok,true);q.state.clock='2026-10-07T03:00:00.001Z';denied(q.verify());});
test('two current observations reject disabled/deleted/unverified or re-linked accounts at either lookup',()=>{for(const at of [1,2])for(const change of [u=>{u.disabled=true;},u=>{u.emailVerified=false;},u=>{u.email='different@gmail.com';},u=>{u.localId='different';},u=>{u.tenantId='other-tenant';},u=>{u.providerUserInfo[0].rawId='different';},u=>{u.providerUserInfo[0].email='different@gmail.com';},u=>{delete u.providerUserInfo[0].rawId;},u=>{delete u.providerUserInfo[0].email;},u=>{u.providerUserInfo[0].providerId='password';}]){const f=fixture();f.hooks.fetch=n=>{if(n===at)change(f.state.record);return f.response();};denied(f.verify());assert.equal(f.calls.length,at);}for(const at of [1,2]){const f=fixture();f.hooks.fetch=n=>n===at?f.response(400,'SYNTHETIC_PRIVATE_ERROR'):f.response();denied(f.verify());assert.equal(f.calls.length,at);}});
test('one exact current account and one current Google provider are required without display-name fallback',()=>{for(const users of [[],[fixture().state.record,fixture().state.record],{},null]){const f=fixture();f.hooks.fetch=()=>f.response(200,JSON.stringify({users}));denied(f.verify());}for(const providers of [[],[{providerId:'password',rawId:SUBJECT,email:EMAIL}],[fixture().state.record.providerUserInfo[0],fixture().state.record.providerUserInfo[0]],Array.from({length:17},()=>({providerId:'google.com',rawId:SUBJECT,email:EMAIL})),null,{}]){const f=fixture();f.state.record.providerUserInfo=providers;denied(f.verify());}const f=fixture();f.state.record.providerUserInfo.push({providerId:'password',rawId:'other',email:'different@gmail.com'});assert.equal(f.verify().ok,true);});
test('documented optional disabled and revocation defaults apply only to trusted successful JSON',()=>{const f=fixture();delete f.state.record.disabled;delete f.state.record.validSince;assert.equal(f.verify().ok,true);for(const patch of [{disabled:null},{disabled:0},{disabled:'false'},{validSince:0},{validSince:false},{validSince:null},{validSince:''},{validSince:'01'},{validSince:'1.5'},{validSince:'1e3'},{validSince:'9007199254740991'}]){const q=fixture();Object.assign(q.state.record,patch);denied(q.verify());}const q=fixture();q.state.record.validSince='0';assert.equal(q.verify().ok,true);});
test('revocation uses original auth_time rather than iat and accepts exact second-boundary equality',()=>{const f=fixture();f.state.payload.auth_time=SECOND-86400;f.state.payload.iat=SECOND;f.state.record.validSince=String(SECOND-60);denied(f.verify(SESSION));assert.equal(f.calls.length,1);const q=fixture();q.state.record.validSince=String(q.state.payload.auth_time);assert.equal(q.verify().ok,true);for(const at of [1,2]){const r=fixture();r.hooks.fetch=n=>{if(n===at)r.state.record.validSince=String(SECOND-119);return r.response();};denied(r.verify());assert.equal(r.calls.length,at);}});
test('a disappearing or decreasing previously observed revocation fence is not silently normalized',()=>{for(const change of [u=>{delete u.validSince;},u=>{u.validSince=String(SECOND-301);}]){const f=fixture();f.hooks.fetch=n=>{if(n===2)change(f.state.record);return f.response();};denied(f.verify());assert.equal(f.calls.length,2);}const f=fixture();delete f.state.record.validSince;f.hooks.fetch=n=>{if(n===2)f.state.record.validSince=String(SECOND-200);return f.response();};assert.equal(f.verify().ok,true);});
test('lookup error/redirect/quota bodies and raw native exceptions are never read or exposed',()=>{for(const code of [201,204,301,302,307,400,401,403,404,429,500]){const f=fixture();f.hooks.fetch=()=>f.response(code,'SYNTHETIC_PRIVATE_ERROR '+EMAIL);denied(f.verify(),[400,401].includes(code)?'access_denied':'unavailable');assert.equal(f.stats.body,0);assert.equal(f.calls.length,1);}const f=fixture();f.hooks.fetch=()=>{throw Error('SYNTHETIC_PRIVATE_ERROR '+f.token());};denied(f.verify(),'unavailable');});
test('response JSON rejects duplicate aliases, prototype markers, malformed arrays and unsafe numbers',()=>{for(const body of ['{"users":[],"users":[]}','{"users":[],"\\u0075sers":[]}','{"users":[{"__proto__":{}}]}','{"constructor":{}}','{"users":[,]}','{"users":[]} trailing','{"users":[],"extra":-0}','{"users":[],"extra":1e999}','{"users":[],"extra":9007199254740992}','null','[]']){const f=fixture();f.hooks.fetch=()=>f.response(200,body);denied(f.verify());assert.equal(f.calls.length,1);}});
test('response byte/count/depth budgets bound admission without weakening current-account selection',()=>{for(const body of ['x'.repeat(A.MAX_RESPONSE_BYTES+1),'{'+'"custom":'+ '['.repeat(18)+'0'+']'.repeat(18)+'}','{"custom":['+'0,'.repeat(4096)+'0]}']){const f=fixture();f.hooks.fetch=()=>f.response(200,body);denied(f.verify(),body.length>A.MAX_RESPONSE_BYTES?'unavailable':'access_denied');assert.equal(f.calls.length,1);}const f=fixture();f.state.record.displayName='雪😀café';assert.equal(f.verify().ok,true);});
test('invalid native UTF-8, sparse/accessor/native bytes or altered array prototypes fail closed',()=>{for(const bytes of [[0xc0,0x80],[0xed,0xa0,0x80],[0xf4,0x90,0x80,0x80],[0xe2,0x82],Array(1),'not-bytes',[256],[-129],Object.assign([1],{extra:true}),Object.setPrototypeOf([1],null)]){const f=fixture(),r=f.response();r.getContent=()=>bytes;f.hooks.fetch=()=>r;denied(f.verify(),'unavailable');}const f=fixture(),bytes=[],r=f.response();let hits=0;Object.defineProperty(bytes,'0',{enumerable:true,get(){hits++;throw Error('private');}});r.getContent=()=>bytes;f.hooks.fetch=()=>r;denied(f.verify(),'unavailable');assert.equal(hits,0);});
test('ambiguous native headers, compression/redirect controls and wrong MIME fail before reading bytes',()=>{for(const headers of [{'Content-Type':'text/html'},{'Content-Type':['application/json']},{'Content-Type':'application/json','content-type':'application/json'},{'Content-Type':'application/json','Content-Encoding':'gzip'},{'Content-Type':'application/json',Location:'https://foreign.invalid'},{'Content-Type':'application/json','Content-Length':String(A.MAX_RESPONSE_BYTES+1)},{'Content-Type':'application/json','Content-Length':'01'}]){const f=fixture();f.hooks.fetch=()=>f.response(200,'private',headers);denied(f.verify(),'unavailable');assert.equal(f.stats.body,0);}const f=fixture();let hits=0;const headers={};Object.defineProperty(headers,'Content-Type',{enumerable:true,get(){hits++;throw Error('private');}});f.hooks.fetch=()=>f.response(200,'private',headers);denied(f.verify(),'unavailable');assert.equal(hits,0);});
test('response status/method accessors and native method drift do not execute untrusted getters',()=>{for(const key of ['getResponseCode','getAllHeaders','getContent']){const f=fixture(),r=f.response();let hits=0;Object.defineProperty(r,key,{get(){hits++;throw Error('private');}});f.hooks.fetch=()=>r;denied(f.verify(),'unavailable');assert.equal(hits,0);}const f=fixture(),r=f.response();r.getAllHeaders=()=>{r.getContent=()=>[];return {'Content-Type':'application/json'};};f.hooks.fetch=()=>r;denied(f.verify(),'unavailable');assert.equal(f.stats.body,0);});
test('native fetch drift during any lookup or clock callback latches rejection',()=>{for(const at of [1,2]){const f=fixture(),a=f.create(),original=f.host.fetch;f.hooks.fetch=n=>{if(n===at)f.host.fetch=()=>f.response();return f.response();};denied(a.verify({idToken:f.token()}),'unavailable');f.host.fetch=original;f.hooks.fetch=null;denied(a.verify({idToken:f.token()}),'unavailable');assert.equal(f.calls.length,at);}const f=fixture();f.hooks.clock=()=>{f.host.fetch=()=>f.response();return NOW;};denied(f.verify(),'unavailable');assert.equal(f.calls.length,0);});
test('expiry/freshness during first or second Google lookup prevents successful identity',()=>{for(const factory of [ENROLL,SESSION])for(const at of [1,2]){const f=fixture();f.state.payload.exp=SECOND+1;f.hooks.fetch=n=>{if(n===at)f.state.clock='2026-10-07T03:00:01.000Z';return f.response();};denied(f.verify(factory));assert.equal(f.calls.length,at);}const f=fixture();f.hooks.fetch=n=>{if(n===2)f.state.clock='2026-10-07T03:04:00.000Z';return f.response();};denied(f.verify());assert.equal(f.calls.length,2);});
test('bad clocks and rollback across repeated invocations reject before another native request',()=>{for(const clock of ['bad','2026-10-07T03:00:00Z','2026-02-30T03:00:00.000Z',null,1]){const f=fixture();f.state.clock=clock;denied(f.verify(),'unavailable');assert.equal(f.calls.length,0);}const f=fixture(),a=f.create();assert.equal(a.verify({idToken:f.token()}).ok,true);f.state.clock='2026-10-07T02:59:59.999Z';denied(a.verify({idToken:f.token()}),'unavailable');assert.equal(f.calls.length,2);});
test('configuration snapshots do not follow later caller binding/host/key replacements',()=>{const f=fixture(),a=f.create();f.options.binding.projectId='demo-other-project';f.options.binding.apiKey='FOREIGN_PUBLIC_KEY_000000000';f.options.urlFetchApp=null;f.options.clock=()=>{throw Error('private');};assert.equal(a.verify({idToken:f.token()}).ok,true);assert.equal(f.calls[0].url.endsWith(KEY),true);});
test('no token/account cache exists and reentrant callbacks cannot overlap identity verification',()=>{const f=fixture(),a=f.create();f.hooks.fetch=()=>{denied(a.verify({idToken:f.token()}),'unavailable');return f.response();};assert.equal(a.verify({idToken:f.token()}).ok,true);assert.equal(a.verify({idToken:f.token()}).ok,true);assert.equal(f.calls.length,4);delete f.state.record.validSince;f.state.record.disabled=true;denied(a.verify({idToken:f.token()}));assert.equal(f.calls.length,5);});
test('forged error/accessor exceptions expose no private detail or error getter',()=>{const f=fixture();let hits=0;const e=Object.create(Error.prototype);Object.defineProperty(e,'code',{get(){hits++;throw Error('private');}});f.hooks.clock=()=>{throw e;};denied(f.verify(),'unavailable');assert.equal(hits,0);});
test('inherited Object/Array/String toJSON hooks cannot observe or replace the token body',()=>{const f=fixture(),token=f.token(),body=JSON.stringify({users:[f.state.record]}),a=f.create(),prototypes=[Object.prototype,Array.prototype,String.prototype],saved=prototypes.map(p=>Object.getOwnPropertyDescriptor(p,'toJSON'));let hits=0,result;
  f.hooks.fetch=()=>f.response(200,body);
  try{for(const p of prototypes)Object.defineProperty(p,'toJSON',{configurable:true,get(){hits++;throw Error('SYNTHETIC_PRIVATE_ERROR');}});result=a.verify({idToken:token});}
  finally{prototypes.forEach((p,i)=>{if(saved[i])Object.defineProperty(p,'toJSON',saved[i]);else delete p.toJSON;});}
  assert.equal(hits,0);assert.equal(result.ok,true);assert.equal(f.calls.length,2);for(const call of f.calls)assert.equal(call.params.payload,'{"idToken":'+JSON.stringify(token)+'}');
});
test('source is independent and has no native global, auth mutation, logger, eval or exported token',()=>{const source=fs.readFileSync(require.resolve('../server/apps-script/current-google-identity.cjs'),'utf8');for(const forbidden of [/\brequire\s*\(/,/\beval\s*\(/,/\bnew\s+Function\s*\(/,/\bconsole\s*\./,/\bLogger\b/,/\bScriptApp\b/,/\bUrlFetchApp\s*\./,/\bdoGet\s*\(/,/\bdoPost\s*\(/,/accounts:(?:update|delete|signIn|signUp)/,/access_token=/,/auth=/,/process\./])assert.equal(forbidden.test(source),false,String(forbidden));assert.deepEqual(Object.keys(A).sort(),['DEFAULT_CONFIGURATION','MAX_RESPONSE_BYTES','MAX_TOKEN_BYTES','createAppsScriptEnrollmentGoogleIdentityVerifier','createAppsScriptSessionGoogleIdentityVerifier'].sort());});
