'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createRevisionSync}=require('../production-revision-sync.js');
function fixture(){
  let signal,failed,clock=0,reads=0,closed=0,allowed=true,current=true,status,read=async()=>({ok:true});const timers=new Map();let next=0;
  const sync=createRevisionSync({subscribe:(s,e)=>{signal=s;failed=e;return()=>closed++;},refresh:()=>{reads++;return read();},isCurrent:()=>current,canRefresh:()=>allowed,onStatus:s=>{status=s;},now:()=>clock,setTimeout:(fn,ms)=>{const id=++next;timers.set(id,{fn,at:clock+ms});return id;},clearTimeout:id=>timers.delete(id)});
  return{sync,signal:v=>signal(v),failed:c=>failed(c),setAllowed:v=>{allowed=v;},setCurrent:v=>{current=v;},setRead:f=>{read=f;},stats:()=>({reads,closed,status,timers:timers.size}),async tick(){const first=[...timers.entries()].sort((a,b)=>a[1].at-b[1].at)[0];if(first){timers.delete(first[0]);clock=first[1].at;await first[1].fn();}}};
}
test('initial revision before data read needs no redundant refresh; later events coalesce',async()=>{const f=fixture();f.signal(1);f.sync.ready();assert.equal(f.stats().reads,0);assert.equal(f.stats().timers,0);f.signal(2);f.signal(3);assert.equal(f.stats().timers,1);await f.tick();assert.equal(f.stats().reads,1);assert.equal(f.stats().status.pending,false);f.signal(3);assert.equal(f.stats().timers,0);});
test('initial late event and mid-initial-read event close missed-change race',async()=>{for(const late of [true,false]){const f=fixture();if(!late){f.signal(1);f.signal(2);}f.sync.ready();if(late)f.signal(1);await f.tick();assert.equal(f.stats().reads,1);}});
test('dirty or hidden form retains notification without network work until resume',async()=>{const f=fixture();f.signal(1);f.sync.ready();f.setAllowed(false);f.signal(2);await f.tick();assert.equal(f.stats().reads,0);assert.equal(f.stats().status.blocked,true);f.setAllowed(true);f.sync.resume();await f.tick();assert.equal(f.stats().reads,1);});
test('change during a read remains pending and refreshes once more',async()=>{const f=fixture();f.signal(1);f.sync.ready();f.setRead(async()=>{f.signal(3);return{ok:true};});f.signal(2);await f.tick();assert.equal(f.stats().status.pending,true);assert.equal(f.stats().timers,1);f.setRead(async()=>({ok:true}));await f.tick();assert.equal(f.stats().reads,2);assert.equal(f.stats().status.pending,false);});
test('no automatic retry storm after failure; explicit refresh acknowledges pending revision',async()=>{const f=fixture();f.signal(1);f.sync.ready();f.setRead(async()=>({ok:false,error:'rate_limited'}));f.signal(2);await f.tick();assert.equal(f.stats().timers,0);assert.equal(f.stats().status.error,'unavailable');f.sync.resume();assert.equal(f.stats().timers,0);f.setRead(async()=>({ok:true}));await f.sync.refreshNow();assert.equal(f.stats().status.pending,false);assert.equal(f.stats().timers,0);});
test('sign-out disposes listener and scheduled work; invalid signals never reach records',async()=>{const f=fixture();f.signal(1);f.sync.ready();f.signal('secret');assert.equal(f.stats().status.error,'unavailable');assert.equal(f.stats().reads,0);f.signal(2);f.setCurrent(false);await f.tick();assert.equal(f.stats().reads,0);assert.equal(f.stats().closed,1);f.sync.dispose();assert.equal(f.stats().closed,1);});
