'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Http=require('../server/production-http-handler.cjs'),Runtime=require('../server/production-runtime.cjs'),Deployment=require('../server/deployment/deployment-runtime.cjs'),History=require('../legacy-stored-history.js'),Codec=require('../server/production-legacy-history-archive-codec.cjs'),State=require('../server/production-identity-state.cjs');
const F=require('./fixtures/identity-tenant.cjs'),PATH='/v1/production/history/own',ORIGIN='https://soldier.example.invalid',TOKEN='synthetic.history.token',VERSION='synthetic-history-version';
const binding=()=>({projectId:F.PROJECT,databaseURL:F.URL,tenantId:F.TENANT,uid:'partner-1',workerId:'worker-1',division:'jahit',grantRevision:1});
function products(){return [{id:'product-1',series:'Synthetic',namaBarang:'Example',size:'M',jahit:[{id:'row-1',tukangId:'worker-1',tanggal:'2025-01-01',jumlah:3,tarif:12.5,total:999.75,dibayar:false,lolos:null},{id:'foreign-row',tukangId:'worker-2',total:12345.75}],arsip:[]}];}
function view(){const r=History.createLegacyStoredHistoryProjector({enabled:true,binding:binding()}).project({snapshotVersion:VERSION,products:products()});assert.equal(r.ok,true);return r.view;}
function request(){const headers={origin:ORIGIN,authorization:'Bearer '+TOKEN};return {method:'GET',url:PATH,headers,rawHeaders:Object.entries(headers).flat()};}
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},end(v){this.body=v===undefined?null:JSON.parse(v);this.writableEnded=true;}};}
async function run(f,req=request()){const res=response();await f.handler(req,res);return res;}
function fixture(extra={}){const calls=[],options={enabled:true,service:{execute:async()=>{throw Error('wrong service');}},legacyHistoryService:{execute:async q=>{calls.push(q);return {ok:true,view:view()};}},historyBinding:{projectId:F.PROJECT,databaseURL:F.URL,tenantId:F.TENANT},allowedOrigins:[ORIGIN],deadlineMs:1000,maxInFlight:1,...extra};return {calls,options,handler:Http.createProductionHttpHandler(options)};}
test('own-history GET preserves stored total, zero/null/absent fields without repricing',async()=>{const f=fixture(),r=await run(f);assert.equal(r.statusCode,200);assert.deepEqual(r.body,{ok:true,view:view()});assert.deepEqual(f.calls,[{idToken:TOKEN}]);assert.equal(r.body.view.records[0].stored.total,999.75);assert.equal(r.body.view.records[0].stored.lolos,null);assert.equal(Object.hasOwn(r.body.view.records[0].stored,'rijek'),false);assert.equal(r.headers['Cache-Control'],'no-store');assert.equal(JSON.stringify(r).includes('foreign-row'),false);assert.equal(JSON.stringify(r).includes(TOKEN),false);});
test('history remains unregistered when no trusted service is assembled',async()=>{const f=fixture();delete f.options.legacyHistoryService;const r=await run({handler:Http.createProductionHttpHandler(f.options)});assert.equal(r.statusCode,400);assert.equal(f.calls.length,0);});
test('caller worker, archive or tenant queries and bodies cannot select history',async()=>{for(const change of [r=>r.url=PATH+'?workerId=worker-2',r=>r.url=PATH+'?snapshotVersion=other',r=>r.url=PATH+'/',r=>{r.rawBody=Buffer.from('{}');},r=>r.headers['content-type']='application/json',r=>r.headers['content-length']='2',r=>r.method='POST']){const f=fixture(),req=request();change(req);assert.ok([400,405].includes((await run(f,req)).statusCode));assert.equal(f.calls.length,0);}});
test('history token, origin, duplicate control headers and compression fail before service',async()=>{for(const change of [r=>r.headers.authorization='Bearer bad',r=>r.headers.origin='https://foreign.example.invalid',r=>r.rawHeaders.push('authorization','Bearer other.token.value'),r=>r.headers['content-encoding']='gzip']){const f=fixture(),req=request();change(req);assert.ok([400,403].includes((await run(f,req)).statusCode));assert.equal(f.calls.length,0);}});
test('GET-only history preflight accepts Authorization without body or identity verification',async()=>{const f=fixture(),req=request();req.method='OPTIONS';req.headers={origin:ORIGIN,'access-control-request-method':'GET','access-control-request-headers':'Authorization'};req.rawHeaders=Object.entries(req.headers).flat();assert.equal((await run(f,req)).statusCode,204);req.headers['access-control-request-method']='POST';req.rawHeaders=Object.entries(req.headers).flat();assert.equal((await run(f,req)).statusCode,400);assert.equal(f.calls.length,0);});
test('foreign scope, foreign worker records, extra private metadata and invalid stored types reject whole view',async()=>{for(const mutate of [v=>v.binding.projectId='demo-foreign',v=>v.binding.databaseURL='https://demo-other.firebaseio.com',v=>v.binding.tenantId='foreign',v=>v.records[0].workerId='worker-2',v=>v.records[0].stored.password='PRIVATE_CANARY',v=>v.records[0].stored.total='999.75']){const v=F.copy(view());mutate(v);const f=fixture({legacyHistoryService:{execute:async()=>({ok:true,view:v})}}),r=await run(f);assert.equal(r.statusCode,503);assert.deepEqual(r.body,{ok:false,error:'unavailable'});assert.equal(JSON.stringify(r).includes('PRIVATE_CANARY'),false);}});
test('result and binding accessors are rejected without reading private values',async()=>{let touched=0;const r={ok:true};Object.defineProperty(r,'view',{enumerable:true,get(){touched++;throw Error('private');}});assert.deepEqual((await run(fixture({legacyHistoryService:{execute:async()=>r}}))).body,{ok:false,error:'unavailable'});const opts=fixture().options;Object.defineProperty(opts,'historyBinding',{get(){touched++;throw Error('private');}});assert.equal((await run({handler:Http.createProductionHttpHandler(opts)})).statusCode,503);assert.equal(touched,0);});
test('service method and option accessors do not invoke private callbacks',async()=>{let touched=0;const svc={};Object.defineProperty(svc,'execute',{get(){touched++;throw Error('private');}});assert.equal((await run(fixture({legacyHistoryService:svc}))).statusCode,503);const opts=fixture().options;Object.defineProperty(opts,'legacyHistoryService',{get(){touched++;throw Error('private');}});assert.equal((await run({handler:Http.createProductionHttpHandler(opts)})).statusCode,503);assert.equal(touched,0);});
test('unavailable history differs from an available empty history',async()=>{for(const products of [null,[]]){const prepared=History.createLegacyStoredHistoryProjector({enabled:true,binding:binding()}).project({snapshotVersion:VERSION,products});assert.equal(prepared.ok,true);const r=await run(fixture({legacyHistoryService:{execute:async()=>({ok:true,view:prepared.view})}}));assert.equal(r.statusCode,200);assert.equal(r.body.view.availability,products===null?'unavailable':'available');assert.deepEqual(r.body.view.records,products===null?null:[]);}});
test('history errors and thrown details remain fixed readonly responses without retrying writes',async()=>{for(const [error,status]of [['access_denied',403],['not_ready',409],['capacity_limit',409],['rate_limited',429],['unavailable',503]]){const r=await run(fixture({legacyHistoryService:{execute:async()=>({ok:false,error})}}));assert.equal(r.statusCode,status);assert.deepEqual(r.body,{ok:false,error});}const r=await run(fixture({legacyHistoryService:{execute:async()=>{throw Error('PRIVATE_CANARY');}}}));assert.deepEqual(r.body,{ok:false,error:'unavailable'});});
test('late reads retain the shared slot until settlement and discard the returned money',async()=>{let release;const p=new Promise(r=>release=r),f=fixture({deadlineMs:5,legacyHistoryService:{execute:()=>p}}),res=response(),first=f.handler(request(),res);await new Promise(r=>setTimeout(r,15));assert.equal(res.writableEnded,undefined);assert.deepEqual((await run(f)).body,{ok:false,error:'busy'});release({ok:true,view:view()});await first;assert.deepEqual(res.body,{ok:false,error:'unavailable'});});
test('disconnected history reads do not free capacity or send late data',async()=>{let release;const p=new Promise(r=>release=r),f=fixture({legacyHistoryService:{execute:()=>p}}),res=response(),first=f.handler(request(),res);res.destroyed=true;assert.equal((await run(f)).body.error,'busy');release({ok:true,view:view()});await first;assert.equal(res.writableEnded,undefined);});
function runtimeFixture(){
 const historyScope={projectId:F.PROJECT,databaseURL:F.URL,tenantId:F.TENANT,snapshotVersion:VERSION},prepared=Codec.createLegacyHistoryArchivePreparer({enabled:true,scope:historyScope,workers:{'worker-1':{division:'jahit',reviewed:true},'worker-2':{division:'jahit',reviewed:true}}}).prepare({products:products()});assert.equal(prepared.ok,true);
 const tenantPath='authorityTenants/'+F.TENANT,archivePath='legacyStoredHistoryArchives/'+F.TENANT+'/'+VERSION,root=new Map([[tenantPath,F.copy(F.claimed())],[archivePath,F.copy(prepared.archive)]]),stats={auth:0,users:0,historyReads:0,tenantWrites:0,rateWrites:0},hooks={},control={uid:'partner-1',subject:'1000123456789',email:F.EMAIL,disabled:false};
 const app={options:{projectId:F.PROJECT,databaseURL:F.URL}},refs=new Map();
 const database={app,ref(path){if(refs.has(path))return refs.get(path);let reference;const snap=value=>({ref:reference,val:()=>F.copy(value)});reference={toString:()=>F.URL+'/'+path,async get(){const value=F.copy(root.get(path)??null);if(path===archivePath){stats.historyReads++;if(hooks.history)hooks.history();}return snap(value);},on(_event,fn){queueMicrotask(()=>fn(snap(root.get(path)??null)));},off(){},async transaction(update){const next=update(F.copy(root.get(path)??null));if(next===undefined)return {committed:false,snapshot:snap(root.get(path)??null)};root.set(path,F.copy(next));if(path===tenantPath)stats.tenantWrites++;else stats.rateWrites++;return {committed:true,snapshot:snap(next)};}};refs.set(path,reference);return reference;}};
 const second=Date.parse(F.NOW)/1000,auth={app,async verifyIdToken(token,revoked){stats.auth++;assert.equal(token,TOKEN);assert.equal(revoked,true);return {uid:control.uid,sub:control.uid,aud:F.PROJECT,iss:'https://securetoken.google.com/'+F.PROJECT,email:control.email,email_verified:true,auth_time:second-86400,iat:second-60,exp:second+3600,firebase:{sign_in_provider:'google.com',identities:{'google.com':[control.subject]}}};},async getUser(uid){stats.users++;return {uid,email:control.email,emailVerified:true,disabled:control.disabled,providerData:[{providerId:'google.com',uid:control.subject,email:control.email}]};}};
 const options={enabled:true,legacyHistoryEnabled:true,legacyHistoryArchive:{snapshotVersion:VERSION,publicationProof:F.copy(prepared.publicationProof)},projectId:F.PROJECT,databaseURL:F.URL,tenantId:F.TENANT,database,auth,allowedOrigins:[ORIGIN],clock:()=>F.NOW,policy:{rateWindowMs:60000,rateLimit:30,deadlineMs:1000,maxInFlight:1}};
 return {options,prepared,root,tenantPath,archivePath,stats,hooks,control};
}
test('assembled history performs Google verification, retained own identity and private admission before archive read',async()=>{const f=runtimeFixture(),before=F.copy(f.root.get(f.tenantPath)),r=await run(Runtime.createProductionRuntime(f.options));assert.equal(r.statusCode,200);assert.deepEqual(r.body.view,view());assert.equal(f.stats.auth,2);assert.equal(f.stats.users,2);assert.equal(f.stats.historyReads,1);assert.equal(f.stats.rateWrites,1);assert.equal(f.stats.tenantWrites,0);assert.deepEqual(f.root.get(f.tenantPath),before);for(const marker of [TOKEN,'foreign-row','12345.75',F.EMAIL,'1000123456789'])assert.equal(JSON.stringify(r).includes(marker),false);});
test('assembled OFF history never inspects archive configuration or verifies Google identity',async()=>{const f=runtimeFixture();f.options.legacyHistoryEnabled=false;let touched=0;Object.defineProperty(f.options,'legacyHistoryArchive',{get(){touched++;throw Error('private');}});assert.equal((await run(Runtime.createProductionRuntime(f.options))).statusCode,400);assert.equal(touched,0);assert.equal(f.stats.auth,0);assert.equal(f.stats.historyReads,0);});
test('assembled malformed/accessor flag and unreviewed scope proof fail without Auth or archive reads',async()=>{for(const change of [f=>f.options.legacyHistoryEnabled='true',f=>f.options.legacyHistoryArchive.publicationProof.reviewed=false,f=>f.options.legacyHistoryArchive.publicationProof.scope.tenantId='foreign',f=>f.options.legacyHistoryArchive.snapshotVersion='other']){const f=runtimeFixture();change(f);assert.equal((await run(Runtime.createProductionRuntime(f.options))).statusCode,503);assert.equal(f.stats.auth,0);assert.equal(f.stats.historyReads,0);}});
test('assembled unknown, disabled, QC and owner accounts cannot read a partner archive',async()=>{for(const change of [f=>f.control.uid='unknown-1',f=>f.control.disabled=true,f=>{f.control.uid='owner-1';f.control.email='syntheticowner@gmail.com';f.control.subject='owner-google';},f=>{const tenant=f.root.get(f.tenantPath);const claimed=State.claimIdentityEnrollment(tenant,F.identity({uid:'quality-1',email:F.QC_EMAIL,googleSubject:'quality-google'}),F.NOW).next;f.root.set(f.tenantPath,F.copy(claimed));f.control.uid='quality-1';f.control.email=F.QC_EMAIL;f.control.subject='quality-google';}]){const f=runtimeFixture();change(f);assert.equal((await run(Runtime.createProductionRuntime(f.options))).body.error,'access_denied');assert.equal(f.stats.historyReads,0);assert.equal(f.stats.rateWrites,0);}});
test('assembled replaced Google subject cannot use the retained worker grant',async()=>{const f=runtimeFixture();f.control.subject='replacement-google';assert.equal((await run(Runtime.createProductionRuntime(f.options))).body.error,'access_denied');assert.equal(f.stats.historyReads,0);assert.equal(f.stats.rateWrites,0);});
test('assembled private proof detects archive tampering before any money response',async()=>{const f=runtimeFixture();f.root.get(f.archivePath).digest='0'.repeat(64);const r=await run(Runtime.createProductionRuntime(f.options));assert.deepEqual(r.body,{ok:false,error:'unavailable'});assert.equal(f.stats.tenantWrites,0);});
test('assembled revocation during archive load discards all late stored wage data',async()=>{const f=runtimeFixture();f.hooks.history=()=>{const next=State.revokeIdentityEnrollment(f.root.get(f.tenantPath),F.revokeCommand(),F.NOW).next;f.root.set(f.tenantPath,F.copy(next));};const r=await run(Runtime.createProductionRuntime(f.options));assert.deepEqual(r.body,{ok:false,error:'access_denied'});assert.equal(Object.hasOwn(r.body,'view'),false);});
const PROJECT='soldier-history-proof',URL='https://'+PROJECT+'.firebaseio.com';
function config(enabled=false){const base={enabled:true,projectId:PROJECT,databaseURL:URL,tenantId:F.TENANT,allowedOrigins:[ORIGIN],serviceAccount:'soldier-production-runtime@'+PROJECT+'.iam.gserviceaccount.com',legacyHistoryEnabled:enabled};if(enabled){const scope={projectId:PROJECT,databaseURL:URL,tenantId:F.TENANT,snapshotVersion:VERSION},r=Codec.createLegacyHistoryArchivePreparer({enabled:true,scope,workers:{'worker-1':{division:'jahit',reviewed:true},'worker-2':{division:'jahit',reviewed:true}}}).prepare({products:products()});assert.equal(r.ok,true);base.legacyHistoryArchive={snapshotVersion:VERSION,publicationProof:F.copy(r.publicationProof)};}return base;}
function deployment(configuration=config()){
 const stats={load:0,adc:0,init:0},calls={},env={GOOGLE_CLOUD_PROJECT:PROJECT,GCLOUD_PROJECT:PROJECT,FUNCTION_TARGET:'soldierProduction',K_SERVICE:'soldierproduction'};
 const sdk={getApps:()=>[],applicationDefault:()=>{stats.adc++;return {};},initializeApp:(options,name)=>{stats.init++;return {options,name};},getDatabase:app=>({app}),getAuth:app=>({app})};
 const instance=Deployment.createDeployment({host:'functions',configuration,environment:()=>env,loadAdminSdk:()=>{stats.load++;return sdk;},createRuntime:options=>{calls.options=options;return {handler:async(_req,res)=>{res.statusCode=200;res.end('{"ok":true}');}};}});return {...instance,stats,calls,env};
}
test('source OFF and default/false host history reject before SDK, ADC or body access',async()=>{assert.equal(require('../server/deployment/configuration.cjs').legacyHistoryEnabled,false);assert.equal(require('../server/deployment/configuration.cjs').legacyHistoryArchive,null);const f=deployment(),req=request();let touched=0;Object.defineProperty(req,'rawBody',{get(){touched++;throw Error('private');}});assert.equal(f.gate(req).status,400);assert.equal((await run(f,req)).statusCode,400);assert.equal(f.stats.adc,0);assert.equal(touched,0);});
test('history host configuration requires exact reviewed private proof and matching server scope',async()=>{for(const mutate of [c=>delete c.legacyHistoryArchive,c=>c.legacyHistoryArchive.publicationProof.reviewed=false,c=>c.legacyHistoryArchive.publicationProof.scope.projectId='foreign',c=>c.legacyHistoryArchive.snapshotVersion='other',c=>c.legacyHistoryEnabled='true']){const c=config(true);mutate(c);const f=deployment(c);assert.equal((await run(f)).statusCode,503);assert.equal(f.stats.load,0);}});
test('host captures detached private archive proof and forwards it only through trusted runtime assembly',async()=>{const c=config(true),f=deployment(c);c.legacyHistoryArchive.publicationProof.digest='0'.repeat(64);c.legacyHistoryArchive.snapshotVersion='other';assert.equal((await run(f)).statusCode,200);assert.equal(f.calls.options.legacyHistoryEnabled,true);assert.equal(f.calls.options.legacyHistoryArchive.snapshotVersion,VERSION);assert.notEqual(f.calls.options.legacyHistoryArchive.publicationProof.digest,'0'.repeat(64));assert.ok(Object.isFrozen(f.calls.options.legacyHistoryArchive.publicationProof));assert.equal(f.stats.init,1);});
test('history host preflight is GET-only and performs no ADC acquisition',async()=>{const f=deployment(config(true)),req=request();req.method='OPTIONS';req.headers={origin:ORIGIN,'access-control-request-method':'GET','access-control-request-headers':'Authorization'};req.rawHeaders=Object.entries(req.headers).flat();assert.equal((await run(f,req)).statusCode,204);req.headers['access-control-request-method']='POST';req.rawHeaders=Object.entries(req.headers).flat();assert.equal((await run(f,req)).statusCode,400);assert.equal(f.stats.load,0);});
test('history host errors stay readonly and never expose private proof, override or money',async()=>{const f=deployment(config(true));f.env.GOOGLE_APPLICATION_CREDENTIALS='PRIVATE_CANARY';const r=await run(f);assert.deepEqual(r.body,{ok:false,error:'unavailable'});assert.equal(f.stats.adc,0);assert.equal(JSON.stringify(r).includes('PRIVATE_CANARY'),false);});
