'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Authority=require('../server/production-authority.cjs'),Runtime=require('../server/production-runtime.cjs');
const PROJECT='demo-runtime-proof',URL='https://'+PROJECT+'.firebaseio.com',ORIGIN='https://soldier.example.invalid',NOW='2026-10-05T03:00:00.000Z';
const copy=v=>v===null?null:JSON.parse(JSON.stringify(v));
function setup(extra={}){
  const tenantId='tenant-1',state=Authority.createAuthority({product:{id:'product-1',series:'Synthetic',namaBarang:'Example',size:'M',cutQuantity:10},cycleId:'cycle-1',workers:[{id:'worker-1',nama:'Synthetic partner'}],assignments:[{id:'assignment-1',workerId:'worker-1',qty:10}],now:NOW});
  const tenant={schemaVersion:1,projectId:PROJECT,tenantId,grants:{'caller-1':{revision:1,profile:{active:true,owner:false,workerId:'worker-1',modules:{jahit:true}}}},products:{'product-1':{cycles:{'cycle-1':{config:{revision:1,active:true,reviewedEmptyCycle:true,tariffPolicy:'explicit-historical-jakarta-v1'},tariffInputs:{revision:1,policy:{version:'policy-1',kind:'jakarta-fixed-local-time',hour:8,minute:0},historyByWorker:{'worker-1':{'tariff-1':{effectiveAt:'2026-01-01T00:00:00.000Z',currency:'IDR',rate:100}}}},wire:Authority.encodeStorage(state)}}}}};
  const root=new Map([['authorityTenants/'+tenantId,tenant]]),stats={refs:0,authorityWrites:0,rateWrites:0,auth:0},control={loseCommit:false,badAck:false};
  const snapshot=v=>({val:()=>copy(v)}),app={options:{projectId:PROJECT,databaseURL:URL}};
  const database={app,ref(path){stats.refs++;return {toString:()=>URL+'/'+path,get:async()=>snapshot(root.get(path)??null),on(event,listener){assert.equal(event,'value');listener(snapshot(root.get(path)??null));},off(){},async transaction(update){const next=update(copy(root.get(path)??null));if(next===undefined)return {committed:false,snapshot:snapshot(root.get(path)??null)};root.set(path,copy(next));if(path.startsWith('authorityTenants/')){stats.authorityWrites++;if(control.loseCommit){control.loseCommit=false;throw Error('synthetic-private-sdk-secret');}if(control.badAck){control.badAck=false;return {};}}else stats.rateWrites++;return {committed:true,snapshot:snapshot(next)};}};}};
  const auth={app,verifyIdToken:async(token,revoked)=>{stats.auth++;assert.equal(revoked,true);assert.equal(token,'header.payload.signature');return {uid:'caller-1',sub:'caller-1',aud:PROJECT,iss:'https://securetoken.google.com/'+PROJECT,email_verified:true,firebase:{sign_in_provider:'google.com'},exp:Date.parse(NOW)/1000+3600};}};
  const opts={enabled:true,projectId:PROJECT,databaseURL:URL,tenantId,database,auth,allowedOrigins:[ORIGIN],clock:()=>NOW,policy:{rateWindowMs:60000,rateLimit:30,deadlineMs:1000,maxInFlight:4},...extra};
  const command=()=>({requestId:'request-1',productId:'product-1',cycleId:'cycle-1',expectedRevision:0,kind:'sewing',payload:{id:'sewing-1',assignmentId:'assignment-1',tanggal:'2026-10-05',good:10,reject:0}});
  const request=c=>{const raw=Buffer.from(JSON.stringify({command:c??command()})),headers={origin:ORIGIN,authorization:'Bearer header.payload.signature','content-type':'application/json','content-length':String(raw.length)};return {method:'POST',url:'/v1/production/commands',headers,rawHeaders:Object.entries(headers).flat(),rawBody:raw};};
  const runtime=()=>Runtime.createProductionRuntime(opts);
  const run=async(c,instance=runtime())=>{const response={headers:{},setHeader(k,v){this.headers[k]=v;},end(raw){this.body=JSON.parse(raw);this.writableEnded=true;}};await instance.handler(request(c),response);return response;};
  const decoded=()=>Authority.decodeStorage(root.get('authorityTenants/'+tenantId).products['product-1'].cycles['cycle-1'].wire);
  return {tenant,root,stats,control,opts,command,runtime,run,decoded};
}
test('disabled assembly makes no SDK references/reads; missing auth project or policy fails closed',async()=>{const f=setup();f.opts.enabled=false;assert.equal((await f.run()).body.error,'service_disabled');assert.equal(f.stats.refs,0);f.opts.enabled=true;f.opts.auth={...f.opts.auth,app:{options:{projectId:'demo-other-project'}}};assert.equal((await f.run()).body.error,'unavailable');assert.equal(f.stats.refs,0);f.opts.auth.app=f.opts.database.app;f.opts.policy={rateLimit:30};assert.equal((await f.run()).body.error,'unavailable');assert.equal(f.stats.refs,0);});
test('assembled raw HTTP command authenticates, consumes a private permit and commits once',async()=>{const f=setup(),r=await f.run();assert.equal(r.statusCode,200);assert.equal(f.stats.auth,1);assert.equal(f.stats.rateWrites,1);assert.equal(f.decoded().revision,1);assert.deepEqual(Object.keys(r.body.receipt).sort(),['acceptedAt','requestId','revision']);assert.equal(JSON.stringify(r.body).includes('worker-1'),false);assert.ok(f.root.has('serverRateLimits/tenant-1/caller-1'));});
test('canonical inactive/absent grant cannot create a rate bucket or write authority',async()=>{for(const change of [g=>{g['caller-1'].profile.active=false;},g=>{delete g['caller-1'];}]){const f=setup();change(f.tenant.grants);const r=await f.run();assert.equal(r.statusCode,429);assert.equal(f.stats.rateWrites,0);assert.equal(f.stats.authorityWrites,0);assert.equal(f.root.has('serverRateLimits/tenant-1/caller-1'),false);}});
test('rate policy is shared across runtime instances and replay cannot bypass it',async()=>{const f=setup();f.opts.policy.rateLimit=1;const a=f.runtime(),b=f.runtime();assert.equal((await f.run(undefined,a)).statusCode,200);assert.equal((await f.run(undefined,b)).statusCode,429);assert.equal(f.decoded().revision,1);assert.equal(f.stats.rateWrites,1);});
test('lost or malformed commit acknowledgment replays the exact command with one business revision',async()=>{for(const mode of ['loseCommit','badAck']){const f=setup(),runtime=f.runtime(),c=f.command();f.control[mode]=true;const lost=await f.run(c,runtime);assert.equal(lost.statusCode,503);assert.equal(lost.body.retrySameCommand,true);assert.equal(JSON.stringify(lost.body).includes('synthetic-private-sdk-secret'),false);assert.equal(f.decoded().revision,1);const retry=await f.run(c,runtime);assert.equal(retry.statusCode,200);assert.equal(retry.body.replayed,true);assert.equal(retry.body.receipt.revision,1);assert.equal(f.decoded().revision,1);assert.equal(Object.keys(f.decoded().sewing).length,1);}});
test('changed payload on accepted requestID and money injection cannot create another operation',async()=>{const f=setup(),runtime=f.runtime(),c=f.command();assert.equal((await f.run(c,runtime)).statusCode,200);c.payload.good=5;assert.equal((await f.run(c,runtime)).statusCode,409);assert.equal(f.decoded().revision,1);const money=f.command();money.requestId='new-request';money.expectedRevision=1;money.payload.tarif=999;assert.equal((await f.run(money,runtime)).statusCode,400);assert.equal(f.decoded().revision,1);});
