'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs');
const Runtime=require('../server/apps-script/legacy-runtime.cjs'),Core=require('../server/production-legacy-operations.cjs'),State=require('../server/production-identity-state.cjs');
const F=require('./fixtures/identity-tenant.cjs');
const SharedAdmission=require('../server/apps-script/shared-request-admission.cjs');
const KEY='SYNTHETIC_PUBLIC_KEY_0000000000000',OAUTH='SYNTHETIC_MANAGED_OAUTH',POLICY={version:'legacy-jahit-current-v1',reviewed:true,timeZone:'Asia/Jakarta',quantityBasis:'good-plus-reject'};
const enc=v=>Buffer.from(JSON.stringify(v)).toString('base64url');
function rootFixture(){return {authorityTenants:{[F.TENANT]:F.copy(F.claimed())},soldier:{produksi:{produksi:[{id:'product-1',series:'Synthetic',namaBarang:'Shirt',size:'M',poAktif:true,poJumlah:20,poTanggal:'2026-10-01',assignJahit:[{id:'assignment-1',tukangId:'worker-1',qty:20,sisa:16}],jahit:[{id:'old-operation',tanggal:'2026-10-01',jumlah:4,lolos:3,rijek:1,tukangId:'worker-1',assignmentId:'assignment-1',tarif:10,total:999.75,dibayar:true}],arsip:[]}]},produksi_meta:{tukangJahit:[{id:'worker-1',nama:'Synthetic Partner',tarif:{'Synthetic|Shirt':12.5}},{id:'worker-2',nama:'Other Partner',tarif:{'Synthetic|Shirt':20}}]},ownerOnly:{private:'SYNTHETIC_PRIVATE_ROOT_CANARY'}},unrelatedRoot:{preserved:true}};}
function fixture(){
  let root=rootFixture(),time=F.NOW;const sec=Date.parse(F.NOW)/1000;
  const stats={google:0,reads:0,puts:0,writes:0,oauth:0,requestAdmission:0,identityAdmission:0},hooks={},calls=[],admissions=[];
  const payload={sub:'partner-1',aud:F.PROJECT,iss:'https://securetoken.google.com/'+F.PROJECT,email:F.EMAIL,email_verified:true,firebase:{sign_in_provider:'google.com',identities:{'google.com':['1000123456789']}},auth_time:sec-1,iat:sec-1,exp:sec+3600};
  const account={localId:'partner-1',email:F.EMAIL,emailVerified:true,disabled:false,validSince:String(sec-300),providerUserInfo:[{providerId:'google.com',rawId:'1000123456789',email:F.EMAIL}],customAttributes:'SYNTHETIC_PRIVATE_ACCOUNT_CANARY'};
  const token=()=>enc({alg:'RS256',kid:'synthetic-key',typ:'JWT'})+'.'+enc(payload)+'.'+Buffer.alloc(256,19).toString('base64url');
  const etag=()=>crypto.createHash('sha1').update(JSON.stringify(root)).digest('base64');
  const response=(status=200,body=JSON.stringify(root),headers={'Content-Type':'application/json; charset=utf-8',ETag:etag()})=>({getResponseCode:()=>status,getAllHeaders:()=>headers,getContent:()=>Array.from(Buffer.from(body),v=>v>127?v-256:v)});
  const script={getOAuthToken(){stats.oauth++;if(hooks.oauth)hooks.oauth(stats.oauth);return OAUTH;}},host={fetch(url,params){
    calls.push({url,params:F.copy(params)});
    if(url==='https://identitytoolkit.googleapis.com/v1/accounts:lookup?key='+KEY){stats.google++;assert.equal(params.method,'post');assert.equal(JSON.parse(params.payload).idToken,token());if(hooks.google){const result=hooks.google(stats.google);if(result)return result;}return response(200,JSON.stringify({users:[account]}),{'Content-Type':'application/json'});}
    assert.equal(url,F.URL+'/.json');assert.equal(params.headers.Authorization,'Bearer '+OAUTH);
    if(params.method==='get'){stats.reads++;if(hooks.read){const result=hooks.read(stats.reads);if(result)return result;}return response();}
    assert.equal(params.method,'put');stats.puts++;if(hooks.beforePut)hooks.beforePut();
    if(params.headers['If-Match']!==etag())return response(412,'{"error":"synthetic conflict"}');
    root=JSON.parse(params.payload);stats.writes++;if(hooks.afterPut){const result=hooks.afterPut();if(result)return result;}return response();
  }};
  const options={enabled:true,binding:{projectId:F.PROJECT,databaseURL:F.URL,tenantId:F.TENANT,apiKey:KEY},urlFetchApp:host,scriptApp:script,clock:()=>time,tariffPolicy:POLICY,
    requestAdmission(q){stats.requestAdmission++;admissions.push(q);return hooks.requestAdmission?hooks.requestAdmission(q):true;},
    identityAdmission(q){stats.identityAdmission++;admissions.push(q);return hooks.identityAdmission?hooks.identityAdmission(q):true;}};
  const core=Core.createProductionLegacyOperations({enabled:true,binding:{projectId:F.PROJECT,databaseURL:F.URL,tenantId:F.TENANT},clock:()=>time,tariffPolicy:POLICY});
  const initial=core.read({root,identity:F.identity()});assert.equal(initial.ok,true);
  const command={kind:'appendJahit',requestId:'request-1',operationId:'operation-1',productId:'product-1',assignmentId:'assignment-1',expectedGrantRevision:1,expectedSourceVersion:initial.view.products[0].sourceVersion,workDate:null,good:2,reject:1};
  return {stats,hooks,calls,admissions,payload,account,host,script,options,command,core,create:()=>Runtime.createAppsScriptLegacyRuntime(options),input:()=>({idToken:token(),command:F.copy(command)}),readInput:()=>({idToken:token()}),response,etag,get root(){return root;},set root(v){root=F.copy(v);},setTime(v){time=v;}};
}
const denied=(r,error)=>{assert.equal(r.ok,false);if(error)assert.equal(r.error,error);assert.equal(Object.isFrozen(r),true);for(const needle of ['SYNTHETIC_PRIVATE',OAUTH,KEY,F.EMAIL,'worker-2','Other Partner'])assert.equal(JSON.stringify(r).includes(needle),false);assert.equal(Object.hasOwn(r,'root'),false);assert.equal(Object.hasOwn(r,'next'),false);};
function revoke(f){const root=f.root;root.authorityTenants[F.TENANT]=State.revokeIdentityEnrollment(root.authorityTenants[F.TENANT],F.revokeCommand(),F.NOW).next;f.root=root;}
test('default runtime is OFF with empty binding and no options/request inspection',()=>{assert.deepEqual(Runtime.DEFAULT_CONFIGURATION,{enabled:false,binding:{projectId:'',databaseURL:'',tenantId:'',apiKey:''}});let hits=0;const options={enabled:false};for(const k of ['binding','urlFetchApp','scriptApp','clock','requestAdmission','identityAdmission','tariffPolicy'])Object.defineProperty(options,k,{get(){hits++;throw Error('PRIVATE');}});const q=new Proxy({},{get(){hits++;throw Error('PRIVATE');},ownKeys(){hits++;throw Error('PRIVATE');}}),r=Runtime.createAppsScriptLegacyRuntime(options);for(const k of ['read','readFinance','execute','resolve'])denied(r[k](q),'service_disabled');assert.equal(hits,0);});
test('factory initializes no native calls and cannot follow replaced options or binding',()=>{const f=fixture(),r=f.create();assert.equal(f.calls.length,0);assert.equal(f.stats.oauth,0);f.options.binding.projectId='demo-other';f.options.binding.apiKey='REPLACED_PUBLIC_KEY_000000000';f.options.urlFetchApp=null;f.options.identityAdmission=()=>false;assert.equal(r.read(f.readInput()).ok,true);});
test('incomplete, extended, unsafe or unreviewed configuration fails without native calls',()=>{for(const change of [o=>{delete o.requestAdmission;},o=>o.profile={owner:true},o=>o.binding.apiKey='',o=>o.binding.tenantId='1',o=>o.binding.databaseURL=F.URL+'/?auth=x',o=>o.tariffPolicy={...POLICY,reviewed:false},o=>o.identityAdmission=true]){const f=fixture();change(f.options);denied(f.create().read(f.readInput()),'unavailable');assert.equal(f.calls.length,0);assert.equal(f.stats.oauth,0);}});
test('read returns only own operations after two actual root reads and fresh Google checks',()=>{const f=fixture(),r=f.create().read(f.readInput());assert.equal(r.ok,true);assert.equal(r.view.binding.workerId,'worker-1');assert.equal(r.view.products[0].assignments[0].remaining,16);for(const needle of [OAUTH,KEY,'SYNTHETIC_PRIVATE',F.EMAIL,'999.75','Other Partner'])assert.equal(JSON.stringify(r).includes(needle),false);assert.deepEqual(Object.keys(r),['ok','view']);assert.equal(f.stats.reads,2);assert.equal(f.stats.google,10);assert.equal(f.stats.writes,0);assert.equal(f.stats.puts,0);});
test('own finance returns preserved historical total and own-only data through the same final checks',()=>{const f=fixture(),r=f.create().readFinance(f.readInput());assert.equal(r.ok,true);assert.equal(r.view.storedJahit.records[0].stored.total,999.75);assert.equal(r.view.combinedPayout,null);assert.equal(r.view.slip.paymentEvidence,'not_proven');assert.equal(JSON.stringify(r).includes('Other Partner'),false);assert.equal(JSON.stringify(r).includes('SYNTHETIC_PRIVATE'),false);assert.equal(f.stats.reads,2);assert.equal(f.stats.google,10);assert.equal(f.stats.writes,0);});
test('shared request budget runs before every network call and identity admission before managed database credential',()=>{const f=fixture();f.hooks.requestAdmission=q=>{assert.equal(f.calls.length,0);assert.equal(f.stats.oauth,0);assert.equal(Object.isFrozen(q),true);assert.deepEqual(q,{projectId:F.PROJECT,kind:'execute',now:F.NOW,maxDatabaseDownloadBytes:3*8*1024*1024,maxGoogleLookupCount:14});return false;};denied(f.create().execute(f.input()),'rate_limited');assert.equal(f.calls.length,0);const q=fixture();q.hooks.identityAdmission=v=>{assert.equal(q.stats.google,2);assert.equal(q.stats.oauth,0);assert.equal(q.stats.reads,0);assert.equal(Object.isFrozen(v),true);assert.deepEqual(v,{projectId:F.PROJECT,uid:'partner-1',email:F.EMAIL,googleSubject:'1000123456789',kind:'read',now:F.NOW});return false;};denied(q.create().read(q.readInput()),'access_denied');assert.equal(q.stats.reads,0);});
test('malformed asynchronous or truthy admission replies cannot authorize a root request',()=>{for(const value of [1,{},Promise.resolve(true),'true',null])for(const hook of ['requestAdmission','identityAdmission']){const f=fixture();f.hooks[hook]=()=>value;denied(f.create().read(f.readInput()),hook==='requestAdmission'?'rate_limited':'access_denied');assert.equal(f.stats.reads,0);assert.equal(f.stats.oauth,0);}});
test('compatible append uses one exact root ETag PUT, preserves source and confirms durable command independently',()=>{const f=fixture(),before=F.copy(f.root),r=f.create().execute(f.input());assert.deepEqual(r,{ok:true,replayed:false,operationId:'operation-1'});assert.equal(f.stats.puts,1);assert.equal(f.stats.writes,1);assert.equal(f.stats.reads,2);assert.equal(f.stats.google,14);assert.deepEqual(f.root.authorityTenants,before.authorityTenants);assert.deepEqual(f.root.soldier.ownerOnly,before.soldier.ownerOnly);assert.deepEqual(f.root.unrelatedRoot,before.unrelatedRoot);assert.deepEqual(f.root.soldier.produksi.produksi[0].jahit[0],before.soldier.produksi.produksi[0].jahit[0]);assert.equal(f.root.soldier.produksi.produksi[0].jahit[1].total,25);assert.ok(f.root.legacyOperationReceipts[F.TENANT].commands['request-1']);for(const needle of ['root','receipt','etag','total','uid','googleSubject'])assert.equal(Object.hasOwn(r,needle),false);});
test('exact replay and read-only resolve do not duplicate a report or issue another PUT',()=>{const f=fixture(),s=f.create();assert.equal(s.execute(f.input()).replayed,false);const before=JSON.stringify(f.root);assert.deepEqual(s.execute(f.input()),{ok:true,replayed:true,operationId:'operation-1'});assert.deepEqual(s.resolve(f.input()),{ok:true,replayed:true,operationId:'operation-1'});assert.equal(f.stats.puts,1);assert.equal(JSON.stringify(f.root),before);});
test('lost native acknowledgement returns uncertainty and the exact command can subsequently resolve',()=>{const f=fixture(),s=f.create();f.hooks.afterPut=()=>{throw Error('SYNTHETIC_PRIVATE_ACK');};assert.deepEqual(s.execute(f.input()),{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(f.stats.writes,1);delete f.hooks.afterPut;assert.deepEqual(s.resolve(f.input()),{ok:true,replayed:true,operationId:'operation-1'});assert.equal(f.stats.writes,1);});
test('known 412 never retries, overwrites a racing change or reports a receipt',()=>{const f=fixture();f.hooks.beforePut=()=>{const r=f.root;r.unrelatedRoot.changedConcurrently=true;f.root=r;};denied(f.create().execute(f.input()),'conflict');assert.equal(f.stats.puts,1);assert.equal(f.stats.writes,0);assert.equal(f.root.unrelatedRoot.changedConcurrently,true);assert.equal(f.stats.reads,1);});
test('missing or changed retained command cannot synthesize a completion receipt',()=>{const f=fixture();denied(f.create().resolve(f.input()),'result_unknown');assert.equal(f.stats.puts,0);const q=fixture(),s=q.create();assert.equal(s.execute(q.input()).ok,true);const changed=q.input();changed.command.good=3;denied(s.resolve(changed),'conflict');assert.equal(q.stats.writes,1);});
test('untrusted command selectors, extra calls, getters and large input fail before admission or network',()=>{for(const extra of [{workerId:'worker-2'},{rate:1},{total:0},{uid:'owner-1'},{role:'owner'},{url:'https://foreign.invalid'}]){const f=fixture(),q=f.input();Object.assign(q.command,extra);denied(f.create().execute(q),'invalid_request');assert.equal(f.calls.length,0);assert.equal(f.stats.requestAdmission,0);}const f=fixture(),r=f.create();denied(r.read(f.readInput(),{}),'invalid_request');denied(r.execute(f.input(),{}),'invalid_request');const q=f.input();let hits=0;Object.defineProperty(q.command,'good',{enumerable:true,get(){hits++;throw Error('PRIVATE');}});denied(r.execute(q),'invalid_request');assert.equal(hits,0);assert.equal(f.calls.length,0);});
test('invalid token, command shape, date, quantities and identity selectors fail before Google',()=>{for(const change of [q=>q.idToken='',q=>q.idToken='x'.repeat(16385),q=>q.email=F.EMAIL,q=>q.command.kind='pay',q=>q.command.operationId='1',q=>q.command.workDate='2026-02-30',q=>q.command.good=-1,q=>q.command.good=1.5,q=>q.command.good=Number.MAX_SAFE_INTEGER,q=>q.command.expectedGrantRevision=0,q=>q.command.expectedSourceVersion='old']){const f=fixture(),q=f.input();change(q);denied(f.create().execute(q),'invalid_request');assert.equal(f.calls.length,0);}});
test('disabled, expired, wrong-project, provider and Google-account errors deny before database admission',()=>{for(const change of [f=>f.account.disabled=true,f=>f.payload.exp=Date.parse(F.NOW)/1000,f=>f.payload.aud='demo-other',f=>f.payload.firebase.sign_in_provider='password',f=>f.account.providerUserInfo[0].rawId='other-subject',f=>f.account.validSince=String(Date.parse(F.NOW)/1000),f=>f.hooks.google=()=>f.response(400,'private')]){const f=fixture();change(f);denied(f.create().read(f.readInput()),'access_denied');assert.equal(f.stats.identityAdmission,0);assert.equal(f.stats.reads,0);assert.equal(f.stats.oauth,0);}});
test('a private allowlist cannot replace a current canonical grant or authorize owner/QC/potong',()=>{for(const change of [revoke,f=>{const r=f.root;delete r.authorityTenants;f.root=r;},f=>{const r=f.root;r.authorityTenants[F.TENANT].grants['partner-1'].profile.workerId='worker-2';f.root=r;}]){const f=fixture();change(f);denied(f.create().read(f.readInput()));assert.equal(f.stats.puts,0);assert.equal(f.stats.reads,1);}});
test('a genuinely matching synthetic QC account and current QC grant still cannot use the Jahit lane',()=>{
  const f=fixture(),root=f.root;root.authorityTenants[F.TENANT]=State.claimIdentityEnrollment(root.authorityTenants[F.TENANT],F.identity({uid:'qc-1',email:F.QC_EMAIL,googleSubject:'qc-subject'}),F.NOW).next;f.root=root;
  f.payload.sub=f.account.localId='qc-1';f.payload.email=f.account.email=f.account.providerUserInfo[0].email=F.QC_EMAIL;f.payload.firebase.identities['google.com'][0]=f.account.providerUserInfo[0].rawId='qc-subject';
  for(const lane of ['read','readFinance','execute'])denied(f.create()[lane](lane==='execute'?f.input():f.readInput()),'access_denied');assert.equal(f.stats.writes,0);
});
test('an owner account or a retained catalog with a non-Jahit worker cannot reuse this lane',()=>{
  const owner=fixture();owner.payload.sub=owner.account.localId='owner-1';denied(owner.create().read(owner.readInput()));assert.equal(owner.stats.puts,0);
  const potong=fixture(),root=potong.root;root.authorityTenants[F.TENANT].workerCatalog.workers['worker-1'].division='potong';potong.root=root;denied(potong.create().readFinance(potong.readInput()));assert.equal(potong.stats.puts,0);
});
test('retained initialization and valid catalog changes are checked separately from the grant revision',()=>{
  for(const mutation of [r=>r.authorityTenants[F.TENANT].workerCatalog.workers['worker-new']={division:'jahit',reviewed:true},r=>r.authorityTenants[F.TENANT].initialization.bootstrapId='replacement-bootstrap']){
    const f=fixture();f.hooks.read=n=>{if(n===2){const root=f.root;mutation(root);f.root=root;}};denied(f.create().read(f.readInput()),'access_denied');assert.equal(f.stats.reads,2);
  }
});
test('grant or initialization changes between root reads suppress both scoped operations and finance',()=>{for(const lane of ['read','readFinance']){const f=fixture();f.hooks.read=n=>{if(n===2)revoke(f);};denied(f.create()[lane](f.readInput()),'access_denied');assert.equal(f.stats.writes,0);assert.equal(f.stats.reads,2);}});
test('final views use the newest root while preserving unchanged identity/grant context',()=>{const f=fixture();f.hooks.read=n=>{if(n===2){const r=f.root;r.soldier.produksi.produksi[0].jahit[0].total=1001.25;f.root=r;}};const r=f.create().readFinance(f.readInput());assert.equal(r.ok,true);assert.equal(r.view.storedJahit.records[0].stored.total,1001.25);});
test('post-PUT grant revocation or durable record alteration cannot produce success',()=>{for(const change of [revoke,f=>{const r=f.root;delete r.legacyOperationReceipts;f.root=r;},f=>{const r=f.root;r.soldier.produksi.produksi[0].jahit[1].total=1;f.root=r;}]){const f=fixture();f.hooks.read=n=>{if(n===2)change(f);};assert.deepEqual(f.create().execute(f.input()),{ok:false,error:'result_unknown',retrySameCommand:true});assert.equal(f.stats.writes,1);assert.equal(f.stats.puts,1);}});
test('native identity revocation during the final response never releases a view or success',()=>{for(const lane of ['read','readFinance','execute']){const f=fixture();f.hooks.google=n=>{if(n===(lane==='execute'?13:9))f.account.disabled=true;};const r=f.create()[lane](lane==='execute'?f.input():f.readInput());denied(r,lane==='execute'?'result_unknown':'access_denied');assert.equal(f.stats.writes,lane==='execute'?1:0);}});
test('root/header/ACK corruption fails closed and an ACK never replaces command confirmation',()=>{for(const lane of ['read','execute']){const f=fixture();if(lane==='read')f.hooks.read=()=>f.response(200,'{"x":1,"x":2}');else f.hooks.afterPut=()=>f.response(200,'{"different":true}');denied(f.create()[lane](lane==='read'?f.readInput():f.input()),lane==='read'?'not_ready':'result_unknown');}});
test('late expiry, clock rollback or native handle drift suppresses data and latches method drift',()=>{for(const change of [f=>f.setTime('2026-10-06T02:59:59.999Z'),f=>f.setTime('2026-10-06T04:00:00.000Z'),f=>f.host.fetch=()=>f.response()]){const f=fixture();f.hooks.read=n=>{if(n===2)change(f);};denied(f.create().read(f.readInput()));}const f=fixture(),s=f.create(),original=f.host.fetch;f.hooks.requestAdmission=()=>{f.host.fetch=()=>f.response();return true;};denied(s.read(f.readInput()),'unavailable');f.host.fetch=original;delete f.hooks.requestAdmission;denied(s.read(f.readInput()),'unavailable');assert.equal(f.calls.length,0);});
test('reentrant callbacks cannot overlap calls and tokens are freshly checked on later invocations',()=>{const f=fixture(),s=f.create();f.hooks.requestAdmission=()=>{denied(s.read(f.readInput()),'busy');return true;};assert.equal(s.read(f.readInput()).ok,true);assert.equal(s.read(f.readInput()).ok,true);assert.equal(f.stats.google,20);f.account.disabled=true;denied(s.read(f.readInput()),'access_denied');assert.equal(f.stats.reads,4);});
test('native exception text and credential/account details never enter errors or runtime logging',()=>{for(const hook of ['requestAdmission','identityAdmission','google','oauth','read']){const f=fixture();f.hooks[hook]=()=>{throw Error('SYNTHETIC_PRIVATE_EXCEPTION '+OAUTH);};denied(f.create().read(f.readInput()));}const source=fs.readFileSync(require.resolve('../server/apps-script/legacy-runtime.cjs'),'utf8');for(const forbidden of [/\bconsole\./,/\bLogger\b/,/\bdoGet\s*\(/,/\bdoPost\s*\(/,/\bUrlFetchApp\./,/\bScriptApp\./,/\bsetTimeout\(/,/\basync\b/,/\bawait\b/])assert.equal(forbidden.test(source),false,String(forbidden));});

test('actual shared admission reserves before the real synthetic coordinator and cannot reset between runtimes',()=>{
  const f=fixture(),budget={projectId:F.PROJECT,policyId:'synthetic-runtime-budget',reviewed:true,startsAt:F.NOW,expiresAt:'2026-10-07T03:00:00.000Z',requestLimit:2,lookupLimit:28,downloadLimitBytes:6*SharedAdmission.ROOT_BYTES,burstWindowMs:60000,burstLimit:2};
  let stored=SharedAdmission.createAdmissionSeed(budget),held=false;const properties={getProperty(k){assert.equal(k,SharedAdmission.PROPERTY_KEY);assert.equal(held,true);return stored;},setProperty(k,v){assert.equal(k,SharedAdmission.PROPERTY_KEY);assert.equal(held,true);stored=v;return properties;}},lock={tryLock(){if(held)return false;held=true;return true;},hasLock(){return held;},releaseLock(){held=false;}};
  function configure(){const gate=SharedAdmission.createAppsScriptSharedRequestAdmission({enabled:true,binding:{projectId:F.PROJECT,policyId:budget.policyId},policy:budget,scriptProperties:properties,scriptLock:lock,clock:()=>F.NOW});f.options.requestAdmission=gate.admit;return f.create();}
  const first=configure();f.hooks.google=n=>{assert.equal(held,false);assert.equal(JSON.parse(stored).requests,n<=14?1:2);};assert.equal(first.execute(f.input()).ok,true);assert.equal(f.stats.google,14);assert.equal(f.stats.writes,1);
  assert.equal(configure().resolve(f.input()).ok,true);assert.equal(JSON.parse(stored).requests,2);assert.equal(JSON.parse(stored).lookups,24);assert.equal(JSON.parse(stored).downloadBytes,5*SharedAdmission.ROOT_BYTES);
  const before={...f.stats},raw=stored;denied(configure().read(f.readInput()),'rate_limited');assert.equal(stored,raw);assert.equal(f.stats.google,before.google);assert.equal(f.stats.reads,before.reads);assert.equal(f.stats.writes,before.writes);
});
