'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createProductionFormController}=require('../production-form-controller.js'),Authority=require('../server/production-authority.cjs'),Earnings=require('../maklon-earnings.js');
const {fixture,ENDPOINT,tick}=require('./helpers/production-bridge-fixture.cjs');
function form(f,module='jahit',extra={}){const states=[],ids={n:0};const c=createProductionFormController({enabled:true,module,endpointURL:ENDPOINT,createBridge:callbacks=>f.create(callbacks),isCurrent:()=>true,onState:s=>states.push(s),newId:()=>{ids.n++;f.formSequence=(f.formSequence||0)+1;return String(f.formSequence);},...extra});return {c,states,ids,last:()=>states.at(-1)};}
const sew={assignmentId:'assignment-1',tanggal:'2026-10-05',good:10,reject:0};
async function open(f,module='jahit',extra={}){const p=form(f,module,extra);assert.deepEqual(await p.c.connect(),{ok:true});assert.deepEqual(p.c.selectCycle('product-1','cycle-1'),{ok:true});return p;}
async function changeQc(f,p){p.c.dispose();const grant=f.roots.get('authorityTenants/tenant-1').grants['caller-1'];grant.revision++;grant.profile={active:true,owner:false,modules:{qc:true}};f.notify();return open(f,'qc');}
const sum=f=>Earnings.summarize(Earnings.normalize(Authority.project(f.decoded()).earningsByWorker['worker-1'],'worker-1')).calculatedTotal;
test('disabled forms never construct bridge or open journal/listener/token/network',async()=>{let calls=0;const c=createProductionFormController({createBridge(){calls++;}});assert.equal((await c.connect()).error,'service_disabled');assert.equal((await c.submit('sewing',sew)).error,'service_disabled');assert.equal(calls,0);});
test('initial canonical view/profile/labels are verified before explicit cycle selection enables work',async()=>{const f=fixture(),p=form(f);assert.equal((await p.c.submit('sewing',sew)).error,'not_ready');assert.equal((await p.c.connect()).ok,true);assert.equal(p.last().phase,'ready');assert.equal(p.last().selectedCycle,null);assert.equal(p.last().cycles[0].workerLabels[0].label,'Synthetic partner');assert.equal(p.last().cycles[0].wage.workerId,'worker-1');assert.equal(p.c.selectCycle('product-1','foreign').error,'invalid_request');assert.ok(Object.isFrozen(p.last().cycles[0].operations));assert.ok([...f.subscribers.keys()].every(k=>k.startsWith('authorityTenants/tenant-1/')));p.c.dispose();});
test('unknown results block new IDs and exact saved replay commits only once through real core/runtime',async()=>{const f=fixture(),p=await open(f);f.controls.loseResponse=true;const result=await p.c.submit('sewing',sew);assert.equal(result.error,'result_unknown');assert.equal(f.decoded().revision,1);assert.equal(p.last().pending[0].requestId,'request-1');assert.equal(p.last().pending[0].payload.good,10);assert.equal((await p.c.submit('sewing',{...sew,good:1})).error,'pending_review');assert.equal(p.ids.n,1);const retry=await p.c.retry('request-1');assert.equal(retry.ok,true);assert.equal(retry.replayed,true);assert.equal(f.decoded().revision,1);assert.equal(Object.keys(f.decoded().sewing).length,1);assert.deepEqual(p.last().pending,[]);p.c.dispose();});
test('real sew/count/batch QC/repair/cancel flow derives wages on server while QC state never contains wages',async()=>{const f=fixture(),p=await open(f);assert.equal((await p.c.submit('sewing',sew)).ok,true);const q=await changeQc(f,p);assert.equal((await q.c.submit('count',{assignmentId:'assignment-1',tanggal:'2026-10-05',jumlah:10})).ok,true);assert.equal(sum(f),1000);const hf=q.last().cycles[0].operations.hitungFisik[0].id;assert.equal((await q.c.submit('inspect',{entries:[{hfId:hf,tanggal:'2026-10-05',ok:5,perbaikan:3,reject:1,offline:1}]})).ok,true);assert.equal(sum(f),500);const qc=q.last().cycles[0].operations.qc[0].id;assert.equal((await q.c.submit('repair',{qcId:qc,tanggal:'2026-10-05',jumlah:2})).ok,true);assert.equal(sum(f),700);const repair=q.last().cycles[0].operations.repairs[0].id;assert.equal((await q.c.submit('cancel',{targetType:'repair',targetId:repair,confirmed:true})).ok,true);assert.equal(sum(f),500);assert.equal(q.last().cycles[0].operations.repairs,undefined);assert.equal(f.decoded().repairs[repair].cancelled,true);for(const s of q.states)for(const cycle of s.cycles){assert.equal(cycle.wage,null);assert.equal(JSON.stringify(cycle.operations).includes('tarif'),false);}q.c.dispose();});
test('money/profile/getters/unknown relationships and ambiguous inputs fail before ID creation, journal or POST',async()=>{const f=fixture(),p=await open(f),before=f.stats.posts;let reads=0;const getter={targetId:'safe',confirmed:true};Object.defineProperty(getter,'targetType',{enumerable:true,get(){reads++;return 'sewing';}});for(const [kind,input]of [['sewing',{...sew,tarif:999}],['sewing',{...sew,workerId:'worker-1'}],['sewing',{...sew,good:'10'}],['sewing',{...sew,assignmentId:'missing'}],['sewing',{...sew,tanggal:'2026-02-30'}],['cancel',getter],['cancel',{targetType:'sewing',targetId:'missing',confirmed:true}],['count',{assignmentId:'assignment-1',tanggal:'2026-10-05',jumlah:1}]])assert.equal((await p.c.submit(kind,input)).error,'invalid_request');assert.equal(reads,0);assert.equal(p.ids.n,0);assert.equal(f.stats.posts,before);assert.deepEqual(p.last().pending,[]);p.c.dispose();});
test('single-flight submits cannot generate another ID while persistence/token request is in progress',async()=>{const f=fixture(),p=await open(f);let release;f.controls.tokenGate=()=>new Promise(r=>{release=r;});const first=p.c.submit('sewing',sew);await tick();assert.equal((await p.c.submit('sewing',sew)).error,'busy');assert.equal(p.ids.n,1);release();assert.equal((await first).ok,true);p.c.dispose();});
test('identity invalidation clears all rendered business state and old journal remains unchanged',async()=>{const f=fixture(),p=await open(f);f.controls.loseResponse=true;await p.c.submit('sewing',sew);const before=JSON.stringify([...f.idb.databases].map(([k,v])=>[k,[...v.stores].map(([n,m])=>[n,[...m]])]));f.switchUser();await tick();assert.equal(p.last().phase,'blocked');assert.equal(p.last().profile,null);assert.deepEqual(p.last().cycles,[]);assert.deepEqual(p.last().pending,[]);assert.equal((await p.c.retry('request-1')).error,'access_denied');assert.equal(JSON.stringify([...f.idb.databases].map(([k,v])=>[k,[...v.stores].map(([n,m])=>[n,[...m]])])),before);assert.equal(f.subscribers.size,0);});
test('grant revision changes hold complete forms without exposing a new grant or losing old commands',async()=>{const f=fixture(),p=await open(f);f.roots.get('authorityTenants/tenant-1').grants['caller-1'].revision++;f.notify();await tick();assert.equal(p.last().phase,'blocked');assert.deepEqual(p.last().cycles,[]);assert.equal((await p.c.submit('sewing',sew)).error,'access_denied');assert.equal(f.stats.posts,0);});
test('restored pending unknown command can be replayed after reopening without new ID or revised payload',async()=>{const f=fixture(),p=await open(f);f.controls.loseResponse=true;await p.c.submit('sewing',sew);p.c.dispose();const q=await open(f);assert.equal(q.last().pending[0].expectedRevision,0);assert.equal(q.ids.n,0);assert.equal((await q.c.retry('request-1')).replayed,true);assert.equal(q.ids.n,0);assert.equal(f.decoded().revision,1);q.c.dispose();});
test('changed revision during prepare causes explicit conflict; no auto rebase or new command on retry',async()=>{const f=fixture(),concurrent=f.create();await concurrent.connect();let changed=false;const p=await open(f,'jahit',{createBridge:callbacks=>{const b=f.create(callbacks);return {...b,async prepare(command){if(!changed){changed=true;await concurrent.prepare({...f.command(),requestId:'other',payload:{...f.command().payload,id:'other-sewing',good:1}});await concurrent.send('other');}return b.prepare(command);}};}});const result=await p.c.submit('sewing',{...sew,good:5});assert.equal(result.error,'conflict');assert.equal(p.last().pending.length,1);assert.equal(p.last().pending[0].expectedRevision,0);const original=JSON.stringify(p.last().pending[0]);assert.equal((await p.c.retry('request-1')).error,'conflict');assert.equal(JSON.stringify(p.last().pending[0]),original);assert.equal(p.ids.n,1);assert.equal(f.decoded().revision,1);concurrent.dispose();p.c.dispose();});
test('terminal identity loss during awaited token cannot repopulate ready business state',async()=>{const f=fixture(),p=await open(f);let release;f.controls.tokenGate=()=>new Promise(r=>{release=r;});const op=p.c.submit('sewing',sew);await tick();f.switchUser();release();assert.equal((await op).ok,false);assert.equal(p.last().phase,'blocked');assert.deepEqual(p.last().cycles,[]);assert.deepEqual(p.last().pending,[]);assert.equal(f.stats.posts,0);});
test('journal write uncertainty holds the captured command; manual retry persists and sends the same ID only',async()=>{const f=fixture(),p=await open(f);f.idb.control.putFail=true;assert.equal((await p.c.submit('sewing',sew)).ok,false);assert.equal(p.last().pending[0].requestId,'request-1');assert.equal(f.stats.posts,0);assert.equal((await p.c.submit('sewing',sew)).error,'pending_review');assert.equal(p.ids.n,1);f.idb.control.putFail=false;assert.equal((await p.c.retry('request-1')).ok,true);assert.equal(p.ids.n,1);assert.equal(f.decoded().revision,1);assert.equal(f.stats.posts,1);p.c.dispose();});
test('caller mutation from ID generation cannot change the prevalidated production snapshot',async()=>{const f=fixture(),input={...sew};const p=await open(f,'jahit',{newId(){input.assignmentId='missing';input.good=1;return 'captured';}});assert.equal((await p.c.submit('sewing',input)).ok,true);const accepted=Object.values(f.decoded().sewing)[0];assert.equal(accepted.lolos,10);assert.equal(accepted.assignmentId,'assignment-1');p.c.dispose();});
test('QC display suppresses owner and dual-role own wage subscriptions at the form boundary',async()=>{for(const profile of [{active:true,owner:true},{active:true,owner:false,workerId:'worker-1',modules:{jahit:true,qc:true}}]){const f=fixture();f.roots.get('authorityTenants/tenant-1').grants['caller-1'].profile=profile;const p=await open(f,'qc');for(const state of p.states)for(const cycle of state.cycles)assert.equal(cycle.wage,null);p.c.dispose();}});
test('credential fields or foreign cycles from a faulty view adapter never reach the ready UI',async()=>{for(const corrupt of [v=>({...v,cycles:v.cycles.map(c=>({...c,cycleId:'foreign-cycle'}))}),v=>({...v,cycles:v.cycles.map(c=>({...c,operations:{...c.operations,password:'synthetic'}}))})]){const f=fixture(),p=form(f,'jahit',{createBridge:callbacks=>f.create({...callbacks,onView:v=>callbacks.onView(corrupt(v))})});assert.equal((await p.c.connect()).ok,false);assert.equal(p.last().phase,'blocked');assert.deepEqual(p.last().cycles,[]);assert.equal(f.stats.posts,0);}});
