'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const Gate=require('../server/apps-script/recurring-request-admission.cjs'),Shared=require('../server/apps-script/shared-request-admission.cjs');
const NOW='2026-10-07T03:00:00.000Z',START='2026-10-01T00:00:00.000Z',END='2026-12-01T00:00:00.000Z',B=Gate.ROOT_BYTES,SMALL=2*1024*1024;
const policy=(cap=B)=>({projectId:'demo-soldier',policyId:'synthetic-recurring-1',reviewed:true,startsAt:START,expiresAt:END,dayRequestLimit:10,dayLookupLimit:140,dayDownloadLimitBytes:30*cap,monthRequestLimit:100,monthLookupLimit:1400,monthDownloadLimitBytes:300*cap,burstWindowMs:1000,burstLimit:2});
function fixture(p=policy(),cap=B){
  let stored=Gate.createRecurringAdmissionSeed(p,cap),time=NOW,owner=null,nextId=0;const hooks={},stats={reads:0,writes:0,acquires:0,releases:0};
  const properties={getProperty(key){assert.equal(key,Gate.PROPERTY_KEY);stats.reads++;return hooks.read?hooks.read(stored):stored;},setProperty(key,value){assert.equal(key,Gate.PROPERTY_KEY);assert.equal(typeof value,'string');stats.writes++;if(hooks.write)return hooks.write(value,v=>{stored=v;});stored=value;return properties;}};
  function create(extra={}){const id=++nextId,lock={tryLock(ms){assert.equal(ms,250);stats.acquires++;if(hooks.acquire)return hooks.acquire(lock);if(owner!==null&&owner!==id)return false;owner=id;return true;},hasLock(){return hooks.held?hooks.held(owner===id):owner===id;},releaseLock(){stats.releases++;if(hooks.release)return hooks.release(()=>{owner=null;});assert.equal(owner,id);owner=null;}};
    const options={enabled:true,binding:{projectId:p.projectId,policyId:p.policyId},policy:p,scriptLock:lock,scriptProperties:properties,clock:()=>time,...(cap===B?{}:{maxRootBytes:cap}),...extra};return {gate:Gate.createAppsScriptRecurringRequestAdmission(options),options,lock,id};}
  const request=(kind='read')=>({projectId:p.projectId,kind,now:time,maxDatabaseDownloadBytes:(kind==='execute'?3:2)*cap,maxGoogleLookupCount:kind==='execute'?14:10});
  return {create,request,hooks,stats,p,properties,get raw(){return stored;},set raw(v){stored=v;},get state(){return JSON.parse(stored);},get owner(){return owner;},set owner(v){owner=v;},get time(){return time;},setTime(v){time=v;},advance(ms){time=new Date(Date.parse(time)+ms).toISOString();}};
}
function privateFree(v){for(const word of ['idToken','OAuth','email','uid','googleSubject','workerId','command','rootData','tariff','wage'])assert.equal(JSON.stringify(v).includes(word),false);}

test('OFF defaults have empty binding and inspect no policy, host, cap or request accessor',()=>{assert.deepEqual(Gate.DEFAULT_CONFIGURATION,{enabled:false,binding:{projectId:'',policyId:''},policy:null,maxRootBytes:B});let hits=0;const o={enabled:false};for(const k of ['policy','binding','clock','scriptProperties','scriptLock','maxRootBytes'])Object.defineProperty(o,k,{get(){hits++;throw Error('PRIVATE');}});const q=new Proxy({},{get(){hits++;throw Error('PRIVATE');},ownKeys(){hits++;throw Error('PRIVATE');}});assert.equal(Gate.createAppsScriptRecurringRequestAdmission(o).admit(q),false);assert.equal(hits,0);});
test('seed is pure, canonical, cap-bound and does not provision native properties',()=>{const f=fixture();assert.equal(f.state.schemaVersion,1);assert.equal(f.state.maxRootBytes,B);assert.equal(f.state.requests,0);assert.equal(f.state.lastAt,Date.parse(START));assert.equal(f.state.day.key,'2026-10-01');assert.equal(f.state.month.key,'2026-10');assert.deepEqual(f.state.burst,[]);assert.equal(f.stats.writes,0);assert.equal(f.raw.length<Gate.MAX_STATE_CHARS,true);assert.equal(Gate.PROPERTY_KEY===Shared.PROPERTY_KEY,false);privateFree(f.state);assert.deepEqual(Gate.SUPPORTED_ROOT_BYTES,[SMALL,B]);});
test('factory snapshots reviewed options, makes no native call and retains default 8 MiB cap',()=>{const f=fixture(),v=f.create();assert.deepEqual(f.stats,{reads:0,writes:0,acquires:0,releases:0});v.options.binding.projectId='demo-other';v.options.policy.dayRequestLimit=100;v.options.maxRootBytes=SMALL;v.options.clock=()=>END;assert.equal(v.gate.admit(f.request()),true);assert.equal(f.state.day.requests,1);assert.equal(f.state.downloadBytes,2*B);assert.equal(f.state.policy.dayRequestLimit,10);});
test('invalid finite horizon, extra policy/options, mismatched binding and unsupported caps cannot touch state',()=>{const cases=[o=>delete o.scriptLock,o=>o.policy.reviewed=false,o=>o.policy.expiresAt=o.policy.startsAt,o=>o.policy.expiresAt='2027-10-03T00:00:00.000Z',o=>o.policy.dayRequestLimit=0,o=>o.policy.monthRequestLimit=0,o=>o.policy.dayLookupLimit=9,o=>o.policy.dayDownloadLimitBytes=1,o=>o.policy.monthDownloadLimitBytes=1,o=>o.policy.burstLimit=33,o=>o.binding.policyId='other',o=>o.policy.extra=1,o=>o.propertyKey='new',o=>o.maxRootBytes=B-1,o=>o.maxRootBytes=1,o=>o.maxRootBytes=String(SMALL)];for(const change of cases){const f=fixture(),v=f.create();change(v.options);assert.equal(Gate.createAppsScriptRecurringRequestAdmission(v.options).admit(f.request()),false);assert.equal(f.stats.acquires,0);assert.equal(f.stats.reads,0);}});
test('first reservation rolls seed date without touching unrelated data and reserves full current envelope',()=>{const f=fixture(),v=f.create();assert.equal(v.gate.admit(f.request('execute')),true);const s=f.state;assert.equal(s.sequence,1);assert.equal(s.requests,1);assert.equal(s.lookups,14);assert.equal(s.downloadBytes,3*B);assert.deepEqual(s.day,{key:'2026-10-07',requests:1,lookups:14,downloadBytes:3*B});assert.deepEqual(s.month,{key:'2026-10',requests:1,lookups:14,downloadBytes:3*B});assert.deepEqual(s.burst,[Date.parse(NOW)]);assert.equal(f.owner,null);assert.equal(f.stats.writes,1);assert.equal(f.stats.reads,2);privateFree(s);});
test('per-day request, lookup and byte ceilings each deny without a property write',()=>{for(const changes of [{dayRequestLimit:1},{dayLookupLimit:14},{dayDownloadLimitBytes:3*B}]){const f=fixture({...policy(),...changes});assert.equal(f.create().gate.admit(f.request('execute')),true);f.advance(1000);const before=f.raw;assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.raw,before);assert.equal(f.stats.writes,1);assert.equal(f.owner,null);}});
test('next UTC day admits within monthly budget and never resets lifetime or monthly reservations',()=>{const f=fixture({...policy(),dayRequestLimit:1});assert.equal(f.create().gate.admit(f.request('execute')),true);f.advance(1000);assert.equal(f.create().gate.admit(f.request()),false);f.setTime('2026-10-08T00:00:00.000Z');assert.equal(f.create().gate.admit(f.request()),true);assert.equal(f.state.day.requests,1);assert.equal(f.state.month.requests,2);assert.equal(f.state.requests,2);assert.equal(f.state.sequence,2);assert.equal(f.state.lookups,24);assert.equal(f.state.downloadBytes,5*B);assert.equal(f.state.month.downloadBytes,5*B);});
test('monthly request, lookup and byte exhaustion survives daily rollover without a new allowance',()=>{for(const changes of [{monthRequestLimit:1},{monthLookupLimit:14},{monthDownloadLimitBytes:3*B}]){const f=fixture({...policy(),...changes});assert.equal(f.create().gate.admit(f.request('execute')),true);f.setTime('2026-10-08T00:00:00.000Z');const before=f.raw;assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.raw,before);assert.equal(f.state.day.key,'2026-10-07');assert.equal(f.stats.writes,1);}});
test('new UTC month rolls both lanes atomically but preserves every lifetime charge',()=>{const f=fixture({...policy(),dayRequestLimit:1,monthRequestLimit:1});assert.equal(f.create().gate.admit(f.request('execute')),true);f.setTime('2026-10-31T03:00:00.000Z');assert.equal(f.create().gate.admit(f.request()),false);f.setTime('2026-11-01T00:00:00.000Z');assert.equal(f.create().gate.admit(f.request('readFinance')),true);assert.deepEqual(f.state.day,{key:'2026-11-01',requests:1,lookups:10,downloadBytes:2*B});assert.deepEqual(f.state.month,{key:'2026-11',requests:1,lookups:10,downloadBytes:2*B});assert.equal(f.state.requests,2);assert.equal(f.state.downloadBytes,5*B);});
test('global rolling burst cannot be bypassed by midnight or month rollover',()=>{for(const first of ['2026-10-07T23:59:59.500Z','2026-10-31T23:59:59.500Z']){const f=fixture({...policy(),burstLimit:1});f.setTime(first);assert.equal(f.create().gate.admit(f.request()),true);f.advance(500);const before=f.raw;assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.raw,before);f.advance(500);assert.equal(f.create().gate.admit(f.request()),true);assert.equal(f.state.requests,2);assert.deepEqual(f.state.burst,[Date.parse(f.time)]);}});
test('skipped days/months create only the current finite lane rather than accumulated credits',()=>{const f=fixture({...policy(),dayRequestLimit:1,monthRequestLimit:2});assert.equal(f.create().gate.admit(f.request()),true);f.setTime('2026-11-20T12:00:00.000Z');assert.equal(f.create().gate.admit(f.request()),true);f.advance(1000);assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.state.day.requests,1);assert.equal(f.state.month.requests,1);assert.equal(f.state.requests,2);});
test('malformed or mismatched state at a new period is never repaired or silently reseeded',()=>{for(const raw of [null,undefined,'','{}','x'.repeat(Gate.MAX_STATE_CHARS+1)]){const f=fixture();f.raw=raw;f.setTime('2026-11-01T00:00:00.000Z');assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.raw,raw);assert.equal(f.stats.writes,0);assert.equal(f.owner,null);}const f=fixture();f.p.policyId='replacement';assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.stats.writes,0);});
test('duplicate/escaped keys, extra state and noncanonical JSON fail without repair',()=>{const changes=[s=>'{"schemaVersion":1,'+JSON.stringify(s).slice(1),s=>JSON.stringify(s).replace('"schemaVersion":1','"schemaVersion":1,"\\u0073chemaVersion":1'),s=>JSON.stringify({...s,foreign:true}),s=>JSON.stringify(s,null,2),s=>JSON.stringify(s).replace('"sequence":0','"sequence":-0')];for(const change of changes){const f=fixture();f.raw=change(f.state);const before=f.raw;assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.raw,before);assert.equal(f.stats.writes,0);}});
test('counter inconsistency, fabricated periods and invalid nested/lifetime cost deltas cannot refill budget',()=>{const changes=[s=>{s.sequence=1;},s=>{s.lookups=1;},s=>{s.downloadBytes=1;},s=>{s.day.key='2026-11-01';},s=>{s.month.key='2026-11';},s=>{s.day.requests=1;},s=>{s.month.downloadBytes=1;},s=>{s.burst=[Date.parse(NOW)];}];for(const change of changes){const f=fixture();const s=f.state;change(s);f.raw=JSON.stringify(s);const before=f.raw;assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.raw,before);}const f=fixture();assert.equal(f.create().gate.admit(f.request()),true);const s=f.state;s.day.lookups=14;s.day.downloadBytes=3*B;f.raw=JSON.stringify(s);assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.state.requests,1);});
test('request cap/date/reset/identity selectors and invented cost discounts fail before native access',()=>{const changes=[q=>q.projectId='demo-other',q=>q.kind='pay',q=>q.maxDatabaseDownloadBytes=SMALL*2,q=>q.maxGoogleLookupCount=2,q=>q.maxRootBytes=SMALL,q=>q.reset=true,q=>q.day='2026-11-01',q=>q.month='2026-11',q=>q.uid='synthetic-owner',q=>q.policyId='other'];for(const change of changes){const f=fixture(),q=f.request();change(q);assert.equal(f.create().gate.admit(q),false);assert.equal(f.stats.acquires,0);}const f=fixture(),v=f.create(),q=f.request();let hits=0;Object.defineProperty(q,'kind',{enumerable:true,get(){hits++;throw Error('PRIVATE');}});assert.equal(v.gate.admit(q),false);assert.equal(hits,0);assert.equal(v.gate.admit(f.request(),{}),false);assert.equal(f.stats.acquires,0);});
test('clock rollback across the same or a new factory cannot resurrect yesterday or last month',()=>{const f=fixture(),v=f.create();assert.equal(v.gate.admit(f.request()),true);f.setTime('2026-11-01T00:00:00.000Z');assert.equal(v.gate.admit(f.request()),true);const before=f.raw;for(const t of ['2026-10-31T23:59:59.999Z','2026-10-07T03:00:00.000Z']){f.setTime(t);assert.equal(v.gate.admit(f.request()),false);assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.raw,before);}assert.equal(f.state.requests,2);});
test('future/stale request timestamp, invalid clock and finite expiry deny without rolling',()=>{for(const time of ['2026-09-30T23:59:59.999Z',END,'2027-01-01T00:00:00.000Z','2026-10-07T03:00:00Z']){const f=fixture();f.setTime(time);const before=f.raw;assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.raw,before);assert.equal(f.stats.writes,0);}const f=fixture(),v=f.create();for(const t of ['2026-10-07T03:00:00.001Z','2026-10-07T02:59:54.999Z']){const q=f.request();q.now=t;assert.equal(v.gate.admit(q),false);}assert.equal(f.stats.acquires,0);});
test('concurrent factories cannot both spend the last daily reservation at rollover',()=>{const f=fixture({...policy(),dayRequestLimit:1}),a=f.create(),b=f.create();let nested;f.hooks.write=(value,store)=>{nested=b.gate.admit(f.request());store(value);return f.properties;};assert.equal(a.gate.admit(f.request()),true);assert.equal(nested,false);assert.equal(f.state.requests,1);assert.equal(f.stats.writes,1);assert.equal(f.owner,null);delete f.hooks.write;f.advance(1000);assert.equal(b.gate.admit(f.request()),false);});
test('pre-held lock is neither borrowed nor released, and ambiguous acquisition cannot admit',()=>{const f=fixture(),v=f.create();f.owner=v.id;assert.equal(v.gate.admit(f.request()),false);assert.equal(f.owner,v.id);assert.equal(f.stats.releases,0);for(const reply of [1,'true',null,Promise.resolve(true)]){const g=fixture();g.hooks.acquire=()=>reply;assert.equal(g.create().gate.admit(g.request()),false);assert.equal(g.stats.writes,0);}});
test('lost acknowledgement retains the reservation and does not refund its day/month/lifetime cost',()=>{const f=fixture({...policy(),dayRequestLimit:1});f.hooks.write=(value,store)=>{store(value);throw Error('PRIVATE_ACK');};assert.equal(f.create().gate.admit(f.request('execute')),false);assert.equal(f.state.requests,1);assert.equal(f.state.day.requests,1);assert.equal(f.state.month.requests,1);assert.equal(f.owner,null);delete f.hooks.write;f.advance(1000);assert.equal(f.create().gate.admit(f.request()),false);f.setTime('2026-10-08T00:00:00.000Z');assert.equal(f.create().gate.admit(f.request()),true);assert.equal(f.state.requests,2);assert.equal(f.state.month.requests,2);assert.equal(f.state.downloadBytes,5*B);});
test('dropped writes, readback mismatch or corrupted persistence never authorize a request',()=>{for(const hook of [()=>undefined,(value,store)=>{store(value.replace('"sequence":1','"sequence":0'));}]){const f=fixture();f.hooks.write=hook;assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.owner,null);}const f=fixture();f.hooks.read=raw=>f.stats.reads===2?null:raw;assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.state.requests,1);});
test('period boundary, expiry, lost lock or failed release after persistence deny and retain cost',()=>{for(const kind of ['day','expiry','ownership','release']){const f=fixture();f.setTime(kind==='day'?'2026-10-07T23:59:59.999Z':NOW);f.hooks.write=(value,store)=>{store(value);if(kind==='day')f.setTime('2026-10-08T00:00:00.000Z');if(kind==='expiry')f.setTime(END);if(kind==='ownership')f.owner=null;return f.properties;};if(kind==='release')f.hooks.release=()=>{throw Error('PRIVATE_RELEASE');};assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.state.requests,1);assert.equal(f.state.day.requests,1);}});
test('reentrant callbacks and native method replacement cannot overlap or restore a drifted gate',()=>{const f=fixture(),v=f.create();f.hooks.write=(value,store)=>{assert.equal(v.gate.admit(f.request()),false);store(value);return f.properties;};assert.equal(v.gate.admit(f.request()),true);delete f.hooks.write;f.advance(1000);const original=f.properties.getProperty;f.properties.getProperty=()=>null;assert.equal(v.gate.admit(f.request()),false);f.properties.getProperty=original;assert.equal(v.gate.admit(f.request()),false);assert.equal(f.state.requests,1);});
test('2 MiB trusted configuration reserves only its matching enforced envelope and binds persisted cap',()=>{const f=fixture(policy(SMALL),SMALL);assert.equal(f.create().gate.admit(f.request('execute')),true);assert.equal(f.state.maxRootBytes,SMALL);assert.equal(f.state.downloadBytes,3*SMALL);f.advance(1000);assert.equal(f.create().gate.admit(f.request('readFinance')),true);assert.equal(f.state.downloadBytes,5*SMALL);assert.equal(f.state.lookups,24);const before=f.raw;assert.equal(f.create({maxRootBytes:B}).gate.admit({...f.request(),maxDatabaseDownloadBytes:2*B}),false);assert.equal(f.raw,before);});
test('cap migration, forged stored cap, accessor cap and request cap mismatch cannot reset or discount cost',()=>{const f=fixture();assert.equal(f.create().gate.admit(f.request()),true);f.advance(1000);const before=f.raw;assert.equal(f.create({maxRootBytes:SMALL}).gate.admit({...f.request(),maxDatabaseDownloadBytes:2*SMALL}),false);assert.equal(f.raw,before);const s=f.state;s.maxRootBytes=SMALL;f.raw=JSON.stringify(s);assert.equal(f.create().gate.admit(f.request()),false);const g=fixture(policy(SMALL),SMALL),v=g.create();let hits=0;Object.defineProperty(v.options,'maxRootBytes',{enumerable:true,get(){hits++;throw Error('PRIVATE');}});assert.equal(Gate.createAppsScriptRecurringRequestAdmission(v.options).admit(g.request()),false);assert.equal(hits,0);const h=fixture(policy(SMALL),SMALL);assert.equal(h.create().gate.admit({...h.request(),maxDatabaseDownloadBytes:2*B}),false);assert.equal(h.stats.acquires,0);});
test('small cap accepts a deliberately narrow reviewed budget without lifting its actual byte allowance',()=>{const p={...policy(SMALL),dayDownloadLimitBytes:2*SMALL,monthDownloadLimitBytes:2*SMALL},f=fixture(p,SMALL);assert.equal(f.create().gate.admit(f.request('execute')),false);assert.equal(f.stats.writes,0);assert.equal(f.create().gate.admit(f.request()),true);f.setTime('2026-10-08T00:00:00.000Z');assert.equal(f.create().gate.admit(f.request()),false);assert.equal(f.state.downloadBytes,2*SMALL);});
test('1–20 saves are not a magic quota: monthly envelope exhaustion stops even an otherwise unused next day',()=>{const p={...policy(SMALL),dayRequestLimit:40,dayLookupLimit:480,dayDownloadLimitBytes:100*SMALL,monthRequestLimit:60,monthLookupLimit:720,monthDownloadLimitBytes:150*SMALL},f=fixture(p,SMALL);for(let day=7;day<=8;day++){f.setTime('2026-10-'+String(day).padStart(2,'0')+'T03:00:00.000Z');for(let pair=0;pair<(day===7?20:10);pair++){assert.equal(f.create().gate.admit(f.request('execute')),true);assert.equal(f.create().gate.admit(f.request()),true);f.advance(1000);}}assert.equal(f.state.requests,60);assert.equal(f.state.lookups,720);assert.equal(f.state.downloadBytes,150*SMALL);f.setTime('2026-10-09T03:00:00.000Z');const before=f.raw;assert.equal(f.create().gate.admit(f.request('execute')),false);assert.equal(f.raw,before);});
test('native exceptions return false only, and source exposes no reset/refund/native global/network/RPC',()=>{for(const hook of ['read','write','acquire','held','release']){const f=fixture();f.hooks[hook]=()=>{throw Error('PRIVATE_TOKEN_OR_RECORD');};assert.equal(f.create().gate.admit(f.request()),false);}const source=fs.readFileSync(require.resolve('../server/apps-script/recurring-request-admission.cjs'),'utf8');for(const forbidden of [/\bconsole\./,/\bLogger\b/,/\bdoGet\s*\(/,/\bdoPost\s*\(/,/\bUrlFetchApp\./,/\bScriptApp\./,/\bPropertiesService\./,/\bLockService\./,/\bdeleteProperty\s*\(/,/\bsetTimeout\(/])assert.equal(forbidden.test(source),false,String(forbidden));assert.deepEqual(Object.keys(Gate.createAppsScriptRecurringRequestAdmission()).sort(),['admit']);});
