'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Deployment=require('../server/deployment/deployment-runtime.cjs');
const projectId='soldier-test-proof',databaseURL='https://soldier-test-proof-default-rtdb.firebaseio.com',tenantId='tenant-proof',origin='https://soldier.example.invalid';
const policy=()=>({version:'legacy-jahit-current-v1',reviewed:true,timeZone:'Asia/Jakarta',quantityBasis:'good-plus-reject'});
const config=()=>({enabled:true,projectId,databaseURL,tenantId,allowedOrigins:[origin],serviceAccount:'soldier-production-runtime@'+projectId+'.iam.gserviceaccount.com',legacyOperationsEnabled:true,legacyOperationsTariffPolicy:policy()});
const environment=()=>({GOOGLE_CLOUD_PROJECT:projectId,GCLOUD_PROJECT:projectId,FUNCTION_TARGET:'soldierProduction',K_SERVICE:'soldierproduction'});
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},end(v){this.writableEnded=true;this.raw=v;this.body=v?JSON.parse(v):null;}};}
function request(url,method=url===Deployment.LEGACY_PATHS[0]?'GET':'POST'){const read=url===Deployment.LEGACY_PATHS[0],headers={origin,authorization:'Bearer header.payload.signature',...(!read?{'content-type':'application/json'}:{})};return {url,method,headers,rawHeaders:Object.entries(headers).flat(),rawBody:read?Buffer.alloc(0):Buffer.from('{"command":{}}')};}
function fixture(configuration=config(),failLoad=false){const counts={load:0,runtime:0},calls={},sdk={getApps:()=>[],applicationDefault:()=>({managedIdentity:true}),initializeApp:(options,name)=>({name,options}),getAuth:app=>({app}),getDatabase:app=>({app})};const deployment=Deployment.createDeployment({host:'functions',configuration,environment,loadAdminSdk(){counts.load++;if(failLoad)throw Error('SYNTHETIC_PRIVATE_EXCEPTION');return sdk;},createRuntime(args){counts.runtime++;calls.args=args;return {handler:async(req,res)=>{res.statusCode=200;res.end('{"ok":true}');}};}});return {counts,calls,deployment,async run(req){const res=response();await deployment.handler(req,res);return res;}};}
test('public legacy host configuration stays OFF with no reviewed tariff policy or binding',()=>{const c=require('../server/deployment/configuration.cjs');assert.equal(c.enabled,false);assert.equal(c.legacyOperationsEnabled,false);assert.equal(c.legacyOperationsTariffPolicy,null);assert.equal(c.projectId,'');});
test('legacy host requires the fixed reviewed tariff selection policy and never invokes policy getters',()=>{let reads=0;const p=policy();Object.defineProperty(p,'reviewed',{enumerable:true,get(){reads++;return true;}});for(const c of [{...config(),legacyOperationsEnabled:'true'},{...config(),legacyOperationsTariffPolicy:null},{...config(),legacyOperationsTariffPolicy:undefined},{...config(),legacyOperationsTariffPolicy:{...policy(),secret:'synthetic'}},{...config(),legacyOperationsTariffPolicy:p},{...config(),legacyOperationsTariffPolicy:{...policy(),reviewed:false}},{...config(),legacyOperationsTariffPolicy:{...policy(),quantityBasis:'good-only'}},{...config(),legacyOperationsEnabled:false,legacyOperationsTariffPolicy:policy()}])assert.equal(Deployment.validateConfiguration(c),null);assert.equal(reads,0);assert.equal(Deployment.validateConfiguration(config()).legacyOperationsEnabled,true);});
test('missing or OFF legacy opt-in rejects all three paths and preflight before importing SDK',async()=>{for(const configuration of [{...config(),legacyOperationsEnabled:false,legacyOperationsTariffPolicy:null},(()=>{const c=config();delete c.legacyOperationsEnabled;delete c.legacyOperationsTariffPolicy;return c;})()]){const f=fixture(configuration);for(const url of Deployment.LEGACY_PATHS){assert.equal((await f.run(request(url))).statusCode,400);const req=request(url,'OPTIONS');req.headers={origin,'access-control-request-method':url.endsWith('/own')?'GET':'POST','access-control-request-headers':url.endsWith('/own')?'authorization':'authorization, content-type'};req.rawHeaders=Object.entries(req.headers).flat();delete req.rawBody;assert.equal((await f.run(req)).statusCode,400);}assert.equal(f.counts.load,0);}});
test('legacy opt-in has exact GET/POST preflight without ADC and cannot admit query/trailing paths',async()=>{const f=fixture();for(const url of Deployment.LEGACY_PATHS){const method=url.endsWith('/own')?'GET':'POST',req=request(url,'OPTIONS');req.headers={origin,'access-control-request-method':method,'access-control-request-headers':method==='GET'?'authorization':'authorization, content-type'};req.rawHeaders=Object.entries(req.headers).flat();delete req.rawBody;const res=await f.run(req);assert.equal(res.statusCode,204);assert.equal(res.headers['Access-Control-Allow-Methods'],method);for(const other of [url+'?workerId=synthetic',url+'/'])assert.equal((await f.run(request(other))).statusCode,400);}assert.equal(f.counts.load,0);});
test('legacy own read rejects body/content-type and commands reject GET before SDK dispatch',async()=>{const f=fixture(),read=request(Deployment.LEGACY_PATHS[0]);read.rawBody=Buffer.from('{"workerId":"synthetic"}');assert.equal((await f.run(read)).statusCode,400);read.rawBody=Buffer.alloc(0);read.headers['content-type']='application/json';read.rawHeaders=Object.entries(read.headers).flat();assert.equal((await f.run(read)).statusCode,400);for(const url of Deployment.LEGACY_PATHS.slice(1))assert.equal((await f.run(request(url,'GET'))).statusCode,405);assert.equal(f.counts.load,0);});
test('cold legacy own failures are readonly and write failures retain stable command instruction',async()=>{const f=fixture(config(),true);for(const url of Deployment.LEGACY_PATHS){const res=await f.run(request(url));assert.equal(res.statusCode,503);assert.deepEqual(res.body,url.endsWith('/own')?{ok:false,error:'unavailable'}:{ok:false,error:'unavailable',retrySameCommand:true});assert.equal(res.raw.includes('PRIVATE'),false);}});
test('host captures trusted policy and passes it only on source-reviewed legacy opt-in',async()=>{const c=config(),f=fixture(c);c.legacyOperationsTariffPolicy.reviewed=false;c.legacyOperationsEnabled=false;assert.equal((await f.run(request(Deployment.LEGACY_PATHS[0]))).statusCode,200);assert.equal(f.calls.args.legacyOperationsEnabled,true);assert.deepEqual(f.calls.args.legacyOperationsTariffPolicy,policy());assert.ok(Object.isFrozen(f.calls.args.legacyOperationsTariffPolicy));assert.equal(f.calls.args.database.app,f.calls.args.auth.app);});
