'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Rpc=require('../server/apps-script/rpc-gateway.cjs'),{createRuntimeFixture,KEY,OAUTH}=require('./helpers/apps-script-runtime-fixture.cjs');
const normal=v=>JSON.parse(JSON.stringify(v));
function fixture(){const f=createRuntimeFixture(),binding={projectId:f.seed.binding.projectId,databaseURL:f.seed.binding.databaseURL,tenantId:f.seed.binding.tenantId},options=f.realm({enabled:true,binding});options.runtime=f.create();const gateway=f.fixture.modules.rpc.createAppsScriptLegacyRpcGateway(options);return {...f,binding,gateway,request:(kind,command=f.command)=>f.realm(['execute','resolve'].includes(kind)?{kind,idToken:f.seed.token,command}:{kind,idToken:f.seed.token})};}
test('RPC is source-OFF and does not inspect caller or dependencies',()=>{let hits=0;const o={enabled:false};for(const k of ['binding','runtime'])Object.defineProperty(o,k,{get(){hits++;throw Error('PRIVATE');}});const request=new Proxy({},{get(){hits++;throw Error('PRIVATE');},ownKeys(){hits++;throw Error('PRIVATE');}});assert.deepEqual(Rpc.createAppsScriptLegacyRpcGateway(o).dispatch(request),{ok:false,error:'service_disabled'});assert.equal(hits,0);});
test('generated gateway admits only scoped production/finance DTOs from actual synthetic runtime',()=>{const f=fixture();for(const kind of ['read','readFinance']){const r=normal(f.gateway.dispatch(f.request(kind)));assert.equal(r.ok,true);assert.equal(r.view.binding.workerId,'worker-1');assert.equal(Object.hasOwn(r,'root'),false);for(const needle of [KEY,OAUTH,'SYNTHETIC_PRIVATE_ROOT_CANARY','Other Partner',f.seed.identity.email])assert.equal(JSON.stringify(r).includes(needle),false);}assert.equal(f.fixture.stats.writes,0);});
test('generated append/replay RPC responses are narrow exact-command receipts',()=>{const f=fixture();assert.deepEqual(normal(f.gateway.dispatch(f.request('execute'))),{ok:true,replayed:false,operationId:'operation-1'});assert.deepEqual(normal(f.gateway.dispatch(f.request('resolve'))),{ok:true,replayed:true,operationId:'operation-1'});assert.equal(f.fixture.stats.writes,1);});
test('RPC uncertainty stays uncertain and resolves without repeating a write',()=>{const f=fixture();f.fixture.controls.loseAck=true;assert.deepEqual(normal(f.gateway.dispatch(f.request('execute'))),{ok:false,error:'result_unknown',retrySameCommand:true});f.fixture.controls.loseAck=false;assert.equal(f.gateway.dispatch(f.request('resolve')).ok,true);assert.equal(f.fixture.stats.writes,1);});
test('caller selectors, invalid kinds, extra arguments and token/command getters fail before native calls',()=>{for(const mutate of [q=>q.kind='ownerRead',q=>q.workerId='other',q=>q.url='https://foreign.invalid',q=>q.idToken='bad token',q=>q.command.total=1,q=>q.command.kind='pay']){const f=fixture(),q=f.request('execute');mutate(q);assert.equal(f.gateway.dispatch(q).error,'invalid_request');assert.equal(f.fixture.stats.google,0);assert.equal(f.fixture.stats.reads,0);}const f=fixture();assert.equal(f.gateway.dispatch(f.request('read'),{}).error,'invalid_request');let hits=0;const q={kind:'read'};Object.defineProperty(q,'idToken',{enumerable:true,get(){hits++;throw Error('PRIVATE');}});assert.equal(Rpc.createAppsScriptLegacyRpcGateway({enabled:true,binding:f.binding,runtime:{read(){},readFinance(){},execute(){},resolve(){}}}).dispatch(q).error,'invalid_request');assert.equal(hits,0);});
test('raw roots, nested finance extras, foreign binding and async runtime replies never escape',()=>{const f=fixture(),valid=normal(f.create().readFinance(f.fixture.readInput()));for(const transform of [r=>({...r,root:{private:true}}),r=>{r.view.storedJahit.records[0].stored.foreignWorker='private';return r;},r=>{r.view.binding.projectId='demo-other';return r;},r=>Promise.resolve(r)]){const reply=transform(normal(valid));const gateway=Rpc.createAppsScriptLegacyRpcGateway({enabled:true,binding:f.binding,runtime:{read:()=>reply,readFinance:()=>reply,execute(){},resolve(){}}});assert.deepEqual(gateway.dispatch({kind:'readFinance',idToken:'header.payload.signature'}),{ok:false,error:'unavailable'});}});
test('write exceptions, malformed receipts and changed method handles cannot imply definite failure or success',()=>{for(const fn of [()=>{throw Error('PRIVATE_TOKEN');},()=>({ok:true,replayed:false,operationId:'wrong'}),()=>({ok:true,replayed:false,operationId:'operation-1',root:{private:true}}),()=>Promise.resolve({ok:true})]){const f=fixture(),runtime={read(){},readFinance(){},execute:fn,resolve:fn},g=Rpc.createAppsScriptLegacyRpcGateway({enabled:true,binding:f.binding,runtime});assert.deepEqual(g.dispatch({kind:'execute',idToken:'header.payload.signature',command:f.command}),{ok:false,error:'result_unknown',retrySameCommand:true});}const f=fixture(),runtime={read:()=>{runtime.read=()=>({ok:false,error:'not_ready'});return {ok:false,error:'not_ready'};},readFinance(){},execute(){},resolve(){}},g=Rpc.createAppsScriptLegacyRpcGateway({enabled:true,binding:f.binding,runtime});assert.equal(g.dispatch({kind:'read',idToken:'header.payload.signature'}).error,'unavailable');assert.equal(g.dispatch({kind:'read',idToken:'header.payload.signature'}).error,'unavailable');});
test('fixed denials are preserved without exception text and malformed retry contracts fail closed',()=>{for(const code of ['access_denied','conflict','capacity_limit','rate_limited','busy','not_ready']){const f=fixture(),fn=()=>({ok:false,error:code}),g=Rpc.createAppsScriptLegacyRpcGateway({enabled:true,binding:f.binding,runtime:{read:fn,readFinance:fn,execute:fn,resolve:fn}});assert.deepEqual(g.dispatch({kind:'execute',idToken:'header.payload.signature',command:f.command}),{ok:false,error:code});}const f=fixture(),fn=()=>({ok:false,error:'result_unknown',retrySameCommand:false}),g=Rpc.createAppsScriptLegacyRpcGateway({enabled:true,binding:f.binding,runtime:{read:fn,readFinance:fn,execute:fn,resolve:fn}});assert.deepEqual(g.dispatch({kind:'execute',idToken:'header.payload.signature',command:f.command}),{ok:false,error:'result_unknown',retrySameCommand:true});assert.deepEqual(g.dispatch({kind:'read',idToken:'header.payload.signature'}),{ok:false,error:'unavailable'});});
test('retained request token is cleared after synchronous runtime call and reentrant calls are denied',()=>{const f=fixture();let retained,g;const fn=q=>{retained=q;assert.deepEqual(g.dispatch({kind:'read',idToken:'header.payload.signature'}),{ok:false,error:'busy'});return {ok:false,error:'not_ready'};};g=Rpc.createAppsScriptLegacyRpcGateway({enabled:true,binding:f.binding,runtime:{read:fn,readFinance:fn,execute:fn,resolve:fn}});assert.equal(g.dispatch({kind:'read',idToken:'header.payload.signature'}).error,'not_ready');assert.equal(retained.idToken,'');});
