'use strict';
// Synthetic retained identities only. No SDK, production data or live calls.
const test=require('node:test'),assert=require('node:assert/strict');
const Scope=require('../server/apps-script/protected-storage-scope.cjs'),State=require('../server/production-identity-state.cjs');
const Rules=require('../security/build-protected-photo-rules.cjs'),F=require('./fixtures/identity-tenant.cjs'),P=require('./fixtures/legacy-lifecycle.cjs');
const copy=F.copy;
function fixture(){const p=P.fixture(),m=Scope.prepareProtectedMigration({root:p.root,binding:p.binding,migrationId:'synthetic-revision-sync',expectedRootETag:'"synthetic-source"'});assert.equal(m.ok,true);const working=copy(m.nextRoot[Scope.KEY].working),api=Scope.createProtectedStorageScope({enabled:true,binding:p.binding,migration:m.migration});return{p,m,working,api};}
function activate(f){const r=f.api.prepareWorkingRevisionReaders({working:f.working,expectedRevision:f.working.revision});assert.equal(r.ok,true);return r.nextWorking;}
test('old envelopes and ordinary writes retain absent header until explicit setup',()=>{const f=fixture(),before=copy(f.working);assert.equal(f.api.readWorking({working:f.working}).ok,true);const root=JSON.parse(f.working.data);root.soldier.privateCash='SYNTHETIC_CHANGED';const write=f.api.prepareWorkingWrite({working:f.working,nextRoot:root,expectedRevision:1});assert.equal(write.ok,true);assert.equal(Object.hasOwn(write.nextWorking,'revisionReaders'),false);assert.deepEqual(f.working,before);});
test('explicit header setup retains exact payload bytes and every monetary/unknown value',()=>{const f=fixture(),before=copy(f.working),next=activate(f);assert.equal(next.revision,2);assert.equal(next.data,before.data);assert.equal(next.dataDigest,before.dataDigest);assert.deepEqual(next.revisionReaders,{'owner-1':true,'partner-1':true,'quality-1':true});assert.deepEqual(f.working,before);const read=f.api.readWorking({working:next});assert.equal(read.ok,true);assert.deepEqual(read.root,JSON.parse(before.data));assert.equal(Object.isFrozen(next.revisionReaders),true);assert.equal(JSON.stringify(next.revisionReaders).includes('@'),false);});
test('explicit setup is idempotent and stale expected revision cannot reset the notification',()=>{const f=fixture(),next=activate(f);assert.deepEqual(f.api.prepareWorkingRevisionReaders({working:next,expectedRevision:2}),{ok:true,replayed:true,nextWorking:next});assert.deepEqual(f.api.prepareWorkingRevisionReaders({working:next,expectedRevision:1}),{ok:false,error:'conflict'});});
test('every accepted working CAS recomputes reader removal from validated retained revocation',()=>{const f=fixture(),working=activate(f),root=JSON.parse(working.data),tenant=root.authorityTenants[F.TENANT];root.authorityTenants[F.TENANT]=State.revokeIdentityEnrollment(tenant,F.revokeCommand(),F.NOW).next;const result=f.api.prepareWorkingWrite({working,nextRoot:root,expectedRevision:2});assert.equal(result.ok,true);assert.deepEqual(result.nextWorking.revisionReaders,{'owner-1':true,'quality-1':true});assert.equal(f.api.readWorking({working:result.nextWorking}).ok,true);assert.deepEqual(JSON.parse(result.nextWorking.data).soldier,JSON.parse(working.data).soldier);});
test('pending approvals receive no reader entry and first retained claim joins atomically',()=>{const f=fixture(),root=JSON.parse(f.working.data);root.authorityTenants[F.TENANT]=F.tenant();const before=f.api.prepareWorkingWrite({working:f.working,nextRoot:root,expectedRevision:1});assert.equal(before.ok,true);const working=f.api.prepareWorkingRevisionReaders({working:before.nextWorking,expectedRevision:2}).nextWorking;assert.deepEqual(working.revisionReaders,{'owner-1':true});const nextRoot=JSON.parse(working.data);nextRoot.authorityTenants[F.TENANT]=State.claimIdentityEnrollment(nextRoot.authorityTenants[F.TENANT],F.identity(),F.NOW).next;const claimed=f.api.prepareWorkingWrite({working,nextRoot,expectedRevision:3});assert.equal(claimed.ok,true);assert.deepEqual(claimed.nextWorking.revisionReaders,{'owner-1':true,'partner-1':true});});
test('stale, forged, false, foreign and missing reader entries fail before returning data',()=>{const f=fixture(),good=activate(f);for(const mutate of [w=>w.revisionReaders['foreign-1']=true,w=>delete w.revisionReaders['owner-1'],w=>w.revisionReaders['partner-1']=false,w=>w.revisionReaders=[],w=>w.revisionReaders=null]){const w=copy(good);mutate(w);assert.deepEqual(f.api.readWorking({working:w}),{ok:false,error:'not_ready'});assert.equal(f.api.prepareWorkingWrite({working:w,nextRoot:JSON.parse(good.data),expectedRevision:2}).ok,false);}});
test('invalid tenant, selected ACL or source metadata cannot activate a reader header',()=>{const f=fixture(),bad=copy(f.working);const root=JSON.parse(bad.data);root.authorityTenants[F.TENANT].grants['foreign-1']={revision:1,profile:{active:true,owner:true}};const malformed=f.api.prepareWorkingWrite({working:f.working,nextRoot:root,expectedRevision:1});assert.equal(malformed.ok,true);assert.deepEqual(f.api.prepareWorkingRevisionReaders({working:malformed.nextWorking,expectedRevision:2}),{ok:false,error:'not_ready'});for(const extra of [{revisionReaders:{'foreign-1':true}},{uid:'owner-1'},{path:'/foreign'}])assert.deepEqual(f.api.prepareWorkingRevisionReaders({working:f.working,expectedRevision:1,...extra}),{ok:false,error:'invalid_request'});});
test('header setup counts its metadata against the same working byte cap and rejects overflow',()=>{const f=fixture(),w=copy(f.working);w.revision=Number.MAX_SAFE_INTEGER;assert.deepEqual(f.api.prepareWorkingRevisionReaders({working:w,expectedRevision:w.revision}),{ok:false,error:'capacity_limit'});const root=JSON.parse(f.working.data);root.padding='';const base=f.api.prepareWorkingWrite({working:f.working,nextRoot:root,expectedRevision:1}).nextWorking;root.padding='x'.repeat(Scope.MAX_WORKING_BYTES-Buffer.byteLength(JSON.stringify(base))-10);const padded=f.api.prepareWorkingWrite({working:f.working,nextRoot:root,expectedRevision:1});assert.equal(padded.ok,true);assert.deepEqual(f.api.prepareWorkingRevisionReaders({working:padded.nextWorking,expectedRevision:2}),{ok:false,error:'capacity_limit'});});
test('revision-only Rules remain SOURCE OFF by default and require private explicit boolean',()=>{const fixed={enabled:true,ownerUid:'owner-1',projectId:F.PROJECT};assert.equal(Object.hasOwn(Rules.buildProtectedOwnerPhotoRules(fixed).rules[Scope.KEY].working,'revision'),false);assert.equal(Object.hasOwn(Rules.buildProtectedOwnerPhotoRules({...fixed,revisionSyncEnabled:false}).rules[Scope.KEY].working,'revision'),false);assert.throws(()=>Rules.buildProtectedOwnerPhotoRules({...fixed,revisionSyncEnabled:'true'}),/invalid_private_binding/);let calls=0;const dangerous={...fixed};Object.defineProperty(dangerous,'revisionSyncEnabled',{enumerable:true,get(){calls++;return true;}});assert.throws(()=>Rules.buildProtectedOwnerPhotoRules(dangerous),/invalid_private_binding/);assert.equal(calls,0);});
test('enabled revision Rules expose only fixed scalar to verified current active-reader UID',()=>{const r=Rules.buildProtectedOwnerPhotoRules({enabled:true,ownerUid:'owner-1',projectId:F.PROJECT,revisionSyncEnabled:true}).rules,w=r[Scope.KEY].working;assert.equal(r['.read'],false);assert.equal(r['.write'],false);assert.equal(w['.read'],false);assert.equal(w['.write'],false);assert.deepEqual(Object.keys(w).sort(),['.read','.write','revision']);assert.equal(w.revision['.write'],false);assert.match(w.revision['.read'],/revisionReaders.*child\(auth\.uid\).*=== true/);assert.match(w.revision['.read'],/email_verified.*google\.com/);assert.match(w.revision['.read'],/migrationId.*sourceRootDigest/);assert.match(w.revision['.read'],/data\.isNumber\(\)/);assert.equal(JSON.stringify(r).includes('authorityTenants'),false);assert.equal(JSON.stringify(r).includes('accessControl'),false);});
