'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Authority=require('../server/production-authority.cjs'),Session=require('../server/production-session-service.cjs'),Http=require('../server/production-http-handler.cjs'),Runtime=require('../server/production-runtime.cjs');
const PROJECT='demo-owner-tariff-proof',URL='https://'+PROJECT+'.firebaseio.com',TENANT='tenant-proof',ORIGIN='https://soldier.example.invalid',NOW='2026-10-06T03:00:00.000Z';
const VIEW='/v1/production/owner/tariffs/view',APPEND='/v1/production/owner/tariffs/append';
const copy=v=>JSON.parse(JSON.stringify(v));
const selection=()=>({productId:'product-1',cycleId:'cycle-1'});
const command=()=>({kind:'appendTariffVersion',requestId:'request-1',productId:'product-1',cycleId:'cycle-1',expectedConfigRevision:2,expectedTariffRevision:3,workerId:'worker-1',tariffVersion:'tariff-3',effectiveAt:'2026-10-07T00:00:00.000Z',currency:'IDR',rate:150});
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},end(v){this.raw=v;this.body=v===undefined?null:JSON.parse(v);this.writableEnded=true;}};}
function request(path=VIEW,payload={selection:selection()}){const rawBody=Buffer.from(JSON.stringify(payload)),headers={origin:ORIGIN,authorization:'Bearer header.payload.signature','content-type':'application/json','content-length':String(rawBody.length)};return {method:'POST',url:path,headers,rawHeaders:Object.entries(headers).flat(),rawBody};}
async function run(handler,req=request()){const res=response();await handler(req,res);return res;}
function fixture(){
  const state=Authority.createAuthority({product:{id:'product-1',series:'Synthetic',namaBarang:'Example only',size:'M',cutQuantity:12},cycleId:'cycle-1',workers:[{id:'worker-2',nama:'Synthetic unassigned'},{id:'worker-1',nama:'Synthetic assigned'}],assignments:[{id:'assignment-2',workerId:'worker-1',qty:2},{id:'assignment-1',workerId:'worker-1',qty:10}],now:NOW});
  const cycle={config:{revision:2,active:true,reviewedEmptyCycle:true,tariffPolicy:'explicit-historical-jakarta-v1'},tariffInputs:{revision:3,policy:{version:'policy-1',kind:'jakarta-fixed-local-time',hour:8,minute:0},historyByWorker:{'worker-1':{'tariff-2':{effectiveAt:'2026-09-01T00:00:00.000Z',currency:'IDR',rate:137},'tariff-1':{effectiveAt:'2026-01-01T00:00:00.000Z',currency:'IDR',rate:100}}}},wire:Authority.encodeStorage(state)};
  const tenant={schemaVersion:1,projectId:PROJECT,tenantId:TENANT,grants:{'caller-1':{revision:7,profile:{active:true,owner:true}},'partner-1':{revision:1,profile:{active:true,owner:false,workerId:'worker-1',modules:{jahit:true}}}},products:{'product-1':{cycles:{'cycle-1':cycle}}}};
  const root=new Map([['authorityTenants/'+TENANT,tenant]]),stats={reads:0,auth:0,admit:0,quota:0,writes:0},hooks={afterRead:null,beforeTransaction:null,loseAck:false};
  const app={options:{projectId:PROJECT,databaseURL:URL}},snapshot=v=>({val:()=>copy(v)});
  const database={app,ref(path){return {toString:()=>URL+'/'+path,async get(){stats.reads++;const value=copy(root.get(path)??null);if(hooks.afterRead)hooks.afterRead();return snapshot(value);},on(event,listener){assert.equal(event,'value');listener(snapshot(root.get(path)??null));},off(){},async transaction(update){if(hooks.beforeTransaction)hooks.beforeTransaction(path);const next=update(copy(root.get(path)??null));if(next===undefined)return {committed:false,snapshot:snapshot(root.get(path)??null)};root.set(path,copy(next));if(path.startsWith('authorityTenants/')){stats.writes++;if(hooks.loseAck){hooks.loseAck=false;throw Error('synthetic-private-error');}}else stats.quota++;return {committed:true,snapshot:snapshot(next)};}};}};
  const token={uid:'caller-1',sub:'caller-1',aud:PROJECT,iss:'https://securetoken.google.com/'+PROJECT,email_verified:true,firebase:{sign_in_provider:'google.com'},exp:Date.parse(NOW)/1000+3600},auth={app,async verifyIdToken(t,revoke){stats.auth++;assert.equal(t,'header.payload.signature');assert.equal(revoke,true);return copy(token);}};
  const options={enabled:true,projectId:PROJECT,databaseURL:URL,tenantId:TENANT,database,auth,clock:()=>NOW,admit:async()=>{stats.admit++;return true;}};
  const reader=()=>Session.createProductionOwnerTariffService(options),read=(r={idToken:'header.payload.signature',selection:selection()})=>reader().execute(r);
  const runtime=()=>Runtime.createProductionRuntime({...options,allowedOrigins:[ORIGIN],policy:{rateWindowMs:60000,rateLimit:30,deadlineMs:1000,maxInFlight:2}});
  return {state,cycle,tenant,root,stats,hooks,token,auth,options,reader,read,runtime};
}
function transport(viewService,writer,overrides={}){return Http.createProductionHttpHandler({enabled:true,service:{execute:async()=>({ok:false,error:'unavailable'})},sessionService:{execute:async()=>({ok:false,error:'unavailable'})},ownerTariffService:viewService,ownerTariffWriter:writer,ownerBinding:{projectId:PROJECT,tenantId:TENANT},allowedOrigins:[ORIGIN],deadlineMs:1000,maxInFlight:1,...overrides});}
test('owner reader is OFF by default with no Auth, admission or database work',async()=>{const f=fixture();f.options.enabled=false;assert.deepEqual(await f.read(),{ok:false,error:'service_disabled'});assert.deepEqual(f.stats,{reads:0,auth:0,admit:0,quota:0,writes:0});});
test('one validated snapshot returns only assigned workers, summed quantities and sorted historical rates',async()=>{const f=fixture(),before=copy(f.tenant),r=await f.read();assert.deepEqual(r,{ok:true,view:{schemaVersion:1,projectId:PROJECT,tenantId:TENANT,uid:'caller-1',grantRevision:7,productId:'product-1',cycleId:'cycle-1',configRevision:2,tariffRevision:3,serverTime:NOW,policy:{version:'policy-1',kind:'jakarta-fixed-local-time',hour:8,minute:0},workers:[{workerId:'worker-1',label:'Synthetic assigned',assignedQuantity:12,history:[{tariffVersion:'tariff-1',effectiveAt:'2026-01-01T00:00:00.000Z',currency:'IDR',rate:100},{tariffVersion:'tariff-2',effectiveAt:'2026-09-01T00:00:00.000Z',currency:'IDR',rate:137}]}]}});assert.equal(f.stats.reads,1);assert.equal(f.stats.auth,1);assert.equal(f.stats.admit,1);assert.deepEqual(f.tenant,before);for(const text of ['partner-1','worker-2','wire','grants','receipts','header.payload.signature'])assert.equal(JSON.stringify(r).includes(text),false);assert.ok(Object.isFrozen(r.view.workers[0].history[0]));});
test('fresh verified Google identity and current owner grant are required on every view',async()=>{for(const mutate of [f=>{f.token.email_verified=false;},f=>{f.token.firebase.sign_in_provider='password';},f=>{f.token.sub='other-uid';},f=>{f.token.aud='demo-other-proof';},f=>{f.token.exp=Date.parse(NOW)/1000;},f=>{f.tenant.grants['caller-1'].profile.owner=false;},f=>{f.tenant.grants['caller-1'].profile.active=false;},f=>{delete f.tenant.grants['caller-1'];},f=>{f.auth.verifyIdToken=async()=>{throw Error('synthetic-private-revocation');};}]){const f=fixture();mutate(f);assert.deepEqual(await f.read(),{ok:false,error:'access_denied'});assert.equal(f.stats.admit,0);assert.equal(f.stats.writes,0);}});
test('owner view refuses unknown/inactive/unreviewed cycles before admission',async()=>{for(const change of [f=>{f.cycle.config.active=false;},f=>{f.cycle.config.reviewedEmptyCycle=false;},f=>{delete f.tenant.products['product-1'];}]){const f=fixture();change(f);assert.deepEqual(await f.read(),{ok:false,error:'not_ready'});assert.equal(f.stats.admit,0);}});
test('selection is exact and rejects body owner/UID/namespace claims and getters',async()=>{for(const r of [{idToken:'header.payload.signature',selection:{...selection(),uid:'caller-1'}},{idToken:'header.payload.signature',selection:{productId:'constructor',cycleId:'cycle-1'}},{idToken:'header.payload.signature',selection:selection(),owner:true},{idToken:'header.payload.signature',selection:[]}]){const f=fixture();assert.deepEqual(await f.read(r),{ok:false,error:'invalid_request'});assert.equal(f.stats.auth,0);}const f=fixture();let called=0;const s=selection();Object.defineProperty(s,'productId',{enumerable:true,get(){called++;return 'product-1';}});assert.deepEqual(await f.read({idToken:'header.payload.signature',selection:s}),{ok:false,error:'invalid_request'});assert.equal(called,0);});
test('selected view has explicit history, response byte and safe quantity-times-rate capacity checks',async()=>{const f=fixture(),history={};for(let i=0;i<513;i++)history['rate-'+i]={effectiveAt:new Date(Date.parse('2026-01-01T00:00:00.000Z')+i*86400000).toISOString(),currency:'IDR',rate:100};f.cycle.tariffInputs.historyByWorker['worker-1']=history;assert.deepEqual(await f.read(),{ok:false,error:'capacity_limit'});assert.equal(f.stats.admit,0);const a=fixture();a.options.maxResponseBytes=32;assert.deepEqual(await a.read(),{ok:false,error:'capacity_limit'});const b=fixture();b.cycle.tariffInputs.historyByWorker['worker-1']['tariff-1'].rate=Number.MAX_SAFE_INTEGER;assert.deepEqual(await b.read(),{ok:false,error:'not_ready'});const c=fixture();c.options.maxResponseBytes=65537;assert.deepEqual(await c.read(),{ok:false,error:'unavailable'});});
test('owner admission may withhold an already-read view after revocation, without stale data disclosure',async()=>{const f=fixture();f.hooks.afterRead=()=>{f.tenant.grants['caller-1'].profile.owner=false;};f.options.admit=async()=>f.tenant.grants['caller-1'].profile.owner;assert.deepEqual(await f.read(),{ok:false,error:'rate_limited'});assert.equal(f.stats.reads,1);});
test('unknown canonical fields or private ledger tampering hold the entire owner view',async()=>{for(const mutate of [f=>{f.tenant.secret='synthetic-secret';},f=>{f.tenant.tariffCommandLedger={schemaVersion:1,entries:{}};},f=>{f.cycle.tariffInputs.historyByWorker['worker-1']['tariff-1'].currency='USD';},f=>{f.tenant.projectId='demo-foreign-project';}]){const f=fixture();mutate(f);const r=await f.read();assert.equal(r.ok,false);assert.equal(f.stats.admit,0);assert.equal(JSON.stringify(r).includes('synthetic'),false);}});
test('HTTP view exposes the exact owner envelope and leaves existing session method untouched',async()=>{const f=fixture(),handler=transport(f.reader(),{execute:async()=>({ok:false,error:'unavailable'})}),r=await run(handler);assert.equal(r.statusCode,200);assert.deepEqual(r.body,await f.read());assert.equal(r.headers['Cache-Control'],'no-store');assert.equal(r.headers['Access-Control-Allow-Origin'],ORIGIN);const wrong=request();wrong.method='GET';assert.equal((await run(handler,wrong)).statusCode,405);});
test('owner routes reject query, body alias, duplicate keys, wrong kind and duplicate security headers before execute',async()=>{let calls=0;const stub={execute:async()=>{calls++;return {ok:false,error:'unavailable'};}},handler=transport(stub,stub);for(const req of [request(VIEW+'?uid=caller-1'),request(VIEW,{selection:{...selection(),owner:true}}),request(VIEW,{command:selection()}),request(APPEND,{command:{kind:'setGrant',uid:'other'}}),request(APPEND,{command:{...command(),rate:1.5}}),request(APPEND,{command:{...command(),secret:'synthetic'}})])assert.equal((await run(handler,req)).statusCode,400);const duplicate=request();duplicate.rawBody=Buffer.from('{"selection":{"productId":"product-1","productId":"product-2","cycleId":"cycle-1"}}');duplicate.headers['content-length']=String(duplicate.rawBody.length);duplicate.rawHeaders=Object.entries(duplicate.headers).flat();assert.equal((await run(handler,duplicate)).statusCode,400);const headers=request();headers.rawHeaders.push('Authorization',headers.headers.authorization);assert.equal((await run(handler,headers)).statusCode,400);assert.equal(calls,0);});
test('owner HTTP success validator refuses foreign scope, unsafe UID/money and executable/private result fields',async()=>{const baseline=await fixture().read();for(const mutate of [r=>{r.view.projectId='demo-foreign-project';},r=>{r.view.tenantId='other-tenant';},r=>{r.view.uid='constructor';},r=>{r.view.productId='other-product';},r=>{r.view.workers[0].history[0].rate=1.5;},r=>{r.view.workers[0].history[0].rate=0;},r=>{r.view.workers[0].history[0].secret='synthetic';},r=>{r.view.workers[0].history.reverse();},r=>{r.view.workers.push(copy(r.view.workers[0]));},r=>{r.view.workers[0].label='bad\nlabel';},r=>{r.view.serverTime='2026-02-30T00:00:00.000Z';},r=>{r.view.grants={};}]){const result=copy(baseline);mutate(result);const h=transport({execute:async()=>result},{execute:async()=>({})});assert.deepEqual((await run(h)).body,{ok:false,error:'unavailable'});}let gets=0;const result=copy(baseline);Object.defineProperty(result.view.workers[0].history[0],'rate',{enumerable:true,get(){gets++;return 100;}});assert.equal((await run(transport({execute:async()=>result},{execute:async()=>({})}))).statusCode,503);assert.equal(gets,0);});
test('owner append results are sanitized and matched to original command including expected next revision',async()=>{const c=command(),receipt={requestId:c.requestId,kind:c.kind,productId:c.productId,cycleId:c.cycleId,workerId:c.workerId,tariffVersion:c.tariffVersion,revision:c.expectedTariffRevision+1,acceptedAt:NOW},result={ok:true,receipt,replayed:false};assert.deepEqual((await run(transport({execute:async()=>({})},{execute:async()=>result}),request(APPEND,{command:c}))).body,result);for(const mutate of [r=>{r.receipt.rate=100;},r=>{r.receipt.revision=5;},r=>{r.receipt.revision=Number.MAX_SAFE_INTEGER+1;},r=>{r.receipt.workerId='other-worker';},r=>{r.receipt.acceptedAt='2026-10-08T00:00:00.000Z';},r=>{r.replayed=1;}]){const r=copy(result);mutate(r);assert.deepEqual((await run(transport({execute:async()=>({})},{execute:async()=>r}),request(APPEND,{command:c}))).body,{ok:false,error:'result_unknown',retrySameCommand:true});}});
test('both owner preflights have only POST JSON headers and do not execute a service',async()=>{let calls=0;const stub={execute:async()=>{calls++;return {};}};for(const path of [VIEW,APPEND]){const req=request(path);req.method='OPTIONS';req.headers={origin:ORIGIN,'access-control-request-method':'POST','access-control-request-headers':'authorization, content-type'};req.rawHeaders=Object.entries(req.headers).flat();delete req.rawBody;assert.equal((await run(transport(stub,stub),req)).statusCode,204);req.headers['access-control-request-method']='GET';req.rawHeaders=Object.entries(req.headers).flat();assert.equal((await run(transport(stub,stub),req)).statusCode,400);}assert.equal(calls,0);});
test('owner reads, writes and session share the same HTTP inFlight gate until operation settles',async()=>{let release;const blocked=new Promise(resolve=>{release=resolve;}),reader={execute:async()=>{await blocked;return fixture().read();}},handler=transport(reader,{execute:async()=>({ok:false,error:'unavailable'})});const pending=run(handler);await new Promise(resolve=>setImmediate(resolve));assert.deepEqual((await run(handler)).body,{ok:false,error:'busy'});assert.deepEqual((await run(handler,request(APPEND,{command:command()}))).body,{ok:false,error:'busy',retrySameCommand:true});release();assert.equal((await pending).statusCode,200);});
test('late owner read is withheld while late append remains an ambiguous same-command result',async()=>{for(const isRead of [true,false]){const stub={execute:async()=>{await new Promise(resolve=>setTimeout(resolve,15));return {ok:false,error:'unavailable'};}},handler=transport(stub,stub,{deadlineMs:1});assert.deepEqual((await run(handler,isRead?request():request(APPEND,{command:command()}))).body,isRead?{ok:false,error:'unavailable'}:{ok:false,error:'result_unknown',retrySameCommand:true});}});
test('assembled owner append persists one durable new version, retains wire/history and replays lost acknowledgment',async()=>{const f=fixture(),runtime=f.runtime(),before=copy(f.cycle.wire),c=command();f.hooks.loseAck=true;assert.deepEqual((await run(runtime.handler,request(APPEND,{command:c}))).body,{ok:false,error:'unavailable',retrySameCommand:true});const retry=await run(runtime.handler,request(APPEND,{command:c}));assert.equal(retry.statusCode,200);assert.equal(retry.body.replayed,true);assert.equal(f.stats.writes,1);const stored=f.root.get('authorityTenants/'+TENANT).products['product-1'].cycles['cycle-1'];assert.deepEqual(stored.wire,before);assert.equal(stored.tariffInputs.revision,4);assert.equal(Object.keys(stored.tariffInputs.historyByWorker['worker-1']).length,3);const changed={...c,rate:151};assert.equal((await run(runtime.handler,request(APPEND,{command:changed}))).statusCode,409);});
test('runtime nonowner/unknown/inactive routes cannot create a quota bucket or write',async()=>{for(const mutate of [f=>{f.tenant.grants['caller-1'].profile.owner=false;},f=>{f.tenant.grants['caller-1'].profile.active=false;},f=>{delete f.tenant.grants['caller-1'];}]){const f=fixture();mutate(f);const runtime=f.runtime();assert.equal((await run(runtime.handler)).body.ok,false);assert.equal((await run(runtime.handler,request(APPEND,{command:command()}))).body.ok,false);assert.equal(f.stats.quota,0);assert.equal(f.stats.writes,0);}});
test('runtime quota record is shared by owner views and appends across assembly instances',async()=>{const f=fixture(),options={...f.options,allowedOrigins:[ORIGIN],policy:{rateWindowMs:60000,rateLimit:1,deadlineMs:1000,maxInFlight:1}},a=Runtime.createProductionRuntime(options),b=Runtime.createProductionRuntime(options);assert.equal((await run(a.handler)).statusCode,200);assert.equal((await run(b.handler,request(APPEND,{command:command()}))).statusCode,429);assert.equal(f.stats.quota,1);assert.equal(f.stats.writes,0);});
test('canonical owner is repeated during append CAS; demotion after admission cannot commit',async()=>{const f=fixture();f.hooks.beforeTransaction=path=>{if(path.startsWith('authorityTenants/'))f.root.get(path).grants['caller-1'].profile.owner=false;};const r=await run(f.runtime().handler,request(APPEND,{command:command()}));assert.equal(r.statusCode,403);assert.equal(f.stats.writes,0);assert.equal(f.root.get('authorityTenants/'+TENANT).products['product-1'].cycles['cycle-1'].tariffInputs.revision,3);});
test('selected owner view bounds depend only on assigned workers and withhold oversized 64KiB history rather than truncate',async()=>{
  const f=fixture(),history={};for(let i=0;i<512;i++)history['rate-'+String(i).padStart(3,'0')+'x'.repeat(120)]={effectiveAt:new Date(Date.parse('2026-01-01T00:00:00.000Z')+i*86400000).toISOString(),currency:'IDR',rate:100};f.cycle.tariffInputs.historyByWorker['worker-1']=history;assert.deepEqual(await f.read(),{ok:false,error:'capacity_limit'});assert.equal(f.stats.admit,0);
  const a=fixture(),workers=[{id:'worker-1',nama:'Synthetic assigned'}];for(let i=0;i<129;i++)workers.push({id:'unused-'+i,nama:'Synthetic unassigned'});a.cycle.wire=Authority.encodeStorage(Authority.createAuthority({product:a.state.product,cycleId:a.state.cycleId,workers,assignments:Object.values(a.state.assignments),now:NOW}));const r=await a.read();assert.equal(r.ok,true);assert.equal(r.view.workers.length,1);assert.equal(JSON.stringify(r).includes('Synthetic unassigned'),false);
});
