'use strict';
// Genuine loopback SDK/Rules proof using synthetic claims only. No real Google
// identity, private bindings, managed OAuth, production data or billing actions.
const {test:nativeTest,before,after}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const HOST='127.0.0.1:9000',PROJECT='demo-soldier-owner-photo-wire',OWNER='synthetic-photo-owner';
const CREDENTIAL_ENV=['GOOGLE_APPLICATION_CREDENTIALS','FIREBASE_TOKEN','GOOGLE_OAUTH_ACCESS_TOKEN','CLOUDSDK_AUTH_ACCESS_TOKEN','CLOUDSDK_AUTH_ACCESS_TOKEN_FILE','CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE','CLOUDSDK_AUTH_IMPERSONATE_SERVICE_ACCOUNT'];
function fence(){assert.equal(process.env.FIREBASE_DATABASE_EMULATOR_HOST,HOST);assert.equal(process.env.FIREBASE_AUTH_EMULATOR_HOST,undefined);assert.ok(CREDENTIAL_ENV.every(k=>process.env[k]===undefined));}
fence();
const {initializeTestEnvironment,assertFails,assertSucceeds}=require('@firebase/rules-unit-testing');
const {SDK_VERSION}=require('firebase/app'),{ref,get,set,remove,runTransaction,onValue}=require('firebase/database');
assert.equal(SDK_VERSION,'10.12.2');
const S=require('../server/apps-script/protected-storage-scope.cjs'),R=require('./build-protected-photo-rules.cjs');
const Initial=require('../server/production-identity-tenant.cjs'),State=require('../server/production-identity-state.cjs');
const binding={projectId:PROJECT,databaseURL:'https://'+PROJECT+'.firebaseio.com',tenantId:'synthetic-owner-photo-tenant'};
const clone=v=>JSON.parse(JSON.stringify(v));let env,seq=0,coverageNeeded=false;
function test(name,options,fn){return nativeTest(name,options,async t=>{try{return await fn(t);}catch(error){coverageNeeded=true;throw error;}});}
function bounded(promise,label,ms=7000){let timer;return Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error(label)),ms);})]).finally(()=>clearTimeout(timer));}
async function admin(fn){fence();let result;await bounded(env.withSecurityRulesDisabled(async c=>{fence();result=await fn(c.database());}),'synthetic photo admin timeout');fence();return result;}
before(async()=>{fence();env=await bounded(initializeTestEnvironment({projectId:PROJECT,database:{host:'127.0.0.1',port:9000,rules:JSON.stringify(R.buildProtectedOwnerPhotoRules({enabled:true,ownerUid:OWNER,projectId:PROJECT,revisionSyncEnabled:true}))}}),'synthetic photo Rules initialization timeout');});
// Fixed loopback-only diagnostic for genuine failed tests. No database values,
// Auth tokens, response strings or raw exceptions are printed. Official native
// report: https://firebase.google.com/docs/rules/emulator-reports .
function readCoverage(){
  fence();return new Promise((resolve,reject)=>{let size=0;const chunks=[];
    const request=http.get('http://127.0.0.1:9000/.inspect/coverage.json?ns=demo-soldier-owner-photo-wire',{headers:{Accept:'application/json',Connection:'close'}},response=>{
      if(response.statusCode!==200){response.resume();reject(Error('synthetic coverage unavailable'));return;}
      response.on('data',chunk=>{size+=chunk.length;if(size>8*1024*1024){response.destroy();request.destroy();reject(Error('synthetic coverage cap'));return;}chunks.push(chunk);});
      response.on('error',reject);response.on('end',()=>{try{fence();resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')));}catch{reject(Error('synthetic coverage invalid'));}});
    });request.on('error',reject);request.setTimeout(4000,()=>request.destroy(Error('synthetic coverage timeout')));
  });
}
function selectedCoverage(raw){
  const rows=[],shape=[];let nodes=0;
  const fieldLabel=key=>/^(?:[0-9]{1,6}|[A-Za-z_][A-Za-z0-9_]{0,47})$/.test(key)?key:'redacted_value_key';
  function visit(value,location,depth){
    if(++nodes>100000||depth>48||!value||typeof value!=='object')return;
    const keys=Object.keys(value);if(shape.length<12)shape.push({location,keys:keys.slice(0,24).map(fieldLabel)});
    const expressions=keys.filter(key=>/^(?:source|expression|expr|text|sourceExpression|code)$/.test(key)&&typeof value[key]==='string'&&/\b(?:newData|data|root)\.(?:child|val|exists|isNumber|isString|isBoolean|hasChildren)\(|\bauth(?:\.|\s*[!=])/.test(value[key])).map(key=>({field:key,expression:value[key].slice(0,600)}));
    const scalars={};for(const key of keys){const v=value[key];if(typeof v==='boolean'||typeof v==='number'&&Number.isFinite(v))scalars[key]=v;else if(typeof v==='string'&&/^(?:type|kind|operation|ruleType)$/.test(key)&&/^[A-Za-z0-9_ -]{1,48}$/.test(v))scalars[key]=v;}
    // False/error records are selected first. Expressions are generated public
    // Rules only; all evaluated string values and complete roots are omitted.
    const rejected=keys.some(key=>value[key]===false||/^(?:false|errors?|failed|failureCount)$/.test(key)&&typeof value[key]==='number'&&value[key]>0);
    if(expressions.length||rejected||keys.some(key=>/error|exception/i.test(key)))rows.push({location,rejected,expressions,scalars});
    for(const key of keys){const nextLocation=location+'/'+fieldLabel(key);visit(value[key],nextLocation,depth+1);}
  }
  visit(raw,'coverage',0);rows.sort((a,b)=>Number(b.rejected)-Number(a.rejected));
  const report={kind:'synthetic-native-photo-rules-failure-diagnostic',nativeReport:true,databaseValuesOmitted:true,visitedNodes:nodes,shape,rows:[]};
  for(const row of rows){report.rows.push(row);if(JSON.stringify(report).length>9500){report.rows.pop();report.truncated=true;break;}}
  return report;
}
after(async()=>{try{if(env&&coverageNeeded){try{const raw=await bounded(readCoverage(),'synthetic photo coverage deadline',5000);console.log(JSON.stringify(selectedCoverage(raw)));}catch{console.log(JSON.stringify({kind:'synthetic-native-photo-rules-failure-diagnostic',available:false,privateValuesSuppressed:true}));}}}finally{if(env)await bounded(env.cleanup(),'synthetic photo namespace cleanup timeout');}});
function client(uid=OWNER,overrides={}){return env.authenticatedContext(uid,{aud:PROJECT,email:'synthetic.owner@gmail.com',email_verified:true,firebase:{sign_in_provider:'google.com'},...overrides}).database();}
function source(){return{soldier:{produksi:{produksi:[{id:'synthetic-product',jahit:[],unknown:{nullable:null,empty:[]}}],images:{'synthetic-\u2603':{image:'data:image/png;base64,AA==',unknown:[null,{},[]]}}},productionPhotos:{pesananOffline:[{id:'synthetic-order',items:[{id:'synthetic-item',gambar:'synthetic-image'}]}]},unknown:{numericMap:{'0':null,'7':[]}}},authorityTenants:{synthetic:{ownerOnly:true}},unknown:{preserve:null}};}
async function acquire(t,original=source(),legacy=false){const marker='owner-photo-proof-'+process.pid+'-'+(++seq),p=(legacy?S.prepareProtectedMigration:S.prepareOwnerSdkPhotoMigration)({root:original,binding,migrationId:marker,expectedRootETag:'"synthetic-original"'});assert.equal(p.ok,true);let owned=false;
  t.after(async()=>{if(!owned)return;fence();assert.match(marker,/^owner-photo-proof-[1-9][0-9]*-[1-9][0-9]*$/);await admin(async db=>{const pointer=ref(db,S.KEY),stored=(await get(pointer)).val();assert.equal(stored?.manifest?.migrationId,marker);await remove(pointer);});});
  await admin(async db=>{const pointer=ref(db,S.KEY);let off;try{await bounded(new Promise((resolve,reject)=>{off=onValue(pointer,s=>resolve(s.exists()),reject);}),'synthetic photo ownership observation timeout');const result=await bounded(runTransaction(pointer,current=>current===null?p.nextRoot[S.KEY]:undefined,{applyLocally:false}),'synthetic photo absent-subtree acquisition timeout');assert.equal(result.committed,true,'fixture must acquire absent subtree');owned=true;}finally{off?.();}});
  return{original,initial:p.nextRoot[S.KEY],marker,get:()=>admin(async db=>(await get(ref(db,S.KEY))).val())};
}
function command(photos,id='synthetic-command'){const p=S.inspectOwnerSdkPhotoEnvelope({photos});assert.equal(p.ok,true);return{requestId:id,expectedRevision:photos.revision,expectedDataDigest:photos.dataDigest,...clone(p.data)};}
function rollback(scope){const r=S.prepareProtectedRollback({protectedRoot:{[S.KEY]:scope},expectedRootETag:'"synthetic-current"'});assert.equal(r.ok,true);return r.nextRoot;}
async function transact(db,command){const pointer=ref(db,S.PATHS.photos);let off;try{await bounded(new Promise((resolve,reject)=>{off=onValue(pointer,s=>resolve(s.exists()),reject);}),'synthetic owner photo observation timeout');return await bounded(runTransaction(pointer,current=>{const result=S.prepareOwnerSdkPhotoMutation({photos:current,command});if(!result.ok)return undefined;return result.replayed?current:result.nextPhotos;},{applyLocally:false}),'synthetic owner photo transaction timeout');}finally{off?.();}}
test('generated Rules grant only verified Google fixed owner photos; deny all working and other paths',{timeout:30000},async t=>{const f=await acquire(t),owner=client();await bounded(assertSucceeds(get(ref(owner,S.PATHS.photos))),'synthetic owner positive photo read timeout');for(const path of ['/',S.PATHS.root,S.PATHS.working,S.PATHS.working+'/data',S.PATHS.root+'/manifest','soldier/produksi/images','soldier/productionPhotos']){await bounded(assertFails(get(ref(owner,path))),'synthetic owner forbidden read timeout');await bounded(assertFails(set(ref(owner,path),'synthetic-forbidden-write')),'synthetic owner forbidden write timeout');}assert.deepEqual(await f.get(),f.initial);});
test('genuine owner SDK CAS preserves both photo slots and unknown empty/null/numeric map fields',{timeout:30000},async t=>{const f=await acquire(t),before=await f.get(),c=command(before.photos);c.images={present:true,value:{empty:[],nil:null,numericMap:{'0':{},'2':null},unicode:'synthetic-\ud83d\ude80',printableAscii:Array.from({length:95},(_,i)=>String.fromCharCode(32+i)).join('')}};const ack=await transact(client(),c);assert.equal(ack.committed,true);const retained=S.resolveOwnerSdkPhotoMutation({photos:ack.snapshot.val(),command:c});assert.equal(retained.ok,true);const after=await f.get();assert.deepEqual(after.photos,ack.snapshot.val());assert.deepEqual(after.working,before.working);assert.deepEqual(after.manifest,before.manifest);const restored=rollback(after);assert.deepEqual(restored.soldier.productionPhotos,f.original.soldier.productionPhotos);assert.deepEqual(restored.soldier.produksi.images,c.images.value);assert.deepEqual(restored.unknown,f.original.unknown);});
test('native committed no-op transaction resolves exact retained ACK after a later photo command',{timeout:30000},async t=>{const f=await acquire(t),first=command(f.initial.photos,'synthetic-first'),a=await transact(client(),first);assert.equal(a.committed,true);const later=command(a.snapshot.val(),'synthetic-later');later.productionPhotos={present:false};const b=await transact(client(),later);assert.equal(b.committed,true);const before=await f.get(),resolved=await transact(client(),first);assert.equal(resolved.committed,true);assert.deepEqual(resolved.snapshot.val(),before.photos);assert.deepEqual(await f.get(),before);assert.equal(S.resolveOwnerSdkPhotoMutation({photos:resolved.snapshot.val(),command:first}).receipt.revision,2);});
test('unknown ACK never permits same request with a changed payload or stale unretained command',{timeout:30000},async t=>{const f=await acquire(t),c=command(f.initial.photos),a=await transact(client(),c);assert.equal(a.committed,true);const changed=clone(c);changed.images={present:false};const conflict=await transact(client(),changed);assert.equal(conflict.committed,false);const stale={...clone(c),requestId:'synthetic-stale-unretained'};const rejected=await transact(client(),stale);assert.equal(rejected.committed,false);assert.deepEqual((await f.get()).photos,a.snapshot.val());});
test('foreign UID, anonymous, unverified email and password-provider claims cannot read or mutate photos',{timeout:30000},async t=>{const f=await acquire(t),c=command(f.initial.photos),p=S.prepareOwnerSdkPhotoMutation({photos:f.initial.photos,command:c});assert.equal(p.ok,true);const users=[env.unauthenticatedContext().database(),client('synthetic-jahit'),client('synthetic-qc'),client(OWNER,{email_verified:false}),client(OWNER,{firebase:{sign_in_provider:'password'}})];for(const db of users){await bounded(assertFails(get(ref(db,S.PATHS.photos))),'synthetic foreign photo read timeout');await bounded(assertFails(set(ref(db,S.PATHS.photos),p.nextPhotos)),'synthetic foreign photo replacement timeout');await bounded(assertFails(remove(ref(db,S.PATHS.photos))),'synthetic foreign photo delete timeout');}assert.deepEqual(await f.get(),f.initial);});
test('Rules deny photo deletion, provenance tampering, unknown fields, stripping receipts and forged no-op fields',{timeout:30000},async t=>{const f=await acquire(t),c=command(f.initial.photos),a=await transact(client(),c);assert.equal(a.committed,true);const good=a.snapshot.val(),db=client();await bounded(assertFails(remove(ref(db,S.PATHS.photos))),'synthetic owner photo root delete timeout');for(const change of [x=>x.binding.tenantId='synthetic-other',x=>x.sourceRootDigest='a'.repeat(64),x=>x.migrationId='synthetic-other',x=>x.data+=' ',x=>x.receipts='',x=>x.receiptCount=0,x=>x.lastReceipt=false,x=>x.password='synthetic-private',x=>x.revision++,x=>x.lastReceipt.payloadDigest='b'.repeat(64)]){const bad=clone(good);change(bad);await bounded(assertFails(set(ref(db,S.PATHS.photos),bad)),'synthetic owner invalid photo envelope timeout');}assert.deepEqual((await f.get()).photos,good);});
test('Rules deny changed image/projection payload without monotonic linked receipt and ASCII wire',{timeout:30000},async t=>{const f=await acquire(t),p=S.prepareOwnerSdkPhotoMutation({photos:f.initial.photos,command:command(f.initial.photos)});assert.equal(p.ok,true);const db=client();for(const change of [x=>x.revision+=1,x=>x.receiptCount+=1,x=>x.lastReceipt.requestId='synthetic-unlinked',x=>x.lastReceipt.revision+=1,x=>x.lastReceipt.dataDigest='a'.repeat(64),x=>x.data+='\u2603',x=>x.data+='\n',x=>x.data+='\x7f',x=>x.data=2,x=>x.receipts=false,x=>x.receipts=x.receipts+'|',x=>x.encoding='synthetic-other']){const bad=clone(p.nextPhotos);change(bad);await bounded(assertFails(set(ref(db,S.PATHS.photos),bad)),'synthetic invalid linked photo mutation timeout');}assert.deepEqual(await f.get(),f.initial);});
test('schema2 exact absent/null/empty photo roots persist through native SDK and rollback independently',{timeout:30000},async t=>{const root=source();delete root.soldier.produksi.images;root.soldier.productionPhotos=null;const f=await acquire(t,root),db=client();const first=await bounded(assertSucceeds(get(ref(db,S.PATHS.photos))),'synthetic empty photo positive read timeout');assert.equal(first.val().lastReceipt,false);assert.deepEqual(rollback(await f.get()),root);const c=command(first.val());c.images={present:true,value:[]};c.productionPhotos={present:true,value:{}};const ack=await transact(db,c);assert.equal(ack.committed,true);const restored=rollback(await f.get());assert.deepEqual(restored.soldier.produksi.images,[]);assert.deepEqual(restored.soldier.productionPhotos,{});});
test('schema1 remains readable only by its prior trusted server lane and cannot be upgraded by SDK owner',{timeout:30000},async t=>{const f=await acquire(t,source(),true),db=client();await bounded(assertFails(get(ref(db,S.PATHS.photos))),'synthetic schema1 SDK read timeout');await bounded(assertFails(set(ref(db,S.PATHS.photos),f.initial.photos)),'synthetic schema1 SDK write timeout');assert.deepEqual(rollback(await f.get()),f.original);});
test('native revision-only listener follows accepted CAS and loses access on the same retained-grant revocation',{timeout:30000},async t=>{
  const now='2026-10-06T03:00:00.000Z',partner='synthetic-revision-partner',email='synthetic.partner@gmail.com';
  const initial=Initial.createInitialIdentityTenantPreparer({enabled:true,scope:{projectId:PROJECT,tenantId:binding.tenantId}}).prepare({ownerUid:OWNER,bootstrapId:'synthetic-revision-bootstrap',initializedAt:'2026-10-06T01:00:00.000Z',workerCatalog:{schemaVersion:1,revision:1,reviewed:true,workers:{'synthetic-worker':{division:'jahit',reviewed:true}}}});assert.equal(initial.ok,true);
  const tenant=clone(initial.tenant);tenant.enrollmentRegistry={schemaVersion:1,approvals:{'synthetic-approval':{email,profile:{active:true,owner:false,workerId:'synthetic-worker',modules:{jahit:true}},reviewed:true,approvedAt:'2026-10-06T02:00:00.000Z',expiresAt:'2026-10-06T04:00:00.000Z',revision:1,status:'pending'}}};
  const identity={projectId:PROJECT,uid:partner,email,googleSubject:'1000555555555',authTimeMs:Date.parse(now)-1000,issuedAtMs:Date.parse(now)-1000,expiresAtMs:Date.parse(now)+3600000,verifiedAt:now};
  const root=source();root.authorityTenants={[binding.tenantId]:State.claimIdentityEnrollment(tenant,identity,now).next};const f=await acquire(t,root),stored=await f.get(),api=S.createProtectedStorageScope({enabled:true,binding,migration:{migrationId:stored.manifest.migrationId,sourceRootDigest:stored.manifest.sourceRootDigest}}),path=S.PATHS.working+'/revision',owner=client(),worker=client(partner,{email});
  await bounded(assertFails(get(ref(owner,path))),'synthetic absent revision header denial timeout');const setup=api.prepareWorkingRevisionReaders({working:stored.working,expectedRevision:1});assert.equal(setup.ok,true);await admin(db=>set(ref(db,S.PATHS.working),setup.nextWorking));
  assert.equal((await bounded(assertSucceeds(get(ref(worker,path))),'synthetic partner revision read timeout')).val(),2);
  for(const db of [owner,worker])for(const forbidden of [S.PATHS.working,S.PATHS.working+'/data',S.PATHS.working+'/revisionReaders',S.PATHS.root])await bounded(assertFails(get(ref(db,forbidden))),'synthetic revision private-path denial timeout');
  for(const db of [owner,worker])await bounded(assertFails(set(ref(db,path),99)),'synthetic revision SDK-write denial timeout');
  for(const db of [client('synthetic-foreign'),env.unauthenticatedContext().database(),client(partner,{email_verified:false}),client(partner,{firebase:{sign_in_provider:'password'}}),client(partner,{aud:'demo-other-project'})])await bounded(assertFails(get(ref(db,path))),'synthetic foreign revision denial timeout');
  let stop=null;const changed=new Promise((resolve,reject)=>{stop=onValue(ref(owner,path),s=>{if(s.val()===3)resolve();},reject);});t.after(()=>stop?.());
  const next=JSON.parse(setup.nextWorking.data);next.authorityTenants[binding.tenantId]=State.revokeIdentityEnrollment(next.authorityTenants[binding.tenantId],{requestId:'synthetic-revoke',approvalId:'synthetic-approval',expectedApprovalRevision:2,expectedGrantRevision:1},now).next;
  const revoked=api.prepareWorkingWrite({working:setup.nextWorking,nextRoot:next,expectedRevision:2});assert.equal(revoked.ok,true);await admin(db=>set(ref(db,S.PATHS.working),revoked.nextWorking));await bounded(changed,'synthetic owner revision notification timeout');stop();stop=null;
  await bounded(assertFails(get(ref(worker,path))),'synthetic revoked reader denial timeout');assert.equal((await get(ref(owner,path))).val(),3);assert.deepEqual(JSON.parse(revoked.nextWorking.data).soldier,JSON.parse(setup.nextWorking.data).soldier);
});
